you can pick up corgis now
citadel-station/citadel-main pull request #10059
Opened 2019-12-06 04:48 UTC by lolman360

you can pick up corgis now

reopening because i actually want this merged

## Changelog
:cl:
add: Added ability to pick up certain simplemobs.
/:cl:

2019-12-19 09:47 UTC, davidchan13 commented
I just realized, does this apply to runtime and Renault?

2019-12-20 02:31 UTC, lolman360 commented
yes

2019-12-20 02:39 UTC, Putnam3145 requested changes

2019-12-20 02:39 UTC, Putnam3145 commented on code/modules/mob/living/carbon/carbon.dm
> +			if(HAS_TRAIT(src, TRAIT_PACIFISM))
should only pacifists be able to throw people?

2019-12-20 06:01 UTC, Putnam3145 approved these changes

2019-12-20 13:20 UTC, Ghommie reviewed
A few changes you may need to apply before I blindly approve and merge this PR.

2019-12-20 13:20 UTC, Ghommie commented on code/modules/mob/living/carbon/carbon.dm
> +		if(!throwable_mob.buckled)
```suggestion
		if(throwable_mob && !throwable_mob.buckled)
```
To prevent potential runtimes.

2019-12-20 13:20 UTC, Ghommie commented on code/modules/mob/living/carbon/carbon.dm
> +			stop_pulling()
```
			if(pulling)
				stop_pulling()
```
To prevent thrown held mobs from stopping the user's pull on objects.

2019-12-20 13:20 UTC, Ghommie commented on code/modules/mob/living/inhand_holder.dm
> +	return
Remove this line.

2019-12-20 13:20 UTC, Ghommie commented on code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
> +	if(user.a_intent=="help")
```suggestion
	if(user.a_intent == INTENT_HELP)
```

2019-12-20 13:20 UTC, Ghommie commented on code/modules/mob/living/inhand_holder.dm
> +		return location.loc.return_air(args)
Safe to remove this one. atom/proc/return_air() by default returns loc?.return_air(), and mobs do not override it.

2019-12-20 13:20 UTC, Ghommie commented on code/modules/mob/living/inhand_holder.dm
> +		return location.loc.remove_air(amount)
But these two have some issues.
Let's say, the holder happens to be inside a backpack worn by some mob, location.loc will be then said mob, then mob remove_air(amount) or assume_air(amount) will be called, which returns null.

A loop like this should be enough.
```
	var/atom/location = loc
	if(!loc)
		return //null
	var/turf/T = get_turf(loc)
	while(location != T)
		location = location.loc
		if(ismob(location))
			return location.loc.proc(amount) //assume_air or remove_air
	return loc.proc(amount) //assume_air or remove_air
```

2019-12-20 13:20 UTC, Ghommie commented on code/modules/mob/living/inhand_holder.dm
> +	..()
```
	. = ..()
	if(mob_try_pickup(user))
		return TRUE
```

2019-12-21 10:05 UTC, merged