Custom Holoforms for pAIs and AIs
citadel-station/citadel-main pull request #10191
Opened 2019-12-15 07:18 UTC by kevinz000

## About The Pull Request

Adds custom holoforms, cloning your current preferences slot with your highest job (if any, otherwise you're nude yay congratulations you) and blending it with a filter of choice.
Use the two new client verbs to set it, 10 second cooldown because getFlatIcon is expensive as hell (but necessary for this to *properly* work unless I add overlays on the pAI/AI hologram holders themselves, which I'm too lazy to do)

## Why It's Good For The Game

customization and my snowflakes

## Changelog
:cl:
add: Custom holoforms have been added for pAIs and AIs
/:cl:

WIP part is the part where I say
1. this isn't tested yet
2. I still need to code in a pAI filtering proc like the AI hologram one
3. adding the menu options to pAI/AI hologram options.

2019-12-15 07:26 UTC, GrayRachnid commented
how would it work if I have AI on high

2019-12-15 07:29 UTC, kevinz000 commented
@GrayRachnid it considers it as no job because ai/cyborg are blacklisted

2019-12-15 07:51 UTC, GrayRachnid commented
So would it go after the medium preference then?

2019-12-15 16:12 UTC, kevinz000 commented
@GrayRachnid nope, that's a limitation it doesn't do the second highest/etc, it just goes for the highest if it's invalid it just assumes no job, I didn't want to complicate the get_highest_job() proc 

In the future I'm hoping someone with the time codes something to allow for custom outfits. I mean, I know enough about html to do it it's rather "what if a player chooses something that will cause issues if spawned, even in nullspace".

2019-12-15 18:02 UTC, ShadeAware commented
**YOU MAD LAD, YOU ACTUALLY DID IT**

2019-12-21 11:14 UTC, Ghommie requested changes
Resolve the followings correctly and It's good to merge.

2019-12-21 11:14 UTC, Ghommie commented on code/__HELPERS/custom_holoforms.dm
> +	CHECK_TICK
Wouldn't it be better if it was done like this?:
```
		var/icon/combined= new
		for(var/D in GLOB.cardinals)
			mannequin.setDir(D)
			COMPILE_OVERLAYS(mannequin)
			CHECK_TICK
			var/icon/partial = getFlatIcon(mannequin)
			CHECK_TICK
			combined.Insert(partial, dir=D)
			CHECK_TICK
```

[Reference](https://github.com/Citadel-Station-13/Citadel-Station-13/blob/7fa485201a4e62d12f8a3930611477b1d21c4f38/code/__HELPERS/icons.dm#L1059)

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
Shitty citadel emotes.
Move the parent call on top, then add an early return if **.** is FALSE.
Then remove this typecheck.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
Same.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
Same.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
Idem.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
As usual.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
Look all this copypasta.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
This says much about the low quality of citadel.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
I regret removing the regression label for a moment.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
Despite the fact `mob_type_allowed_typecache` existed for a reason, you had to do this instead.

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	if(iscarbon(user) || ispAI(user))
It makes no sense for non-carbons / non-pAI to be able to bark silently either. But I'm not here to tell you to add dogs to this one's `mob_type_allowed_typecache`. Or am I?

2019-12-21 11:14 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	mob_type_allowed_typecache = list(/mob/living/carbon, /mob/living/silicon/pai)
Now, once you have replaced all those typechecks with proper parent return value checks, copy this line to each following typepath too, thank you.

2020-01-04 13:07 UTC, Ghommie approved these changes

2020-01-04 13:07 UTC, merged