Fixes Fermi plushie reaction.
citadel-station/citadel-main pull request #10278
Opened 2019-12-24 01:54 UTC by Trilbyspaceclone

## About The Pull Request
Makes fermi plushie need caramel rather then sugar
Lowers the heating needed

## Why It's Good For The Game

This reaction is unable to be done without this fix

## Changelog
:cl:
fix: Fermi plushie can be made once again
/:cl:

2019-12-24 01:59 UTC, YakumoChen commented
this actually doesn't fix it and if anything you're just making it worse. Why would you add a sugar reaction to chemistry without asking @Thalpy if it fucks anything?

2019-12-24 13:29 UTC, Ghommie requested changes

2019-12-24 13:29 UTC, Ghommie commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> -
This is a legit challenge and makes chemistry a little more interesting tbh, and you already fixed the plushie reaction, no need to remove it.

2019-12-26 18:00 UTC, Trilbyspaceclone commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> -
Yes need to remove it, this brakes more reactions like ELS and one other im told

2019-12-27 13:12 UTC, Ghommie commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> -
From what I have seen searching around, the only reaction this beaks is `/datum/chemical_reaction/fermi/secretcatchem` (weird how the unit test never reported of this issue).
You may want to replace the "sugar" with "astrotame" (or another sweet equivalent) on the aforementioned chemical. Or make the caramel reaction require a little bit of water.

Fermi-chems are a bit of a wack to deal with.

2019-12-30 08:15 UTC, silicons submitted a review, later dismissed

2019-12-30 10:13 UTC, Ghommie requested changes
My previous review stands. the sekrit cat chem reaction will still be broken even if you removed the burned caramel reaction.

2020-01-01 10:04 UTC, Trilbyspaceclone commented
Read/test the code again. This works

2020-01-05 14:15 UTC, Ghommie approved these changes

2020-01-05 14:16 UTC, Ghommie commented
I dislike how the bunch of you can't really stand up for a culinary/chemistry challenge and Fermis' kink for sweeties. But consider this merged.

2020-01-05 14:17 UTC, merged