Buffs Engine Goggles a lot!
citadel-station/citadel-main pull request #10301
Opened 2019-12-27 00:31 UTC by Trilbyspaceclone

## About The Pull Request

The Tray scanners now see 4x as far!
The Rad-Scanners now see 12x the tiles!

## Why It's Good For The Game

https://cdn.discordapp.com/attachments/336748540690825216/659907637608972293/unknown.png
Rad mode is hard as hell to see as it is, and is slow. Making it see farther is a needed buff so that you know whom/what/were is leaking rads
Tray buff do to it being so shit, well still making the handscanner usefull

## Changelog
:cl:
tweak: range on Engi Tray scanners and Rad-Scanners 
/:cl:

2019-12-28 15:09 UTC, kevinz000 commented
I'm a bit worried about performance.

2019-12-28 16:12 UTC, Ghommie requested changes
Just increment the initial range var (remember about atmo techs' tray googles) and the maximum range on `show_rads()` (line 93 as of the master branch).
None of this ffs.

2019-12-28 23:15 UTC, Trilbyspaceclone commented
What vaule do you want the internal view to be @Ghommie?

2019-12-28 23:38 UTC, Ghommie commented
It could as well stay more or less the same as long as you comply with the requested changes (ergo move that crap outta `toggle_mode`)

2019-12-29 06:27 UTC, Trilbyspaceclone commented
I dont think were on the same page ghommie... Dosnt it have to be in toggle so that the game knows what range to use at what mode?

2019-12-29 17:02 UTC, Ghommie commented
There is actually an engine googles' subtype (t-ray googles, with only one toggleable mode) with a different base `range` value (2 instead of 1).
Shoving these range values on `toggle_mode()` will damn override t-ray base `range`.

What I'm telling you is to modify these line:
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/b27ab885f34a204cbbd5136b489cea8ccaf37caa/code/modules/clothing/glasses/engine_goggles.dm#L22
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/b27ab885f34a204cbbd5136b489cea8ccaf37caa/code/modules/clothing/glasses/engine_goggles.dm#L93
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/b27ab885f34a204cbbd5136b489cea8ccaf37caa/code/modules/clothing/glasses/engine_goggles.dm#L141

And not the `toggle_mode()`. Got it?

2019-12-30 00:13 UTC, Ghommie commented on code/modules/clothing/glasses/engine_goggles.dm
> +	var/range = 6
Congratulations, this change officially makes tray scanning googles absolutely useless.
Perhaps you may want to push that 6 there and keep this a 4, no?

2019-12-30 10:08 UTC, Ghommie commented
You may want to modify line 74 if you intend to buff the t-ray scanning. Otherwise we are on the good road.

2019-12-30 21:01 UTC, Trilbyspaceclone commented
I dont care about t-ray. I just want Rads to be shown more

2019-12-30 21:23 UTC, Ghommie approved these changes
Ok, I'm not worried about performance.

2019-12-30 21:23 UTC, merged