Ch
citadel-station/citadel-main pull request #10310
Opened 2019-12-27 17:53 UTC by Arturlang

This gives xenomorphs a reason to keep alive hosts, until they burst, so aliens wont be no longer encouraged to kill their host once infected, which gives the host no chance to escape, why not give them a chance, maybe? Xenomorphs already are horribly strong.
🆑
balance: Xenomorph embryos no longer grow in dead hosts.
/🆑

2019-12-27 18:14 UTC, Commandersand commented
people killing hosts to stop xenos
xenos being unable to reproduce in dangerous environments (lavaland/spaced areas, people unsuited will slowly die)

2019-12-27 20:22 UTC, Arturlang commented
Hmm. What do you suggest to make this better, @Commandersand ?

2019-12-27 21:23 UTC, Owai-Seek commented
As far as I know, incubation is already heavily nerfed when someone dies. Even if someone were kept alive for longer, the facehugger keeps them knocked out for at least like, half, of the incubation cycle, unless someone takes the time to take it off their face. If someone takes that time, they're probably making themselves a target for a xeno attack or another facehugger toss.

Maybe make it so if a xeno starts slashing the host, it also damages the egg "organ", making incubation take longer. You could also make it so disembowelment makes the body completely unable to hold an embryo. (I'm not sure if this is the case or not, or if Xeno's can disembowel, I don't actually see them that often?) Just pingponging ideas honestly.

2019-12-27 22:47 UTC, Arturlang commented
I dont think xenos can disembowel, not 100 percent sure @Owai-Seek

2019-12-28 02:41 UTC, Commandersand commented
the whole point was to give people a chance to escape right?
maybe have being nested increase stamina gain or a smaller wait time to resist out so xenos have to check up on you more in the early stage

2019-12-29 21:52 UTC, Ghommie requested changes
Incubation time is not actually nerfed on dead people as of now.

But, considering most benos make nests near the vacuum of space for easier escape, salty players succumbing as a "fuck you xenos", and similar hardships with keeping hosts alive, I think this change is a bit too drastic.

If anything, keeping hosts alive should be awarded before the opposite is penalized.

2019-12-30 08:08 UTC, kevinz000 commented
what ghom said, it kinda fucks xenos over a bit hard.

2019-12-30 18:16 UTC, Arturlang commented
Alright, ill close the PR since its a no, and will need a bit more work.

2019-12-30 18:16 UTC, closed without merging