probably fixes pandoras attacking their owners
citadel-station/citadel-main pull request #10323
Opened 2019-12-28 09:36 UTC by Seris02

## About The Pull Request

Probably stops pandoras from attacking their owners. Closes https://github.com/Citadel-Station-13/Citadel-Station-13/issues/10311

## Someone should probably look at the code since I couldn't actually test this as it requires two people.

## Why It's Good For The Game

Because they aren't supposed to attack their owners?

## Changelog
:cl:
fix: pandoras attacking their owners
/:cl:

2019-12-28 15:39 UTC, Ghommie requested changes

2019-12-28 15:39 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +	nohurt = donthurt
Do this:
```
	if(donthurt)
		hit_things += donthurt
```

2019-12-28 15:39 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +			continue
Remove this.

2019-12-28 16:17 UTC, Seris02 commented on code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +			continue
...but then it does nothing.

2019-12-28 16:19 UTC, Seris02 commented on code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +			continue
nevermind, I see

2019-12-29 10:19 UTC, Seris02 commented
oh.

2019-12-29 16:30 UTC, Ghommie approved these changes

2019-12-29 16:30 UTC, merged