Significantly lowers the forcefield projector health
citadel-station/citadel-main pull request #10326
Opened 2019-12-28 12:04 UTC by chefferz

Does what it says on the tin. 

Having a 250 health portable shield that you can deploy on up to three tiles, has shielding resistant to everything but melee, and can be reset and redeployed quickly has been nothing but abused lately.

This drops the health down to 100 from 250, keeping shield integrity. This also shortens the distance you can place them to four tiles, so no more reaching across the map with this.

2019-12-28 12:05 UTC, kevinz000 commented
(doesn't mean it's a bad pr tho)

2019-12-28 12:10 UTC, Hatterhat commented
at least have the courtesy to branch properly 4head

2019-12-28 14:41 UTC, Ghommie approved these changes
The field distance limit nerfs seems a bit unrelated to the issue. 5 or 6 would be also a better value if you ask me. All good otherwise.

2019-12-28 15:03 UTC, silicons requested changes
make it sustain a Beam() to any shields projected, and not work from inside backpack (or be severely weakened by being inside a container rather than being on the ground). field distance being 7 is fine.
don't make this item completely useless because someone used it effectively a few rounds.

2019-12-28 15:25 UTC, Ghommie commented
> not work from inside backpack (or be severely weakened by being inside a container rather than being on the ground)

What do you exactly mean? Aren't they supposed to be held in some way to do their job like most tools?

2019-12-28 23:25 UTC, kevinz000 commented
@Ghommie 
haahhahaha god I wish
Right now you basically do the following:
backpack
14 forcefield projectors in 2 boxes
project forcefields, put in box
repeat ad nauseum until you have an obscene amount of forcefields up to lock down the area

2019-12-31 13:15 UTC, Detective-Google commented
> @Ghommie
> haahhahaha god I wish
> Right now you basically do the following:
> backpack
> 14 forcefield projectors in 2 boxes
> take out, project forcefields, put back in box
> repeat ad nauseum until you have an obscene amount of forcefields up to lock down the area
> 
> taking out that alone would make these far more niche in its usage instead of a free area lockdown.

I have used these to great memey effect due to the fact that they block tasers (and projectiles)
there's a reason these only allow adjacent placement on tg iirc.

2020-01-01 00:01 UTC, GrayRachnid commented
they're funny and deserve a nerf.

2020-01-02 01:37 UTC, closed without merging