Removes a bunch of things from captain locker
citadel-station/citadel-main pull request #10360
Opened 2019-12-30 22:32 UTC by Trilbyspaceclone

A more robust version of #10287
## About The Pull Request
Cleans out - 
Pet collar - Has no use as cap dosnt offten get a animal.
Pet carrier - Same as above.
Cap hat - Has quite some armor, and cap spawns in with it anyways. + the spare white one if needed
Spare capcarapace - Cap spawns with one and theirs a parade verson, basically this is free spare good armor
Normal spare cap headset - They get a brownman, so why have 2?
Spare gloves - Spawns with them, no need to have a spare of it
Silver ID box - Hop spawns with a box of them, theirs more in brige. Not needed from caps room
Zipties - Every cap just gets normal handcuffs from sec anyways. No real use in these

## Why It's Good For The Game

Caps locker has a lot of powercreep, like 2 full sets of cap level armor for anyone to take + spawning with a full cap armor set. This also helps stop overflowing amout of item creep in this locker.

## Changelog
:cl:
del: Removes several items from captain locker. 
/:cl:

2019-12-30 23:08 UTC, deathride58 commented
A much better solution would be to just give the captain's locker a higher capacity

2019-12-30 23:10 UTC, Trilbyspaceclone commented
@deathride58 I gave it a think thunk, and have to point out that the goal of the pr is in 2 folds
1) lower the powercreep in said locker - Doups of free grate armor/gloves/headsetkeys
2) lower items outside the locker. This is a better imo way to do that then making the locker itself hold more. As one day we might want/will make access lockers craftable.

2019-12-30 23:25 UTC, chefferz commented
This is all here so if the captain gets killed they've got a spare outfit. I don't see a reason for this.

2019-12-30 23:51 UTC, Trilbyspaceclone commented
@chefferz Main problem with that is that, a few things happends
1 captain + 1 locker = 3 caps gear - 3 headsetkeys
When every other head only has 1 set of back up gear.

2019-12-31 02:31 UTC, necromanceranne commented
All this is necessary for when the cap dies/when it gets destroyed somehow (usually fire), or someone has assumed captaincy and can wear the uniform. It makes extremely little sense to get rid of the original versions of these items when you could just move the alternative items to another locker or a vendor.

2019-12-31 04:13 UTC, Trilbyspaceclone commented
Cap spawns with a pare of cap gloves, and the normal get up.
The alt set armor wise is the same.
Its some of the best non-hardsuit armor on the station. Having three of them is quite powerful.

2019-12-31 20:56 UTC, GrayRachnid commented
Silver ID box - Hop spawns with a box of them, theirs more in brige. Not needed from caps room

The hop spawns with a normal Id box, not silver.

2020-01-01 03:30 UTC, silicons requested changes
Nah, just add a captain's wardrobe vendor

Passing comment that vendor malfunction is a horrible event and needs redesign but obviously out of scope of this PR, just mentioning it for when someone says but kev vendor malfunction fucks that

2020-01-01 09:37 UTC, Trilbyspaceclone commented
Why do we want endless cap gear?
"Ah yes lets make it so you can meme 50 cap hats/chest armor and other gear by making it a vender!"

2020-01-02 05:37 UTC, kevinz000 commented
I honestly don't have too much of an issue with spare gear. TG does it, the mild powergaming potential of having some extra armor isn't enough for me to throw a fit over it.

2020-01-04 01:45 UTC, Trilbyspaceclone commented
No other head has spare gear for their spare gear. Its non-logical

2020-01-07 05:03 UTC, Trilbyspaceclone commented
More venders make mapping harder
More venders lead to explotes
More venders lead to malf AI/events being more robust

2020-01-07 13:24 UTC, Bran34 commented
Can't say I've ever seen anyone powergame by giving out the captain armor.

Don't fix it if it ain't broke...

2020-01-13 08:33 UTC, closed without merging