Chess!
citadel-station/citadel-main pull request #10405
Opened 2020-01-02 12:22 UTC by KathrinBailey

## About The Pull Request

Brings chess to Space Station 13!
 Adds twelve jumbo chess pieces with the Staunton style to the game as structures with no density, so they can be walked through and dragged on top of other pieces. Each chess piece costs two metal, requiring 64 metal in total to build a complete chess set. Originally, the pieces were going to be crafted with titanium or plastitanium. Instead, I decided on metal. With the pieces themselves being cheap and easy to build, people can spend effort in making good-looking chess boards.

## Why It's Good For The Game
Gives players the option to craft a jumbo chess set, using an 8x8 space (+1 tile to store pieces). The Staunton design is the most common design, popularised in England in the mid 1800s, it is the most prevalent design in Europe and America. Ever look at the """"""chess"""""" programme in the holodeck and get confused at what piece is what? Did you see April and Duke Moxley use security gear as chess pieces that one time and wonder what you're even looking at? Then heck yeah, having actual chess pieces in the game is a good solution!

One thing people like to do is complain about extended. What can you do in Extended? Refurbish something, build a mini-station, build crazy power setups, make a rage cage. Why not make the intellectual rage cage? A spectator sport for all! One of those book-reading nerds of the Wizard Federation coming over? Challenge them to a game of chess! Those nerds can't refuse!

Oh, it also allows you to play chess in Space Station 13, chess is fun, it's something different to do whilst you're on the station.

## Why not just create a table that occupies one tile to play chess in?
**The complex answer:** I want chess not to be just an arcade machine that you play in the bar, I don't want this to be a round-start thing, because then the content will get stale fast. I want this to be something you have to set-up, so its a fun spectacle and it is something to work towards during a greenshift or low threat shift. Although the pieces are kind of the same, I want people to get creative and make cool new chess boards and spectating areas for it.
**The simple answer:** I don't know how to code that and I want chess that can be spectated.

## Changelog
:cl:
add: Jumbo chess!
add: Chess Singularity.
/:cl:

## Images

![image](https://user-images.githubusercontent.com/53862927/71666241-086db180-2d58-11ea-895d-72f268efbf6c.png)
![image](https://user-images.githubusercontent.com/53862927/71666233-03106700-2d58-11ea-8f87-04018361f3fc.png)
![image](https://user-images.githubusercontent.com/53862927/71666267-17ecfa80-2d58-11ea-915c-f41b714fd73d.png)

_please don't crush my dreams I just wanna play chess in space with drewfus and my other friends_

2020-01-02 12:27 UTC, KathrinBailey commented
I just realised that I committed the change to floors.dmi
The change so everyone is aware:
Adds a marble tile that isn't actually in the code anywhere so it cannot be yet utilised. I might make it into a stack and potentially in the future make marble something you can mine and make it an actual resource that you can construct things with, I need to dabble more in the relevant code before I can pull that off.

2020-01-02 16:10 UTC, KingTerrytheTerrible commented
looks like a fucking downie did the sprites and code

2020-01-02 16:11 UTC, gardenBanter commented
inferior servers stealing pp features once again smh

2020-01-02 16:19 UTC, KathrinBailey commented
It's a very mentally deficient take to say anyone who doesn't know how to code and hasn't sprited before is a downie. Probably just as much of a mentally deficient take to say I'm stealing PPstation features when none of this is at all related to PPstation.

Yikes, brigading over a chess PR. Grow the fuck up and fuck off perhaps?

2020-01-02 19:49 UTC, gardenBanter commented
KingTerry is one of the best programmers in his country and I have over 100 confirmed SS13 commits, every single one of which made history books. Stay MAD. The sprites are ugly (poo poo).

2020-01-02 19:51 UTC, KingTerrytheTerrible commented
>they joined March 26 2019

2020-01-02 20:34 UTC, MrJWhit commented
I'm a bit worried about the metal crafting page getting too large, is there a chance this could be its own crafting page?

2020-01-02 21:15 UTC, gardenBanter commented
horrrrrrrrrrrrible sprites

2020-01-03 04:58 UTC, KathrinBailey commented
> I'm a bit worried about the metal crafting page getting too large, is there a chance this could be its own crafting page?

I could alternatively make it craftable using different materials with much smaller crafting lists, like titanium, since titanium is usually always in excess in the ore silo.

2020-01-03 07:24 UTC, MrJWhit commented
I think titanium is a great idea, it has a pretty low use normally.

2020-01-03 10:06 UTC, YakumoChen commented
I like the descriptions but it could do without the coder reference tbh. the "manufactured" part doesn't even make sense anyway since you build them yourself

2020-01-11 20:43 UTC, Ghommie requested changes
Alas, the pieces sprites stick out like a sore thumb compared to the surroundings, bulky and borderless with a shading that doesn't fit much their elavation or "flatness". Could use a flatter shading (less variated color palette), some borders and perhaps topdown perspective with less attention to minor details (they are 32x32, don't overdo yourself).

Moving on to the code...

2020-01-11 20:43 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> +	resistance_flags = FLAMMABLE
Ok, it's made of metal. Why should it be flammable, copypasta?

2020-01-11 20:43 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> +	var/buildstackamount = 2
Useless vars, these are not windows or chairs with subtypes made of different materials.

2020-01-11 20:43 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> +	var/obj/item/stack/sheet/metal/M = new (loc, 2)
Use drop_location() instead of loc.

2020-01-11 20:43 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> +	playsound(src.loc, 'sound/items/deconstruct.ogg', 50, 1)
```suggestion
	tool.play_tool_sound(src)
```

2020-01-11 20:43 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> +	desc = "A white pawn manufactured by Kat-Kea. Get accused of cheating when executing a sick En Passant."
Could you stick with generic descriptions without all these blurps, jokes, fun facts, memes? Some of them are downright stupid, others could be moved somewhere else.

2020-01-11 20:43 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> +	name = "White Pawn"
Use the `\improper` text macro before all these names or lowercase them.

2020-01-11 20:43 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> +/obj/structure/chess/BlackPawn
honestly black pieces could be subtypes with different color matrix.

2020-01-11 20:43 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> + */
All of this whining just discourages me from merging.

2020-01-30 02:51 UTC, Ghommie commented
Fix conflicts and requested changes soon, please.

2020-02-01 17:44 UTC, closed without merging