Nightshift improvements: public area settings/levels, nightshift auth requirement change, config changes, etc etc
citadel-station/citadel-main pull request #10417
Opened 2020-01-03 08:04 UTC by kevinz000

## About The Pull Request

Nightshift is much more configurable. 

## Why It's Good For The Game

People hate nightshifts as they are now. This makes them less obnoxious by default, and able to be by default set without an ID in most places.
Having the functionality is nice for a light dim switch.

## Changelog
:cl:
config: Added a few more nightshift config entries
add: nightshift_public_area variable in areas to determine how public an area is.
add: NIGHT_SHIFT_PUBLIC_AREAS_ONLY config entry allows the server to be configured to only nightshift areas of that level and below (so areas that are more public)
add: Config entries added for requiring authorizations to toggle nightshift. Defaults to only requiring on public areas as determined by above
/:cl:

2020-01-13 14:18 UTC, Ghommie requested changes

2020-01-13 14:18 UTC, Ghommie commented on code/modules/power/apc.dm
> +	var/authorized = (!locked || !usr.has_unlimited_silicon_privilege || failure_timer || (integration_cog && (is_servant_of_ratvar(usr))))
```suggestion
	var/authorized = (!locked || usr.has_unlimited_silicon_privilege || (integration_cog && (is_servant_of_ratvar(usr))))
```

2020-01-13 14:18 UTC, Ghommie commented on code/modules/power/apc.dm
> +	if(authorized)
Early return.

2020-01-13 14:18 UTC, Ghommie commented on code/modules/power/apc.dm
> +		. = TRUE
```suggestion
		return TRUE
```

2020-01-16 01:02 UTC, dapnee commented
Kevin broke APCs, AI's can't interact with them thanks.

2020-01-16 02:17 UTC, Ghommie approved these changes

2020-01-16 02:17 UTC, Ghommie commented
The interaction issue was pointed out and fixed.

2020-01-16 02:21 UTC, merged