Makes monkey gorrilize on radiation easier to achieve
citadel-station/citadel-main pull request #10466
Opened 2020-01-07 07:45 UTC by kevinz000

## About The Pull Request

Title

## Why It's Good For The Game

Gorillas are too rare no one does this anymore this is hilarious

## Changelog
:cl:
balance: monkies gorrilize easier now
/:cl:

2020-01-18 03:12 UTC, Ghommie requested changes

2020-01-18 03:12 UTC, Ghommie commented on code/modules/mob/living/carbon/monkey/life.dm
> +		if(prob(max(0, radiation - RAD_MOB_MUTATE) / 25))
I imagine we should add a variable one line above and then check if such variable is greater than 0 before running prob() every tick.

2020-01-20 20:49 UTC, Ghommie commented
Interesting, the web editor straight out is unable to resolve line endings as I suspected many times, how awful.

2020-01-20 21:05 UTC, kappa-sama commented
now ghommie feels the true power of the web editor..

2020-01-20 21:05 UTC, Ghommie approved these changes

2020-01-26 04:50 UTC, merged