[s] i'm trying to sneak around
citadel-station/citadel-main pull request #10502
Opened 2020-01-10 04:43 UTC by Linzolle

2020-01-10 04:44 UTC, deathride58 approved these changes

2020-01-10 04:44 UTC, deathride58 requested changes
actually wait put this under the if(holder) check

2020-01-10 04:44 UTC, Linzolle commented
ah right

2020-01-10 05:33 UTC, deathride58 approved these changes

2020-01-11 14:24 UTC, Ghommie approved these changes
Ummh, Colonel Burger.

2020-01-11 14:24 UTC, merged