Halves research points obtained through bombs.
citadel-station/citadel-main pull request #10512
Opened 2020-01-10 21:02 UTC by chefferz

Does as it says on the tin.

Getting a bit exhausting seeing research make a 50k point bomb sub 10 minutes into the shift and have a fully decked out research tree that can counter whatever has been announced. This makes it less stronger, because it seems almost every antagonist now has to hard counter science far too early in the shift.

2020-01-10 21:39 UTC, kappa-sama commented
just a note that deleting toxins will just tell people to find out the other far far more broken methods of gaining points, and toxins is a 1 and done flat gain that requires knowledge of how atmos works (or a guide) where-as the other methods of gaining points don't have a cap and can gain points faster without having a guide

2020-01-10 21:39 UTC, Hatterhat commented
:salt:

2020-01-10 21:42 UTC, GrayRachnid commented
Time to bring forth the meta of harvesting corpses.

2020-01-10 21:49 UTC, GrayRachnid requested changes

2020-01-10 21:49 UTC, GrayRachnid commented on code/game/machinery/doppler_array.dm
> +		point_gain = (41650 * orig_light) / (orig_light + 3000)
This shouldn't have been touched.

2020-01-10 21:59 UTC, silicons requested changes
Bad nerf, there's ways to make toxins more interesting or atleast more hands on/less blindfire that doesn't make it useless/near useless and still the same boring run (average scientists run it in 10 minutes).

I'd rather something else be done like requiring a far lower specific range of detonation (which forces people to figure it out although I'm sure someone will make a calculator or some shit), which will make toxins more interactive.
There's in general not enough ways to get points. There's no reason to hammer down one of the only ones.

2020-01-10 21:59 UTC, chefferz commented
> 
> 
> just a note that deleting toxins will just tell people to find out the other far far more broken methods of gaining points, and toxins is a 1 and done flat gain that requires knowledge of how atmos works (or a guide) where-as the other methods of gaining points don't have a cap and can gain points faster without having a guide

If you know of ways to cheese points, then bring them up.

2020-01-10 22:01 UTC, chefferz commented
> 
> 
> Bad nerf, there's ways to make toxins more interesting or atleast more hands on/less blindfire that doesn't make it useless/near useless and still the same boring run (average scientists run it in 10 minutes).
> 
> I'd rather something else be done like requiring a far lower specific range of detonation (which forces people to figure it out although I'm sure someone will make a calculator or some shit), which will make toxins more interactive.
> There's in general not enough ways to get points. There's no reason to hammer down one of the only ones.

Gonna be honest and would like a bit more input from maintainers where this isn't their bread and butter. Getting "gamered" because research has enough points 10 minutes in to neuter you as an antag is ridiculous. All this does is delete 10 minutes worth of points.

2020-01-10 22:33 UTC, GrayRachnid commented
>If you know of ways to cheese points, then bring them up.

>Time to bring forth the meta of harvesting corpses.

2020-01-11 06:56 UTC, davidchan13 commented
There is not enough reliable point generation as is and toxins isn't repeatable, and now you want to nerf that even when science rarely maxes out on research anyways? Why.

2020-01-11 09:37 UTC, Putnam3145 commented
Hyper-noblium production gets me 250000 if I did really, really badly, and 1.5 million on average. BZ production lets you make some points without much issue by just pumping a bit of plasma and N2O into the scrubbers pipes. You can deconstruct slime crossbreeds in the destructive analyzer for 2000 points *at least*.

Personally? Cap it at 50000, but you can't do it in one bomb.

2020-01-13 01:55 UTC, keronshb commented
If anything I think the PR should be increasing costs of weapon-based tech trees, rather than the bomb.  Research nanites were also introduced to make points come by faster as well, so rushing nanites after parts has a use now too.

Most of the time the bomb will be rushed to get the parts needed for the station + BoH.  About halfway through making the bomb the miners will already have Mining + Mining Satchels.  So by the time the bomb is finished you should be able to comfortably get all tiers of parts + whatever you want.  So if the points for weapons were raised, this would dissuade weapon rushing if this is the issue and it could be put into more research related trees like nanites or dissection surgery.

2020-01-21 01:30 UTC, Ghommie commented
Seems like most players and staff is not really in favor of this change.. I honestly don't care too much but there could always be a few other ways to shake off bombastic research, it's not top priority.

2020-01-21 01:30 UTC, closed without merging