you like examining things? - port of tgstation 40920
citadel-station/citadel-main pull request #10520
Opened 2020-01-11 04:57 UTC by Hatterhat

i swear to god i fucking tested this kinda sorta just with protolathes
## About The Pull Request
ports tgstation/tgstation#40920
## Why It's Good For The Game
"god i sure love not having to hit a machine with a BRPED to know that it's upgraded"
## Changelog
:cl: Denton, ported by Hatterhat
tweak: Most upgradeable machines now show their upgrade status when examined while standing right next to them.
tweak: Added examine messages to teleporter stations that hint at their multitool/wirecutter interactions.
tweak: Renamed teleporter stations from station to teleporter station.
code: Changed the teleporter hub accurate var to accuracy; the old name misled people into thinking that it was a boolean.
/:cl:

2020-01-11 20:03 UTC, Ghommie requested changes
You forgot to update most of these examine changes to the current refactored code.
Ergo: `. = ..()` instead of `..()` and `. += msg` instead of `to_chat(user, msg)`.

2020-01-12 08:47 UTC, Hatterhat commented
in my defense it was a straight copy-paste from the original PR

2020-01-12 22:24 UTC, Ghommie commented
Yes, but that was from before examine was refactored to use a list of text keys joined together with the newline macro.

2020-01-19 15:37 UTC, Ghommie approved these changes

2020-01-19 15:37 UTC, merged