pixel-based, non-screenshake recoil
citadel-station/citadel-main pull request #10540
Opened 2020-01-12 05:05 UTC by Hatterhat

## About The Pull Request
port of vgstation-coders/vgstation13#25163

warning: may somehow break burstfire? maybe it's just my broken copy of the code? i don't fucking know someone PLEASE double check that shit
## Why It's Good For The Game
screenshake for recoil sucks @deathride58 
## Changelog
:cl:
tweak: Recoil is now pixel-based and not just screenshake.
/:cl:

2020-01-12 05:12 UTC, deathride58 requested changes

2020-01-12 05:12 UTC, deathride58 commented on code/modules/mob/mob_helpers.dm
> +	sleep(2)
Please use timer callbacks instead of sleep()

2020-01-12 05:13 UTC, deathride58 commented
Keeping screenshake recoil for weapons with a lot more oomph behind them like shotguns and sniper rifles would probably be recommended.

2020-01-18 18:39 UTC, Ghommie requested changes

2020-01-18 18:39 UTC, Ghommie commented on code/__HELPERS/unsorted.dm
> +/proc/get_angle(atom/a, atom/b)
I'm unsure this has the same results as `Get_Pixel_Angle` but anyway give it a different name, it can be easily confused with `Get_Angle`.

2020-02-05 06:29 UTC, Ghommie commented
Yo, perhaps I'll do this port myself later if you are having some issues with it. Ok?

2020-02-16 06:53 UTC, closed without merging