PDA blocking
citadel-station/citadel-main pull request #10608
Opened 2020-01-19 02:22 UTC by kevinz000

## About The Pull Request

Adds simple PDA message blocking

## Why It's Good For The Game

mass message spam/message spam is funny until it gets unfunny.

## Changelog
:cl:
add: you can now block people on your PDA
/:cl:

2020-01-20 02:01 UTC, Ghommie requested changes
A few suggestions.

2020-01-20 02:01 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +/obj/item/pda/proc/unblock_pda(mob/user, unblock_target)
I think these two procs should consolidated into one toggle, so players who blocked someone accidentally by misclicking the button can unblock them by clicking it again

2020-01-20 02:01 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +							dat += "<li><a href='byond://?src=[REF(src)];choice=Message;target=[REF(P)]'>[P]</a>"
You could as well add the block button here too, just in case someone wants to pre-emptively block another PDA, it's not a big deal.

2020-01-20 02:01 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +		to_chat(user, "<span class='warning'>[icon2html(src, user)] The following PDAs have blocked your message: [string_blocked].</span>")
```suggestion
		to_chat(user, "<span class='warning'>[icon2html(src, user)] The following recipients have blocked your message: [string_blocked].</span>")
```
Minor peeve, just for clarity.

2020-01-20 02:01 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +	tnote += "<i><b>&larr; From <a href='byond://?src=[REF(src)];choice=Message;target=[REF(signal.source)]'>[signal.data["name"]]</a> ([signal.data["job"]]):</b></i> <a href='byond://?src=[REF(src)];bl
That's the PDA message history anyway, is it intended for the block href link not to display in the chat?

Also I'd like to point out that the PDA messaging console can also send messages and how the hrefs lack sanity checks to stop runtimes from happening if people try to reply or block messaging console, deleted PDAs or unrelated atoms through href exploits.

https://github.com/tgstation/tgstation/blob/57ef294efdf0842a8abe8da0ebf35a0393c45a1c/code/game/objects/items/devices/PDA/PDA.dm#L547 is how the message href issue was fixed on tg, you propably gotta do something similar for (un)blocking.

2020-01-20 02:01 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +		for(var/mob/M in GLOB.player_list)
Should be `for(/mob/dead/observer/O in GLOB.player_list)` considering there is already an observer typecheck below (and remove said typecheck).

2020-01-20 05:41 UTC, kevinz000 commented on code/game/objects/items/devices/PDA/PDA.dm
> +							dat += "<li><a href='byond://?src=[REF(src)];choice=Message;target=[REF(P)]'>[P]</a>"
intentional so people don't metablock anyone

2020-01-21 00:16 UTC, Ghommie requested changes

2020-01-21 00:16 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +				toggle_blocking(usr, href_list["target"])
```
				var/obj/item/pda/P = locate(href_list["target"]) in GLOB.PDAs
				if(P)
					toggle_blocking(usr, P)
```
or
```
				toggle_blocking(usr, locate(href_list["target"]) in GLOB.PDAs)
```
Though, in the latter case, it's still required to check if the target exists or not in the proc itself.

2020-01-21 00:16 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +				block_pda(usr, href_list["target"])
Idem.

2020-01-21 00:16 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +				unblock_pda(usr, href_list["target"])
Idem.

2020-01-21 00:16 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +							dat += "<li><a href='byond://?src=[REF(src)];choice=Message;target=[REF(P)]'>[P]</a>"
I mean, it's not a big deal but fine.

2020-01-21 00:16 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +	tnote += "<i><b>&larr; From <a href='byond://?src=[REF(src)];choice=Message;target=[REF(signal.source)]'>[signal.data["name"]]</a> ([signal.data["job"]]):</b></i> <a href='byond://?src=[REF(src)];ch
This is going to be a fairly obscure feature if the blocking option is only added to the notes and not displayed in the chat message. Is it intended?

2020-01-21 00:59 UTC, Ghommie commented on code/game/objects/items/devices/PDA/PDA.dm
> +				toggle_blocking(usr, href_list["target"])
EDIT: it uses the owner name as target, I'm dumb and no real issue here.

2020-01-21 01:13 UTC, Ghommie approved these changes

2020-01-21 01:13 UTC, merged