Craftable Switchblades, except I've made this PR four times now with each time fucking up worse than the last.
citadel-station/citadel-main pull request #10644
Opened 2020-01-22 00:14 UTC by ShadeAware

## About The Pull Request
**AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA**
Adds Makeshift Switchblades, an easily concealed retractable self defense tool.

## Why It's Good For The Game
More variety when it comes to petty crime, weapons crafting, self defense tools, and antaging! Helps aid realism as not many people would want to carry around an entire _Butcher's Cleaver_, but may be more inclined to go through the effort of getting a Switchblade.

## Changelog
:cl:
add: Makeshift Switchblades, a weaker subtype of normal switchblades that can be crafted using a Kitchen Knife, Modular Receiver, Rifle Stock and some Cable Coil. Requires a welder to complete.
/:cl:
_God please let this work this time, I'm so very tired._

2020-01-22 00:16 UTC, ShadeAware commented
God please let this work this time without issue.

2020-01-22 00:16 UTC, ShadeAware commented
Also I fixed the throwing code bit so everything should work fine now. Keyword is _should_
 but fucking nothing else has been so far so I don't fucking know haha :joy:

2020-01-22 09:54 UTC, Arturlang commented
You are pring from your master which isnt reccomended, also, please stop with making excessive new prs and actually use git

2020-01-22 12:10 UTC, ShadeAware commented
I'm trying yet failing

2020-01-22 17:56 UTC, Commandersand commented
15 damage pocket knife, yikes
looks fun

2020-01-22 23:02 UTC, ShadeAware commented
### **ARE YOU PROUD OF ME NOW GHOMMIE?**

2020-01-23 03:54 UTC, Ghommie commented on code/game/objects/items/weaponry.dm
> +/obj/item/switchblade/makeshift //It took me so fucking long to make this not shitcode holy FUCK. GODDAMN IT. SHIT. FUCK. NI-
No need to be so upset-ti in the comment, my gucci.

2020-01-23 15:35 UTC, Ghommie requested changes
Sprites are roughly the same as the base switchblade, nothing makeshift-looking.

2020-01-23 16:32 UTC, ShadeAware commented
> Sprites are roughly the same as the base switchblade, nothing makeshift-looking.

The switchblades are supposed to keep the same style, so theres more reason to use them besides being concealed.
Tbh over time these have become less makeshift and more craftable so I _might_ do a name change to clear up the confusion.

2020-01-23 21:43 UTC, ShadeAware commented
Did a name change from makeshift to crafted because I refuse to compromise on the sprite. Its too sexy to not include.

2020-01-26 21:44 UTC, ShadeAware commented
### The makeshift sprites cometh; down with Security, the Grey Tide rises in Wood and Steel.

2020-01-30 02:25 UTC, ShadeAware commented
Travis does not like me very much does he.

2020-01-30 02:29 UTC, Ghommie commented
No, this time that was my mistake with unbalanced parenthesis.
Please be careful when web-editing.

2020-01-30 20:30 UTC, Ghommie approved these changes

2020-01-30 20:30 UTC, merged