adds in a 'no eorg' preference that teleports you to the ghost cafe in round end
citadel-station/citadel-main pull request #10675
Opened 2020-01-23 14:44 UTC by Seris02

## About The Pull Request

see title

## Why It's Good For The Game

Because people get salty over eorg and this is one way to stop it, at least for a while until I have to code in some edge case to stop them from eorging in the ghost cafe.

## Changelog
:cl:
add: Ability to be transported to the ghost cafe on roundend instead of eorg
/:cl:

2020-01-23 15:06 UTC, Ghommie requested changes
I have a certain perplexity on this feature.
Under normal conditions, the game will restart in 1 minute anyway, so roleplay is irrelevant.
On delayed restarts, people may assume the cafe as a no EORG zone and ahelp the grievers while the admins are busy dealing with other tickets.

2020-01-23 15:06 UTC, Ghommie commented on code/__HELPERS/roundend.dm
> +	for(var/mob/m in GLOB.mob_list)
One, all atoms in mob_list should be mobs, so the typecheck is not necessary versus a new line `var/mob/M = m`.
Two, it'll tele people left stranded on the station to the ghost cafe too.
Third, I think it should be better if you used the player_list.

2020-01-23 15:06 UTC, Ghommie commented on code/__HELPERS/roundend.dm
> +		if (m.client)
Early return if they don't have a client.

2020-01-23 15:06 UTC, Ghommie commented on code/__HELPERS/roundend.dm
> +				for (var/obj/item/W in H)
```
				for (var/i in H.get_equipped_items(TRUE))
					var/obj/item/I = i
```

2020-01-23 15:06 UTC, Ghommie commented on code/__HELPERS/roundend.dm
> +			if (ishuman(m))
the human check is only necessary for the uniform and shoes. bring it down there.

2020-01-23 15:06 UTC, Ghommie commented on code/__HELPERS/roundend.dm
> +					H.dropItemToGround(W)
Oh yea, btw this will light plasmamemes on fire.

2020-01-23 17:18 UTC, Putnam3145 commented on code/__HELPERS/roundend.dm
> +	for(var/mob/m in GLOB.mob_list)
For reference: the second line is faster than the typecheck. You should prefer it when it's possible to do.

2020-01-23 17:18 UTC, Putnam3145 commented on code/__HELPERS/roundend.dm
> +			if (ishuman(m))
Also, this shouldn't be ROUNDSTART_TRAIT added, though it's kind of hilariously irrelevant

2020-01-23 20:05 UTC, Seris02 commented on code/__HELPERS/roundend.dm
> +				for (var/obj/item/W in H)
why though

2020-01-23 20:05 UTC, Seris02 commented on code/__HELPERS/roundend.dm
> +			if (ishuman(m))
and the revival but ok

2020-01-23 20:06 UTC, Seris02 commented on code/__HELPERS/roundend.dm
> +					H.dropItemToGround(W)
true.

2020-01-23 20:14 UTC, Ghommie commented on code/__HELPERS/roundend.dm
> +				for (var/obj/item/W in H)
cavity implants, and any other item that's not equipped but found inside the mob anyway.

2020-01-24 00:28 UTC, Seris02 commented on code/__HELPERS/roundend.dm
> +				for (var/obj/item/W in H)
it works for the ninja net though but alright.

2020-01-24 01:53 UTC, kevinz000 commented
this is just hugbox

2020-01-24 01:54 UTC, Seris02 commented
basically yeah

2020-01-24 01:57 UTC, Seris02 commented on code/__HELPERS/roundend.dm
> +	for(var/mob/m in GLOB.mob_list)
I want it to tele people on the station with this on, and it does it after it collects the roundend report, so it shouldn't affect anything.

2020-01-25 03:00 UTC, Ghommie commented
This is irrelevant, you can still use the ghost cafe in case of delayed round ends.

2020-01-25 03:00 UTC, closed without merging