The Bark Box vendor for pet items, with new pet items and fun.
citadel-station/citadel-main pull request #10719
Opened 2020-01-26 00:02 UTC by ItzGabby

## About The Pull Request
Merges most if not all pet fluff items all into their own collective files for people to add onto, which adds two new sets of fluff items, rubber bones, and frisbees. The tennis balls and frisbees not only can be used as fluff items but now usable with special launchers which then can fire them. 
## Why It's Good For The Game
Adds new items for flavor to the server fluff wise, new separate vendor-with a wide selection of items, and contraband/premium items-also allows for more map specific genre's for targeted audiences for more immersive environments. Generally new fun looking stuff is fun for everyone most of the time.
## Changelog
:cl:
add: Chewy bones, frisbees, launchers for tennis balls and frisbees, cargo order for the vendor, machine boards, and main menu backpack loadout slots.
del: Previous ball fluff files
imageadd: Moved ball fluff DMI's into one big fluff DMI's for fluff items, mouth and handheld sprites along with vendor DMI's.
imagedel: Previous ball fluff DMI's.
/:cl:

2020-01-26 17:29 UTC, Ghommie requested changes
Tbh, save for special ones, all other tennis balls/frisbees and bones should be of an unique grayscale type (check wirecutters and hyper-eutactic blades for examples).
You really shouldn't follow the same path of whoever added tennis balls in first place, please keep this relatively minor feature slim instead.

2020-01-26 17:29 UTC, Ghommie commented on code/game/objects/items/flufflaunchers.dm
> +	damage = 0
Save for the icon_state, all these variables are the same for most if not all ball projectiles, so just move them to the `/obj/item/projectile/bullet/reusable/ball` parent type

2020-01-26 17:29 UTC, Ghommie commented on code/game/objects/items/flufflaunchers.dm
> +	damage = 0
Same here, for `/obj/item/projectile/bullet/reusable/frisbee`

2020-01-26 17:29 UTC, Ghommie commented on code/game/objects/items/flufflaunchers.dm
> +/*		2077 WARCRIMES ARE NOW LEGAL
This file should be moved to the `code/modules/projectiles/guns/ballistic` folder.

2020-01-26 17:29 UTC, Ghommie commented on code/game/objects/items/fluff.dm
> +/*		FLUFFY FUN
tennis balls and frisbees should be moved to the `code/modules/projectiles/ammunition/caseless` folder, and the projectiles to the `code/modules/projectiles/projectile/reusable` one.

2020-01-27 03:54 UTC, ItzGabby commented on code/game/objects/items/flufflaunchers.dm
> +	damage = 0
Right, so I can just slim it down to the icon_states, gotcha. First time making weapons to be honest.

2020-01-27 05:32 UTC, ItzGabby commented on code/game/objects/items/flufflaunchers.dm
> +	damage = 0
> Tbh, save for special ones, all other tennis balls/frisbees and bones should be of an unique grayscale type (check wirecutters and hyper-eutactic blades for examples).
> You really shouldn't follow the same path of whoever added tennis balls in first place, please keep this relatively minor feature slim instead.
So after a good two hours I've been doing some thinking.
This basically is asking me to change everything I've done, although I'll still do this. I'll probably work on something with the polychromic system, and I'll have to rethink and remake how I've done the weapons. While saying to keep this slim, just possibly doing the polychromic system and reworking how the projectiles are might just expand it further. But that's possibility and I'll have to compare after once I'm done and all that.

2020-01-27 14:30 UTC, Ghommie commented on code/game/objects/items/flufflaunchers.dm
> +	damage = 0
Don't do a polychromatic clothing copypaste, just stick with the monochomatic here.

2020-02-21 01:40 UTC, Ghommie commented
Stale jank.

2020-02-21 01:40 UTC, closed without merging