Winter Coat Rebalancing, Fixes, Etc.
citadel-station/citadel-main pull request #10778
Opened 2020-01-30 01:17 UTC by Tupinambis

## About The Pull Request

Ensures winter coats are proper sidegrades to equivalent suit slot items instead of the current weirdness. Winter coats typically cover more body and protect from cold than standard armor, so in those cases armor is slightly worse and fire resistance is very poor. Winter coats should also now all have proper suit slot lists (You can carry the egun on HoP coat for example.) Also minor descriptions to emphasize the sidegrade nature of winter coats.

## Why It's Good For The Game

Winter coats shouldn't be completely useless nor should they be a straight upgrade from the common alternatives, this should hopefully resolve those issues and ensure winter coats are a proper sidegrade (and a lizard/slime favorite). Argue about locker itemcreep in the comments below.

## Changelog
:cl: Tupinambis
balance: rebalances armor values and protections to be more in line with what a sidegrade should be.
fix:  Winter coats should now use armor values closer to expected, and be able to fit the suit slot items that are expected.
/:cl:

2020-01-30 01:22 UTC, Seris02 commented on code/modules/clothing/suits/miscellaneous.dm
> +	allowed = null
>You can carry the egun on the HoP winter coat now

at least fix it or update your PR description

2020-01-30 01:29 UTC, Seris02 commented on code/modules/clothing/suits/miscellaneous.dm
> +	allowed = list(/obj/item/gun/energy, /obj/item/melee/baton, /obj/item/restraints/handcuffs, /obj/item/tank/internals/emergency_oxygen, /obj/item/tank/internals/plasmaman)
at least make it have all the allowed things from a normal winter coat too

2020-01-30 01:30 UTC, Seris02 commented on code/modules/clothing/suits/miscellaneous.dm
> +	flags_inv = HIDEGLOVES|HIDESHOES|HIDEJUMPSUIT
but it doesn't hid the jumpsuit, think of anyone wearing a CC winter coat and say, a science jumpsuit with pants

2020-01-30 01:53 UTC, ShadeAware commented
Can we finally carry flashlights in the exosuit slot now

2020-01-31 10:45 UTC, Arturlang commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 80, "bullet" = 80, "laser" = 50, "energy" = 50, "bomb" = 100, "bio" = 100, "rad" = 100, "fire" = 90, "acid" = 90)
Are you sure this is admin only? Its better than basically all the station armor at no slowdown.

2020-02-02 16:53 UTC, Ghommie requested changes

2020-02-02 16:53 UTC, Ghommie commented on code/modules/clothing/suits/miscellaneous.dm
> +	flags_inv = HIDEGLOVES|HIDESHOES|HIDEJUMPSUIT
Remove this line, it will cause wearers to appear naked behind the coat.

2020-02-02 16:53 UTC, Ghommie commented on code/modules/clothing/suits/miscellaneous.dm
>  /obj/item/clothing/suit/hooded/wintercoat/centcom
The changes done to this subtype are too excessive. This is not meant for deathsquads.

2020-02-02 16:53 UTC, Ghommie commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 80, "bullet" = 80, "laser" = 50, "energy" = 50, "bomb" = 100, "bio" = 100, "rad" = 100, "fire" = 90, "acid" = 90)
Remove armor changes.

2020-02-02 16:53 UTC, Ghommie commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 45, "bullet" = 35, "laser" = 45, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 35, "acid" = 85)
Remove melee/bullet/laser changes.

2020-02-02 16:53 UTC, Ghommie commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 25, "bullet" = 25, "laser" = 25, "energy" = 10, "bomb" = 20, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 45)
Lower armor buffs.

2020-02-02 16:53 UTC, Ghommie commented on code/modules/clothing/suits/miscellaneous.dm
> +		allowed = GLOB.security_vest_allowed
Just do this:
```
	allowed |= GLOB.security_vest_allowed
```

2020-02-02 16:53 UTC, Ghommie commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 0, "bullet" = 0, "laser" = 0, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 40, "acid" = 100)
Ah, the bomb protection is fine considering toxins bomb making.

2020-02-09 21:16 UTC, Ghommie commented on code/modules/clothing/suits/miscellaneous.dm
> +	allowed |= GLOB.security_vest_allowed
```suggestion
	allowed += GLOB.security_vest_allowed
```
Turns out allowed is null by default. My bad.

2020-02-14 14:08 UTC, closed without merging