Well Deserved Pepperspray Buffs. Now you can actually use it!
citadel-station/citadel-main pull request #10802
Opened 2020-01-31 05:19 UTC by Tupinambis

## About The Pull Request

Pepperspray has been buffed by a large amount. It now ONLY checks for gas protection (which only gas masks, bio suits, rad suits?, and space suits have.) and has had it's stamina damage increased to 30 from 25. Very slight pretty much negligable nerf to confusion since that's more Flashes thing.

As it stands, this weapon has a mix of both Flash and Stunbaton traits, and most importantly has a hard knockdown (It disarms!) which if #10741 gets merged, means pepperspray has a leg up, especially against conversion antags and groups of enemies. 

This should result in conversion antags just being a tad easier to deal with, as not everyone will have a mask.

*I swear to god if you can print gas masks at the lathe*

## Why It's Good For The Game

Pepperspray is quite literally useless currently, and I think it's an awfully pretty fun and unique option to just never be used. These change should hopefully result in pepperspray getting regular and standard use.

## Changelog
:cl: Tupinambis
balance: Pepperspray now only checks gas protection, and does more stamina damage.
/:cl:

2020-01-31 08:12 UTC, KrabSpider commented
Shouldn't there be a minimum on the amount of capsaicin you need to induce the effects...?
I have a bit of concern about the possibility of people breaking into security checkpoints, filling up a spray bottle of *any* kind with pepperspray from the refill stations to have a 2-tile range that ignores shields and projectile immunity without much concern for running out of charge or the like.

This seems pretty overtuned.

2020-01-31 08:30 UTC, kevinz000 commented
if we remove hardstuns from a staple of melee for security why would we increase the power of a resprited and speedier spray bottle with how downright stupid reagent spraying code is?

2020-01-31 15:02 UTC, Commandersand commented
reagent spray code is funny, it INJECTS it into you instead of spraying it
why?

2020-01-31 18:02 UTC, Tupinambis commented
I undid the stamina damage buffs, probably dumb move.

2020-02-01 17:41 UTC, Ghommie requested changes

2020-02-01 17:41 UTC, Ghommie commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +		if (face_covered)
At this point, just replace lines 291-297 with this:
```
		if (victim.wear_mask && victim.wear_mask.clothing_flags & BLOCK_GAS_SMOKE_EFFECT)
				return
```

2020-02-21 01:37 UTC, Ghommie commented
Hello?

2020-02-27 00:12 UTC, closed without merging