Mining Update : Anti-Shitter versions
citadel-station/citadel-main pull request #10832
Opened 2020-02-01 05:13 UTC by r4d6

This is a response about the "complains" that I got concerning the public mining base.

## About The Pull Request
I was told that people broke in the miner-only section of the mining base
I was told that shitty miners took more than 1 PKA, with 3 max being available roundstart

So I stuffed 10 PKA in a crate on the miner's side.
I put R-walls and a vault door to separate the miner's side.

There, now you have more PKA to yoink when someone take 2 PKA instead of one, and Shitters can't break in the miner's side to cause shit.

## Why It's Good For The Game
_**Less shitters complain, are you happy now?**_

## Changelog
:cl:
change: Mining is harder to shitters
/:cl:

2020-02-01 05:49 UTC, Owai-Seek commented
The only issue was that the spare lockers were removed, and people wanted them back.

2020-02-01 11:57 UTC, YakumoChen commented
ok but can you make a version of this PR that isn't retarded

2020-02-02 05:15 UTC, Ghommie commented
What Chen said, a couple spare PKAs would suffice. 10 PKAs are excessive, and same can be said about the r-wall and vault door. Just make sure the windows are of reinforced plasma glass and the underneath grilles connected to the power grid.

2020-02-02 05:16 UTC, Ghommie requested changes
What Chen said, a couple spare PKAs would suffice. 10 PKAs are excessive, and same can be said about the r-wall and vault door. Just make sure the windows are of reinforced plasma glass and the underneath grilles connected to the power grid.

2020-02-02 08:38 UTC, kevinz000 commented
like i said yesterday in discord is there a reason to not just put the 3 mining lockers in the mining part and call it a day, why is all this necessary.

2020-02-05 06:04 UTC, Ghommie approved these changes

2020-02-05 06:20 UTC, merged