Makes a proc for meteor string gen along with adding a bit for meteor alerts to change based on type
citadel-station/citadel-main pull request #10854
Opened 2020-02-02 05:22 UTC by Seris02

## About The Pull Request

Meteor alerts now go:
- catastrophic: An entire asteroid field has been detected...
- threatening: An abundance of meteors have been detected...
- normal: Meteors have been detected...

also makes a proc for meteor string generation becuase
### NOBODY FUCKING UPDATES THE HALLUCINATION TEXT SO NOW I DON'T HAVE TO FUCK WITH IT ANYMORE THANK YOU

## Why It's Good For The Game

better code? + meteor alert levels

## Changelog
:cl:
add: meteor alert level to the announcement
fix : meteor hallucinations (again)
/:cl:

2020-02-02 05:23 UTC, kevinz000 commented
i don't like giving everyone the knowledge of what kind of wave but i'm also not not liking it enough to deny this /shrug

2020-02-04 04:37 UTC, Ghommie requested changes
Remove the threat specification strings, they only butcher the weak thrill and suspence of unknown threats out the game furthermore.

2020-02-04 05:23 UTC, Seris02 commented
fuck that was my favorite part of coding this

2020-02-04 07:15 UTC, Ghommie approved these changes

2020-02-04 07:15 UTC, merged