Buffs carps again
citadel-station/citadel-main pull request #10894
Opened 2020-02-04 12:14 UTC by Trilbyspaceclone

## About The Pull Request

Normal and Mega carps have 10~ 20~ more HP
Mega carps lower damage add on is now 4 to 10 rather then 2 to 10
The Nukie carp now can regen passively 
## Why It's Good For The Game

The nukie carp is a ghost role that will likely take a few hits and then die, or sit on the shuttle/space well the team dies/wins the game mode. Having it stuck in a "man if only they would heal me" mode kinda sucks and makes them more usefull

As for carp hp buffs, they go down in 2-3 hits with a spear/tool box and are not that much of a threat to anyone in space. 

Mega carps are buffed a bit more so that they are less of a hit it /4 to 5!/ times and have them bit a less squishy for being a massive mob that can mess you up if you dont prepare for the fight

## Changelog
:cl:
add: Carps have evolved to take more damage
/:cl:

2020-02-04 12:35 UTC, Arturlang commented
Sounds good, carp really needed a buff anyways.

2020-02-04 20:59 UTC, BlueWildrose commented
An indirect buff to the dehydrated space carp traitor item too. Nice.

2020-02-04 23:00 UTC, Ghommie requested changes

2020-02-04 23:00 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +
Move this procedure to the base space carp type and add a new variable to toggle the health regeneration for Cayenne and mega carps.

2020-02-05 02:07 UTC, Ghommie requested changes

2020-02-05 02:07 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +	else
Replace these three lines with
```
	if(regen)
```

2020-02-05 02:07 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +	if(regen_cooldown < world.time)
```suggestion
	if(regen && regen_cooldown < world.time)
```

2020-02-05 02:07 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +	var/heal_amout = 0 //How much is healed pre regen cooldown
You could merge `regen` and `heal_amount` into an unique var.

2020-02-05 05:13 UTC, Ghommie approved these changes

2020-02-05 17:32 UTC, merged