Buffs the Pirate Ship to be bomb resistant
citadel-station/citadel-main pull request #10926
Opened 2020-02-05 23:30 UTC by keronshb

## About The Pull Request

Title, also makes a few computers/machines indestructible and buffs turret health.  It also allows turrets to be repairable now.

## Why It's Good For The Game

Bomber man bad.

## Changelog
:cl:
add: Added repairable turrets
tweak: made the pirate shuttle + turrets bomb resistant
tweak: made most pirate machines + consoles indestructible
tweak: increased pirate turret health
/:cl:

2020-02-07 01:55 UTC, Detective-Google commented
the pirate ship is already made of plastitanim which is bomb resistant, if you let the crew get to your  ship/find where it is and plant a bomb you should be punished for it and the pirates already have relevant protection.

2020-02-07 21:32 UTC, keronshb commented
> 
> 
> the pirate ship is already made of plastitanim which is bomb resistant, if you let the crew get to your ship/find where it is and plant a bomb you should be punished for it and the pirates already have relevant protection.

I think the issue here is that there's players (and borgs) actively hunting for the ship, and the Nukie ship, just to do a one and done bomb/console destroy/turret destroy.  This isn't with the Data Siphon on, it's with it off.  This will help prevent what I would argue is bad matching.

2020-02-07 22:45 UTC, Ghommie requested changes
Also you removed two couple directional windows from where the incomplete artillery mounts are, potentially exposing the area to depressurized space. Please fix that.

2020-02-07 22:45 UTC, Ghommie commented on code/game/machinery/porta_turret/portable_turret.dm
> +/obj/machinery/porta_turret/attackby(obj/item/I, mob/living/user, params)
Use the `welder_act` proc instead.

2020-02-07 22:45 UTC, Ghommie commented on code/game/objects/structures/window.dm
> +/obj/structure/window/plastitaniumpirate
Make this a subtype of `/obj/structure/window/plastitanium` and remove any duplicate variable statement on this path.

2020-02-07 22:45 UTC, Ghommie commented on code/game/turfs/simulated/wall/mineral_walls.dm
> +/turf/closed/wall/mineral/plastitaniumpirate
Make this a subtype of `/turf/closed/wall/r_wall/syndicate`, just for the description.

2020-02-07 22:45 UTC, Ghommie commented on code/game/turfs/simulated/wall/mineral_walls.dm
> +/turf/closed/wall/mineral/plastitaniumpirate/explosive/ex_act(severity)
Oh, remove this, please.

2020-02-09 20:37 UTC, Ghommie requested changes

2020-02-09 20:37 UTC, Ghommie commented on code/game/objects/effects/spawners/structure.dm
> +	explosion_block = 50
Remove this line, it's a spawner and its explosion_block value is totally meaningless.

2020-02-09 20:37 UTC, Ghommie commented on code/game/objects/structures/window.dm
> +	explosion_block = 50
Bring this down to 20, they shouldn't be more bomb proof than the syndicate's

2020-02-09 20:37 UTC, Ghommie commented on code/game/turfs/simulated/wall/mineral_walls.dm
> +/turf/closed/wall/mineral/plastitanium/pirate
I told you to make this a subtype of `/turf/closed/wall/r_wall/syndicate`.
Also remove the `explosion_block` value of 50, the parent type's 20 will suffice.

2020-02-09 20:37 UTC, Ghommie commented on code/game/turfs/simulated/wall/mineral_walls.dm
> +/turf/closed/wall/mineral/plastitanium/overspace/pirate/
Also you'll fuck up the smoothing if you don't move the `/pirate` path before `/overspace`, `/nosmooth` and `/nodiagonal`. 
Refer to https://github.com/Citadel-Station-13/Citadel-Station-13/blob/2acb52fb56a7ba8e3706f5e08bd515c3620f3588/code/game/turfs/simulated/wall/mineral_walls.dm#L261 for types' values.

2020-02-09 21:26 UTC, Ghommie requested changes

2020-02-09 21:26 UTC, Ghommie commented on code/game/machinery/porta_turret/portable_turret.dm
> +
This will affect other energy turrets outside the pirate ship ones, please make a new subtype for them space seafolks.

2020-02-09 21:26 UTC, Ghommie commented on code/game/machinery/porta_turret/portable_turret.dm
> +	explosion_block = 50
Change this with armor values:
```
	armor = list("melee" = 50, "bullet" = 30, "laser" = 30, "energy" = 30, "bomb" = 50, "bio" = 0, "rad" = 0, "fire" = 90, "acid" = 90)
```
That's the base turret armor plus 20 extra points of bomb armor.

2020-02-09 22:45 UTC, Ghommie requested changes

2020-02-09 22:45 UTC, Ghommie commented on code/game/machinery/porta_turret/portable_turret.dm
> +	armor = list("melee" = 50, "bullet" = 30, "laser" = 30, "energy" = 30, "bomb" = 50, "bio" = 0, "rad" = 0, "fire" = 90, "acid" = 90)
move the armor changes to the `/obj/machinery/porta_turret/syndicate/energy/pirate` path.

2020-02-09 22:45 UTC, Ghommie commented on code/game/machinery/porta_turret/portable_turret.dm
> +	desc = "An energy blaster auto-turret. Use a welder to fix."
Undo the desc change and instead add this line above the welder_act()
```
/obj/machinery/porta_turret/examine(mob/user)
	. = ..()
	if(obj_integrity < max_integrity)
		. += "<span class='notice'>Use a welder to fix it.</span>"
```

2020-02-09 22:45 UTC, Ghommie commented on code/game/objects/effects/spawners/structure.dm
> +/obj/effect/spawner/structure/window/plastitanium/pirate
Add back this line or it'll spawn normal plastitanium windows.
```
	spawn_list = list(/obj/structure/grille, /obj/structure/window/plastitanium/pirate)
```

2020-02-09 22:45 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +/turf/closed/wall/r_wall/syndicate/pirate/nodiagonal/
Remove the last slash from the line.

2020-02-09 22:45 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +/turf/closed/wall/r_wall/syndicate/pirate/nosmooth/
Same.

2020-02-09 22:45 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +/turf/closed/wall/r_wall/syndicate/pirate/overspace/
Idem.

2020-02-09 22:45 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +	explosion_block = 30
Remove, it's already the same as the parent type's

2020-02-09 22:45 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +	explosion_block = 30
Same

2020-02-09 22:45 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +	explosion_block = 30
Idem

2020-02-09 22:45 UTC, Ghommie commented on code/game/machinery/porta_turret/portable_turret.dm
> +	return
Remove this line.

2020-02-09 22:45 UTC, Ghommie commented on code/game/machinery/porta_turret/portable_turret.dm
> +/obj/machinery/porta_turret/welder_act(mob/living/user, obj/item/I)
add a `. = TRUE` line below.

2020-02-09 22:45 UTC, Ghommie commented on code/game/machinery/porta_turret/portable_turret.dm
> +			return TRUE
Remove this line.

2020-02-10 03:35 UTC, Ghommie requested changes

2020-02-10 03:35 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +	explosion_block = 30
Remove, `/turf/closed/wall/r_wall/syndicate/pirate` explosion_block is already 30.

2020-02-10 03:35 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +	explosion_block = 30
Same.

2020-02-10 03:35 UTC, Ghommie commented on code/game/turfs/simulated/wall/reinf_walls.dm
> +	explosion_block = 30
Same.

2020-02-10 07:39 UTC, Ghommie approved these changes

2020-02-10 07:40 UTC, merged