Adds the Captain's Wardrobe, removes a TON of Captain's Locker bloat items.
citadel-station/citadel-main pull request #10975
Opened 2020-02-08 09:07 UTC by ShadeAware

## About The Pull Request
Adds in a new Wardrobe, the Captain's Wardrobe, which holds all cosmetic Captain clothing. Clothing has been moved from the Locker to the vender because of this. 

First time editing a map so expect everything to go wrong. 🙃 

## Why It's Good For The Game
The Captain's locker is bloated to shit. This helps alleviate the problem and still let people have their fancy mix-and-match outfits.

## Changelog
:cl:
Add: The Captain's Wardrobe, a vender that holds all cosmetic Captain's clothing.
Remove: Most cosmetic items from the Captain's locker.
/:cl:

2020-02-08 09:08 UTC, ShadeAware commented
ah cool, conflicts

2020-02-08 16:11 UTC, kappa-sama commented
F

2020-02-08 16:12 UTC, kappa-sama commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +/obj/structure/closet/secure_closet/captains //Unbloated by ShadeAware aka Michael Labs
recommend changing comment to tell people that the other stuff is in vending/wardrobes

2020-02-08 18:51 UTC, ShadeAware commented
Its getting there.

2020-02-08 18:58 UTC, Ghommie requested changes
Also merge conflicts

2020-02-08 18:58 UTC, Ghommie commented on code/modules/vending/wardrobes.dm
> +					/obj/item/clothing/under/rank/captain/femformal = 1, //Fuck your Citadel Edits and fuck locker bloat, we VENDERSTATION now.
Remove comment.

2020-02-11 21:24 UTC, closed without merging

2020-02-11 21:25 UTC, ShadeAware commented
Im just going to try to redo this entirely.