Nerfs public autolathes
citadel-station/citadel-main pull request #10970
Opened 2020-02-08 07:02 UTC by kevinz000

## About The Pull Request

I was going to add a whole DESIGN FLAG (!!! WOW!!!) to flag things but I realized I can just

hackable = FALSE

easy

## Why It's Good For The Game

i'm stubborn about public lathes but i'm perfectly fine with most of the hacked designs not being available without asking. i'm kinda worried this will turn into "secure the good stuff behind hack barrier" but honestly why would i be worried that works for the most part

oh and you can print this special secure autolathe board too and stuff yeah.

## Changelog
:cl:
balance: Public autolathes can no longer be hacked.
/:cl:

2020-02-08 18:59 UTC, Tupinambis commented
Honestly I think this is a really silly way to handle it.

I'd rather either:
A: Remove public autolathes
B: change what public autolathes can print to begin with (Only very basic stuff that other departments pretty much need to function)
C: Nerf all lathes in this fashion.

Making them unhackable I think will just confuse people and honestly feels like an icky hugbox approach.

2020-02-09 04:13 UTC, kevinz000 commented
b is exactly what i am doing only not that hugboxed aka basic items only
c is absolutely not; autolathes are fine at the moment.

2020-02-11 08:38 UTC, Ghommie requested changes

2020-02-11 08:38 UTC, Ghommie commented on code/game/machinery/autolathe.dm
> +	if(hackable || !hacked)
Early return if not hackable.

2020-02-11 08:38 UTC, Ghommie commented on code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
> +/datum/design/board/autolathe_secure
Unused design, please remove.

2020-02-13 08:16 UTC, Ghommie commented on code/modules/research/techweb/all_nodes.dm
> +	"atmosalerts", "atmos_control", "recycler", "autolathe", "secure_autolathe", "high_micro_laser", "nano_mani", "mesons", "thermomachine", "rad_collector", "tesla_coil", "grounding_rod",
```suggestion
	"atmosalerts", "atmos_control", "recycler", "autolathe", "autolathe_secure", "high_micro_laser", "nano_mani", "mesons", "thermomachine", "rad_collector", "tesla_coil", "grounding_rod",
```

2020-02-16 06:37 UTC, Ghommie approved these changes

2020-02-16 06:37 UTC, merged