wall walking boots for traitors
citadel-station/citadel-main pull request #10986
Opened 2020-02-09 05:13 UTC by Seris02

## About The Pull Request

Wall walking boots, need to be on walking intent to use, has 4 charges in them when bought.
can be recharged with 1 bluespace crystal = 1 charge
when walking through something solid, they:
- cause 5-15 oxy loss
- 10% chance of causing 3-5 brute loss
- take one charge from the boots
- make sparks
- make an orange flash

## Why It's Good For The Game

new traitor items + fun stuff

## Changelog
:cl:
add: wall walking boots
/:cl:

2020-02-09 05:15 UTC, Detective-Google commented
I must admin I'm a bit sad these don't flip you sideways and make you walk on the walls not through them 😔 

anyway
```
sv_cheats 1
noclip
```

2020-02-09 05:15 UTC, Tupinambis commented
Isn't RTA/Teleprod the same thing?

Jokes aside, good PR

2020-02-09 05:15 UTC, kevinz000 commented
rta + first aid kit was the same thing until they nerfed it because i abused it

2020-02-09 05:19 UTC, deathride58 commented
holy shit, a weapon to surpass emags. +support

also hey it'd probably be a good idea if recharging required an item that can only be received from the uplink, similar to the emag's charges, as ore silos mean that mats are relatively easy to access

2020-02-09 05:26 UTC, kappa-sama commented
same as above

2020-02-09 05:37 UTC, Detective-Google commented
perhaps a progress bar for walking through them as well

2020-02-09 07:05 UTC, YakumoChen commented
There's already an item that can be recharged with bluespace crystals in the uplink though

2020-02-16 16:07 UTC, Ghommie requested changes
First review, there will probably be more things to change later but I don't want to sound too confusing.

2020-02-16 16:07 UTC, Ghommie commented on code/modules/clothing/shoes/miscellaneous.dm
> +	LAZYREMOVE(user.user_movement_hooks,src)
Hey, will you please replace the whole `user_movement_hooks` hack with component signals? Do not worry about the unused old old old flightpacks, thank you.

Oh yea, the new comsig should early return `Client/Move` before the `. = ..()` call since the shoes already handle the mob movement.

2020-02-16 16:07 UTC, Ghommie commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if (walkcool < world.time && m.m_intent == MOVE_INTENT_WALK && wallcharges > 0)
Early return if the opposite is TRUE.

2020-02-16 16:07 UTC, Ghommie commented on code/modules/uplink/uplink_items/uplink_devices.dm
> +	desc = "A small device intended for recharging Wall Walking boots. Using it will add six charges to them. Use ten bluespace crystals on this recharger to add three more charges to it. "
Would be nice if it was compatible with the shrinking device whatever too.

2020-02-16 16:07 UTC, Ghommie commented on code/modules/clothing/shoes/miscellaneous.dm
> +			qdel(I)
Just run this: `B.use(10)`

2020-02-22 12:24 UTC, Seris02 commented on code/modules/uplink/uplink_items/uplink_devices.dm
> +	desc = "A small device intended for recharging Wall Walking boots. Using it will add six charges to them. Use ten bluespace crystals on this recharger to add three more charges to it. "
nah. they use different amounts.

2020-02-22 12:39 UTC, Seris02 commented on code/modules/clothing/shoes/miscellaneous.dm
> +	LAZYREMOVE(user.user_movement_hooks,src)
so you want me to make an entirely new component for something that already exists and works?

2020-03-24 06:04 UTC, Ludox235 commented
can't wait for somebody to use these with a bluespace duffel bag to put 5 maxcaps into the brig and run away

2020-03-26 01:40 UTC, Ghommie commented
Conflicts, also use the component signal now.

2020-04-12 03:49 UTC, Ghommie commented
Still working on solving the conflicts and making use of the component signal instead?

2020-04-13 12:03 UTC, Ghommie requested changes
Final feedback.

2020-04-13 12:03 UTC, Ghommie commented on code/modules/clothing/shoes/miscellaneous.dm
> +		RegisterSignal(user, COMSIG_MOB_CLIENT_MOVE)
Remove.

2020-04-13 12:03 UTC, Ghommie commented on code/modules/clothing/shoes/miscellaneous.dm
> +	..()
```suggestion
	. = ..()
```

2020-04-13 12:03 UTC, Ghommie commented on code/modules/clothing/shoes/miscellaneous.dm
> +	RegisterSignal(user, COMSIG_MOB_CLIENT_MOVE)
```suggestion
	. = ..()
	UnregisterSignal(user, COMSIG_MOB_CLIENT_MOVE)
```

2020-04-13 12:03 UTC, Ghommie commented on code/modules/clothing/shoes/miscellaneous.dm
> +/obj/item/clothing/shoes/wallwalkers/proc/intercept_user_move(mob/living/m, client,dir,newloc,oldloc)
```suggestion
/obj/item/clothing/shoes/wallwalkers/proc/intercept_user_move(mob/living/m, client/client, dir, newloc, oldloc)
```

2020-04-13 12:08 UTC, Seris02 commented on code/modules/clothing/shoes/miscellaneous.dm
> +		RegisterSignal(user, COMSIG_MOB_CLIENT_MOVE)
oop

2020-04-13 12:09 UTC, Seris02 commented on code/modules/clothing/shoes/miscellaneous.dm
> +	RegisterSignal(user, COMSIG_MOB_CLIENT_MOVE)
oop again

2020-04-13 12:25 UTC, Ghommie approved these changes

2020-04-13 12:25 UTC, merged