Replaces fireball wand on lava land with Drake tail
citadel-station/citadel-main pull request #10991
Opened 2020-02-09 22:35 UTC by Trilbyspaceclone

## About The Pull Request

The fireball wand has been replaced with a 20 burn 2 tile reach whip that stets any carbon aflame, as well as disarms their active item.

## Why It's Good For The Game

The fireball wand is a magic item that is has no reason to be their, it was a nod at the drakes fire attacks, but the drake itself had no magic. Replacing it with this tail whip makes more logical idea of what you "win" be defeating them rather then space magic.
It also take away, the seen to be by the upper people, a powerful weapon that has few counters outside of Chaplin. 

## Changelog
:cl:
add: The ash drag tail has been seen to be used as a powerful weapon by miners
balance: replaces the firewand from drake loot table with a whip that disarms, set ablaze and reaches.
/:cl:

2020-02-09 22:36 UTC, Trilbyspaceclone commented on code/modules/mining/lavaland/necropolis_chests.dm
> +	icon_state = "draketail"
I rather like how the tail whip came out.

2020-02-09 22:36 UTC, kappa-sama commented
better than fireball wand but maybe without the disarm? there's already a lot of stuff going on for a 2 tile melee weapon

2020-02-09 22:39 UTC, Hatterhat commented
belmont machine

2020-02-09 22:39 UTC, KeRSedChaplain commented
Yeah, the disarm might make it a bit broken.

Also, I feel like chainhit.ogg doesn't fit the thing if its literally just the severed tail of an Ash drake.

2020-02-09 22:42 UTC, kiwedespars commented
3 hit fireball wand replaced with an infinite use weapon that may or may not be better than the stunbaton.

2020-02-09 22:51 UTC, lolman360 commented
at least you have to get closer than fireball.

With fireball you land one shot across the screen and it's a knockout+damage+sets them on fire. so what if it's limited use, it literally takes one hit to guarantee a kill. if you're a non-antag you're really only going to be validhunting with this (fireball isnt effective on lavaland/vs simples). if you're an antag and you use it's a fastmoving instastun with one counter (null rod).

2020-02-09 22:55 UTC, Ghommie commented
More than a drake tail, that thing looks like a bullwhip, and only sets fuel-doused people aflame.
This is a pretty bland effortless brute version of the welder misguised as improvement.

2020-02-09 22:59 UTC, Trilbyspaceclone commented
@Ghommie
The sprite came out fine, it looks good. It looks like a tail. It uses the colours of the drake.

2020-02-10 03:31 UTC, YakumoChen commented
It maybe looks like a tail if the dragon was, in fact, a gigantic rat

but I'm pretty sure it isn't

2020-02-10 09:22 UTC, Trilbyspaceclone commented
@YakumoChen What?
The sprite stuff is coppyed from chain of comman but the code itself is just normal melee item code thats not copy'ed from CoC.

2020-02-15 18:27 UTC, Ghommie requested changes
Looks like a bullwhip/rat tail, inhand sprite is the same as the command chain. Wouldn't say it's a good replacement to the fireball wand and rather keep it admin only for the time being.

2020-02-15 18:27 UTC, Ghommie commented on code/modules/mining/lavaland/necropolis_chests.dm
> +	damtype = "fire"
```suggestion
	damtype = BURN
```

2020-02-15 18:27 UTC, Ghommie commented on code/modules/mining/lavaland/necropolis_chests.dm
> +	item_flags = NONE
It's one awful stingy weapon, remove this line and let securibots do their job here.

2020-02-15 18:27 UTC, Ghommie commented on code/modules/mining/lavaland/necropolis_chests.dm
> +	w_class = WEIGHT_CLASS_NORMAL
Same value as parent type, remove.

2020-02-15 18:27 UTC, Ghommie commented on code/modules/mining/lavaland/necropolis_chests.dm
> +	throwforce = 20
Whips are not really good throwing weapons, Trilby, give it a less senseless value.

2020-02-15 18:27 UTC, Ghommie commented on code/modules/mining/lavaland/necropolis_chests.dm
> +	slot_flags = ITEM_SLOT_BELT
Sorry, but at this point just make this a chain of command subtype, Yakumo is not really wrong saying this is a copypasta.

2020-02-15 18:27 UTC, Ghommie commented on code/modules/mining/lavaland/necropolis_chests.dm
> +/obj/item/melee/fire_tail/afterattack(target, mob/user, proximity_flag)
```suggestion
/obj/item/melee/fire_tail/afterattack(atom/target, mob/user, proximity_flag)
```

2020-02-15 18:27 UTC, Ghommie commented on code/modules/mining/lavaland/necropolis_chests.dm
> +	. = ..()
add a proximity return check after this line please.

2020-02-20 21:10 UTC, Ghommie commented on code/modules/mining/lavaland/necropolis_chests.dm
> +/obj/item/melee/fire_tail/afterattack(atom/target, mob/user, proximity_flag)
```suggestion
/obj/item/melee/chainofcommand/fire_tail/afterattack(atom/target, mob/user, proximity_flag)
```

2020-02-21 01:50 UTC, Ghommie commented
Pretty janky and looks like a rat tail. No.

2020-02-21 01:50 UTC, closed without merging