buckshot buff - 60 to 81 on all pellet pointblank
citadel-station/citadel-main pull request #10992
Opened 2020-02-10 01:09 UTC by Hatterhat

## About The Pull Request
see title, accomplishes this by bumping individual pellet starting damage from 10 to 13.5
## Why It's Good For The Game
giving a reason to pb the shit out of dudes with buck instead of the all-rounder slug
## Changelog
:cl:
balance: Buckshot individual pellet damage up from 10 to 13.5. Still firing 6 pellets.
/:cl:

2020-02-10 01:09 UTC, kappa-sama commented
how much damage falloff do they got doe

2020-02-10 01:10 UTC, Hatterhat commented
still the default damage falloff

2020-02-10 01:10 UTC, kappa-sama commented
i don't know the damage falloff bro

2020-02-10 02:46 UTC, Ghommie requested changes

2020-02-10 02:46 UTC, Ghommie commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	damage = 13.5
But the original damage was:
```suggestion
	damage = 12.5
```

2020-02-10 09:35 UTC, kevinz000 commented
@Hatterhat outright implement requiring a free hand to rack shotguns/being able to rack them through alt click if they are on floor if you're doing this.

2020-02-11 13:59 UTC, Ghommie commented
@kevinz000 tgstation made riot/combat shotguns heavy firearms (ergo need two hands to use them) while giving sawn off shotties less accuracy and extra recoil iirc. That's a better approach to be honest.

2020-02-12 09:34 UTC, Ghommie approved these changes

2020-02-12 09:34 UTC, merged