Makes ninja now longer spawn with a suit with sensors
citadel-station/citadel-main pull request #11026
Opened 2020-02-11 20:46 UTC by Trilbyspaceclone

## About The Pull Request

Ninja now spawns with a tactical turtleneck so that they are not spawning with max suits to be pin pointed

## Why It's Good For The Game

Stops ninjas for being known as soon as they spawn by a medical officer going `Huh whos this new unknown guy in space` and then sec getting pin pointers to track them down to their location

## Changelog
:cl:
balance: The suit full of spiders also known as a ninja now is a tactical turtleneck
/:cl:

2020-02-11 20:47 UTC, KeRSedChaplain commented
what if we do the same for wizards.

2020-02-11 20:48 UTC, Trilbyspaceclone commented
@KeRSedChaplain Good idea

2020-02-12 09:31 UTC, Ghommie requested changes

2020-02-12 09:31 UTC, Ghommie commented on code/modules/clothing/under/color.dm
> +	name = "purple jumpsuit"
Remove, same value as parent.

2020-02-12 09:31 UTC, Ghommie commented on code/modules/clothing/under/color.dm
> +	item_color = "lightpurple"
Idem.

2020-02-12 09:31 UTC, Ghommie commented on code/modules/ninja/outfit.dm
> +	uniform = /obj/item/clothing/under/syndicate
This change brings a collateral melee resistance buff to space ninjas, make a no sensors black jumpsuit subtype, please.

2020-02-13 08:35 UTC, Ghommie approved these changes

2020-02-13 08:36 UTC, merged