Changes cult stunhand when halos are out
citadel-station/citadel-main pull request #11053
Opened 2020-02-13 02:27 UTC by keronshb

## About The Pull Request

Turns the stunhand into a burn + knockback hand.  So it remains more defensive than offensive.

## Why It's Good For The Game

This should reduce the power the cult has during late-game cult play.  So instead of a 1 hit stunhand at their final phase, it's a defensive tool.

## Changelog
:cl:
add: Added burn and knockback to stunhand during HALOS on cult.
balance: Added burn and knockback to stunhand during HALOS on cult.
/:cl:

2020-02-13 02:28 UTC, BlackMajor commented
Good PR

2020-02-13 03:56 UTC, silicons approved these changes

2020-02-15 18:32 UTC, Ghommie requested changes

2020-02-15 18:32 UTC, Ghommie commented on code/modules/antagonists/cult/blood_magic.dm
> +					var/atom/throw_target = get_edge_target_turf(L, user.dir)
Move this line below the deprecable anchored check.

2020-02-15 18:32 UTC, Ghommie commented on code/modules/antagonists/cult/blood_magic.dm
> +					if(!L.anchored)
```suggestion
					if(L.move_resist < MOVE_FORCE_STRONG)
```
Or `MOVE_FORCE_VERY_STRONG`, your choice.

2020-02-17 11:47 UTC, Ghommie approved these changes

2020-02-17 12:29 UTC, merged