All improvised guns are now slap crafted, as well as adding in makeshift pistols
citadel-station/citadel-main pull request #11077
Opened 2020-02-13 19:01 UTC by Trilbyspaceclone

## About The Pull Request

No longer can you just "craft" the improvised shotgun and rifle! Just like back in the day you now have to craft it using what is needed rather then waiting 100 desceconds for a timer to fill.
Added in a makeshift pistol that has 9mm 10mm and .45, one shot at a time
Added a makeshift high caliber pistol that holds .38 .357 and n762, one shot at a time
The makeshift pistols have fail odds and take more to craft, failing does a simular action to what detectives does

## Why It's Good For The Game

Adds more skill into crafting these weapons, as well as more guns to craft to stick it to sec when you viva!
The improvised pistols are balanced rather well imo and moving the improvised rifle and shotgun out of crafting makes them more of a hidden craftable, for those that know the way of slap crafting. Declutters crafting as well making it better.

## Changelog
:cl:
add: High caliber and normal makeshift pistols - only gettable via slap crafting
balance: Improvised shotgun and rifle are now slap craftable and out of the menu
/:cl:

2020-02-13 19:05 UTC, Trilbyspaceclone commented
Its all 100% tested! (Unless I somehow missed something)

2020-02-15 18:41 UTC, silicons requested changes
No makeshift pistols/revolvers.

Leave it adminspawn only/admingive only for crafting recipe if you want, I do not want this roundstart.

2020-02-15 18:42 UTC, kevinz000 commented on code/datums/components/crafting/guncrafting.dm
> +			to_chat(user, "<span class='notice'>Improvised Rifle Completed!</span>")
Don't capitalize every word.

2020-02-15 18:42 UTC, kevinz000 commented on code/datums/components/crafting/guncrafting.dm
> +			to_chat(user, "<span class='notice'>Improvised Pistol Completed!</span>")
Ditto

2020-02-15 18:42 UTC, kevinz000 commented on code/datums/components/crafting/guncrafting.dm
> +/obj/item/weaponcrafting/receiver/stock/barrled/gun/short
Misspelled typepath

2020-02-15 18:42 UTC, kevinz000 commented on code/datums/components/crafting/guncrafting.dm
> +			to_chat(user, "<span class='notice'>Improvised High Caliber Pistol Completed!</span>")
Ditto

2020-02-15 18:42 UTC, kevinz000 commented on code/datums/components/crafting/guncrafting.dm
> +		to_chat(user, "<span class='notice'>The barrle is exstended making a longer gun!</span>")
Typo

2020-02-15 18:42 UTC, kevinz000 commented on code/datums/components/crafting/guncrafting.dm
> +			to_chat(user, "<span class='notice'>The barrle is sawn off making a smaller gun!</span>")
Typo

2020-02-15 18:43 UTC, kevinz000 commented on code/datums/components/crafting/guncrafting.dm
> +			to_chat(user, "<span class='warning'>You need at least ten lengths of package wrap if you want to make a attach this pipe!</span>")
Grammar

2020-02-19 04:10 UTC, IronEleven commented
How does this make pipe guns any harder to make aside from a few days of confused mhelps?

2020-02-19 10:51 UTC, Trilbyspaceclone commented
@IronEleven its faster, and thats it.

2020-02-20 02:08 UTC, silicons requested changes
there's still typos everywhere, there's still free for all improvised pistols/revolver recipes

i already said no more improvised guns it's just unnecessary the greytide has enough weapons. why the hell do we need more?

2020-02-20 02:18 UTC, Trilbyspaceclone commented on code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
> +	always_availible = FALSE
@kevinz000 What...

2020-02-21 02:06 UTC, Ghommie commented
Reopening in faith that this whole crafting code will be improved into a datum or something more acceptable.

2020-02-21 02:27 UTC, Ghommie requested changes

2020-02-21 02:27 UTC, Ghommie commented on code/datums/components/crafting/guncrafting.dm
> +		var/obj/item/weaponcrafting/receiver/stock/R = /obj/item/weaponcrafting/receiver/stock
Just remove this line use the Path in place of R on the `new` procedure.

This also applies to most, if not all, other steps.

2020-02-21 02:27 UTC, Ghommie commented on code/datums/components/crafting/guncrafting.dm
> +	..()
Always set the parent return call as the standard return value unless you have a reason not to.
`. = ..()`, not `..()`.
This also applies to other steps.

2020-02-21 02:27 UTC, Ghommie commented on code/datums/components/crafting/guncrafting.dm
> +	if(istype(D, /obj/item/screwdriver))
Use tool behaviours checks or the appropriate tools act procedure if possible, not type checks.
This also applies to all other steps.

2020-02-21 02:27 UTC, Ghommie commented on code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
> +	subcategory = CAT_WEAPON
Remove, these shouldn't be craftable this way.

2020-02-21 02:27 UTC, Ghommie commented on code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
> +/datum/crafting_recipe/ispistol
Same here.

2020-02-22 22:59 UTC, Trilbyspaceclone commented
@Ghommie What other changes are needed?

2020-03-21 01:23 UTC, BobJoga commented
I don't see how this makes crafting any harder. It justs makes coding and spriting harder and more painful.
-1, pretty bad

2020-04-22 21:26 UTC, closed without merging