Some sprite fixes
citadel-station/citadel-main pull request #11089
Opened 2020-02-14 09:16 UTC by Microvolnovka19

## Yea
I drew some sprites for  tentacle,tapered, hemi, knotted hemi(Sizes 1-4 were the same).
## And
This is my second try because of: 

Ghommie:
EDIT: Misread the title.
Good change but you got to do it over again since I have cleaned up the file quite a bit.

## Changelog
:cl:
imageadd: added some icons and images
code: changed some code
/:cl:

2020-02-14 12:35 UTC, Ghommie requested changes
You are accidentally reverting some icon state changes here. Check the icon diff bot.

2020-02-15 10:03 UTC, Microvolnovka19 commented
Fixing this thing

2020-02-15 10:23 UTC, Microvolnovka19 commented
I think i fixed it.

2020-02-15 10:29 UTC, Ghommie approved these changes

2020-02-15 10:30 UTC, merged