purifying longswords - alt title "there's no way this should have worked"
citadel-station/citadel-main pull request #11083
Opened 2020-02-14 03:34 UTC by Hatterhat

## About The Pull Request
allows purifying eldritch longswords like you could bloody bastard swords
## Why It's Good For The Game
allows the new strat of dabbing on cultists by purifying their swords and then using those to beat the shit out of them
## Changelog
:cl:
balance: You can now purify eldritch longswords with a bible. This creates holy claymores.
/:cl:

2020-02-14 06:24 UTC, Ghommie requested changes

2020-02-14 06:24 UTC, Ghommie commented on code/game/objects/items/storage/book.dm
> +		var/obj/item/sword = A
These two lines are fairly useless now.

2020-02-14 06:24 UTC, Ghommie commented on code/game/objects/items/storage/book.dm
> +			if(isbastardsword)
```suggestion
			if(istype(A, /obj/item/twohanded/required/cult_bastard))
```

2020-02-15 08:05 UTC, necromanceranne commented
I mentioned this to Hatterhat already but making it so that you can potentially start seeding among the crew even more nullrods is not a good move. We have claymores that aren't carrying the antimagic abilities that would be exclusive to the chaplain's nullrod, and even if they are significantly more potent than eldritch longswords in force (40 over the longsword's 30, has block compared to no block), they're being used against opponents who are very, very good at melee combat and generally have the advantage still. The loss of just one of the swords that the cult produces infinitely via a spell just ends up being disastrous.

I'd even recommend just making a new item what is a 30 force sword. Once it's merged on tg, there is a pr I have there that updates the claymore sprites that probably would be worth porting for that.

2020-02-15 18:35 UTC, Ghommie commented
Oh, yea, more or less what the person above said. Null rod rewards for dunking cultists will only results in the cult being snowballed harder. Perhaps 20 damage or so not so holy claymores would be better.

2020-02-16 06:35 UTC, Ghommie requested changes

2020-02-16 06:35 UTC, Ghommie commented on code/game/objects/items/storage/book.dm
> +			new /obj/item/claymore/purified(get_turf(A))
Replace these three lines with:
```
		else
			new /obj/item/claymore/purified(get_turf(A))
```

2020-02-18 18:02 UTC, Ghommie approved these changes

2020-02-18 18:02 UTC, merged