Podpeople species cosmetic tweaks; also lifebringer name fix?
citadel-station/citadel-main pull request #11091
Opened 2020-02-14 12:27 UTC by BlueWildrose

## About The Pull Request

- Podpeople can wag tails now; they weren't able to before for some reason.
- Moved a few features into the podperson race itself instead of its weaker, roundstart variant; this in theory, will allow pod-grown hydroponics podpeople to have hair now, as well as all those anthropomorphic features, should they be revived through this method. The weaker roundstart variant should respectively not be changed at all.
- Fixed the ghost role lifebringers having no name somehow while I was fiddling with them but... currently lifebringers under this change I bring will turn them into animal anthropomorphic fuzzy mutants of some kind until I figure out how to make them the bald, normal looking podpeople that they once were, could use some help with this.

## Why It's Good For The Game
If someone is revived through the podperson method they can keep most of their snowflakey attributes, they're just a plant now. This probably means that they don't need to run off to xenobiology for those green extracts to become a slimeperson that can regain their lost features this way.

Tail wagging should have been a thing for a species that could have tails, but wasn't.

currently the lifebringers are a little weird but at least their names are fixed.

## Changelog
:cl:
tweak: changed it so normal podpeople can have the same mutant bodyparts that their weaker roundstart variant can have.
add: podpeople tail wagging
tweak: lifebringer ghost role fixes (and fix attempts - need help with this...)
/:cl:

2020-02-17 12:59 UTC, Ghommie requested changes

2020-02-17 12:59 UTC, Ghommie commented on code/game/objects/structures/ghost_role_spawners.dm
>  /obj/effect/mob_spawn/human/seed_vault/special(mob/living/new_spawn)
Remove this line now.

2020-02-17 12:59 UTC, Ghommie commented on code/modules/mob/living/carbon/human/species_types/podpeople.dm
> +	default_features = list("mcolor" = "FFF","mcolor2" = "FFF","mcolor3" = "FFF", "mam_snouts" = "Husky", "mam_tail" = "Husky", "mam_ears" = "Husky", "mam_body_markings" = "Husky", "taur" = "None", "leg
I'm very very very very very very against this. Like, can't you just man up and leave the standard one looking like a walking broccoli? It's the iconical side-effect of replica pods after all.
Bug the xenobiologist for some mutation toxin or something.

2020-02-17 12:59 UTC, Ghommie commented on code/modules/mob/living/carbon/human/species_types/podpeople.dm
> +
Remember to move this to the subspecies after reverting the above snowflakes change.

2020-02-18 02:48 UTC, BlueWildrose commented
Very well, the changes are made.

2020-02-18 16:11 UTC, Ghommie approved these changes

2020-02-18 16:11 UTC, merged