you kids like extend votes?
citadel-station/citadel-main pull request #11110
Opened 2020-02-16 07:30 UTC by Hatterhat

## About The Pull Request
extend votes.
## Why It's Good For The Game
green shifts are bad but you can make them exponentially worse by voting on this
## Changelog
:cl:
add: Extend votes! Ported from Hyper, ported from AUstation.
/:cl:

2020-02-16 07:31 UTC, silicons submitted a review, later dismissed

2020-02-16 08:12 UTC, Ghommie commented
Make it compile.

2020-02-16 12:04 UTC, Arturlang commented
Why not port the add antag option from bay for !!FUN!!

2020-02-17 12:32 UTC, Ghommie requested changes

2020-02-17 12:32 UTC, Ghommie commented on code/controllers/configuration/entries/general.dm
> +	integer = FALSE
The value is in deciseconds and byond ticks are 1 ds minimum. I don't understand why it should be a float.

2020-02-17 12:32 UTC, Ghommie commented on code/controllers/configuration/entries/general.dm
> +	integer = FALSE
Same.

2020-02-18 04:27 UTC, keronshb commented
Honestly I do see the good in this but also the bad.

Some rounds are suppose to be short fun things (Wiz, Nukies, Gangs, maybe Cult if they're speedrunning)

Most should be a good medium run (Cult, Traitors, Bloodsuckers, etc), but I feel this might turn those into big shitter safari rounds.  These are the 1:30 - 2:30 hr rounds.

I know this would be left up to the players to vote in game, but rounds end up going past 2:30 (even then it feels too long), people might get round fatigued a lot more.  Especially if people start rallying behind votes like they use to when they weren't hidden for dynamic.

This feels like a big blow also for the tots or cult that was caught too early + killed and then it's "forced extended" for the rest of the shift and if it gets voted... even longer?  I know ghost roles do exist, but just like the station you can only do so much with them in the current allotted time that going past that feels like an eternity.

I feel like if this does stay, midrounds should be 2x or 3x the appearance rate when the round is voted to be extended.

2020-02-20 14:44 UTC, Ghommie requested changes
Remember to remove the shuttle subsystem's `auto_call` variable and modify its `autoEnd` procedure accordingly.

2020-02-22 23:14 UTC, Ghommie approved these changes

2020-02-22 23:15 UTC, Ghommie requested changes

2020-02-22 23:15 UTC, Ghommie commented on code/controllers/subsystem/shuttle.dm
>  		emergencyNoRecall = TRUE
```suggestion
	emergencyNoRecall = TRUE
```

2020-02-22 23:15 UTC, Ghommie commented on code/controllers/subsystem/shuttle.dm
> +		endvote_passed = TRUE
```suggestion
	endvote_passed = TRUE
```

2020-02-24 15:38 UTC, Ghommie approved these changes

2020-02-24 15:39 UTC, merged