Timid women/men costumes!
citadel-station/citadel-main pull request #11198
Opened 2020-02-22 04:49 UTC by BlueWildrose

## About The Pull Request

![image](https://i.imgur.com/ciRaviA.png)
This will add timid women/men costumes into the game.
These are simply cute costumes, nothing more.
A total of six new items (eight if you count the hood objects) have been added, and a new pair of socks that are selectable from the character creation menu or from a dresser.
The new objects are the following:
**Timid woman/man hoodie:** Polychromic suit, belt loop and buckle, toggleable hoodie. I pretty much just copypasted the code from the polychromic winter coat.
**Timid woman/man mask:** Functions identically to the mime/clown mask.
**Timid woman/man shoes:** Polychromic shoes, only one tone.
The socks: Garters. They're intended to compliment the timid woman outfit in full if someone wants to fully dress up like the intended outfit, but otherwise it's available for everyone to use.
![image](https://i.imgur.com/XxLOqlz.png)

Recommended to use a gear harness with the timid outfit.

These costume pieces have been added to the **Autodrobe** vendor.
Additionally, if you're a **mime**, you can **include the costume pieces into your loadout** for a total of 3 points, so you can start with the costume. Make it your part of your gimmick as a mime that way!

_Known issues:_ The inventory icon when the hoodie is toggled up will look ugly. This is also an issue with the polychromic winter coat as well.

## Why It's Good For The Game

More costumes means more fun. More clothing is always fun.

## Changelog
:cl:
add: Adds timid women/men costumes
add: Adds said above costumes to the autodrobe vendor
add: The costume pieces are added to the loadout - exclusive to the Mime job.
add: New pair of socks: Garters
imageadd: Obviously, adding a costume means adding in new sprites; a total of 12 DMI files have been modified.
/:cl:

2020-02-22 05:27 UTC, Commandersand commented
why is the male belt and mask neon pink and green

2020-02-22 05:35 UTC, BlueWildrose commented
> 
> 
> why is the male belt and mask neon pink and green

Just me demonstrating polychromic stuff. Obviously better options can be picked. It defaults to brown and yellow, just like what's presented on the floor and on the female one to the left.

2020-02-22 06:41 UTC, BlueWildrose commented
oh great, conflicts - was some other clothing added recently that I missed?

2020-03-01 17:15 UTC, Ghommie requested changes
Merge conflicts.

2020-03-01 17:15 UTC, Ghommie commented on code/modules/mob/dead/new_player/sprite_accessories/socks.dm
> +	icon_state = "garter"
Being grayscale it could also have `has_color = TRUE`

2020-03-10 16:33 UTC, closed without merging

2020-03-10 18:05 UTC, Iamgoofball commented
i dont understand, are these like tentacle monster shy guys?

2020-03-10 19:25 UTC, Ghommie commented
It's their snowflake character's tails.

2020-03-10 23:07 UTC, Iamgoofball commented
Understandable carry on