Adds Squish Emote. Please stop squishing at me so lewdly.
citadel-station/citadel-main pull request #11243
Opened 2020-02-25 13:51 UTC by Xantholne

## About The Pull Request

Adds *squish emote

## Why It's Good For The Game

We have barks, beeps, pings, nyas, chitters, but nothing for slimes in terms of a vocal emote until now.

## Changelog
:cl:
add: You can now *squish
/:cl:

2020-02-25 14:18 UTC, Ghommie requested changes
Simple emotes, clothing and trinkets alone don't make the game any more interesting. I wish you would make more meaningful features instead.

2020-02-25 14:18 UTC, Ghommie commented on modular_citadel/code/modules/mob/cit_emotes.dm
> +	restraint_check = false
```suggestion
	restraint_check = FALSE
```

2020-02-25 21:33 UTC, kappa-sama commented
no more modular citadel pls

2020-03-02 15:14 UTC, Ghommie commented
Not this time, sorry.

2020-03-02 15:14 UTC, closed without merging