En garde! (nah just sword pointing)
citadel-station/citadel-main pull request #11277
Opened 2020-02-28 20:37 UTC by kevinz000

## About The Pull Request

You can now point the tip of some more swords/sharp tipped things (including spears, for the revolutionaries out there) at people.

## Why It's Good For The Game

En garde!

## Changelog
:cl:
tweak: You can now right click to point the tip of some sharp tipped weapons at people.
/:cl:

2020-02-28 20:39 UTC, Arturlang commented
Wouldnt it make more sense if you were holding an item and if you pointed while holding and it being selected just pointing with the item always, when normally pointing?

2020-02-28 20:40 UTC, kevinz000 commented
@Arturlang yes but this is just an advanced webeditor PR 
can easily be switched to that since it's an element (and some things wouldn't make sense why would you for example point with a toolbox lmao)

2020-02-28 20:42 UTC, Kraseo commented on code/game/objects/items/twohanded.dm
> +	AddComponent(/datum/component/josuting)
josuting

2020-02-29 01:57 UTC, lolman360 commented on code/game/objects/items/twohanded.dm
> +	AddComponent(/datum/component/josuting)
kveinz000

2020-03-03 20:22 UTC, Ghommie requested changes

2020-03-03 20:22 UTC, Ghommie commented on code/game/objects/items/melee/energy.dm
> +	AddElement(/datum/element/sword_point)
should only be doneable when active. Also remove lines 273-276.

2020-03-03 20:22 UTC, Ghommie commented on code/datums/elements/sword_point.dm
> +		user.visible_message("<span class='warning'>[user] points the tip of [source] at [target]!</span>")
```suggestion
		user.visible_message("<span class='notice'>[user] points the tip of [src] at [target].</span>", "<span class='notice'>You point the tip of [src] at [target].</span>")
```

2020-03-03 20:22 UTC, Ghommie commented on code/game/objects/items/twohanded.dm
> +	AddElement(/datum/element/sword_point)
Remove, this is a subtype of `/obj/item/twohanded/dualsaber` anyway.

2020-03-04 16:11 UTC, Ghommie approved these changes

2020-03-04 16:11 UTC, merged