Makes most winter coats and hoods have their own desc
citadel-station/citadel-main pull request #11283
Opened 2020-02-29 14:52 UTC by Trilbyspaceclone

## About The Pull Request

Makes almost all the winter gear not read the same thing

## Why It's Good For The Game

Flavour is nice 

## Changelog
:cl:
add: All winter coats and hoods might be different if slightly from one a other.
/:cl:

2020-02-29 19:57 UTC, r4d6 reviewed
You forgot a bunch of stuff.

2020-02-29 19:57 UTC, r4d6 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat some padding."
I think you forgot a word there.

2020-02-29 19:57 UTC, r4d6 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A yellow and blue winter coat the zipper pully is made to look like a breath mask."
Probably should put a . or a , after coat.

2020-02-29 19:57 UTC, r4d6 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A dusty button up winter coat the zipper looks like a small pickaxe."
There too.

2020-02-29 19:57 UTC, r4d6 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A brass button up winter coat the zipper looks like a small set of cogs."
Here as well.

2020-02-29 19:57 UTC, r4d6 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A black button up winter coat the zipper looks like a blood trail."
Here.

2020-02-29 19:57 UTC, r4d6 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A brass colour button up winter coat the zipper is of a set of cogs."
At this place too.

2020-02-29 19:57 UTC, r4d6 commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A dusty button up winter coat the zipper pull looks like a blood drop."
And I ran out of synonyms.

2020-02-29 21:02 UTC, Ragolution commented
Lily why are you always the queen of typos

2020-02-29 22:10 UTC, Ragolution requested changes

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A cozy winter coat, covered in corgi fur."
Isn't the sprite for this blue? I know there's red trim but Corgi fur would make it orange.

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A red armor padded winter coat."
```suggestion
	desc = "A red, armor-padded winter coat. It glitters with a mild ablative coating and a robust air of authority.  The zipper tab is a pair of jingly little handcuffs and got annoying after the first ten seconds."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A red armor padded winter hood."
```suggestion
	desc = "A red, armor-padded winter hood."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A red armor padded winter coat, with double woven threads to soften any attack."
```suggestion
	desc = "A red, armor-padded winter coat, lovingly woven with a Kevlar interleave and reinforced with semi-ablative polymers and a silver azide fill material. The zipper tab looks like a tiny replica of Beepsky."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A red armor padded winter hood, with double woven threads to soften any attack."
```suggestion
	desc = "A red, armor-padded winter hood, lovingly woven with a Kevlar interleave. Definitely not bulletproof, especially not the part where your face goes."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A red armor padded winter hood, with double woven threads to soften any attack."
By adding a 'kevlar interleaving' you can imply that it has armor without saying 'it's armored', just as well as giving people the idea that it has more value as as coat than as a piece of armor. People know, for example, that kevlar is commonly used to protect from bullets and other attacks. While it's a little more difficult to convey laser-resistance, for example, you can use fluffy terminology for stuff like that.

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat with a small blue caduceus for a zipper handle."
```suggestion
	desc = "An arctic white winter coat with a small blue caduceus instead of a plastic zipper tab. Snazzy."
```

How did you spell caduceus right... /s

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat with a small blue caduceus for a zipper handle."
```suggestion
	desc = "An arctic white winter coat with a small blue caduceus instead of a plastic zipper tab. The normal liner is replaced with an exceptionally thick, soft layer of fur."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat with some acid resistant fibers."
```suggestion
	desc = "A lab-grade winter coat made with acid resistant polymers. For the enterprising chemist who was exiled to a frozen wasteland on the go."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat with green markings."
```suggestion
	desc = "A white winter coat with green markings. Warm, but wont fight off the common cold or any other disease. Might make people stand far away from you in the hallway. The zipper tab looks like an oversized bacteriophage."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat with green markings."
Feel kinda dodgy about this one. Virology coat has no special stats and wanted to reflect that.

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat with an atom for the zipper puller."
```suggestion
	desc = "A white winter coat with an outdated atomic model instead of a plastic zipper tab."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat."
```suggestion
	desc = "A white winter coat hood. This one will keep your brain warm. About as much as the others, really."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A black winter coat with a claw for the zipper puller."
```suggestion
	desc = "A black winter coat with a badass flaming robotic skull for the zipper tab. This one has bright red designs and a few useless buttons."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A black winter coat hood"
```suggestion
	desc = "A black winter coat hood. You can pull it down over your eyes and pretend that you're an outdated, late 1980s interpretation of a futuristic mechanized police force. They'll fix you. They fix everything."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat with a DNA genome for the zipper puller."
```suggestion
	desc = "A white winter coat with a DNA helix for the zipper tab. "
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat hood."
```suggestion
	desc = "A white winter coat hood. It's warm."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat some padding."
```suggestion
	desc = "A thick arctic winter coat with an outdated atomic model instead of a plastic zipper tab. Most in the know are heavily aware that Bohr's model of the atom was outdated by the time of the 1930s when the Heisenbergian and Schrodinger models were generally accepted for true. Nevertheless, we still see its use in anachronism, roleplaying, and, in this case, as a zipper tab. At least it should keep you warm on your ivory pillar."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat hood."
```suggestion
	desc = "A white winter coat hood. It smells faintly of hair gel."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat hood."
We all know you use gel, Dr. Skylar.

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat with reflective orange strips."
```suggestion
	desc = "A white winter coat with reflective green and yellow stripes. Stuffed with asbestos, treated with fire retardant PBDE, lined with a micro thin sheet of lead foil and snugly fitted to your body's measurements. This baby's ready to save you from anything except the thyroid cancer and systemic fibrosis you'll get from wearing it. The zipper tab is a tiny golden wrench."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A white winter coat hood."
```suggestion
	desc = "A white winter coat hood. Feels surprisingly heavy. The tag says that it's not child safe."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A yellow winter coat with reflective orange strips. It has a small wrench for its zipper pully"
```suggestion
	desc = "A surprisingly heavy yellow winter coat with reflective orange stripes. It has a small wrench for its zipper tab, and the inside layer is covered with a radiation-resistant silver-nylon blend. Because you're worth it."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A yellow winter coat hood"
```suggestion
	desc = "A yellow winter coat hood. Definitely not a replacement for a hard hat."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A yellow and blue winter coat the zipper pully is made to look like a breath mask."
```suggestion
	desc = "A yellow and blue winter coat. The zipper pull-tab is made to look like a miniature breath mask."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A yellow and blue winter coat hood"
```suggestion
	desc = "A yellow and blue winter coat hood."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A green winter coat, the zipper looks like a space vine."
```suggestion
	desc = "A green and blue winter coat. The zipper tab looks like the flower from a member of Rosa Hesperrhodos, a pretty pink-and-white rose. The colors absolutely clash."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A clean winter hood that smells of space cleaner."
```suggestion
	desc = "A purple hood that smells of space cleaner."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A clean winter coat that smells of space cleaner"
```suggestion
	desc = "A purple-and-beige winter coat that smells of space cleaner."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A starry winter coat that even glows softly"
```suggestion
	desc = "A starry winter coat that even glows softly."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "An orange winter coat that has a crate pin for its zipper pully."
```suggestion
	desc = "A tan-and-grey winter coat that has a crate for its zipper pull tab. It fills you with the warmth of a fierce independence."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "An orange winter hood"
```suggestion
	desc = "A grey hood for a winter coat."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "An orange winter coat that has a crate pin for its zipper pully."
```suggestion
	desc = "A dark brown winter coat that has a golden crate pin for its zipper pully."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "An orange winter hood"
```suggestion
	desc = "A dark brown winter hood"
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A dusty button up winter coat the zipper looks like a small pickaxe."
```suggestion
	desc = "A dusty button up winter coat. The zipper tab looks like a tiny pickaxe."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A brass button up winter coat the zipper looks like a small set of cogs."
```suggestion
	desc = "A brass-plated button up winter coat. Instead of a zipper tab, it has a brass cog with a tiny red gemstone inset."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A brass colour winter hood that glows softly."
```suggestion
	desc = "A brass-plated winter hood that glows softly, hinting at its divinity."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A black button up winter coat the zipper looks like a blood trail."
```suggestion
	desc = "A somber button-up in tones of grey entropy and a wicked crimson zipper. When pulled all the way up, the zipper looks like a bloody gash. The zipper pull looks like a single drop of blood."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A black winter hood."
```suggestion
	desc = "A black winter hood full of whispering secrets that only He shall ever know."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A brass colour button up winter coat the zipper is of a set of cogs."
```suggestion
	desc = "A brass-plated button up winter coat. Instead of a zipper tab, it has a brass cog with a tiny red piece of plastic as an inset."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A dusty button up winter coat the zipper pull looks like a blood drop."
```suggestion
	desc = "A dusty button up winter coat in the tones of oblivion and ash. The zipper pull looks like a single drop of blood."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A heavy winter coat made with real animal furs!"
```suggestion
	desc = "A luxuriant winter coat, stuffed with the down of the endangered Uka bird and trimmed with genuine sable. The fabric is an indulgently soft micro-fiber, and the deep ultramarine color is only one that could be achieved with minute amounts of crystalline bluespace dust woven into the thread between the plectrums. Extremely lavish, and extremely durable. The tiny flakes of protective material make it nothing short of extremely light lamellar armor."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A cozy winter coat, covered in corgi fur."
Why would he kill his own dog...

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A cozy winter coat, covered in corgi fur."
Cruelty to animals........

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A cozy winter coat, covered in corgi fur."
```suggestion
	desc = "A cozy winter coat, covered in thick fur. The breast features a proud yellow chevron, reminding everyone that you're the second banana."
```

2020-02-29 22:10 UTC, Ragolution commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A heavy winter coat made with real animal furs!"
I might have gone a little over the top here.

2020-02-29 22:12 UTC, Ragolution requested changes
I did these while looking at the coat sprite sheet so I made sure to go over and look at the colorations. There was a couple mistakes (orange vs brown) but otherwise, I hope this helps, Lily.

2020-03-01 19:40 UTC, Linzolle commented
> 
> 
> Lily why are you always the queen of typos

english isn't her first language

2020-03-01 22:12 UTC, Ragolution commented
> > Lily why are you always the queen of typos
> 
> english isn't her first language

Gee. I wonder.

2020-03-02 15:18 UTC, Ghommie approved these changes

2020-03-02 15:18 UTC, merged