Kat Furniture! New sofas, chess pieces, nine new posters and shower curtain functionality!
citadel-station/citadel-main pull request #11314
Opened 2020-03-03 13:38 UTC by KathrinBailey

## About The Pull Request
Adds the following features:
• New sofas with armrest and buckle functionality.
• Buildable green and purple comfy chairs, to fit in with green and purple carpets and tables.
• Shower curtains now block sight only once closed, and let you see through them once open!
• Shower curtains can be crafted with ten plastic sheets.
• Nine new posters!
• Chess pieces!

## Why It's Good For The Game
Adds new assets. The sofas are already used on other sofas and add variety for both mappers and players, as they can craft them.
Comfy chair colours are a bit bland. Green and purple chairs seem like okay options for new colours without cluttering the list too much.
Shower curtain functionality gives a lot of freedom for mappers. It also opens up a ton of roleplay potential. Changing booths for pools? Check!
Chess pieces. This is not intended to be a round-start feature. You are supposed to make a chess board to play. This stops chess being played every shift until it gets bland, you have to put a bit of effort into it.
Nine new posters that are all in-universe and can be used in roleplay. I did a blind tent and asked people to point out what posters are new and asked them if any don't fit in (no one said they don't). The results are at the bottom of this PR. I accidentally put 21 and 22 twice. Oops.

## What is required after this PR?
Anyone doing a bugfix on BoxStation should delete the tinted windows under the curtains. These windows were added so that the shower curtains blocked sight at all times. It was either that, or it allows sight at all times.
If you do a bugfix on BoxStation, please add the HoochMaster (bar chem-master) to the bar. I forgot to re-add it back ages ago and it's my fault. It was never supposed to be removed, hence it's a bug.

## Changelog
:cl:
add: Nine new posters!
add: Shower curtains can be crafted.
add: New sofas!
add: Green and purple comfy chairs to the crafting menu to fit green and purple carpets.
fix: Shower curtains now let you see through them once open, and don't once closed.
/:cl:

## Additional Credits
• Whoever made the original sofa sprites. They were ported from Hyper, who ported them from elsewhere. I edited the sprites a bit and added arm-rests.
• Ghommie for suggesting improvements to the original Chess PR.

## Images
![image](https://user-images.githubusercontent.com/53862927/75780227-dd510f80-5d52-11ea-9bf7-485db57705bf.png)
**The new posters are:
• NTAPDA 600
• NTAPDA 800
• Hydro
• SCUM
• NT Storm
• NT Storm, but the other version
• Medical (Green +)
• Syndicate (White S but snake head)
• Fashion!**

## Blind Test
![image](https://user-images.githubusercontent.com/53862927/75780557-7ed86100-5d53-11ea-806f-ef5bdd09d051.png)
![image](https://user-images.githubusercontent.com/53862927/75780603-9a436c00-5d53-11ea-9b90-7e54af37afa3.png)
![image](https://user-images.githubusercontent.com/53862927/75780623-a2031080-5d53-11ea-8051-d888dbe6c118.png)
**Answers:**
_6, 8, 9, 10, 11, 13, 15, 24 and 26._

2020-03-03 14:18 UTC, Detective-Google commented
I'm pretty sure those sofa sprites come from Eris, which I've said a few times. If I was at my computer I'd go find it on their code and show you, but generally it's a dick move not to credit the sprite authors when porting sprites.

2020-03-03 14:24 UTC, KathrinBailey commented
> I'm pretty sure those sofa sprites come from Eris, which I've said a few times. If I was at my computer I'd go find it on their code and show you, but generally it's a dick move not to credit the sprite authors when porting sprites.

And afterwards, I checked maps to look around for CEV Eris and couldn't find any of the sofas there to confirm it.
I actually gave credit for the sofas, twice, but it seems like the full credit is in the backup files I made and I didn't copy and paste it over. I'm re-adding the credits that were unintentionally missed off.

2020-03-03 20:12 UTC, Ghommie requested changes

2020-03-03 20:12 UTC, Ghommie commented on code/game/objects/effects/contraband.dm
> +	icon_state = "poster47"
Same description, same name, same path, just different icon states.
I believe the second is pertinent to something else and not security though.

2020-03-03 20:12 UTC, Ghommie commented on code/game/objects/structures/chess.dm
> +/obj/structure/chess/WhitePawn
keep the paths lowercase.

2020-03-03 20:12 UTC, Ghommie commented on code/game/objects/structures/watercloset.dm
> +		opacity = 1
TRUE

2020-03-03 20:12 UTC, Ghommie commented on code/game/objects/structures/watercloset.dm
> +		opacity = 0
FALSE

2020-03-03 20:15 UTC, Ghommie requested changes
Just noticed it was a new file.

2020-03-03 20:15 UTC, Ghommie commented on code/game/objects/structures/beds_chairs/sofa.dm
> +/obj/structure/chair/corp_sofa
Move normal sofas into this file amd make these ones a subtype of them.

2020-03-04 01:37 UTC, KathrinBailey commented
Change requests are done.
Armrest spawning on wrong sofa dir also fixed, armrests tested and working.

2020-03-04 13:26 UTC, Ghommie approved these changes

2020-03-04 13:26 UTC, Ghommie commented on code/game/objects/structures/beds_chairs/sofa.dm
> +	icon = 'icons/obj/sofa.dmi'
remove.

2020-03-04 14:40 UTC, merged