Pixel shifting for ERP
citadel-station/citadel-main pull request #11349
Opened 2020-03-06 09:34 UTC by monster860

This code is completely 100% untested.

## About The Pull Request

What this does is make it so that if you are holding ctrl+shift and then do a direction it causes you to pixel shift

## Why It's Good For The Game

well you see I was doing a threesome ERP and I was on top of someone with someone else and we couldn't position ourselves correctly so I open this PR so that no one else has to deal with the limitations of tile based movement when trying to ERP.

## Changelog
:cl:
add: Use Ctrl-Shift-direction key to shift your characters position. Use for ERP.
/:cl:

2020-03-06 10:01 UTC, monster860 commented
Against my better judgement I tested the PR. Here's a picture

![image](https://user-images.githubusercontent.com/3681297/76073361-7e181880-5f67-11ea-89d5-cca0d2816fa3.png)

2020-03-06 10:04 UTC, monster860 commented
![image](https://user-images.githubusercontent.com/3681297/76073621-e5ce6380-5f67-11ea-82b7-fd60e2f4c81f.png)

2020-03-06 10:07 UTC, BlackMajor commented
PR of the year.
Make sure it works for other mobs too. Like ash drakes, borgs and xenos.

2020-03-06 10:08 UTC, monster860 commented
it should work on all mobs

2020-03-06 10:08 UTC, BlackMajor commented
Bless.

2020-03-06 11:28 UTC, dapnee commented
absolute madlad. 
now for this to be used for combat /s

2020-03-06 13:22 UTC, Ragolution commented
> absolute madlad.
> now for this to be used for combat /s

If it doesn't already, this should have a line specifying a recenter on movement, to prevent abuse.

2020-03-06 20:45 UTC, Detective-Google commented
> > absolute madlad.
> > now for this to be used for combat /s
> 
> If it doesn't already do so on tile transition, this should have a line specifying a recenter on movement, to prevent abuse.

Should also be a limit to prevent shifting out of the tile they're currently in(don't want people shifting their sprites into walls and whatnot.)

2020-03-06 21:06 UTC, monster860 commented
you can't shift more than 16 pixels in a direction to prevent aboos

2020-03-06 21:50 UTC, Ragolution approved these changes
I think it's funny I can even approve things.

2020-03-07 00:17 UTC, Ghommie commented
The pixel shift doesn't reset on move, perhaps add two variables to store the x and y shifted pixels amount and a comsig hook to reset them on move.

2020-03-07 00:18 UTC, Ghommie requested changes
The pixel shifting doesn't reset on move, perhaps add two variables to store the x and y shifted pixels amount and a comsig hook to do the job.

2020-03-07 03:06 UTC, monster860 commented
there I did the thing

2020-03-07 08:08 UTC, kevinz000 commented on code/modules/mob/mob_defines.dm
> +	var/is_shifted = 0
False

2020-03-09 05:20 UTC, Detective-Google commented
@monster860 as of commit c8535275ce being testmerged on the server, using the "set custom holoform" pAI option and then swapping your holo to the new one whilst pixel shifted will result in your "default" position to being the position you were shifted in when you set the holoform.

2020-03-10 16:37 UTC, Ghommie approved these changes

2020-03-10 17:01 UTC, merged