tasers (disabler alt fire that no one uses) are now as fast as disablers and 7 --> 14 tile range
citadel-station/citadel-main pull request #11351
Opened 2020-03-06 12:32 UTC by kevinz000

## About The Pull Request

changes projectile speed to match disablers

## Why It's Good For The Game

maybe i should have just killed it instead of making it a weird thing but uh ok

## Changelog
:cl:
balance: disabler taser alt fire shots are faster and have a 14 tile range now
/:cl:

2020-03-06 12:34 UTC, kevinz000 commented
oh yeah not just those have the taser shots ugh

2020-03-06 13:19 UTC, Ragolution commented
why tho

2020-03-06 13:24 UTC, Ghommie requested changes
No, nerf disablers cost instead, a good chunk of the disabler buffs were only made to discourage taser use when the latter mode was still dominant.

2020-03-06 13:46 UTC, kevinz000 commented
Updated to entirely remove the DoT and just be a slow at the cost of 2.5 disabler shots.
Tasers were meant to be a slowdown alt fire for niche/situational cases, not just a better disabler or a worse one (which is what it is as of right now, there's no reason to use it when you can just use disablers).

And re: disabler nerfs, I don't think it's necessary with security already having been nerfed a lot, the current sprint changes, and the fact that just about nothing else has been patched/redone to match the new numbers and such. It's important to realize that while security shouldn't AUTOMATICALLY WIN 1v1s, we're already long, long past that point with new weapons. Antags shouldn't take on security without a good reason to and it shouldn't be incentivized by security being made out of paper mache (is that how you spell it lmao). We're a long ways away from the old stun & done security combat, you now have a decent-ish chance with just mediocre preparations if you are skilled, and for an antagonist, your usual equipment makes you pretty good already (even if baton disarm will always be a fucking meme but it's as of right now kind of a bandaid for how terrible every other part of the system is).

I don't want to reward validhunting/mindless charging the antags but I also don't want antagonists to be downright unstoppable half the time. In a perfect world, yes, the crew will band together and security will have teamwork. But consider that solo antagonists should rely on stealth and surprise ambushes instead of going and charging down security default vs default gear, you can already do this if you well, buy loud weapons, but they shouldn't automatically win just like how sec shouldn't automatically win. Anyways, regarding teamwork and requiring groups of people to take down one SOLO ANTAGONIST:

This is citadel.
Even on /tg/, that doesn't work out. This game platform itself and the entirety of the combat system is just, not built for effective teamwork.
Why would it work out here even if it's made a necessity?

2020-03-20 02:14 UTC, Ghommie approved these changes

2020-03-20 02:15 UTC, merged