Kills screen-wide EMPs
citadel-station/citadel-main pull request #11375
Opened 2020-03-07 06:48 UTC by Auris456852

## About The Pull Request

This makes a small line change to make the EMP reaction's size be determined logarithmically, rather than linearly. That meaning, there's diminishing returns on EMPs. As a consequence, there's not TOO much reason to try to make a very big EMP, like with maxcaps before toxins became research... Though I'm sure some of you, who like to get the largest numbers on things possible, can still reach some ungodly numbers with payloads.

## Why It's Good For The Game

Because you won't be able to EMP the whole station with one grenade anymore. You should, of course, be welcome to reach for new heights, but you shouldn't be able to lolEMP the entire station. Even if it costs a fair deal of uranium, a good miner can get 15 sheets in no time, assuming the ORM is upgraded in a timely manner.

## Changelog
:cl:
balance: Made EMP reaction growth logarithmic.
/:cl:

2020-03-07 06:52 UTC, monster860 reviewed
for 200 multiplier its 6 heavy and 9 light.

![image](https://user-images.githubusercontent.com/3681297/76138455-43b98480-6016-11ea-8a70-12faef25df60.png)

2020-03-07 08:00 UTC, shellspeed1 commented
It might be worth tweaking emps so that after a certain point they get much stronger and do more damage to exos and borgs. As it is, emps which are supposed to be the counter to exosuits are well. junk at best especially with upgraded cells and parts.

2020-03-07 08:05 UTC, kevinz000 commented
hot take

I actually like large emps 
Why not make a system for more granular EMP power rather than a hard log cap?

2020-03-07 17:16 UTC, Auris456852 commented
Theoretically a sound plan, but we'd likely need to change the empulse function in its entirety for that... Not that I looked into its inner workings. It's likely possible to scale EMP damage with the size of it, but unless we gave a buff to all EMP-based weapons in general, which is a delicate balance I would rather be careful with, it would only make chem-made EMPs notably better against silicons, as the others all call the empulse function straight up, with no changes in size. This only changes the calculation on the chem reaction.
If I had to make a suggestion on that front, which I may get on in the near or far future, just make the heavy part drain a percentage of their cell's max power to deal with the borgs and exos? Constant + percentage if you want it to counter slime cell ones better, too, which have little max power, but regenerate... But that'd be a bit too much methinks. @shellspeed1 

~~i either don't have enough math skill for that or enough knowledge in english to know exactly what you mean by granular @kevinz000~~

2020-03-08 01:07 UTC, Ghommie commented
Logarithms alone make the growth curve a bit too drastic here, the gain of a 480 units reaction here is not even the double of the 48 units one. Feel free to use different functions, but personally I'd say a rational exponent is enough.

2020-03-08 01:07 UTC, Ghommie requested changes
The logarithms alone make the growth curves a bit too dramatic here, the gain of a 480 units reaction here is not even the double of the 48 units one. Feel free to solve the issue with different functions of your choice.

2020-03-20 14:56 UTC, Auris456852 commented
Going over this, it appears I may have miscalculated things previously as well...
And the comment had lied to me too, though I should've been able to tell that one sooner - through some debugging (making it use multiplier alone for the EMPulse), I found that a 50/50 iron/uranium grenade has the multiplier of 50. However, that very same grenade previously had the range of the 100 multiplier listed in the comment. As one would expect when trying to use exponents or logarithms, this changes things a bit. I changed it to work progressively worse past the 50 multiplier point instead.

2020-03-21 15:08 UTC, Ghommie approved these changes

2020-03-21 15:09 UTC, merged