Box theatre starboard vent/scrubber fix
citadel-station/citadel-main pull request #11385
Opened 2020-03-08 11:31 UTC by bunny232

## About The Pull Request
Moves a vent and scrubber down 5 pixels

## Why It's Good For The Game
Things looking nice is nice.

## Changelog
:cl:
fix: moved a scrubber and vent down 5 pixels
/:cl:

2020-03-08 12:36 UTC, bunny232 commented
Fun fact easy facing vents/scrubbers spawn with pixel_y set to 5 for me aaaaaaaaaa

2020-03-08 13:05 UTC, Ghommie requested changes
You can add the suggestions to a batch and apply them in a single commit

2020-03-08 13:05 UTC, Ghommie commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	pixel_y = 0
```suggestion
	dir = 4
```

2020-03-08 13:05 UTC, Ghommie commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	pixel_y = 0
```suggestion
```

2020-03-08 13:05 UTC, Ghommie commented on _maps/map_files/BoxStation/BoxStation.dmm
>  	dir = 4;
```suggestion
	dir = 4
```

2020-03-08 13:05 UTC, Ghommie commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	pixel_y = 0
```suggestion
```

2020-03-08 13:05 UTC, Ghommie commented on _maps/map_files/BoxStation/BoxStation.dmm
>  	dir = 4;
```suggestion
	dir = 4
```

2020-03-08 15:12 UTC, bunny232 commented
> You can add the suggestions to a batch and apply them in a single commit

Neat

2020-03-11 12:10 UTC, Ghommie approved these changes

2020-03-11 12:10 UTC, merged