Fix runtimes some more.
citadel-station/citadel-main pull request #11418
Opened 2020-03-10 21:55 UTC by Ghommie

## About The Pull Request 
Fixing some runtimes, also `dropped` user arg for clarity.

## Why It's Good For The Game
Fixing some runtime errors.

## Changelog
None.

2020-03-11 23:11 UTC, Putnam3145 requested changes

2020-03-11 23:11 UTC, Putnam3145 commented on code/game/objects/items/granters.dm
> +	if(do_after(user,50, TRUE, user))
WEW LAD

2020-03-11 23:11 UTC, Putnam3145 commented on code/game/objects/objs.dm
> -				if (usr.client && usr.machine==src) // && M.machine == src is omitted because if we triggered this by using the dialog, it doesn't matter if our machine changed in between triggering it and this
the rare and highly dangerous triple nested if statement, now tamed

2020-03-11 23:11 UTC, Putnam3145 commented on code/modules/hydroponics/grown/banana.dm
> +			S.speed += round(10 - 10 * (seed.potency/100), 1)
I know this is fixing a divide-by-zero, but it's a... totally different equation.
![image](https://user-images.githubusercontent.com/3927690/76472458-d5c4e280-63b2-11ea-9900-d8b8a75de179.png)

2020-03-11 23:59 UTC, silicons approved these changes

2020-03-12 00:00 UTC, Putnam3145 approved these changes

2020-03-12 00:01 UTC, merged