Nerfs piggyback and fireman carrying
citadel-station/citadel-main pull request #11555
Opened 2020-03-20 17:42 UTC by kevinz000

## About The Pull Request

You can no longer use items while fireman carrying.
You are now slowed by 1 while piggyback carrying.

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2020-03-22 19:12 UTC, Linzolle commented
seems reasonable to me

2020-03-24 20:08 UTC, Ghommie requested changes

2020-03-24 20:08 UTC, Ghommie commented on code/datums/components/riding.dm
> +		stack_trace("Warning: parent was not a human on [type]/Destroy().")
When the parent is deleted, its components are deleted too. This will end up in useless stack traces every time a vehicle is deleted.

2020-03-25 20:16 UTC, Ghommie approved these changes

2020-03-25 20:16 UTC, merged