Makes a few space ruins hard spawn
citadel-station/citadel-main pull request #11606
Opened 2020-03-24 21:56 UTC by Trilbyspaceclone

## About The Pull Request

Lost ship, Syndie mining base in space and broken old tele relay are now all hard spawns
Corrects a few words on BM's space ruins

## Why It's Good For The Game

Lost ship is rare and rare and its rather nice to get.
Syndie mining base is one of the few ruins needed for cargo thus it should be prob spawning in.
Old Tele Relay is just a really good space ruin to teleport to and make a new ~~ERP~~ room for people to hangout in

## Changelog
:cl:
balance: White Ships, Telerelays and a defunk mining post are now always going to spawn.
spellcheck: Corrects a few desc on station side ruins
/:cl:

2020-03-25 13:41 UTC, Ghommie requested changes
I'm ok with the abandoned teleporter (and maybe the whiteship if it weren't for the GPS), but not the rest, Citadel already runs a shrunk amount of space ruins levels and there is no need to make them more formulaic.

2020-03-25 20:27 UTC, Trilbyspaceclone commented
@Ghommie Relay Tele is the small one thats like an ball in space.
OneStation is the small safe ruin in space with the syndia docks
The white ship should 100% be a hard spawn these days. Its rare and rarer

2020-03-26 14:15 UTC, Ghommie commented
What I was saying is that making some ruins always spawn will make deep space more predictable.

2020-03-27 06:11 UTC, Trilbyspaceclone commented
@Ghommie Ok. What one do you dislike?
Im more then willing to take off Old-Tele Relay.

2020-03-29 01:52 UTC, Ghommie approved these changes

2020-03-29 01:53 UTC, merged