Wouldn't it be wild if you could color a lot of clothing to your personal liking?
citadel-station/citadel-main pull request #11687
Opened 2020-03-29 23:20 UTC by Xantholne

## About The Pull Request

Deletes some duplicate icons, makes neck worn overlays actually universal for coloring on all neck pieces, removes a ton of excessive items in loadout and cloathesmate making them instead poly chromic. Originally Putnam and I both without knowing were planning on it, ended up finally doing it.
Also hats and gloves can be made polychromic now for any new aditions.
Also adds some elbow length gloves and a new croptop with a jacket design.
Still left in the regular mime beret though since it is used in food recipes.

## Why It's Good For The Game

Duplicate icons, more things can be made polychromic now outside of uniforms, collars (Because who set it to be collar and not neck??) and wintercoats, cuts down on menu bloat, not sure if I should just delete the code lines that still exist of the former stuff

## Changelog
:cl:
del: Removed some duplicate icons
add: New jacket croptop and elbow length gloves
tweak: Made a lot of clothesmate and loadout items polychromic removing the previous
/:cl:

2020-03-30 01:32 UTC, Linzolle commented on code/modules/clothing/clothing.dm
> +	return TRUE
put all this into its own proc so you don't have to copy-paste it a ton of times... or maybe even just put it under /obj/item/clothing/AltClick()

2020-03-30 01:32 UTC, Linzolle commented on code/modules/clothing/clothing.dm
> +	return TRUE
since it'll never get called if they don't have the polychrome vars anyway.

2020-03-30 01:33 UTC, Linzolle commented on code/modules/clothing/neck/_neck.dm
> +	name = "polychromic scarf long"
long polychromic scarf sounds more natural

2020-03-30 01:34 UTC, Linzolle commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = "A Qipao, traditionally worn in ancient Earth China by women during social events and lunar new years.."
Why two periods?

2020-03-30 01:35 UTC, Linzolle commented on code/modules/vending/clothesmate.dm
> -					/obj/item/clothing/under/suit/sl = 3,
did you mean to delete this?

2020-03-30 01:37 UTC, Linzolle commented on modular_citadel/code/modules/client/loadout/neck.dm
> +	name = "PolyChromic Long Scarf"
weird capitalision, long should be first word

2020-03-30 01:37 UTC, Linzolle commented on modular_citadel/code/modules/client/loadout/uniform.dm
> +	name = "PolyChromic Croptop"
capitalisation

2020-03-30 01:37 UTC, Linzolle commented on modular_citadel/code/modules/client/loadout/uniform.dm
> +	name = "Polychromic Skimpy Croptop"
putting skimpy first sounds more natural

2020-03-30 01:39 UTC, Linzolle commented on code/modules/vending/clothesmate.dm
> -					/obj/item/clothing/neck/scarf/christmas = 3,
these two have special icons that can't be replicated with colouring

2020-03-30 02:25 UTC, deathride58 requested changes
DNM until:

- [ ] The overrides to handle polychromic items are properly integrated into the /obj/item/clothing type or turned into a component (this PR literally just copy-pastes polychromic code to the level of specific categories, which is unacceptable for our standards)
- [ ] This PR is made to use color matrices instead of an extra three(!!!!) potential appearance mutations *per item* OR a damn good reason is provided for introducing that massive of a potential memory + performance impact during highpop ("polychromic clothes were like that" is not a reason)

2020-04-18 03:15 UTC, Ghommie commented
Stale and full of yucky copypasta. But I addressed most the requests done by deathride (minus the matrix instead of overlays, which is not that tangible seeing how `update_atom_colour` works), FYI.

Please avoid from attempting this many copypastas in the future.

2020-04-18 03:15 UTC, closed without merging