Buffs Stimpacks
citadel-station/citadel-main pull request #11737
Opened 2020-04-04 04:14 UTC by Trilbyspaceclone

## About The Pull Request
``
Wow 5 tc for 5 mins of SPEED, so amazing so useless so wast of credits.
Just buy stim implant its flat out better!
```
Well kiddos not anymore! You can now inject yourself through hardsuits - yay, as well as it now has a controlled injection of 10u per click! Meaning it gives 1 min per injection of stim action, and can share! - Legally dont share needles IRL just a bad idea 
## Why It's Good For The Game

Makes stimpacks not trash that is outclassed by a chemi with a micro or a implant that costs about the same, ecomic wise its still fucken better to buy the emp proof implant >:L but hey baby steps.

This also means chemis or traitors with smarts cant refill the needle with a cocktail of bad chems to inject all at one 50u.
## Changelog
:cl:
balance: Stimpacks now use a hypo meaning they can inject through hardsuits. Only inject 10u per injection (meaning you can inject someone or yourself upto 5 times). Sadly no longer just a 50u injection of chems, that can be refilled.
/:cl:

2020-04-04 04:30 UTC, kappa-sama commented
explain why you think stimpak needs a buff lol

2020-04-04 04:52 UTC, Trilbyspaceclone commented
They are trash in what they do. For 3 tc more you get 3x the stams, works through hardsuits, and during stam crit.
Their is no reason to go buy these over the implant as they are now. You also get a box too with the implant!

2020-04-04 05:14 UTC, kappa-sama commented
do you know what stimpak does

2020-04-04 05:25 UTC, Trilbyspaceclone commented
> also your math is wrong

No? You get to use stams 3x that means its able to be used 3x more cuz 3 x 1.
Ye you get "40%" less stams but you end up wasting so much of a stim injection from the needle. If order to make the 5tc "investment" to work you need to use 40% MORE of the reagents. As the implant works well stam crit works well in a hardsuit. Theirs only 1 case /ever/ to get the 3 tc less injector and that is when you are low on tc and cant afford the 3 tc more.
Im not tweaking the /time and affect/ of the implant
Im not balancing the chem loads
Im just making a better reason to buy the injector rather then having to deal with "welp I never got to use the 1 time only chem and now im stam crit."

2020-04-04 06:19 UTC, kevinz000 commented
no thank you

2020-04-04 06:19 UTC, kevinz000 commented
this is already really, really good.

2020-04-04 07:51 UTC, Trilbyspaceclone commented
Citation needed kev, its never actively gotton from what I can tell.

2020-04-04 07:54 UTC, Trilbyspaceclone commented
Its main "buff" is that it now injects more slowly in smaller douses and works through hardsuits.
*Same thing the implant does*
@kevinz000 Show me proof were its "already really, really good."
And that I would want to use this annoying needle over the implant other then the price differences

2020-04-04 08:32 UTC, necromanceranne commented
So this is similar to a change on tg where we changed it to a medipen for the same reasons. It goes through hardsuits.

Currently, and while it can't be used through hardsuits, it can be refilled to be used for healmixes down the road and lets you inject 50 units all at once. Additionally it can be used as a 50 unit syringe dart. Frankly I think the syringe is a little outdated and making it a 1 minute dosage per application hypo is an even better change than the medipen. If it wasn't for this, I'd have just ported the medipen.

2020-04-04 14:18 UTC, kevinz000 commented
@Trilbyspaceclone the implant is for 3-4 uses of getting out of a stamcrit situation or getting the upper hand on a fight.
stimpack is for 5 minutes of extremely high speed stamina regeneration in which time you can easily take out all of security.
i do not see why we need them to be multi use. use adrenals for that.

2020-04-06 22:58 UTC, kappa-sama commented
the statistics page is buggy just so you know and prone to errors, like not showing accurate results of what people buy (maybe because the end-of-round does the same)

2020-04-06 23:01 UTC, silicons requested changes
make it a medipen that injects all 50 in one go.

stimpacks are the do-or-die rampage for 5 minutes item.

if you want freely usable burst we have an item called adrenal implants.

2020-04-07 07:43 UTC, Trilbyspaceclone commented
@kevinz000 Horrable way to balance healing chems

2020-04-09 13:57 UTC, silicons approved these changes
eh see https://canary.discordapp.com/channels/161574200581029888/418907500876791808/697807248596008960

2020-04-09 13:57 UTC, merged