adds extra functionality to storage whitelists
citadel-station/citadel-main pull request #11832
Opened 2020-04-12 08:45 UTC by Seris02

## About The Pull Request

allows specific items to overcome weight class and other whitelists if needed in storage

## Why It's Good For The Game

someone asked for this and it's better functionality I guess? also someone will be using it in a further pr.

## Changelog
:cl:
add: more storage whitelist functionality
/:cl:

2020-04-14 08:33 UTC, kevinz000 commented
#11809 should come first @Citadel-Station-13/project-management

2020-04-20 20:38 UTC, Ghommie requested changes

2020-04-20 20:38 UTC, Ghommie commented on code/datums/components/storage/storage.dm
> +				return FALSE
```suggestion
		if(length(can_hold) && !is_type_in_typecache(I, can_hold))
			if(!stop_messages)
				to_chat(M, "<span class='warning'>[host] cannot hold [I]!</span>")
			return FALSE
```

2020-04-20 20:38 UTC, Ghommie commented on code/datums/components/storage/storage.dm
> +				return FALSE
```suggestion
		if(storage_flags & STORAGE_LIMIT_MAX_W_CLASS && I.w_class > max_w_class)
			if(!stop_messages)
				to_chat(M, "<span class='warning'>[I] is too long for [host]!</span>")
			return FALSE
```

2020-04-25 00:50 UTC, Ghommie approved these changes

2020-04-25 00:50 UTC, merged