thieving gloves disguise
citadel-station/citadel-main pull request #11833
Opened 2020-04-12 08:51 UTC by Seris02

## About The Pull Request

disguises thieving gloves from anyone except antags

oh also fixes agent IDs
(probably)

## Why It's Good For The Game

because people examining people and seeing thieving gloves is bad, and I still want them to be recognisable to antags easily

## Changelog
:cl:
add: antag only alternate appearance, adds it to thieving gloves
/:cl:

2020-04-12 18:14 UTC, kappa-sama commented
do you want to make it so chameleon (ie agent id) hud actions only show up if you're an antag?

2020-04-22 02:25 UTC, Ghommie requested changes

2020-04-22 02:25 UTC, Ghommie commented on code/modules/antagonists/_common/antag_datum.dm
> +
Unneeded proc overhead, remove.

2020-04-22 04:32 UTC, Seris02 commented on code/modules/antagonists/_common/antag_datum.dm
> +
weh

2020-05-15 04:03 UTC, Detective-Google commented
the gloves should have a description giving away that they're not normal gloves, even if the name is just 'black gloves'

2020-06-01 19:51 UTC, closed without merging