toggle for tetris bags
citadel-station/citadel-main pull request #11912
Opened 2020-04-18 10:31 UTC by Seris02

## About The Pull Request

title

## Why It's Good For The Game

it looks like fucking shit and most people aren't going to like it

## Changelog
:cl:
add: toggle for tetris bags
/:cl:

2020-04-18 10:48 UTC, Arturlang commented
This seems abusable..

2020-04-18 11:32 UTC, Ghommie commented
The feature is currently undergoing some bugfixing by kevinz, and personally I don't think this is a good way to fix those issues.

2020-04-18 12:35 UTC, Seris02 commented
he gave me his blessings to make it, all it does it alter how the bags are viewed by the person, as far as I know

2020-04-22 02:20 UTC, Ghommie requested changes

2020-04-22 02:20 UTC, Ghommie commented on modular_citadel/code/modules/client/preferences.dm
> +	var/no_tetris_storage = FALSE
No, move it away from modular_file, I'm still planning on deconstructing that ruin of a folder.

2020-04-22 20:26 UTC, Ghommie approved these changes

2020-04-22 20:26 UTC, merged