Adds a safty lable to donk pockets
citadel-station/citadel-main pull request #11914
Opened 2020-04-18 11:58 UTC by Trilbyspaceclone

## About The Pull Request

Donk pockets after a legal battle have now placed a warning on the box
## Why It's Good For The Game

Was suggested as this still kills people from time to time + the food quirk making it much easyer to od on donks 

## Changelog
:cl:
add: New safety label has been added to Donk Pocket Box
/:cl:

2020-04-18 12:05 UTC, CinderWC commented on code/game/objects/items/storage/boxes.dm
> +	desc = "<B>Instructions:</B> <I>Heat in microwave. Product will cool if not eaten within seven minutes. WARING: Eating to many at once may lead to bodily harm!</I>"
Spell Check: **too** many

2020-04-18 12:06 UTC, CinderWC commented on code/game/objects/items/storage/boxes.dm
> +	desc = "<B>Instructions:</B> <I>Heat in microwave. Product will cool if not eaten within seven minutes. WARING: Eating to many at once may lead to bodily harm!</I>"
Also **Warning** instead of Waring

2020-04-18 12:10 UTC, CinderWC commented
Spell check in title too <3

**safety label**

2020-04-18 12:11 UTC, ghost approved these changes

2020-04-18 12:17 UTC, Ghommie requested changes
It's very unlikely for someone to actually OD on omnizine by binging on warm donk pockets alone, the box only contains 6 units with 3u of ominize each, for a total of 18u vs the od threshold of 20, not including the click delay per bite and food intake cap...
But if that ever happens, that's a well deserved quality gameplay punishment for being too voracious folks, no need to try and idiotproof it.

2020-04-18 12:19 UTC, CinderWC commented
Honestly... Ghommie does have a good point here. Maybe we should change the warning to something thats more towards liggers instead?

2020-04-18 12:26 UTC, Trilbyspaceclone commented
It was suggested, personally I agree their should be a, just last week someone walked into sci, and was in crit do to donk OD. It does happen time to time

2020-04-18 12:27 UTC, CinderWC commented
They have to eat more than a box of Dink to actually OD off the omnizine, that or they are a dumb ligger who ate them

2020-04-18 12:38 UTC, Ghommie commented
EDIT: It's actually not so unlikely to OD on donk pockets with an upgraded microwave because upgraded machines are straight up capable of multiplying atoms and reagents like loaves and fishes. I'm fed up of it.

2020-04-18 12:39 UTC, CinderWC commented
> EDIT: It's actually not so unlikely to OD on donk pockets with an upgraded microwave because upgraded machines are straight up capable of multiplying atoms and reagents like loaves and fishes. I'm fed up of it.

Nerf it upstream. Even if it's denied I would port it down here

2020-04-18 12:49 UTC, Trilbyspaceclone commented
I thought they od'ed on 1 donk and  2 bites. Cuz the first and only time ive od on donks was with an upgraded microwave - note this like 3 years ago and now I tend to eat cooks food rather then vender trash if any at all

2020-04-18 13:51 UTC, CinderWC commented
Wait I just realized this is Citadel tf am I doing here.

Why am I getting notifications for cit

2020-04-20 23:36 UTC, Ghommie commented
Upgraded microwaves were nerfed, no need for a label anymore.

2020-04-20 23:36 UTC, closed without merging