shotgun shell clips
citadel-station/citadel-main pull request #11955
Opened 2020-04-20 21:02 UTC by Hatterhat

## About The Pull Request
Shotgun shell clips. Small items, hold 4 shells in 1 slot, can be used to reload a shotgun (one shell per click). Not roundstart - you'll have to figure out that they exist, first, before you can get your grubby mitts on them.
## Why It's Good For The Game
Shotgun shells are a bit of a hassle to throw around. This might make things a little better if you have to lug around boxes of shells - then again, if you're lugging around boxes of shells, you might have more pressing matters.
## Changelog
:cl:
add: Rumors of the existence of metal strips designed to hold shotgun shells have reached Citadel Station 13.
/:cl:

2020-04-20 21:08 UTC, BobJogaIsForkinBanned commented
oh hi

2020-04-20 21:08 UTC, CinderWC commented
Damn bro how about you credit us next time https://github.com/Skyrat-SS13/Skyrat13/pull/1405

2020-04-20 21:09 UTC, Strazyplus commented
Big brain

2020-04-20 21:10 UTC, CinderWC commented
![PDUp9LC](https://user-images.githubusercontent.com/51722986/79800229-23425100-835c-11ea-863d-b095da4ae709.png)
![W1LZOgs](https://user-images.githubusercontent.com/51722986/79800231-24737e00-835c-11ea-943f-5df9202b608e.png)

2020-04-20 21:12 UTC, Investigator77 commented
Hey, wait, I know this one!

2020-04-20 21:34 UTC, Ghommie commented
DNM tag until the original is merged downstream, and thus legitimely under the same licenses defined in the OP.

2020-04-20 21:43 UTC, Putnam3145 commented
hell's going on in the comments in here

2020-04-20 21:46 UTC, Hatterhat commented
looks like i owe myself five bucks for not getting away with that

2020-04-20 21:48 UTC, Investigator77 commented
Dismantled and bluepilled

2020-04-20 22:04 UTC, ShadeAware commented
TF is wrong with you Hatter smh

2020-04-20 22:04 UTC, CinderWC commented
@Hatterhat Credit us next time or we will show up at your door with soap socks

2020-04-20 22:17 UTC, Hatterhat commented
@CinderWC square up nerd

2020-04-20 22:24 UTC, Putnam3145 commented
@CinderWC okay while i do think it's good practice to credit people let it be clear that it is neither in the spirit nor the letter of our licenses to do that

2020-04-20 22:29 UTC, CinderWC commented
@Putnam3145 Oh i never meant any of this in a law sense as in "Ima sick the lawyers onto you"
I just wanted us/our contributors to be credited for this as its just in bad spirit to take without credit whatsoever.

2020-04-20 22:31 UTC, MrJWhit commented
I don't really see it as bad spirit, take what you want or not. Credit is nice, but not required in any way.

2020-04-21 03:05 UTC, BobJogaIsForkinBanned commented
> I don't really see it as bad spirit, take what you want or not. Credit is nice, but not required in any way.

Credit isn't required - but it's appreciated. Copying something without at least crediting the original is bad spirit, but i wouldn't say it's legally worrisome.

2020-04-21 07:19 UTC, Hatterhat commented
copying something without crediting the original sounds like what downstreams do :^)

2020-04-21 07:26 UTC, CinderWC commented
> 
> 
> copying something without crediting the original sounds like what downstreams do :^)

Sounds like it, but in theory it seems to be Contributors on upstream that seem to really like to do it. Case in point.

2020-04-21 09:39 UTC, Hatterhat commented
turnabout is fair play

2020-04-21 09:58 UTC, CinderWC commented
![5ef42524816b9b7da110641149508307](https://user-images.githubusercontent.com/51722986/79852812-76052280-83c7-11ea-8f9e-ea8477a01e6e.png)

2020-04-22 14:43 UTC, Ghommie requested changes
Useroth & co told me to just merge and spare them from modular conflicts, but there are some glaring hacky code that has to be dealt with. See #11976.

2020-04-22 14:43 UTC, Ghommie commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +	cut_overlay(shell_overlay_list, TRUE)
Remove.

2020-04-22 14:43 UTC, Ghommie commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +	update_overlays()
This is already done, remove.

2020-04-22 14:43 UTC, Ghommie commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +			add_overlay(shell_overlay, TRUE)
```suggestion
			. += shell_overlay
```

2020-04-22 14:43 UTC, Ghommie commented on code/modules/projectiles/ammunition/ballistic/shotgun.dm
> +	var/mutable_appearance/current_overlay // for stripper clips
pretty much unused, remove.

2020-04-22 14:43 UTC, Ghommie commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +			C.current_overlay = shell_overlay
Idem.

2020-04-22 14:43 UTC, Ghommie commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +	var/shell_overlay_list = list(null, null, null, null)
remove.

2020-04-22 14:43 UTC, Ghommie commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +		for(var/obj/item/ammo_casing/shotgun/C in stored_ammo)
```suggestion
		for(var/A in stored_ammo)
			var/obj/item/ammo_casing/shotgun/C = A
```

2020-04-23 18:44 UTC, kevinz000 commented
I'm not exactly a fan of buffing shotguns this way.
They're meant to be clunky.
That plus and this'll need inventory stuff done considering they currently take the same amount of space as just a regular shell (guess throwing normal sized on it would work though, volumetric system automatically handles it and it'd be less efficient than boxes as a trade-off).
@Citadel-Station-13/project-management

2020-05-09 00:49 UTC, Ghommie approved these changes
To be honest, these are just shell holders, not stripper clips, and probably are gonna stay as such here.

2020-05-09 00:49 UTC, merged