Nerfs Tactical Cock Flattening
citadel-station/citadel-main pull request #11978
Opened 2020-04-22 16:34 UTC by necromanceranne

## About The Pull Request

A smaller dick = more aerodynamic to hunt valids.

## Why It's Good For The Game

I hate ERP code

## Changelog
:cl:
fix: Adds a check for enlargement when your junk goes below the enlargement values.
/:cl:

2020-04-22 17:42 UTC, silicons approved these changes

2020-04-22 20:09 UTC, Ghommie requested changes
I wonder what you are trying to accomplish here...

2020-04-22 20:09 UTC, Ghommie commented on modular_citadel/code/modules/arousal/organs/breasts.dm
> +		enlargement = FALSE
Unreachable code, `enlargement` is already FALSE.

2020-04-22 20:09 UTC, Ghommie commented on modular_citadel/code/modules/arousal/organs/penis.dm
> +		enlargement = FALSE
Idem.

2020-04-23 17:31 UTC, necromanceranne commented
Well apparently this isn't going to do anything so...probably best I just close this?

2020-04-23 17:31 UTC, closed without merging