removes modular_citadel
citadel-station/citadel-main pull request #12001
Opened 2020-04-24 02:51 UTC by Seris02

## About The Pull Request

title
it compiles
now all I need to do is merge conflicts

## Why It's Good For The Game

yes

## Changelog
:cl:
code: removes modular_citadel
/:cl:

2020-04-24 02:52 UTC, kappa-sama commented
the man's done it

2020-04-24 13:46 UTC, Ghommie commented
Lots of files to review and lots of peeves to fix. Please noboy merge this until I finish reviewing.

2020-04-24 16:30 UTC, Ghommie requested changes
I told you to split take your time and make several smaller PRs instead, instead you make a single, hasty and massive PR. I'm upset you just changed the typepaths of many .dmi files instead of cut and pasting the states in the right places.
Whatever, hopefully you'll have the patience to resolve these requests. Right now the review only covers about half the done changes. The interface gets pretty laggy on PRs with several files modified.

Also delete `__HELPERS/lists.dm` and move its lines to `__HELPERS/_lists.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/_onclick/hud/screen_objects.dm
> +		theuser.lay_down()
We already have the original rest button (`/obj/screen/rest`) that does the same thing now. I think you should remove this one and modify line 244 of `hud/human.dm` accordingly

2020-04-24 16:30 UTC, Ghommie commented on code/_onclick/hud/sprint.dm
> +	icon = 'icons/ui/screen_midnight.dmi'
Please do it properly, move the states to `icons/mob/screen_midnight.dmi` and delete this copypaste. Same for all other screen dmi files.

Also move this file contents to `screen_objects.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/__HELPERS/list2list.dm
> +/proc/tg_ui_icon_to_cit_ui(ui_style)
Once you are done, delete this.

2020-04-24 16:30 UTC, Ghommie commented on code/_onclick/hud/stamina.dm
>  /obj/screen/staminas
move these to `screen_objects.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/game/machinery/wishgranter.dm
> +/obj/machinery/wish_granter/attack_hand(mob/living/carbon/user)
Remove the former `attack_hand` definition.

2020-04-24 16:30 UTC, Ghommie commented on code/game/objects/items/balls.dm
> +	mob_overlay_icon = 'icons/mob/mouthball.dmi'
`icons/mob/clothing/mask.dmi` and move the states to that file.

2020-04-24 16:30 UTC, Ghommie commented on code/game/objects/items/devices/radio/electropack.dm
> +	mob_overlay_icon = 'icons/mob/citadel/neck.dmi'
'icons/mob/clothing/neck.dmi', and move the states to that file.

2020-04-24 16:30 UTC, Ghommie commented on code/game/objects/items/pneumaticCannon.dm
> +	shake_camera(user, (pressureSetting * 0.75 + 1), (pressureSetting * 0.75))
Just add this line to the former definition of `fire_items`.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/antagonists/nukeop/equipment/borgchameleon.dm
> +				disguise_icon_override = 'icons/mob/robots_citadel.dmi'
Just move the robots to the normal robots file as long as they are 32x32.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/client/preferences.dm
> +	LAZYINITLIST(L)
```suggestion
	var/list/L = list()
```

2020-04-24 16:30 UTC, Ghommie commented on code/modules/client/preferences_savefile.dm
> +		features["mcolor3"] = pick("FFFFFF","7F7F7F", "7FFF7F", "7F7FFF", "FF7F7F", "7FFFFF", "FF7FFF", "FFFF7F")
Move these savefile operations before the `update_character()` call.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/client/preferences_savefile.dm
> +			LAZYADD(chosen_gear, path)
```suggestion
			chosen_gear += path
```

2020-04-24 16:30 UTC, Ghommie commented on code/modules/client/preferences_savefile.dm
> +	S["loadout"] >> text_to_load
Also move these two lines before the `update_character()` call.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/clothing/head/cit_hats.dm
>  /obj/item/clothing/head/hunter
Move this stuff to `head/misc.dm` and delete this file.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/clothing/neck/_neck.dm
> +	..()
```suggestion
	. = ..()
```

2020-04-24 16:30 UTC, Ghommie commented on code/modules/clothing/suits/cit_suits.dm
> +/obj/item/clothing/suit/trek/ds9
Move these to `suits/miscellaneous.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/clothing/suits/cit_suits.dm
> +/obj/item/clothing/suit/armor/hos/trenchcoat/cloak
`armor.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/clothing/suits/cit_suits.dm
> +/obj/item/clothing/suit/hooded/cloak/david
`cloaks.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/mob/dead/new_player/preferences_setup.dm
> +	mannequin.add_overlay(mutable_appearance('icons/ui/backgrounds.dmi', bgstate, layer = SPACE_LAYER))
Just use the ones found in `icons/turf/floors.dmi` and rename the states in the prefs bg options, they are not even saved, so no savefile conversion problem.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/mob/living/carbon/damage_procs.dm
> +/mob/living/carbon/adjustStaminaLoss(amount, updating_health = TRUE, forced = FALSE, affected_zone = BODY_ZONE_CHEST)
Delete the former `carbon/adjustStaminaLoss`.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/mob/living/emote.dm
> +/datum/emote/living/scream/run_emote(mob/living/user, params) //I can't not port this shit, come on.
move this by its emote typepath.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/mob/living/living.dm
> +/mob/living/carbon/update_stamina()
Move this to `carbon/carbon.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/mob/living/living_movement.dm
> +	pixel_z = pseudo_z_axis
```suggestion
	pixel_z = pseudo_z_axis = newloc.get_fake_z()
```

2020-04-24 16:30 UTC, Ghommie commented on code/__DEFINES/mobs.dm
> +#define DEFAULT_BODYPART_ICON_CITADEL 'icons/mob/mutant_bodyparts.dmi'
Remove this define, move the parts to `icons/mob/human_parts_greyscale.dmi` instead.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/ammunition/ballistic/rifle.dm
> +/obj/item/ammo_casing/c46x30mm/rubber
This goes to `ballistic/smg.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/boxes_magazines/external/pistol.dm
> +	icon = 'icons/obj/guns/cit_guns.dmi'
This should go in 'icons/obj/ammo.dmi', like all modular magazines and casings.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/boxes_magazines/external/rifle.dm
> +/obj/item/ammo_box/magazine/wt550m9/wtrubber
`external/smg.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/guns/ballistic/pistol.dm
> +	icon = 'icons/obj/guns/cit_guns.dmi'
`guns/projectile.dmi`, like all non-magical/laser firearms.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/guns/ballistic/rifles.dm
> +	icon = 'icons/obj/guns/cit_guns.dmi'
toy guns go to `guns/toy.dmi` though.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/guns/ballistic/toy.dm
> +	icon = 'icons/obj/guns/toys.dmi'
move these to `guns/toy.dmi`, without the s.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/guns/ballistic/toy.dm
> +	icon = 'icons/obj/guns/pumpactionblaster.dmi'
`guns/energy.dmi`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/guns/ballistic/toy.dm
> +/obj/item/gun/energy/pumpaction		//parent object with all procs defined under. Useless in-game, but VERY important codewise
Also these are not toys, give them their own file in `guns/energy`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/guns/energy/energy_gun.dm
> +	icon = 'icons/obj/guns/cit_guns.dmi'
`guns/energy.dmi`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/guns/energy/laser.dm
> +	icon = 'icons/obj/guns/VGguns.dmi'
Heck, `guns/energy.dmi`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/guns/energy/laser.dm
> +	icon = 'icons/obj/guns/cit_guns.dmi'
.

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/projectile/beams.dm
> +	icon = 'icons/obj/guns/cit_guns.dmi'
`obj/projectiles.dmi`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/projectile/bullets/rifle.dm
> +/obj/item/projectile/bullet/c46x30mm/rubber
This goes to `bullets/smg.dm`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/projectile/bullets/special.dm
> +	icon = 'icons/obj/guns/cit_guns.dmi'
`obj/projectiles.dmi`

2020-04-24 16:30 UTC, Ghommie commented on code/modules/projectiles/projectile/megabuster.dm
> +	lefthand_file = 'icons/mob/citadel/guns_lefthand.dmi'
Move all the states of this file to 'icons/mob/inhands/weapons/guns_lefthand.dmi', damnit.

2020-04-25 01:24 UTC, Seris02 commented on code/modules/antagonists/nukeop/equipment/borgchameleon.dm
> +				disguise_icon_override = 'icons/mob/robots_citadel.dmi'
can't, too many overlapping sprite names and it would take about half an hour just to seperate them all

2020-04-25 01:27 UTC, Seris02 commented on code/_onclick/hud/sprint.dm
> +	icon = 'icons/ui/screen_midnight.dmi'
I didn't even know that icons/mob/screen_midnight.dmi was a file, why would it be in modular_citadel/icons/**ui**/screen_midnight.dmi. Don't sound like such an ass when you're making comments that aren't actually obvious.

2020-04-25 11:57 UTC, Ghommie commented on code/_onclick/hud/sprint.dm
> +	icon = 'icons/ui/screen_midnight.dmi'
Sorry, I thought you noticed that going through so many files.

2020-04-25 11:59 UTC, Ghommie commented on code/modules/antagonists/nukeop/equipment/borgchameleon.dm
> +				disguise_icon_override = 'icons/mob/robots_citadel.dmi'
ok

2020-04-26 02:22 UTC, kappa-sama commented
almost there

2020-05-01 12:38 UTC, closed without merging

2020-05-01 12:38 UTC, Seris02 commented
I can't do this right now, too much shit irl, reopen it if you want to make your own edits @Ghommie