Kilo station improvements
citadel-station/citadel-main pull request #12006
Opened 2020-04-24 15:40 UTC by Trilbyspaceclone

## About The Pull Request
This is no fixing this, this is a lost war before the first battle.
removed:Removes the spare tasers that are in sec
removed:Removes the egun on the shuttle
removed:Removes 210000000 decals all over
removed:Removes 200 plant stacks for no reason that looked like trash
removed:Removed round start posi brain and ninates
removed:Removed a bunch of blood/skeles
removed:Removed almost all rust from departments/halls
add:Added a few more clean bots
tweak:Shrink-ed turbine
balance:viro gets less sec gear
Likely did other things to

## Why It's Good For The Game

Less lag from all the annoying decals all over that bug out all the time to stab your eyes
Less power gamer creep round start with DUEL TASER ACTION
Less horrable plant boxes that have no reason to have 12 different plants per tile
Less mess to clean
Less horrable rust walls all over that make no real logic to be their other then `Hahah meteor get it?`
Less "hey isnt vaild hunting against the rules?"
Less "Hey why do I get handcuffs and almost a spear and or stunprod?"
Less horrable map i.g
Why did we even port this

## Changelog
:cl:
del: Removes the spare tasers that are in sec
del: Removes the egun on the shuttle
del: Removes 210000000 decals all over
del: Removes 200 plant stacks for no reason that looked like trash
del: Removed round start posi brain and ninates
del: Removed a bunch of blood/skeles
del: Removed almost all rust from departments/halls
del: Removed the catdoc that kills people and drops free ID
balance: Viro gets less sec gear
add:Added a few more clean bots
tweak:Shrink-ed turbine
/:cl:

2020-04-26 00:38 UTC, Linzolle commented
removing the Gamer stuff is fine with me but removal of the decals is kind of removing what makes Kilo... Kilo. Are you sure it actually impacts the performance? I've never heard of decals doing that.

2020-04-26 14:30 UTC, EmeraldSundisk commented
Can we get a visual example of some of these changes?

2020-04-26 18:45 UTC, Trilbyspaceclone commented
@EmeraldSundisk map diff shows before and afters as well as differents

2020-04-27 08:05 UTC, silicons requested changes
whatever after the map diffs was viewed by me because i finally figured out it was the second and not the first link this looks alright except for;
- return posibrain/nanites. no reason to remove one of the unique features of the map tbh.

2020-04-29 18:59 UTC, merged