Removes the radioactive stuff from uranium
citadel-station/citadel-main pull request #12049
Opened 2020-04-29 00:53 UTC by Trilbyspaceclone

## About The Pull Request

Makes items made from uranium no longer radioactive
sorry plux makers, you now need something a bit better then 4000 toolboxes

## Why It's Good For The Game
https://github.com/Skyrat-SS13/Skyrat13/pull/1597 sums it up p-well

Not even counting the abuse of this, its just a bad and adds nothing to the game that is worth having.

## Changelog
:cl:
del: uranium is no longer big bad evil rad man that it once was
/:cl:

2020-04-29 03:58 UTC, Putnam3145 commented
TG already dealt with most of this; check how they did it. I don't really know of any specific PRs, though...

2020-04-29 05:27 UTC, Trilbyspaceclone commented
I think the burning of urinain being rads is ok
urinain being just radioactive by itself?
Thats not really ok

2020-04-30 17:37 UTC, kevinz000 commented
what putnam said

2020-05-01 01:38 UTC, Trilbyspaceclone commented
@kevinz000 This way is better for the game then keeping the unrealistic rads from urainium
1 - Is legit against the rules, political stuff is meant to stay out of the game - Look at Make SS13 grate again AI board,  meme gone to far
2 - The stuff itself is rarely used outside of 1 stock part and a few implants, other then that its mostly used to look like nice walls/floors
3 - Game wise its fucken powerfull, 20 rads pre tick per item... You can legit abuse it for passive income, endless plux and more
4 - We already have a system that punishes you for miss-use of uranium why do we /need or want/ 3 differey ways to discourage the use of the mat?
5 - Heating it still gives off rads as thats tactical and emergent strats to get plux rather then passively with walls/floors/items
This adds to skills and takes away pointless "ahaha got em" gimmic uranium has

2020-05-01 22:34 UTC, Ghommie requested changes
You are always welcome to make the radioactivity of the material more laughably modest. I don't approve of this removal here.

2020-05-02 01:00 UTC, Trilbyspaceclone commented
@Ghommie this is modest

2020-05-06 22:15 UTC, Ghommie commented
Salt PR.

2020-05-06 22:15 UTC, closed without merging