Adds OOC notes
citadel-station/citadel-main pull request #12067
Opened 2020-04-30 21:10 UTC by kevinz000

## About The Pull Request
![image](https://user-images.githubusercontent.com/2003111/80759542-51f2c100-8aec-11ea-855d-f7649adccaec.png)

see I'd port skyrat's but I don't like the toggles, they're too blunt for my taste. 

## Why It's Good For The Game

Separate from flavor text, always shows, does not save with DNA.
Don't be that guy who metagames and ruins it for everyone.

## Changelog
:cl:
add: OOC notes has been added for ERP-related preferences. Please do not metagame or abuse this, and it is also not for character descriptions.
/:cl:

2020-05-01 00:31 UTC, kevinz000 commented
oh yeah bug report if you use manage flavor texts in game as opposed to from prefs the window doesn't word-wrap properly but that's not caused by me :^) @Ghommie

2020-05-01 08:34 UTC, lolman360 commented
kev i thought you didn't use ooc notes

2020-05-09 01:10 UTC, Ghommie requested changes

2020-05-09 01:10 UTC, Ghommie commented on code/modules/mob/living/carbon/human/human.dm
> +	AddElement(/datum/element/flavor_text/carbon, _name = "OOC Notes", _addendum = "Put information on ERP/vore/lewd-related preferences here. THIS SHOULD NOT CONTAIN REGULAR FLAVORTEXT!!", _always_show
Sorry for the late reply, but just make another `/datum/element/flavor_text` subtype for other prefs stuff or something, `/datum/element/flavor_text/carbon` is for dna stuff.

2020-05-09 01:10 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +	var/save_key
Also add a new variable used to override the standard examine list input on lines on lines 64-68.
We need a simple `[OOC]` text href button, without the first 37 characters of possible kinks.

2020-05-09 16:55 UTC, kevinz000 commented
moved pref load functionality up, it is only triggered if the prefs have the save key in it.
ooc notes is now base flavor text as it doesn't require any proc overrides

2020-05-10 23:27 UTC, Ghommie approved these changes

2020-05-10 23:27 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +	if(ishuman(target))
```suggestion
	if(save_key && ishuman(target))
```

2020-05-10 23:27 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +	var/dna_carryover = TRUE
```suggestion
```

2020-05-10 23:27 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +/datum/element/flavor_text/carbon/Attach(datum/target, text = "", _name = "Flavor Text", _addendum, _max_len = MAX_FLAVOR_LEN, _always_show = FALSE, _edit = TRUE, _save_key = "flavor_text", _examine_
```suggestion
/datum/element/flavor_text/carbon/Attach(datum/target, text = "", _name = "Flavor Text", _addendum, _max_len = MAX_FLAVOR_LEN, _always_show = FALSE, _edit = TRUE, _save_key = "flavor_text", _examine_no_preview = FALSE)
```

2020-05-10 23:27 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +	src.dna_carryover = _dna_carryover
```suggestion
```

2020-05-10 23:27 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +	texts_by_atom[C] = dna_carryover? C.dna.features[save_key] : C.client?.prefs?.features[save_key]
```suggestion
	texts_by_atom[C] = C.dna.features[save_key]
```

2020-05-10 23:27 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +	if(. && user.dna && dna_carryover)		// only save to dna if carrying over.
```suggestion
	if(. && user.dna)
```

2020-05-10 23:27 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +		user.dna.features["[save_key]"] = texts_by_atom[user]
```suggestion
		user.dna.features[save_key] = texts_by_atom[user]
```

2020-05-10 23:27 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +			user.dna.features["[save_key]"] = ""
```suggestion
			user.dna.features[save_key] = ""
```

2020-05-10 23:27 UTC, Ghommie commented on code/modules/client/preferences.dm
> +		"ooc_notes" = "",
Though this is not exactly a dna feature, I'll let it slide.

2020-05-10 23:27 UTC, Ghommie commented on code/modules/client/preferences.dm
> +				if(!length(features["ooc_notes"]))
```suggestion
			var/ooc_notes_len = length(features["ooc_notes"])
			if(ooc_notes_len <= 40)
				if(!ooc_notes_len)
```

2020-05-10 23:29 UTC, Ghommie commented on code/datums/elements/flavor_text.dm
> +	// if we aren't carrying over from dna load from prefs instead
```suggestion
```

2020-05-10 23:35 UTC, merged