[DNM - shuttles still do not work] Introducing niotstabxoB
citadel-station/citadel-main pull request #12073
Opened 2020-05-01 09:53 UTC by kevinz000

## About The Pull Request

hahaha sike I'm not a mapper (yet)
![image](https://user-images.githubusercontent.com/2003111/80797479-cb26fe00-8b56-11ea-9d1e-bd069d2e8c82.png)

No but adds map rotation in the literal sense of the word. I'll probably PR random mining ruin rotation in another PR.

## Why It's Good For The Game

More possibilities, etc etc. Disabled by default ofcourse, I'm not that cruel ;)

## Changelog
:cl:
add: The map loader is now rotational.
/:cl:

2020-05-01 11:18 UTC, kevinz000 commented
OH SHIT IT WORKS

2020-05-01 18:49 UTC, Linzolle commented
this is cursed

2020-05-01 19:07 UTC, Putnam3145 commented
what the fuck is a Boxbatstoin

2020-05-02 04:54 UTC, MrJWhit commented
Hey, this is _awful_ to play in. I can understand it being used in something like a wizard or an adminbus round where it's meant to be confusing and disorientating. But a regular-ass round? No, please stop it.

There's a minor issues with decals not rotating while in the center of the map making weird visual glitches.

But mostly, this is pain and I hate it.

2020-05-02 11:51 UTC, lolman360 commented
ah yes, Boxbatstoin, my favorite station

2020-05-02 22:48 UTC, kevinz000 commented
@MrJWhit support will be left in but this isn't for rotating primary maps

the ongoing stuff is mostly just testing.

in the future the only plans to actually use this will be for lavaland and similar ruins, and I guess when an admin feels like being funny.

2020-05-05 23:31 UTC, Ghommie requested changes

2020-05-05 23:31 UTC, Ghommie commented on code/modules/mapping/map_template.dm
> +	var/y = centered? max(FLOOR((world.maxy - height) / 2, 1), 1) : 1
```suggestion
	var/x = centered? max(round((world.maxx - width) / 2), 1) : 1
	var/y = centered? max(round((world.maxy - height) / 2), 1) : 1
```
round(value) without second arg already acts like FLOOR(value, 1)

2020-05-05 23:31 UTC, Ghommie commented on code/modules/mapping/map_template.dm
> +	template.load_new_z(orientation, ztraits)
```suggestion
	return template.load_new_z(orientation, ztraits)
```
The return value is used in createRandomZlevel to announce wheter the zlevel was successfully loaded or not.

2020-05-05 23:31 UTC, Ghommie commented on code/modules/mapping/map_template.dm
> +		var/turf/corner = locate(placement.x - FLOOR(((orientation & (NORTH|SOUTH))? width : height) / 2, 1), placement.y - FLOOR(((orientation & (NORTH|SOUTH))? height : width) / 2, 1), placement.z) // %1
```suggestion
		var/turf/corner = locate(placement.x - round(((orientation & (NORTH|SOUTH))? width : height) / 2), placement.y - round(((orientation & (NORTH|SOUTH))? height : width) / 2), placement.z) // %180 catches East/West (90,270) rotations on true, North/South (0,180) rotations on false
```

2020-05-05 23:31 UTC, Ghommie commented on code/modules/mapping/map_template.dm
> +		T = locate(T.x - FLOOR(((orientation & (NORTH|SOUTH))? width : height) / 2, 1) , T.y - FLOOR(((orientation & (NORTH|SOUTH)) ? height : width) / 2, 1) , T.z) // %180 catches East/West (90,270) rotat
```suggestion
		T = locate(T.x - round(((orientation & (NORTH|SOUTH))? width : height) / 2) , T.y - round(((orientation & (NORTH|SOUTH)) ? height : width) / 2) , T.z) // %180 catches East/West (90,270) rotations on true, North/South (0,180) rotations on false
```
Feel free to disregard these suggestions if the FLOOR macro turns out to be more efficient than the integrated round() function.

2020-05-06 15:50 UTC, Ghommie approved these changes

2020-05-06 15:50 UTC, merged