Nerfs Drake Armor
citadel-station/citadel-main pull request #12133
Opened 2020-05-07 07:04 UTC by Trilbyspaceclone

## About The Pull Request

Makes drake armor less better then any other sec suit
`armor = list("melee" = 65, "bullet" = 5, "laser" = 5, "energy" = 5, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 100, "acid" = 80)`

## Why It's Good For The Game

![image](https://user-images.githubusercontent.com/30435998/81264443-66185000-900f-11ea-8ce5-b046669c6220.png)

## Changelog
:cl:
balance: Drake suits are no longer one of the best none-antag/admin armor in the game
/:cl:

2020-05-07 10:14 UTC, necromanceranne commented
Though this being said while it makes you fireproof you are somewhat better with using your explorer suit after this.

2020-05-07 14:07 UTC, BobJoga commented
You have to kill a dragon to get one. The other you literally just get roundstart by having access to the armory. Of course the one you kill a dragon for is better.

2020-05-07 14:19 UTC, silicons requested changes
don't remove ACID_PROOF from it, that's different from actual acid armor.

2020-05-07 16:33 UTC, silicons approved these changes

2020-05-07 22:31 UTC, Linzolle commented
personally against this for the same reason BobJoga said. Of course it's better than suits you can get roundstart, you have to kill a boss for it. It's not even used for the same purpose as riot suits are. It's used as an upgrade to the explorer's suit for fighting the tougher megafauna.

2020-05-08 16:07 UTC, keronshb commented
At the very least I don't think the Melee damage should be touched because of other Lavaland Megas.

Does bullet effect Colossus' bullets?  If so then maybe that shouldn't be touched either.

2020-05-08 17:49 UTC, BobJoga commented
> At the very least I don't think the Melee damage should be touched because of other Lavaland Megas.
> 
> Does bullet effect Colossus' bullets? If so then maybe that shouldn't be touched either.

Colossus has 100% armor penetration, therefore bullet resistance doesn't matter. The thing that worries me about drake armor is the fact it has laser resistance for no good reason, being objectively better than the HECK since all of the rest of the stats are basically the same.
I don't get why this PR is a thing.

2020-05-11 11:14 UTC, kevinz000 commented
the reason i haven't merged this yet is the new stats do look a little low compared to standard tier armor and i'm wondering if it's a better or worse idea to just increase megafauna difficulty like /tg/ did 
however increasing megafauna difficulty still doesn't solve the issue of "good" mining players rushing these and becoming pvp gods when the role isn't about that

@Ghommie

2020-05-11 12:15 UTC, Ghommie commented
Yea, I'm cool with it, though I suppose it could have an extra 10 to 15 melee armor, so it still does its job as a buff riot armor against fauna.

2020-05-15 01:40 UTC, merged