Buffs space heaters
citadel-station/citadel-main pull request #12241
Opened 2020-05-13 17:45 UTC by Trilbyspaceclone

## About The Pull Request

space heaters can now be wrenched and unwrenched to remove bolts
space heaters now have 300% more laser powering and 200% more capacitor power

## Why It's Good For The Game

These things are worthless at dealing with most things above just 120~c or below -30~C
taking a long time and generaly only fixing slowly the 4~ tile area its around this fixes that
QoL to not have to make and un make a newly built space heater when you have to move it to cool the room
## Changelog
:cl:
add: Space heaters can now be wrenched and unwrenched
balance: Space heaters drain less and can reach even hotter/colder temps faster!
/:cl:

2020-05-16 03:02 UTC, Ghommie requested changes

2020-05-16 03:02 UTC, Ghommie commented on code/game/machinery/spaceheater.dm
> +		return
Move this to the `/wrench_act` procpath

2020-05-17 23:46 UTC, Trilbyspaceclone commented
@Ghommie Sorry for the delay but like that?

2020-05-18 00:31 UTC, Ghommie approved these changes
Well, let's see how this goes.

2020-05-18 00:31 UTC, merged