Makes Spears rational.
citadel-station/citadel-main pull request #12401
Opened 2020-05-30 18:00 UTC by Yawet330

## About The Pull Request
Drops the spear from 90% embed FLAT across it (and its subtypes) to 65% for the spear, 75% for the plasmatipped one, and 0% for the elance

## Why It's Good For The Game
hello yes funny spear 1hit kills you if it embeds, and elance spear that gibs you! 
Fuck 1 hit gib weapons

## Changelog
:cl:
balance: Rebalanced spears etc to be less dumb in combat, dropped embed rates to 65/75/0
/:cl:

2020-05-30 19:55 UTC, Ghommie approved these changes

2020-05-30 19:58 UTC, Ghommie requested changes
Yeeeea, I forgot embedding still uses singleton variable holders here.

2020-05-30 19:58 UTC, Ghommie commented on code/game/objects/items/twohanded.dm
> +	embedding = list("embedded_impact_pain_multiplier" = 1.5, "embed_chance" = 65)
```suggestion
	embedding = getEmbeddingBehavior(embed_chance = 65, embedded_pain_multiplier = 1.5)
```

2020-05-30 19:58 UTC, Ghommie commented on code/game/objects/items/twohanded.dm
> +		embedding = list("embedded_impact_pain_multiplier" = 1.5, "embed_chance" = 75) //plasmaglass spears are sharper
```suggestion
		embedding = getEmbeddingBehavior(embed_chance = 75, embedded_pain_multiplier = 1.5) //plasmaglass spears are sharper
```

2020-05-30 19:58 UTC, Ghommie commented on code/game/objects/items/twohanded.dm
> +		embedding = list("embedded_impact_pain_multiplier" = 1, "embed_chance" = 0)//elances should not be embeddable
```suggestion
		embedding = getEmbeddingBehavior(embed_chance = 0, embedded_pain_multiplier = 1)//elances should not be embeddable
```

2020-05-31 09:45 UTC, Yawet330 commented
Thanks @Ghommie

2020-05-31 11:44 UTC, Ghommie commented on code/game/objects/items/twohanded.dm
> +	embedding = getEmbeddingBehavior(embed_chance = 65, embedded_pain_multiplier = 1.5)
```suggestion
	embedding = list("embedded_impact_pain_multiplier" = 1.5, "embed_chance" = 65)
```
I didn't notice this was the object definition, so constants are expected.

2020-05-31 23:44 UTC, Ghommie approved these changes

2020-05-31 23:44 UTC, merged