poplocks hijack/glorious death
citadel-station/citadel-main pull request #12471
Opened 2020-06-07 09:13 UTC by kevinz000

## About The Pull Request

bandaid for now

## Why It's Good For The Game

no one wants to play lowpop hijack/glorious death it's cbt for all involved

## Changelog
:cl:
add: traitor classes can now be poplocked. hijack/glorious death are now locked to 35/25 respectively.
/:cl:

2020-06-07 10:28 UTC, bunny232 commented
hi yes im the person that caused this and this is cool and good

2020-06-07 19:16 UTC, Linzolle submitted a review, later dismissed

2020-06-07 20:04 UTC, shellspeed1 commented
Gonna actually disagree with this one because people might use this to meta the objectives of the traitor.

2020-06-08 23:14 UTC, Ghommie requested changes

2020-06-08 23:14 UTC, Ghommie commented on code/modules/antagonists/traitor/classes/hijack.dm
> +	min_players = 35
```suggestion
	min_players = 25
```
Latejoiners and stuff

2020-06-08 23:14 UTC, Ghommie commented on code/modules/antagonists/traitor/classes/martyr.dm
> +	min_players = 25
```suggestion
	min_players = 20
```
Idem.

2020-06-09 04:17 UTC, kevinz000 commented
@Ghommie done
@shellspeed1 it might be a good idea to put this on config someday but for now, well, after one night of the server's pop quite literaly going down the drain in 10 minutes from roundstart i'm a bit disappointed in some people.

2020-06-09 15:01 UTC, Ghommie approved these changes

2020-06-09 15:02 UTC, merged