[s] xenobio golems can no longer be used to exploit eldritch affairs mechanics
citadel-station/citadel-main pull request #12493
Opened 2020-06-08 17:17 UTC by DeltaFire15

## About The Pull Request
As of now, people could create golems as an traitor cultist, which became actual full-on cultists, allowing for skipping any and all inbuilt restrictions of eldritch affairs. This fixes that so the golems are neutered too. (Done via neutered/traitor so they don't show up on the endroud screen either.)

## Why It's Good For The Game
Maaybe having golems / simillar be able to fully circumvent all restrictions set by eldritch affairs aiiin't the best idea..

## Changelog
:cl:
fix: Golems / simillar now inherit the neutered antag datum if the creator is neutered.
/:cl:

2020-06-08 18:09 UTC, Yawet330 commented
@DeltaFire15 this doesnt stop the exact same exploit with narsian golems though :eyes:

2020-06-08 18:17 UTC, Ghommie requested changes
Little logic performance improvement.

2020-06-08 18:17 UTC, Ghommie commented on code/datums/mind.dm
> +		src.add_antag_datum(/datum/antagonist/cult/neutered/traitor)
```suggestion
	if(iscultist(creator))
		if(iscultist(creator, TRUE))
			SSticker.mode.add_cultist(src)
		else
			add_antag_datum(/datum/antagonist/cult/neutered/traitor)
```

2020-06-08 18:17 UTC, Ghommie commented on code/datums/mind.dm
> +		add_servant_of_ratvar(current, FALSE, FALSE, /datum/antagonist/clockcult/neutered/traitor)
```suggestion
	else if(is_servant_of_ratvar(creator))
		if(is_servant_of_ratvar(creator, TRUE))
			add_servant_of_ratvar(current)
		else
			add_servant_of_ratvar(current, FALSE, FALSE, /datum/antagonist/clockcult/neutered/traitor)
```

2020-06-08 19:36 UTC, DeltaFire15 commented on code/datums/mind.dm
> +		src.add_antag_datum(/datum/antagonist/cult/neutered/traitor)
taken care of

2020-06-08 19:36 UTC, DeltaFire15 commented on code/datums/mind.dm
> +		add_servant_of_ratvar(current, FALSE, FALSE, /datum/antagonist/clockcult/neutered/traitor)
same here

2020-06-08 21:13 UTC, TheObserver-sys commented
Sad to see it go, but it'd only be a matter of time before someone pulls the epic NAR'SIE HAS RISEN on the station and ruin many other players rounds pretty hard core.

2020-06-09 00:21 UTC, Ghommie approved these changes

2020-06-09 00:22 UTC, merged