New brain damage string
citadel-station/citadel-main pull request #12772
Opened 2020-07-14 12:58 UTC by Ragolution

@silicons 

## About The Pull Request

Adds a single new Brain Damage string.

## Why It's Good For The Game

It makes me smiel.

## Changelog
:cl:
add: new brain damage trauma string
/:cl:

2020-07-17 06:34 UTC, LetterN requested changes
Spaces on jsons, not tabs.

2020-07-17 06:34 UTC, LetterN commented on strings/traumas.json
> +        "rp"
arrpee?

2020-07-18 02:37 UTC, ghost requested changes
M O R E

2020-07-19 08:02 UTC, Ragolution commented
> Spaces on jsons, not tabs.

I am 900% sure I did spaces

2020-08-30 04:30 UTC, closed without merging