[READY] ports plumbing (no more waiting for tgui4)
citadel-station/citadel-main pull request #13178
Opened 2020-08-16 02:26 UTC by lolman360

since we have tgui4 this is all ready

https://github.com/tgstation/tgstation/pull/44833

also: automatic hydro trays. take like 20x more gaia to transcend, accept reagents via pipe, autoharvest

## Changelog
:cl: Time-Green (copypasta'd by lolman360)
add: plumbing
add: automatic hydro trays
/:cl:

2020-08-16 02:27 UTC, Tupinambis commented
29 commits is a mood. Also nice PR, finally some good fucking features.

2020-08-16 06:01 UTC, lolman360 commented
you don't commit every change?

2020-08-18 03:24 UTC, Hatterhat requested changes
you left some MAT_PLASTIC defines in idiot

2020-08-18 03:24 UTC, Hatterhat commented on code/modules/research/designs/medical_designs.dm
> +	materials = list(/datum/material/iron = 5000, /datum/material/glass = 1000, MAT_PLASTIC = 1000)
>MAT_PLASTIC

2020-08-18 03:24 UTC, Hatterhat commented on code/modules/research/designs/medical_designs.dm
> +	materials = list(/datum/material/iron = 10000, /datum/material/glass = 10000, MAT_PLASTIC = 4000)
>MAT_PLASTIC

2020-08-21 04:32 UTC, merged