Makes dwarf text not check every replacement every time.
citadel-station/citadel-main pull request #13346
Opened 2020-09-05 00:51 UTC by Putnam3145

## About The Pull Request

Rather than do a for loop through 1500 replacements and running replaceTextEx on the line of speech every single time, making this one proc one of the top 10 laggiest in the entire codebase, it runs through each individual word in the line of speech and grabs the line from the file that way, making it run approximately 100 times faster.

## Why It's Good For The Game

Just because they're both O(n) doesn't mean one isn't faster.

## Changelog
:cl:
refactor: Dwarf speech is no longer absolutely paranoid about word replacement.
/:cl:

2020-09-06 07:20 UTC, Ghommie requested changes
Necessary changes to make it work. All good otherwise.

2020-09-06 07:20 UTC, Ghommie commented on code/modules/mob/living/carbon/human/species_types/dwarves.dm
> +			var/value = dwarf_words[word] //Thus they will always be in character.
```suggestion
			var/value = dwarf_words[word] //Thus they will always be in character.
			if(!value)
				continue
```

2020-09-06 07:20 UTC, Ghommie commented on code/modules/mob/living/carbon/human/species_types/dwarves.dm
> +			message = replacetextEx(message, " [uppertext(key)]", " [uppertext(value)]")
```suggestion
			message = replacetextEx(message, " [uppertext(word)]", " [uppertext(value)]")
```

2020-09-06 07:20 UTC, Ghommie commented on code/modules/mob/living/carbon/human/species_types/dwarves.dm
> +			message = replacetextEx(message, " [capitalize(key)]", " [capitalize(value)]")
```suggestion
			message = replacetextEx(message, " [capitalize(word)]", " [capitalize(value)]")
```

2020-09-06 07:20 UTC, Ghommie commented on code/modules/mob/living/carbon/human/species_types/dwarves.dm
> +			message = replacetextEx(message, " [key]", " [value]") //Also its scottish.
```suggestion
			message = replacetextEx(message, " [word]", " [value]") //Also its scottish.
```

2020-10-01 09:58 UTC, silicons commented
@Putnam3145 e

2020-10-12 11:26 UTC, merged