Refactors for easier Species Development
citadel-station/citadel-main pull request #13497
Opened 2020-10-02 22:40 UTC by Zandario

## About The Pull Request

Me following out on my promise to help with the upcoming Species, since this codebase isn't well-suited for such things, this here is a step to help with that.

## Why It's Good For The Game

Doesn't really do anything to the game, this is just back-end shit.

## Changelog
:cl:
code: Added some framework for future species expansions, including clothing refitting.
refactor: Made majority of the relevant Species IDs and Categories pre-defined, also for easier expansion and use.
/:cl:

2020-10-02 22:40 UTC, Zandario commented
This is only the first part of what I need to get done, I'll get the dmi part sorted later

2020-10-03 00:20 UTC, timothyteakettle commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		H.set_species(species_category)
i dont think species category is the right change here, assuming you did a replace all on it and it caught this, as it's an entirely different thing to species type

2020-10-03 01:57 UTC, LetterN commented on code/game/objects/items.dm
> +	*/
```suggestion
	/* 
	 * Species-specific sprites, concept stolen from Paradise//vg/.
	 * ex:
	 * sprite_sheets = list(
	 * 	SPECIES_FELINID = 'icons/cat/are/bad'
	 * 	)
	 * If index term exists and icon_override is not set, this sprite sheet will be used.
	 */
```
dmdoc

2020-10-03 02:00 UTC, LetterN requested changes

2020-10-03 02:00 UTC, LetterN commented on code/modules/clothing/clothing.dm
> +	*/
```suggestion
	/*
	 * 	Sprites used when the clothing item is refit. This is done by setting icon_override.
	 * 	For best results, if this is set then sprite_sheets should be null and vice versa, but that is by no means necessary.
	 * 	Ideally, sprite_sheets_refit should be used for "hard" clothing items that can't change shape very well to fit the wearer (e.g. helmets, hardsuits),
	 * 	while sprite_sheets should be used for "flexible" clothing items that do not need to be refitted (e.g. aliens wearing jumpsuits).
	 */
```

2020-10-03 02:00 UTC, LetterN commented on code/modules/clothing/clothing.dm
> +	var/list/sprite_sheets_refit = null
you do not need to explicitly set this to null

2020-10-03 02:00 UTC, LetterN commented on code/modules/clothing/clothing.dm
> +/obj/item/clothing/proc/refit_for_species(var/target_species)
```suggestion
/obj/item/clothing/proc/refit_for_species(target_species)
```
do not add `var/` on args

2020-10-03 02:00 UTC, LetterN commented on code/modules/clothing/clothing.dm
> +/obj/item/clothing/head/helmet/refit_for_species(var/target_species)
```suggestion
/obj/item/clothing/head/helmet/refit_for_species(target_species)
```

2020-10-04 01:06 UTC, silicons commented on code/game/objects/items.dm
> +	///Species Sprite Overrides
ok so all of the item/clothing stuff can't be merged unless we know exactly what we're doing with it
we have tens of thousands of items per round and these are all wasted lists unless they're specifically needed, even with a typelist system like the rest of the code uses

2020-10-11 05:00 UTC, merged