Makes welder code better*
citadel-station/citadel-main pull request #13604
Opened 2020-10-21 09:54 UTC by Trilbyspaceclone

## About The Pull Request

Makes welder code just be better
Buffs Brass welder to reload itself faster, thats it

## Why It's Good For The Game

Brass welders are cult and magic should, be somewhat better imo, legit dosnt do to much in terms of active gameplay
Code wise - easier to read and more cleanly imo runs
## Changelog
:cl:
balance: Brass welders are 50% faster at refueling
code: redoes self fueling welders in the code to be less speggie
/:cl:

2020-10-24 02:55 UTC, jjpark-kb commented on code/game/objects/items/tools/weldingtool.dm
> +	var/self_fueling = FALSE //Do we refill areself or not
```suggestion
	var/self_fueling = FALSE //Do we refill ourselves or not
```

2020-10-24 03:04 UTC, jjpark-kb commented on code/game/objects/items/tools/weldingtool.dm
> +	//Then looks if we refuel areselfs are not.
```suggestion
	//Then looks if we refuel ourselves or not.
```

2020-10-24 03:05 UTC, jjpark-kb commented on code/game/objects/items/tools/weldingtool.dm
> +	//This handles refuelung, its looking at how much fuel the tool has, and comparing it to the how much it holds
```suggestion
	//This handles refueling. Its looking at how much fuel the tool has and comparing that to how much it holds
```

2020-10-24 03:06 UTC, jjpark-kb commented on code/game/objects/items/tools/weldingtool.dm
> +	next_fueling = 5 //makes welding fuel faster then experimental ones
```suggestion
	next_fueling = 5 //makes welding fuel faster than experimental ones
```

2020-10-24 03:06 UTC, jjpark-kb commented on code/game/objects/items/tools/weldingtool.dm
> +	var/next_fueling = 10 //How long do we wait before refilling
```suggestion
	var/next_fueling = 10 //How long we wait before refilling
```

2020-10-28 14:45 UTC, silicons requested changes
just do a variable for amount of fuel to regenerate per cycle

also this doesn't take into account that process() isn't going to be called if the welder isn't turned on

2020-10-28 16:38 UTC, Trilbyspaceclone commented
@silicons done I guess

2020-11-07 07:18 UTC, merged