character size scaling
citadel-station/citadel-main pull request #13630
Opened 2020-10-26 17:52 UTC by timothyteakettle

## About The Pull Request
before you downvote this and cry because of the title, please read the pr description, please.

the size limits are 90% to 125%
these do not stack with the dwarf species, i.e. they just outright will not apply

if you go under 100% size, REGARDLESS OF BY HOW MUCH, you will lose 10 max health, meaning you can't gamer the debuff by being 99% size or 91% or something dumb in that regard

if you go above 100% size, nothing happens, you're just bigger, congratulations on having a bigger hitbox
the reason it's capped at 125% is because this is the size of the gigantism trait and id rather it not be bigger than that because i dont want people filling my screen with their size on main

## Why It's Good For The Game
size customization in a sane manner when done correctly can be good

## Changelog
:cl:
add: you can now customize your size from 90% to 130%, going below 100% makes you have 10 less max health
/:cl:

2020-10-26 17:54 UTC, MrJWhit commented
No.

2020-10-26 17:54 UTC, timothyteakettle commented
thanks for your detailed constructive feedback i will use this to make my prs better

2020-10-26 17:59 UTC, MrJWhit commented
It's not worth it to open this door, dwarves are kind of balanced because of their hilarious booze need and the fact that they can't speak for shit. Even though they're still busted because of the hitbox.
Reducing hp isn't that serious of a penalty when you are less likely to be hit, because you're physically smaller and it's harder to just click on them. Stack that with cit's movespeed, and anyone half decent at dodging, is going to just crush with it.

10 less hp does what, exactly? Put them into crit 1 click faster? That's /not/ enough of a deterrent.

Size mechanics are inhearently broken unless you rework how the sprites and hitboxes are hit, you are inherently better at combat because of this.

2020-10-26 18:04 UTC, timothyteakettle commented
Being 10% smaller is too small a change for it to be incredibly strong, the 10 less max health is literally enough for it to be mechanically not worth using, to be convinced that having 10 less health is worth being 10% smaller from a purely mechanical point of view is silly.

2020-10-26 18:09 UTC, timothyteakettle commented
Ill add some reference images later today for 90%, 100%, and 125% size ranges on the same character, next to eachother to show the actual hitbox differences

2020-10-26 18:58 UTC, deathride58 requested changes
the config stuff for character size caps should be left in, same with the config penalties for sizes smaller than certain values

2020-10-26 20:09 UTC, timothyteakettle commented
yeah that's fine

2020-10-26 20:41 UTC, timothyteakettle commented
re-added slow stride formula on-top of the 10 hp reduction, however i changed the values of the config to have the multiplier be 0 for now, so it can be enabled/tuned by whoever touches configs

i.e. the support for it is there and it is up to other people to enable it if they wish for it to be used

2020-10-26 21:26 UTC, deathride58 submitted a review, later dismissed

2020-10-26 21:38 UTC, YakumoChen commented
Is this 10 HP based on the human max of 200 or the crit threshold of 100

2020-10-26 21:48 UTC, timothyteakettle commented
based on the maximum such that you go into crit 10 health earlier

2020-10-26 23:53 UTC, timothyteakettle commented
had to do a fix because there was an old issue with the original size code

2020-10-27 19:57 UTC, Tupinambis commented
I'm against this for consistency, visual clarity, visual quality, and gameplay reasons. I get why customization and better *showing* the size of people sounds good in theory, but I feel like it will just make gameplay more inconsistent and make things look uglier. I've seen allowing size scaling in action and I'm really not in any way a fan. It doesn't feel like the benefits are worth the drawbacks.

2020-10-27 21:02 UTC, YakumoChen commented
Sprite distortion is incredibly ugly.

2020-10-28 14:54 UTC, silicons commented
*takes a deep breath*

2020-10-28 17:35 UTC, timothyteakettle commented
sprites can look distorted (it warns you when selecting your sprite size!), this is typically worse when downsizing the sprite compared to upsizing the sprite, but the problem is minimised due to the cap of 90%

i feel like having this testmerged and getting feedback once people have actually seen and tried it would be nice

2020-10-30 20:06 UTC, Echopsychotic commented
I think the sprites would look better at 150 personally, again it's only a hitbox taker for the person and not much of a bad change to increase the size the sprites can take.

2020-11-01 07:47 UTC, YakumoChen commented
is there a way to make the hitbox static but not affect the size?

2020-11-01 23:55 UTC, moltoretardo commented
Flashbacks from cit 6 years ago 😨

2020-11-07 07:19 UTC, merged