Allows mass sticking money into your id
citadel-station/citadel-main pull request #13924
Opened 2020-12-30 17:00 UTC by SandPoot

## About The Pull Request
Title.

## Why It's Good For The Game
Faster money taking, unless you still want it with do afters.

## Changelog
:cl:
tweak: You can attack a pile of money on the floor with your id to put it all in quickly.
/:cl:

2020-12-31 18:09 UTC, DeltaFire15 requested changes
Looks alright, though probably put a else if here to preserve the else at the end working as before.

2020-12-31 18:09 UTC, DeltaFire15 commented on code/modules/mining/ores_coins.dm
> +	if(istype(W, /obj/item/card/id))
```suggestion
	else if(istype(W, /obj/item/card/id))
```

2020-12-31 19:59 UTC, SandPoot commented on code/modules/mining/ores_coins.dm
> +	if(istype(W, /obj/item/card/id))
yea, sounds about right

2021-01-01 07:15 UTC, DeltaFire15 approved these changes

2021-01-01 07:15 UTC, merged