Porting the ability to wear the caution sign
citadel-station/citadel-main pull request #13981
Opened 2021-01-06 08:53 UTC by MrJWhit

## About The Pull Request

Lets you wear the caution sign, and updates everything so it's only wearable items.

Port of: https://github.com/tgstation/tgstation/pull/44289

Here it is working on my copy:
![image](https://user-images.githubusercontent.com/48370570/103748704-83ece900-4fd2-11eb-99af-53614769394b.png)

## Why It's Good For The Game

What is 13 spacemans in a hunk of metal, but a game where you can see a "caution, wet floors", and decide "I should put that over my head and wear it".
Plus just imagine the fashion choices people can have.

## Changelog
:cl:
add: Adds the ability to wear the caution sign
/:cl

2021-01-06 17:50 UTC, DeltaFire15 approved these changes, later dismissed

2021-01-06 17:53 UTC, DeltaFire15 requested changes
Actually, looking at it more closely, you left in the old object definition aswell as the new one, both with the same name (or well, more specifically, typepath). Might wanna clear that up.

2021-01-06 19:43 UTC, MrJWhit commented
Old definition removed.

2021-01-07 19:16 UTC, DeltaFire15 approved these changes

2021-01-07 19:17 UTC, merged