Replaces extools with auxtools; atmos overhaul
citadel-station/citadel-main pull request #13991
Opened 2021-01-07 08:12 UTC by Putnam3145

## About The Pull Request

Extools has been replaced with auxtools, a Rust-based replacement.

LINDA has been mostly torn out and replaced with my own FEA follow-up, FDA, a highly parallel finite difference method atmospheric protocol which is far more consistent, fast and reasonable than the previous. It moves gas in a LINDA-like way, but never gets stuck, has heat properly moving around and has the same performance no matter how many pressure differences there are (yes, really). It doesn't break planetary atmos and is, in general, easier to understand.

## Why It's Good For The Game

Extools has been a bit of a disaster. It causes issues with planet atmos, it causes crashes when loading away missions, and is just... unsafe code. The move to Rust and designing of an atmos subsystem with it being written in a fast, safe, concurrent-able programming language to begin should bring a huge improvement.

## Changelog
:cl:
add: FDA, LINDA without the bookkeeping.
add: Putnamos, a simpler replacement for Monstermos. If I can get Monstermos to work, this will be Monstermos instead.
del: LINDA, the old active-turfs-based atmos subsystem.
del: Monstermos? I would rather not get rid of this, but I can't get it to work correctly.
server: Extools has been removed, and loading extools alongside auxtools will cause massive problems. If this is tested or merged, remove extools from the static files.
/:cl:

2021-01-20 02:34 UTC, MarinaGryphon requested changes
code\__HELPERS\_extools_api.dm is not included.

2021-01-20 02:34 UTC, MarinaGryphon commented on code/__DEFINES/subsystems.dm
> +#define SSAIR_PIPENETS 1
Lines 245-254 need to be removed.

2021-01-20 02:44 UTC, MarinaGryphon requested changes
~~I found out a way to leave suggestions on unchanged lines too.~~

2021-01-20 02:44 UTC, MarinaGryphon commented on code/controllers/subsystem/time_track.dm
> +			length(SSair.active_super_conductivity)
```suggestion
```

2021-01-20 02:44 UTC, MarinaGryphon commented on code/controllers/subsystem/time_track.dm
> +			SSair.get_amt_excited_groups(),
```suggestion
```

2021-01-20 02:44 UTC, MarinaGryphon commented on code/controllers/subsystem/time_track.dm
> +			SSair.get_active_turfs(), //does not return a list, which is what we want
```suggestion
```
These removed entries may need to be replaced with some of the new procs/vars, like `turf_process_time()`, `heat_process_time()`, `cost_post_process`, etc., depending on how logs are formatted.

2021-01-21 03:43 UTC, MarinaGryphon requested changes
I made a mistake with the `isfinite` logic when testing it. It straight up doesn't work as-is.

2021-01-21 03:43 UTC, MarinaGryphon commented on code/game/world.dm
> +	log_world("World loaded at [TIME_STAMP("hh:mm:ss", FALSE)]!")
This is a duplicate of line 32.

2021-01-21 03:43 UTC, MarinaGryphon commented on code/__DEFINES/is_helpers.dm
> +#define isfinite(n) (isnum(n) && n == n)
This doesn't actually work.
```suggestion
#define isfinite(n) (x != 1.#IND && abs(x) < 1.#INF)
```
Handles NaN, positive infinity, and negative infinity.

2021-02-18 14:45 UTC, DeltaFire15 commented
Merge conflicting.

2021-03-02 09:47 UTC, Putnam3145 commented
(this is gonna fail until the CI is updated to 514)

2021-03-06 02:46 UTC, DeltaFire15 commented
Merge conflicting once again.

2021-04-24 20:16 UTC, DeltaFire15 commented
Marking this PR as stale due to its merge conflicting state combined with having gone a long timeframe without commits.

2021-06-22 01:51 UTC, MitztheKat commented
If you added this to default clones of citadel... you are the sole cause of my aneurysm today. 
I spent six hours trying to run citadel without knowing this exists

2021-06-22 12:29 UTC, MarinaGryphon commented
> If you added this to default clones of citadel... you are the sole cause of my aneurysm today.
> I spent six hours trying to run citadel without knowing this exists

You're misunderstanding. Citadel has extools-based atmos, currently, which only works below a certain 513 BYOND version. This PR *fixes* that by replacing it with something that works on current versions and isn't a pain in the ass to update to newer ones.

2021-06-27 18:01 UTC, silicons commented
i love you so much putnam

2021-06-27 18:01 UTC, merged