Fixes fermichem EMPs being massive.
citadel-station/citadel-main pull request #14031
Opened 2021-01-12 05:10 UTC by Putnam3145

## About The Pull Request

Multiplying by volume means that the EMP, instead of being "very small" as the comment claims, becomes a station-wide nightmare.

## Why It's Good For The Game

zeolites or funny sex chems breaking the entire station every 5 or 6 rounds isn't good

## Changelog
:cl:
balance: fermichem explosion EMPs don't cover the entire station
/:cl:

2021-01-12 08:54 UTC, YakumoChen commented
Classic Trilby

2021-01-13 16:58 UTC, DeltaFire15 requested changes

2021-01-13 16:58 UTC, DeltaFire15 commented on modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
> +		empulse(T, impureTot, 1)
```suggestion
		empulse(T, ImpureTot, 1)
```

2021-01-16 17:39 UTC, Trilbyspaceclone commented
> Classic Trilby

@YakumoChen ?
EMP stuff wasnt me tho, I had nothing to do with this.

2021-01-30 17:44 UTC, DeltaFire15 approved these changes

2021-01-30 17:44 UTC, merged