adds sanity checks to heretic blade shatters
citadel-station/citadel-main pull request #14237
Opened 2021-02-13 01:53 UTC by silicons

good one gamers

2021-02-13 04:55 UTC, DeltaFire15 commented
Oh oops uhh just rename check_flags of that action to required_mobility_flags and make the isavailable check the ..() return value instead, while doing the same for Trigger()

2021-02-14 05:25 UTC, Linzolle approved these changes, later dismissed

2021-02-15 20:29 UTC, Linzolle requested changes
see above. required_mobility_flags instead of check_flags to fix issue

2021-02-19 05:51 UTC, Linzolle approved these changes

2021-02-19 05:51 UTC, merged