More arousal logging; adds back aphro/nympho
citadel-station/citadel-main pull request #14269
Opened 2021-02-19 05:37 UTC by Putnam3145

## About The Pull Request

I was a goddamn idiot to just remove instead of adding better logging. Now all sources of arousal as well as climaxes are logged in the emote log, including whether they're forced or not.

## Why It's Good For The Game

Because the logging is good enough, we can bring back stuff like this without too much issue.

## Changelog
:cl:
add: (Hexa)crocin
add: (Hexa)camphor
add: Nymphomaniac quirk
admin: All climaxes and arousals are now logged, as well as genital exposure.
/:cl:

2021-02-19 05:42 UTC, kappa-sama commented
L

2021-02-19 05:46 UTC, moltoretardo commented
L

2021-02-19 05:48 UTC, LetterN requested changes

2021-02-19 05:48 UTC, LetterN commented on code/modules/mob/living/carbon/human/species.dm
> +			target.mob_climax(forced_climax=TRUE, "masochism")
```suggestion
			target.mob_climax(forced_climax=TRUE, cause = "masochism")
```

2021-02-19 05:48 UTC, LetterN commented on code/modules/mob/living/carbon/human/species.dm
> +						H.mob_climax(forced_climax=TRUE, "masochism")
```suggestion
						H.mob_climax(forced_climax=TRUE, cause  = "masochism")
```

2021-02-19 05:48 UTC, LetterN commented on code/modules/vending/kinkmate.dm
> +				/obj/item/reagent_containers/glass/bottle/camphor = 5
```suggestion
				/obj/item/reagent_containers/glass/bottle/camphor = 5,
```

2021-02-19 05:48 UTC, LetterN commented on modular_citadel/code/datums/status_effects/chems.dm
> +					H.mob_climax(forced_climax=TRUE, "MKUltra")
```suggestion
					H.mob_climax(forced_climax=TRUE, cause = "MKUltra")
```

2021-02-19 07:54 UTC, BlueWildrose commented
Oh shit.

Is circuits gonna make a comeback too?

2021-02-19 11:58 UTC, Putnam3145 commented
> 
> 
> Oh shit.
> 
> Is arousal circuits gonna make a comeback too?

almost definitely not tbh. like, *maybe*? but they're... really extreme even for this stuff, cause they're too easy to target directly without causing loud text that gives you seconds to react.

2021-02-19 14:46 UTC, dzahlus commented
my balls finally feel full again

2021-02-19 14:47 UTC, keronshb commented
Putnam I sent the station nuke to the ghost cafe to get rid of the horny and this is what I get?

2021-02-20 11:59 UTC, SmArtKar commented
we NEED arousal circutry back. Just for memes. Just for lewd

2021-02-21 21:50 UTC, silicons commented
Arousal circuits aren't coming back.

2021-02-21 21:50 UTC, merged