stops people using Message All on PDAs when their cartridge doesn't allow it
citadel-station/citadel-main pull request #14262
Opened 2021-02-17 17:27 UTC by timothyteakettle

## About The Pull Request
stops people using Message All on PDAs when their cartridge doesn't allow it

## Why It's Good For The Game
stops people using Message All on PDAs when their cartridge doesn't allow it

## Changelog
:cl:
fix: stops people using Message All on PDAs when their cartridge doesn't allow it
/:cl:

2021-02-17 20:25 UTC, Arturlang commented
pr Info not accurate, spam enabled are more than just te lawyer's

2021-02-18 14:46 UTC, LetterN requested changes

2021-02-18 14:46 UTC, LetterN commented on code/game/objects/items/devices/PDA/PDA.dm
> +				if(cartridge && cartridge.spam_enabled)
```suggestion
				if(cartridge?.spam_enabled)
```

2021-02-19 02:13 UTC, timothyteakettle commented on code/game/objects/items/devices/PDA/PDA.dm
> +				if(cartridge && cartridge.spam_enabled)
thanks

2021-02-19 05:34 UTC, merged