Small QoL changes to TCG
citadel-station/citadel-main pull request #14261
Opened 2021-02-17 14:08 UTC by SmArtKar

## About The Pull Request

See title

## Why It's Good For The Game

Played my first propper game, found some problems

## Changelog
:cl:
tweak: Added some QoL changes to TCG
/:cl:

2021-02-18 14:43 UTC, LetterN requested changes

2021-02-18 14:43 UTC, LetterN commented on code/modules/tcg/cards.dm
> +		if(choice && choice in decks)
```suggestion
		if(choice && choice in decks)
```
```suggestion
		if(choice && (choice in decks))
```

2021-02-18 14:43 UTC, LetterN commented on code/modules/tcg/cards.dm
> +				decks[named].Add(card.name)
```suggestion
				decks[named] += card.name
```

2021-02-19 05:42 UTC, Linzolle approved these changes

2021-02-19 20:37 UTC, merged