Changes to ash drake transformation
citadel-station/citadel-main pull request #14324
Opened 2021-02-26 15:08 UTC by dzahlus

## About The Pull Request
Creates a new subtype for lesser ash drakes that is balanced around player control as well as rebalancing the shapeshift spell

## Why It's Good For The Game
Why yes I'd to be able to transform into megafauna with MOVE_FORCE_OVERPOWERING, ENVIRONMENT_SMASH_RWALLS 20 burn adjustfireloss breath, swoop attack that goes through walls, atmos immunity, full no grav movement and gibbing every 20 seconds willy nilly without any downsides except i get 2 hit by kinetic crushers on backstab, which is never an issue anyways because I can just transform right back.

No let's please not do that, cooldown is now 3 minutes for transforming and you dont turn into literal megafauna instead a new subtype that is balanced around playe control, you are now not vulnerable to crusher detonation, you have burn and brute armor and you still get to keep the 80 obj damage for smashing machinery and airlocks if you so desire. And lastly you get to alt click swoop dunk and breathe fire that now adds fire stacks instead of armor piercing burn of 20

## Changelog
:cl:
add: Added new subtype to lesser ash drake balanced around player control
balance: rebalanced dragon transformation to 3 minute cooldown as well as using the new subtype of megafauna
/:cl:

2021-02-26 20:31 UTC, kappa-sama commented
if you're nerfing the actual mob (which is cool) could you keep the cooldown low since we already nerfed polymorph spells by making it default for damage to transfer across forms instead of going by dnd rules where it's a second hitbar

2021-02-27 15:27 UTC, dzahlus commented
> if you're nerfing the actual mob (which is cool) could you keep the cooldown low since we already nerfed polymorph spells by making it default for damage to transfer across forms instead of going by dnd rules where it's a second hitbar

The reason I keep the cooldown this high is because I want to make transforming into an ash drake a conscious choice. Since people that have this transformation 9 times out of 10 have stuff like ash drake armor and other mining funny gear. I want this to be like "okay I'm gonna turn into an ash drake for this combat engagement because I think this gives me a better advantage" Or "Okay I'm gonna go drake because atmos is going haywire here" as opposed to being able to change you form at will during combat as it get's rather unfun to play against in it's current state of "I'm gonna valid/antagonize this person, oh no my gamer gear isn't good against what he is using against me so I'll turn into an ash drake now and oh no he brought out the crusher time to turn back"

2021-02-27 21:01 UTC, kappa-sama commented
yeah but it's already being made useless there's no reason to make it take nearly 3% of your round timer to use something that's useless on lavaland and nearly so on station

one nerf or the other and see how it pans out, then add more nerfs if it's still dsquad-spawning deathmachine after one round of nerfs

2021-02-28 15:54 UTC, dzahlus commented
> yeah but it's already being made useless there's no reason to make it take nearly 3% of your round timer to use something that's useless on lavaland and nearly so on station
> 
> one nerf or the other and see how it pans out, then add more nerfs if it's still dsquad-spawning deathmachine after one round of nerfs
> 
> edit: don't get me wrong the fact that miner gamer gear is 90% of the time useless on lavaland and 100% of the time OP on station is garbage but i feel like ash drake is slightly lower on that list than a couple other big hitters with the exception of the biannual drake rampage that ends with admins spawning in 2 guys with lethal lasers that immediately delete the dragon man
> 
> something that's probably more of an issue with ash drake transformation is the fact that it gibs bodies on the go, healing itself in the process, instead of its innate strength, since the only strong ability it really has besides that is the extended invincibility from flight and the potential damage if someone gets stunned or slowed down and starts getting pelted with aerial fireballs, not the ability to swap between forms

You make compelling arguments, I'll think about not nerfing the cooldown but instead giving it lavaland purpose by giving it monster bonus damage or something. Gonna be real here my main gripe is that you can't use martial arts against simplemobs but miners validhunting is an admin problem not a code problem.

2021-03-02 01:33 UTC, silicons requested changes
just keep the ash drake nerf without transformation CD nerf for now

2021-03-02 01:42 UTC, merged