[WIP] Ports ambition objectives system from Skyrat
citadel-station/citadel-main pull request #14369
Opened 2021-03-05 19:04 UTC by dzahlus

im taking severe offense to this

## About The Pull Request
I can't believe Silicons made me code, what it says on the tin

## Why It's Good For The Game
Silicons told me to do this, that's why it's good for the game. No seriously though we're having a lot of issues with antags being too boring, lame, what have you, because of their absolute inability to accept the fact that greentext is not what it is about. Hopefully this will change everything as it allows you to set your own objectives modularily.

WIP by the way lol, please check this code and tell me if you see anything that could break shit this is as of yet untested.

## Changelog
:cl:
add: Added ambition objective system
del: Removed old objective generation
tweak: tweaked the entire objective system
refactor: refactored a bunch of shit to work with ambition
config: added configs for ambition system
admin: changes to antag panel for ambition system
/:cl:

2021-03-05 21:00 UTC, timothyteakettle commented
reference the original pr and actually say what the system is

2021-03-05 21:10 UTC, timothyteakettle commented
alright read through it and I can't see how this is anything but extremely counterproductive given responses we have seen with things such as free objectives and the removal of greentext, this just outright won't work well on this server

2021-03-05 21:21 UTC, dzahlus commented
> alright read through it and I can't see how this is anything but extremely counterproductive given responses we have seen with things such as free objectives and the removal of greentext, this just outright won't work well on this server

doesn't remove greentext at all, it literally just gives you prayer+, the ability to request completion/removal of objectives and addition of new ones. 

see: http://prntscr.com/10dxei3

2021-03-06 01:39 UTC, shellspeed1 commented
I like this idea. Now I can set really dumb objectives like steal as many donuts as possible.

2021-03-06 01:48 UTC, qweq12yt commented
in general i actually want this to go through because there will be some quite funny possibilities!!
but when it comes down to making antags less "boring" i don't think it will cut it. imo it covers edge cases, that's about it

2021-03-06 03:10 UTC, shellspeed1 commented
Really antags being boring comes down to the creativity of the person that is the antag. This lets people create their own objectives and maybe will give admins an idea of what they are doing in order to make shit even more funny.

2021-03-11 01:23 UTC, LetterN requested changes

2021-03-11 01:23 UTC, LetterN commented on code/__DEFINES/cooldowns.dm
> +#define COOLDOWN_CHECK(cd_source, cd_index) (cd_source.cd_index < world.time)
dupe of cd finish

2021-03-15 13:34 UTC, dzahlus commented on code/__DEFINES/cooldowns.dm
> +#define COOLDOWN_CHECK(cd_source, cd_index) (cd_source.cd_index < world.time)
i sure hope this doesn't break anything

2021-04-11 03:10 UTC, DeltaFire15 commented
Merge conflicting again.

2021-04-24 20:20 UTC, DeltaFire15 commented
Marking PR as stale due to its long period without commits despite being marked WIP.

2021-04-29 03:18 UTC, silicons commented
taking this over once rules are done in the next few days

2021-08-26 02:34 UTC, DeltaFire15 commented
Marking this as stale again due to it having no commits since may.

2021-10-21 19:05 UTC, DeltaFire15 commented
Closing this due to staleness.

2022-02-11 05:33 UTC, Linzolle commented
Is there any word on this at all? Kevin reopened this and removed the stale but there's been no work on it since long before then.

2022-02-11 21:00 UTC, keronshb commented
> Is there any word on this at all? Kevin reopened this and removed the stale but there's been no work on it since long before then.

It works as far as I know.  He had me do a test of it and it complies with the code.

If it's implemented, I don't know.  But as far as this exists, it doesn't have any errors or conflicts.

2022-02-22 21:49 UTC, Linzolle commented
If you want to actually fix the conflicts on this, open it again. Closing.

2022-02-22 21:49 UTC, closed without merging