organic repair surgery can be done on a cyborg torso
citadel-station/citadel-main pull request #14435
Opened 2021-03-14 20:25 UTC by DrPainis

## About The Pull Request

Title says it all.

## Why It's Good For The Game

Sometimes people need their torsos replaced due to infection, resulting in someone who has a cyborg torso but is otherwise organic.

## Changelog
:cl:
tweak: you can repair organic limbs on a person with a cyborg torso
/:cl:

2021-03-18 12:40 UTC, silicons commented on code/modules/surgery/healing.dm
> +	requires_bodypart_type = 0
NONE instead of 0, please!

2021-04-02 17:27 UTC, DeltaFire15 requested changes
To prevent some issues (mainly, confusion for people who see both surgery types pop up on people with robot limbs, even if a full robot), please add an check akin to repair surgery for robots, just with the robot limb check replaced with a check for if it's an organic limb.
 (reference: ../code/modules/surgery/robot_healing.dm, proc: /datum/surgery/robot_healing/can_start)

2021-04-02 17:30 UTC, DrPainis commented
> To prevent some issues (mainly, confusion for people who see both surgery types pop up on people with robot limbs, even if a full robot), please add an check akin to repair surgery for robots, just with the robot limb check replaced with a check for if it's an organic limb.
> (reference: ../code/modules/surgery/robot_healing.dm, proc: /datum/surgery/robot_healing/can_start)

...how would I check if OTHER limbs are organic? This is for people with mechanical torsos and an otherwise organic body.

2021-04-02 18:31 UTC, DeltaFire15 commented
> > To prevent some issues (mainly, confusion for people who see both surgery types pop up on people with robot limbs, even if a full robot), please add an check akin to repair surgery for robots, just with the robot limb check replaced with a check for if it's an organic limb.
> > (reference: ../code/modules/surgery/robot_healing.dm, proc: /datum/surgery/robot_healing/can_start)
> 
> ...how would I check if OTHER limbs are organic? This is for people with mechanical torsos and an otherwise organic body.

Look at the refernece I mentioned, it checks for if at least one limb is robotic and only does the other cheks / allows it if that'd be a case. here it'd basically just be the inverted version, aka checking for if at least one bodypart is overganic (ignoring hybrid bodyparts, so with the TRUE arg for the is_organic proc

The code part here is:

/datum/surgery/robot_healing/can_start(mob/user, mob/living/carbon/target, obj/item/tool)
	for(var/obj/item/bodypart/B in target.bodyparts)
		if(B.is_robotic_limb())
			return ..()

Copypaste it into a reasonable place in the file, with the correct path (so the normal heal surgery's instead of robot_healing), change the is_robotic_limb() for is_organic_limb(TRUE), and it should work

2021-04-03 22:17 UTC, DeltaFire15 approved these changes

2021-04-03 22:18 UTC, merged