telescopic batons now have a message when being toggled. you can now threateningly point extended telebatons at people.
citadel-station/citadel-main pull request #14580
Opened 2021-04-07 02:29 UTC by silicons

2021-04-07 02:49 UTC, DeltaFire15 commented on code/game/objects/items/melee/misc.dm
> +	var/sword_poit = TRUE
```suggestion
	var/sword_point = TRUE
```

2021-04-11 02:47 UTC, DeltaFire15 requested changes
See above comment.

2021-04-13 01:39 UTC, silicons commented
@DeltaFire15 pog

2021-04-13 08:21 UTC, DeltaFire15 approved these changes

2021-04-13 08:22 UTC, merged