the roasted roasted roasted roasted roasted roasted roasted roasted.........
citadel-station/citadel-main pull request #14850
Opened 2021-06-14 21:11 UTC by silicons

## About The Pull Request

sanity checks to prevent doubleroasting

## Why It's Good For The Game

if you are roasting things so much it blows up my 4k screen without widescreen, you shouldn't be roasting it that much.

## Changelog
:cl:
fix: no more doubleroasting
/:cl:

2021-06-15 01:55 UTC, keronshb commented
Please don't kill the sticky bro...

2021-06-16 17:25 UTC, DeltaFire15 requested changes
Apparently roasted never gets set away from FALSE looking at code, so you'd have to set it to true when finishing aswell.

2021-06-18 07:44 UTC, Putnam3145 commented on code/game/objects/items/melee/misc.dm
> +	if(!held_sausage || held_sausage.roasted)
```suggestion
	if(held_sausage?.roasted)
```

2021-06-21 15:54 UTC, DeltaFire15 approved these changes

2021-06-21 15:54 UTC, merged