[DRAFT] Fixes Plague Rats
citadel-station/citadel-main pull request #15084
Opened 2021-09-06 13:34 UTC by keronshb

## About The Pull Request

Fixes a myriad of issues with Plague Rats:

1. No more decals.  They were nice, but I want to cut down on lag.
2. Only one corpse can spawn per tile now.

TO DO:
Prevent respawning on anything but the station z level
Put a hard cap on spawning or check config.

## Why It's Good For The Game

While their explosive nature was great, it was a bit too good and caused the server to crash.

## Changelog
:cl:
fix: Plague Rats will no longer spawn thousands of dirt decals
fix: Plague Rats will no longer spawn thousands of corpses
/:cl:

2021-09-08 13:58 UTC, necromanceranne commented
I'm gonna be honest chief, introducing a creature that literally just exists to make atmos hell may as well be server sabotage given just how much of a problem atmos diffs cause.

2021-09-09 01:22 UTC, LetterN commented on code/modules/mob/living/simple_animal/hostile/plaguerat.dm
> +				new /obj/effect/mob_spawn/human/corpse/assistant(T)
this is still iffy, we don't want to have assistants within every tile

2021-09-09 01:26 UTC, LetterN requested changes
Fix the
```dm
	if(isopenturf(loc))
		var/turf/open/T = src.loc
		if(T.air)
			T.atmos_spawn_air("miasma=5;TEMP=293.15")
```

2021-09-09 01:26 UTC, LetterN commented on code/modules/mob/living/simple_animal/hostile/plaguerat.dm
> +				new /obj/effect/mob_spawn/human/corpse/assistant(T)
still iffy, we do not want to have assistants in every single tile.

2021-09-19 18:03 UTC, silicons commented
merging since this is better than nothing

plague rats stay disabled until rework tho

2021-09-19 18:03 UTC, merged