Ports station traits from TGstation
citadel-station/citadel-main pull request #15423
Opened 2021-12-09 00:29 UTC by Putnam3145

## About The Pull Request

Port of https://github.com/tgstation/tgstation/pull/56309

- [x] port the actual code
- [ ] map in the hangover locations (this is harder)

## Why It's Good For The Game

It's cool.

## Changelog
:cl:
add: Adds station traits: Small modifiers that can randomly be chosen each round. They are usually logged in the intercept the station receives early in the round
refactor: Announcement audio is now stored in a datum to make it easy to add different announcers
/:cl:

2021-12-09 01:16 UTC, Putnam3145 commented
why is it like this. if this isn't squash merged i will end you

2021-12-09 07:46 UTC, BlueWildrose commented
There's a pretty cool variety here, I like it.

2021-12-27 15:45 UTC, LordSaladin commented
We could add some server specific traits like a golden [REDACTED] spawning in maint

2022-01-09 16:11 UTC, DeltaFire15 requested changes
I know that hangover is not enabled yet, but to really make it "done but no mapping done yet", please nonetheless disable Synthetics from being affected by it as they do not process alcohol and it'd be impossible for them to suffer from it. 
Should probably be good to testmerge after.

2022-03-22 16:13 UTC, DeltaFire15 commented
Unaddressed merge conflicts and requested changes. Marking PR as stale.

2022-03-30 02:39 UTC, Putnam3145 commented
ping me on discord, notifications on github are not very good for me since I get them for every single comment on every single PR opened here

2022-03-30 19:40 UTC, Putnam3145 commented
> I know that hangover is not enabled yet, but to really make it "done but no mapping done yet", please nonetheless disable Synthetics from being affected by it as they do not process alcohol and it'd be impossible for them to suffer from it. Should probably be good to testmerge after.

also, i hate to say this, but, uh, actually robots do process alcohol. this might be an oversight of some sort but there's nothing preventing them at all, from what I can tell. I'm fixing it anyway, but yeah

2022-05-28 02:23 UTC, deathride58 requested changes
Only one tiny bug before it can be merged proper

2022-05-28 02:23 UTC, deathride58 commented on code/__HELPERS/priority_announce.dm
> +		priority_announce("A report has been downloaded and printed out at all communications consoles.", "Incoming Classified Message", "commandreport", SSstation.announcer.get_rand_report_sound(), has_im
These args are malformed; command report sounds are muted as a result ("commandreport" is no longer an announcer event sound).

2022-06-02 20:06 UTC, deathride58 commented
Remaining oddities:
- "Modify station traits" has no TGUI at all; it simply returns "Interface StationTraitsPanel was not found."
- Command reports.... Somehow still don't have sound? Very weird.

2022-08-08 01:10 UTC, merged