smithing v2 (it's got acutal gameplay now)
citadel-station/citadel-main pull request #15464
Opened 2022-01-08 07:32 UTC by lolman360

## About The Pull Request

smithing now isn't rng/super quality dependent

all recipes now have 3 steps that need to be done in order to finish the piece, and the height needs to be in a certain range for that to happen

these are told to you when you start the recipe 

## Why It's Good For The Game

og smithing is shit and this is something i should've done literally years ago

## Changelog
:cl:
add: smithing is now better
/:cl:

2022-01-08 07:34 UTC, LeadOnTaste commented
Check the "workplace" var, it may be bugged.

2022-01-08 07:41 UTC, lolman360 commented
intentional

2022-01-09 00:56 UTC, TripleShades commented
Why does it look like you removed a lot of recipes?

2022-01-09 18:10 UTC, DeltaFire15 commented
How does this improve smithing, given from what I can see this removes much of the room for improvement or progression and doesn't really add anything new save for always doing the same steps for your item because you only get a bonus at the one perfect value, so the only thing to increase during a ongoing round becomes your skill stat as opposed to tool, varying steps depending on your item step count, trying to get quality higher and being more risky to achieve that, etc?

2022-01-12 01:48 UTC, lolman360 commented
> Why does it look like you removed a lot of recipes?

a lot of recipes were just reskins I can readd them if they're wanted otherwise they're just bloat

> How does this improve smithing, given from what I can see this removes much of the room for improvement or progression and doesn't really add anything new save for always doing the same steps for your item because you only get a bonus at the one perfect value (also also deletes many recipes), so the only thing to increase during a ongoing round becomes your skill stat as opposed to tool, varying steps depending on your item step count, trying to get quality higher and being more risky to achieve that, etc?

working on making it more interesting by making anvil progression more of a factor through quality +/- as well as variance (which is imo a lot better than just outright rng failing, and I'd like for there to be a little randomness)

the last system also was easily 'solvable' to get the optimum quality for the anvil with the minimal fail chance

this one doesn't have a fail chance and is intended to be more 'solveable' (i.e somewhat less rng-dependent) since I don't like rng fail chances

hammer progression will probably be reimplemented, I might add hammer variance/toolspeed based on quality

2022-01-12 11:42 UTC, LeadOnTaste commented
> > Why does it look like you removed a lot of recipes?
> 
> a lot of recipes were just reskins I can readd them if they're wanted otherwise they're just bloat
> 
> > How does this improve smithing, given from what I can see this removes much of the room for improvement or progression and doesn't really add anything new save for always doing the same steps for your item because you only get a bonus at the one perfect value (also also deletes many recipes), so the only thing to increase during a ongoing round becomes your skill stat as opposed to tool, varying steps depending on your item step count, trying to get quality higher and being more risky to achieve that, etc?
> 
> working on making it more interesting by making anvil progression more of a factor through quality +/- as well as variance (which is imo a lot better than just outright rng failing, and I'd like for there to be a little randomness)
> 
> the last system also was easily 'solvable' to get the optimum quality for the anvil with the minimal fail chance
> 
> this one doesn't have a fail chance and is intended to be more 'solveable' (i.e somewhat less rng-dependent) since I don't like rng fail chances
> 
> hammer progression will probably be reimplemented, I might add hammer variance/toolspeed based on quality

Dude, those are SURELY NOT reskins, they have different damage formulas and stats.

2022-01-12 23:51 UTC, lolman360 commented
i literally made the feature
the only things that were removed that weren't reskins are the 2 other spears, zweihander, waki and sabre

2022-01-21 01:08 UTC, lolman360 commented
also it's not like previous blacksmithing wasn't also 'solvable' 
in fact you only ever needed to be 'risky' when making your first hammer or two and then you can shit out minimum quality for essentially 0 effort

2022-01-30 20:51 UTC, TripleShades commented
Put them all back.

2022-05-17 19:45 UTC, deathride58 requested changes
A review a few months late! IMO the way this PR reworks blacksmithing is pretty underrated.

There's a handful of bits that're perplexing, but are likely easy to fix up. This PR very much deserves a testmerge.

2022-05-17 19:45 UTC, deathride58 commented on code/modules/smithing/anvil.dm
> +			to_chat(user, "WRONG3STEP")
Debug text?

2022-05-17 19:45 UTC, deathride58 commented on code/modules/smithing/anvil.dm
> +	to_chat(user, "generating item")
Debug text. This could probably be made more descriptive to be more fitting for a player-facing message.

2022-05-17 19:45 UTC, deathride58 commented on code/modules/smithing/anvil.dm
> -/obj/structure/anvil/obtainable/bone
Why exactly was this removed, anyhow? This is pretty useful for ashwalkers.

2022-05-17 19:45 UTC, deathride58 commented on code/modules/smithing/smithed_items.dm
> -	custom_materials = list(/datum/material/bone=4000)
Same as the bone anvil removal; what's up with bone ingots being removed?

2023-11-13 09:12 UTC, DeltaFire15 commented
Unaddressed changes for a long long time.

2023-11-13 09:12 UTC, closed without merging