Syndicate Skinned Box Station
citadel-station/citadel-main pull request #15580
Opened 2022-04-02 21:52 UTC by DJKouta

## About The Pull Request

Visually changed version of Box I whipped up for Events.

## Why It's Good For The Game

Variety, and being able to run certain events. It's mostly a re-skin but some of maints has been changed in terms of furniture and such. Some maint loot is a little dangerous so perhaps not a rotation map, but strictly for events.

## Changelog
:cl:
add: Syndicate Box Station
/:cl:

2022-05-15 00:00 UTC, deathride58 requested changes
Needs a json to be properly loadable ingame as a station map!

2022-05-23 19:24 UTC, deathride58 approved these changes

2023-11-13 11:20 UTC, DeltaFire15 commented
I don't know why this has been sitting at approved when it didn't even work because of missing code parts, but oh well I fixed that and it's like 3mb payload so may aswell have it sit around.

2023-11-13 11:48 UTC, DeltaFire15 approved these changes

2023-11-13 11:48 UTC, merged