HoS plate carrier
citadel-station/citadel-main pull request #15676
Opened 2022-06-08 22:59 UTC by TrojanCoyote

adds a plate carrier for the HoS

## About The Pull Request

 adds a plate carrier with a small amount of storage to the game and job restricted loadout for HoS

## Why It's Good For The Game

 variety in fashion and gear is good, also plate carriers should have some storage w/o taking up a belt slot change my mind.

## Changelog
:cl:
add: Adds a plate carrier to HoS loadout, sprites for such

/:cl:

2022-06-10 23:27 UTC, deathride58 commented
Admittedly fairly ambivalent on this, as this is out of line for what's expected of loadout entries. For the most part, things in the loadout menu are either straight downgrades to what a job normally has (such as the sechud glasses), entirely cosmetic variants of otherwise beneficial items (such as the fake sunglasses and jackboots), or 1:1 alternatives to what they already spawn with (like the star trek job uniforms). Equipment with actual differences are usually instead a part of job equipment vending machines, or contained within a job's locker (or in the case of the chaplain and curator, selectable roundstart). The item added by this PR is more or less a sidegrade to the HoS's trenchcoat with the main benefits being extra storage space (something particularly at a premium earlier in the round!) and extra bullet resist (a particularly specialized form of resistance), with the main costs being lack of leg protection and gutted fire & acid protection (meaning more vulnerability to environmental hazards, and traitors who have some form of departmental access). This is admittedly balanced decently well as a sidegrade.

I'd be fully in support of this if it were instead an item in the HoS's locker, but this PR's current approach of having it be a part of the loadout menu is one that could set an unhealthy precedent for future loadout items going forward.

2022-06-11 00:06 UTC, TrojanCoyote commented
ngl I just didnt have an idea of how to actually put it in a vendor(more likely into the HoS's locker as I think it'd be a bit too good for normal sec to have them) I'm all down for removing it from the loadout.

2022-06-11 00:18 UTC, SandPoot commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/suit/armor/hos/platecarrier
```suggestion
	new /obj/item/clothing/suit/armor/hos/platecarrier(src)
```
Let me give you a little hand

2022-06-13 00:44 UTC, deathride58 approved these changes

2022-06-13 13:49 UTC, SandPoot requested changes
Everything looks fine but if you could remove the var without any effect (max_volume) and let inheritance handle certain vars since it has the same value it would be great.

2022-06-13 16:20 UTC, SandPoot commented
Alright, it's better enough.

2022-06-13 16:20 UTC, SandPoot approved these changes

2022-06-20 01:56 UTC, merged