dullahans 2: testmerge only or i will be very upset
citadel-station/citadel-main pull request #15755
Opened 2022-08-05 20:47 UTC by timothyteakettle

## About The Pull Request
title

dullahan is now a 0 point quirk
changes done to you mirror over to the head
things like ears/snouts/hair/etc copy over to the head

## Why It's Good For The Game
idk, sex?

## Changelog
:cl:
add: rewrites dullahans to not be awful
/:cl:

2022-08-05 21:23 UTC, Putnam3145 requested changes

2022-08-05 21:23 UTC, Putnam3145 commented on code/datums/components/dullahan.dm
> +	var/mob/living/human/H = parent
just remove this line

2022-08-05 21:23 UTC, Putnam3145 commented on code/datums/components/dullahan.dm
> +	H.gib()
```suggestion
	owner.gib()
```

2022-08-05 21:39 UTC, timothyteakettle commented
closing while i fix bugs because i don't want it testmerged if i am already aware of some bugs from my own testing

2022-08-08 01:45 UTC, timothyteakettle commented
closing again while i fix an issue to do with the head not being renamed

2022-08-12 18:12 UTC, LiteralMushroom commented
Can you add some way to get working high-luminosity eyes as a dullahan?
I need it for
very specific purposes.

2022-09-27 06:14 UTC, LiteralMushroom commented
Hey uuuuhhh why is this still in Testmerge Hell and not actually merged yet?

2022-12-09 13:28 UTC, timothyteakettle commented
i forgot to change the title so i guess it never got fully merged but um heres some updates to make dullahans have those old traits again??

2022-12-15 02:08 UTC, merged