Action button refactor/rework: Enhanced Dragging
citadel-station/citadel-main pull request #16052
Opened 2024-01-04 01:48 UTC by SandPoot

## About The Pull Request
***Ports [tgstation/65180](https://github.com/tgstation/tgstation/pull/65180)***
Check description THERE.

## Why It's Good For The Game
Players have more control over the clutter on their screen.
Buttons are available, but not in the way,
Since any player move of a button saves it, any lack of clarity in the way buttons work will be forced out by buttons not just resetting when a new game starts.
We don't overlap any existing screen elements, unless the upper button list gets really long.
The code is much less crummy (I think, may have made it worse it's hard for me to judge my own work)

If it ends up not being as usable as I'd like, I'll rip out the existing changes and just implement the qol and backend stuff. I think it's worth doing though.

## Changelog
:cl:
add: Expanded heavily on action buttons
add: Adds an action button dropdown that sits just under the normal list in the top left. You can drag new buttons onto it to insert them. Click on it to show its contents, do what you want to do, then click again anywhere to contract it. Alt click it to reset all button positions
add: Action buttons will now remember their position between rounds. So if you really like your flashlight right next to your player for some reason, we support that now
add: When you start to drag an action button, docking ports will appear in places that it can be inserted into. (Outside of just floating somewhere on your screen of course)
del: Removed action button locking, and the associated preference. I'm reasonably sure literally none uses this, but if you do hit me up
qol: Dragging an action button will now give you an outline of its size around your cursor
fix: You can no longer cause the screen to expand by putting an action button on the edge of widescreen, and then resizing to standard.
refactor: Refactors action and button code significantly. lots of little things.
/:cl:

2024-01-04 04:36 UTC, SandPoot commented
Hang on, target appearance is broken, will have to fix.

2024-01-13 04:04 UTC, deathride58 requested changes
Pretty much the only thing that sticks out in review is a partial regression of #15645 (The code I added with that PR is present! But so is the code I removed)

My fix makes TG's older method of checking specifically for middle-click dragging obsolete, as checking specifically for `DRAG` during mouse-up/mouse-down events (the only cases where `DRAG` gets sent) makes it possible to patch out the aimbot exploit in its entirety

2024-01-13 04:04 UTC, deathride58 commented on code/_onclick/drag_drop.dm
> +			middle_drag_atom_ref = null
Regression of #15645

2024-01-13 04:04 UTC, deathride58 commented on code/_onclick/drag_drop.dm
> +	..()
Regression of #15645

2024-01-13 04:04 UTC, deathride58 commented on code/modules/client/client_defines.dm
> +	var/datum/weakref/middle_drag_atom_ref
Regression of #15645

2024-01-13 04:04 UTC, deathride58 commented on code/modules/client/client_procs.dm
> +
Regression of #15645

2024-01-13 04:04 UTC, deathride58 commented on code/modules/client/client_procs.dm
> +					message_admins("[ADMIN_LOOKUPFLW(usr)] [ADMIN_KICK(usr)] is using the middle click aimbot exploit</span>")
Regression of #15645

2024-01-16 19:36 UTC, deathride58 approved these changes
There we go!

2024-01-16 19:39 UTC, merged