Custom Job Titles
citadel-station/citadel-main pull request #16112
Opened 2024-11-02 07:18 UTC by sheepishgoat

## About The Pull Request
Adds in custom job titles. This is a upstream version of this PR on our downstream repo: https://github.com/sheepishgoat/GS13-Citadel/pulls

## Why It's Good For The Game
This helps encourage roleplay by letting people choose job titles closer to what their character actually does.

## Changelog
:cl:
add: Adds in custom job titles.
/:cl:

2024-11-17 08:40 UTC, deathride58 commented on code/modules/jobs/job_titles.dm
> +	alt_titles = list("Custodian", "Sanitation Technician", "Maid", "Trash Can", "Disposal Unit")
>"Trash Can"
How do I approve a PR multiple times

2024-11-17 08:45 UTC, deathride58 requested changes
Code's good! Just a few porting artifacts left over

2024-11-17 08:45 UTC, deathride58 commented on code/modules/jobs/job_titles.dm
> +/datum/job/psychologist
Psychologists do not exist (could probably roll into doctor itself)

2024-11-17 08:45 UTC, deathride58 commented on code/modules/jobs/job_titles.dm
> +/datum/job/junior_doctor
Junior doctors do not exist

2024-11-17 08:45 UTC, deathride58 commented on code/modules/jobs/job_titles.dm
> +/datum/job/junior_scientist
Junior Scientists do not exist

2024-11-17 08:45 UTC, deathride58 commented on code/modules/jobs/job_titles.dm
> +/datum/job/junior_engineer
Junior engineers do not exist

2024-11-17 08:45 UTC, deathride58 commented on code/modules/jobs/job_titles.dm
> +/datum/job/junior_officer
Junior officers do not exist

2024-11-17 21:46 UTC, deathride58 approved these changes

2024-11-17 21:49 UTC, merged

2024-11-18 01:45 UTC, SandPoot commented
I am not fond of how this PR goes stuff that could end up in issues
I'd rather have sandstorm's version be ported over as it can support special behaviors without being intrusive