Cloning-Genitalia-Fix
citadel-station/citadel-main pull request #277
Opened 2017-03-14 16:31 UTC by ktccd

:cl: Cloned Genitals Fix
fix: Various methods of cloning now gives the organs the clone's DNA says they should have and updates genital appearance along with clone updating of appearance.
/:cl:

2017-03-16 01:03 UTC, LetterJay commented
Since this is @TalkingCactus 's thing, I'll let him review/merge.

2017-03-17 15:12 UTC, TalkingCactus requested changes

2017-03-17 15:12 UTC, TalkingCactus commented on code/modules/mob/living/carbon/human/human.dm
> +	give_genitals()
`if(!(NOGENITALS in dna.species.species_traits))`

2017-03-26 10:37 UTC, TalkingCactus commented
I don't suppose you could bundle a fix for the other half of #269 ? Clones apparently have white eyes, but I haven't seen it myself.

2017-03-27 18:01 UTC, ktccd commented
There. Added sanity, removed old and harmful sanity and so on.
And yes, now the eyes fix is in here as well. It's completely unrelated to why genitalia was broken, but since it shares the same issue ticket and it seemed like a simple fix, I just added it in here as well.
Turns out, handle_body code was checking if you were NOT husked AND no disabilities before they drew eyes or lips. Only one of those things should be relevant and it's not disabilities. Blind people also have eyes.

2017-03-27 18:07 UTC, ktccd reviewed
IDK how the request changes thing works, but I implemented the suggestion in my latest commit...

2017-03-27 18:07 UTC, ktccd commented on code/modules/mob/living/carbon/human/human.dm
> +	give_genitals()
I'm... uhm, not sure what this means, I'm not very used to github. I don't really understand what you want changed :S.

2017-03-27 18:07 UTC, ktccd commented on code/modules/mob/living/carbon/human/human.dm
> +	give_genitals()
Ok, so reading up a bit... this seems like, if anything, it should be in the give_genitals() proc, rather than hardcoded in this specific place. Nothing should ever get genitals if it has NOGENITALS trait in its dna and anything that has genitals needs to have dna to begin with, right? 'cause it's a carbon/human proc?

2017-03-27 20:06 UTC, ktccd commented
Travis loves me again!

2017-03-28 05:50 UTC, LetterJay commented
need an update on this

2017-03-28 07:00 UTC, ktccd commented
What'd you mean? Update how? O.o

2017-03-31 17:01 UTC, TalkingCactus commented on code/modules/mob/living/carbon/human/human.dm
> +	give_genitals()
It checks it as a failsafe, but doing one check here instead of potentially doing it several times later is better.

2017-03-31 17:16 UTC, ktccd commented on code/modules/mob/living/carbon/human/human.dm
> +	give_genitals()
I already added a check in give_genitals now though? It's not... like... better to check outside it. The proc responsible for handling genitals should be doing the checks, right?

2017-03-31 17:25 UTC, TalkingCactus commented on code/modules/mob/living/carbon/human/human.dm
> +	give_genitals()
That works, yes.

2017-03-31 17:26 UTC, TalkingCactus approved these changes

2017-04-01 15:40 UTC, merged