Mining Vendor Redo
citadel-station/citadel-main pull request #298
Opened 2017-03-19 20:40 UTC by katnep

basically Re adds all the stuff i added back at the start of 6th port,
also re added stimpacks to the lsit becuase i don't see why they needed
to be removed from it

2017-03-20 01:03 UTC, TalkingCactus requested changes

2017-03-20 01:03 UTC, TalkingCactus commented on code/modules/mining/machine_vending.dm
> +		new /datum/data/mining_equipment("Syringe Economy Pack",/obj/item/weapon/storage/box/medipens/survival,							2250),
This needs a more descriptive name.

2017-03-20 01:03 UTC, TalkingCactus commented on code/modules/mining/machine_vending.dm
> +		new /datum/data/mining_equipment("Whetstone",			/obj/item/weapon/sharpener,												400),
Whetstones can stay gone.

2017-03-20 01:03 UTC, TalkingCactus commented on code/game/objects/items/weapons/storage/boxes.dm
> +
Excessive line spacing, remove one.

2017-03-20 20:29 UTC, Roland410 commented on code/modules/mining/machine_vending.dm
> +		new /datum/data/mining_equipment("Whetstone",			/obj/item/weapon/sharpener,												400),
Whetstones aren't a REALLY bad thing and I don't understand why they were removed anyways.

2017-03-21 17:48 UTC, katnep commented on code/modules/mining/machine_vending.dm
> +		new /datum/data/mining_equipment("Syringe Economy Pack",/obj/item/weapon/storage/box/medipens/survival,							2250),
done changed to 'survival pen economy pack'

2017-03-21 17:49 UTC, katnep commented on code/modules/mining/machine_vending.dm
> +		new /datum/data/mining_equipment("Whetstone",			/obj/item/weapon/sharpener,												400),
removed

2017-03-21 17:49 UTC, katnep commented on code/game/objects/items/weapons/storage/boxes.dm
> +
removed the line

2017-03-21 17:52 UTC, TalkingCactus commented on code/modules/mining/machine_vending.dm
> +		new /datum/data/mining_equipment("Stimpack Economy Pack",/obj/item/weapon/storage/box/medipens/utility,							1000),
Trailing comma, remove it.

2017-03-21 17:56 UTC, TalkingCactus commented on code/game/objects/items/weapons/storage/boxes.dm
> +
The line is still there.

2017-03-26 11:05 UTC, TalkingCactus commented
This will be closed after seven days of inactivity.

2017-03-26 14:28 UTC, TalkingCactus approved these changes

2017-03-29 21:11 UTC, merged