Fixes digestion messages displaying to everyone nearby
citadel-station/citadel-main pull request #349
Opened 2017-04-10 03:42 UTC by lm40

no idea why this was the way it was, but the arguments for visible_message were wrong

2017-04-10 04:07 UTC, LetterJay commented
who all was seeing this happen? Just ghosts?

2017-04-10 04:21 UTC, lm40 commented
anyone within visible range, but only for fast digestion. now the fast digestion messages are the same as the normal ones.

2017-04-10 04:27 UTC, LetterJay commented
that's what the visible_message proc does.

2017-04-10 04:28 UTC, ktccd commented
Seems like an intentional feature?

2017-04-10 04:29 UTC, LetterJay commented
I dunno. I'd have to look more into it. Or let Poojawa. I know Cactus won't touch this stuff.

2017-04-10 04:30 UTC, lm40 commented
well yeah but it was showing everyone the giant red letters when it was (probably) supposed to just be showing them the "form loses its additions" part. it would be an easy fix by switching around the order of the arguments, but since the normal digestion doesn't show any of this at all i just axed the whole thing.

2017-04-10 04:31 UTC, ktccd commented
I meant that the fact the only purpose for that line of code is to display to people the message, it seems very intentional. I guess it's meant so you can't secretly fast-digest someone?
I take it this code is either from another era here, or from vorestation? Where I think you could use vore for antag purposes and the reason it's displayed this way was to give prey a chance to be saved or preds to be caught?

2017-04-10 04:35 UTC, lm40 commented
vorestation doesn't have fast digestion

2017-04-10 04:36 UTC, ktccd commented
Personally I don't mind people outside a person being able to tell when they suddenly digest their own bodymass in food, as sprites don't convey this.
But I think the usage of "userdanger" span class is abused here. IDK much about chat formatting, but the name userdanger seems to imply this is meant for IMPORTANT SHIT KILLING **YOU** RIGHT NOW kind of text.

2017-04-10 04:38 UTC, ktccd commented
And this is obviously NOT a danger to the person receiving the chat message about it. Would lowering the span format to the danger class, which is meant for dangerous shit to OTHER people, work for a fix?

2017-04-10 04:38 UTC, lm40 commented
it was never meant to display the danger message to the bystanders, that's why this is a bug

2017-04-10 04:39 UTC, ktccd commented
So don't remove it, fix it?

2017-04-10 04:39 UTC, lm40 commented
i don't really see the point of having this message at all so i'm just removing it

2017-04-10 04:40 UTC, ktccd commented
Damn, conversations moving too fast for me to be able to edit in time ^^.
What about the point I raised earlier though?

2017-04-10 04:42 UTC, lm40 commented
it's more of an rp mechanic than a game one so i don't think this is really necessary

2017-04-10 04:44 UTC, ktccd commented
But... I do? Like, even from an RP point of view.
The sprite system we have don't currently allow for being able to tell when people are full or anything, so there's no way to notice a person suddenly shrinking down half their bodymass without constantly spamming examine and suddenly the message about them being full is gone.
I kind of like that there's a prompt that does let you notice a noticeable change like that.

Now, obviously I don't like that the span class is incorrect, but that's an easy fix.

2017-04-10 04:45 UTC, lm40 commented
this is (mechnically) the same thing that happens when you finish digesting someone at regular speed and that shows no message, it should be consistently one way or the other and this way was marginally easier

2017-04-10 04:48 UTC, ktccd commented
Well, I'd like that one to have something similar too honestly. So for consistency, adding a similar thing there would also work. This is a very visually noticeable thing which I think is kind of weird that you can SEE if you look at the person but it's odd if you can't notice it changing without spamming examine.
(And I don't really like taking the easy way out just for the sake of being easier :S)

2017-04-10 04:52 UTC, lm40 commented
i'm too tired to argue about this so it's easier to just change it, either way i want to resolve the issue of random bystanders feeling people gushing through their system or w/e

2017-04-10 04:54 UTC, ktccd commented
I think you removed the messages that are sent to the prey. Those are the M << message things.

2017-04-10 04:55 UTC, ktccd commented
Also, wait, bystanders "feel people gushing through their system"? You mean the OWNER messages are sent to bystanders?

2017-04-10 04:56 UTC, lm40 commented
yes, the order of the arguments were wrong, that's why it was a bug.

2017-04-10 04:59 UTC, ktccd commented
THAT is a different kind of bug ^^. I think that's because the visible_message contained those strings where it shouldn't have? Would removing the [digest_alert_owner] and [digest_alert_prey] pieces from the visible_message fix it?

2017-04-10 05:00 UTC, ktccd commented
because those things should have been sent to their respective players with the << operator.

2017-04-10 05:00 UTC, lm40 commented
no, the error was in visible_message, the << bit worked perfectly fine and it's why this bug only existed when people fast digested

2017-04-10 05:01 UTC, ktccd commented
Yeah, so keep the part of visible message that shows they kind of digested someone, but don't send them the digest_alert strings? 'cause those are usually written from the perspective of the prey/pred.

2017-04-10 05:02 UTC, ktccd commented
... would be cool to have a 3rd person string for this purpose, but meh, not the scope of this PR.

2017-04-10 05:02 UTC, lm40 commented
...that's what i did.

2017-04-10 05:02 UTC, ktccd commented
Didn't you say you removed everything?

2017-04-10 05:03 UTC, lm40 commented
i did but i fixed it the other way since you were complaining and i'm too tired to argue

2017-04-10 05:04 UTC, ktccd commented
Yes, but when you did THAT commit, you ALSO removed the prey recieving a message at ALL...

2017-04-10 05:04 UTC, lm40 commented
see visible_message

2017-04-10 05:05 UTC, ktccd commented
Yes... but this would display a message from the prey's point of view to everyone, wouldn't it?

2017-04-10 05:05 UTC, lm40 commented
// Show a message to all player mobs who sees this atom
// Show a message to the src mob (if the src is a mob)
// Use for atoms performing visible actions
// message is output to anyone who can see, e.g. "The [src] does something!"
// self_message (optional) is what the src mob sees e.g. "You do something!"
// blind_message (optional) is what blind people will hear e.g. "You hear something!"
// vision_distance (optional) define how many tiles away the message can be seen.
// ignored_mob (optional) doesn't show any message to a given mob if TRUE.

/atom/proc/visible_message(message, self_message, blind_message, vision_distance, ignored_mob)

2017-04-10 05:06 UTC, ktccd commented
FUCK, I missed the comma. I thought it was just appended at the end of a string.... FML, my bad.

2017-04-10 05:07 UTC, ktccd commented
Yeah, your fix was correct then. Damn I should be sleeping regularly, I make dumb mistakes like this...

2017-04-10 05:16 UTC, TalkingCactus requested changes

2017-04-10 05:16 UTC, TalkingCactus commented on code/modules/vore/eating/bellymodes_vr.dm
>  				owner << "<span class='warning'>" + digest_alert_owner + "</span>"
to_chat(owner, "\<span class='warning'\>"digest_alert_owner"\</span\>")

2017-04-10 05:16 UTC, TalkingCactus commented on code/modules/vore/eating/bellymodes_vr.dm
> +				M.visible_message("<span class='notice'>You watch as [owner]'s form lose its additions.</span>", "<span class='warning'>[digest_alert_prey]</span>")
loses

2017-04-10 05:16 UTC, TalkingCactus commented on code/modules/vore/eating/bellymodes_vr.dm
> +				M.visible_message("<span class='notice'>You watch as [owner]'s form lose its additions.</span>", "<span class='warning'>[digest_alert_prey]</span>")
loses

2017-04-10 05:16 UTC, TalkingCactus commented on code/modules/vore/eating/bellymodes_vr.dm
>  				owner << "<span class='warning'>" + digest_alert_owner + "</span>"
to_chat(owner, "\<span class='warning'\>"digest_alert_owner"\</span\>")

2017-04-10 05:44 UTC, lm40 commented
>doesn't compile

w/e i'll fix this tomorrow

2017-04-11 18:48 UTC, LetterJay commented
This show as pending reviews requested, but I don't see anything?

2017-04-11 18:52 UTC, TalkingCactus approved these changes

2017-04-11 18:53 UTC, TalkingCactus commented
I had to approve them, also yeah sorry I forgot to replace the quotation marks with square brackets.

2017-04-11 18:53 UTC, merged