[MIRROR] Divides species in subtypes, makes viruses able to infect certain subtypes
citadel-station/citadel-main pull request #4076
Opened 2017-11-22 21:37 UTC by CitadelStationBot

Original PR: https://github.com/tgstation/tgstation/pull/32858
--------------------
:cl: XDTM
add: Added two new symptoms: one allows viruses to still work while dead, and allows infection of undead species, and one allows infection of inorganic species (such as plasmapeople or golems).
/:cl:

Species are now separated into Organic, Inorganic, Undead and Robotic. The virusimmune tag was kept for species who are effectively organic but immune to viruses for special reasons (abductors).

You can now set the types of species viruses can infect; i made some adjustments that i thought made sense (beesease infecting zombies, parrot possession infecting anyone).

Added process_dead as an additional effect for the new symptom, allowing the disease to tick on corpses; it doesn't have many uses i can think of, but it can heal up people in case of a defibrillation or something like that.

Fixes #32832

2017-11-23 01:15 UTC, deathride58 requested changes
Gonna have to add SPECIES_ORGANIC to the existing cit races

2017-11-28 04:10 UTC, Partheo commented
@deathride58 I'm having the same issue with the PRMirror bot putting diff markers like <<<<<< HEAD in certain PRs. Any clue on how to resolve the issue?

2017-11-28 04:28 UTC, deathride58 commented
Those are merge conflicts. The only way to resolve the issue is to resolve the conflicts manually.

2017-12-04 21:57 UTC, deathride58 approved these changes

2017-12-04 21:57 UTC, merged