Cargo orm security
citadel-station/citadel-main pull request #5168
Opened 2018-01-29 03:12 UTC by Zna12

Ore Redemption Machines have been moved to more publicly accessible areas on Box and Delta stations. All stations now have a Mineral Storage locked windoor in front of the ORM. Also moved the Cargo Protolathe into the mining dock on Box because Miners kept breaking into the cargo bay to grab shit on high pop rounds.

🆑 ORM Movement
tweak: Box Station ORM Moved to 2 tiles south of Cargo Office Door.
tweak: Delta Station ORM moved to the southernmost window of Cargo.
tweak: Box, Delta, Meta stations now have Windoors with Mineral Storage access blocking them.
/🆑

[why]: Because originally, people were moving the ORM to break into cargo. An earlier PR overcorrected and removed ORM access to anyone but cargo. Hopefully this works better as a middleground.

(This is just a copypasta of the original PR's CL and reasoning. Nothing has changed between the failed PR and this one besides actually learning how to mapmerge properly.

2018-01-29 03:12 UTC, Zna12 commented
222 and 192. Much more reasonable.

2018-01-29 04:07 UTC, deathride58 requested changes

2018-01-29 04:07 UTC, deathride58 commented on _maps/cit_map_files/BoxStation/BoxStation.dmm
>  /turf/open/floor/plasteel,
>plasteel floors underneath windows

Please use a plating here

2018-01-29 04:07 UTC, deathride58 commented on _maps/cit_map_files/Deltastation/DeltaStation2.dmm
>  /turf/open/floor/plasteel/neutral,
Ditto

2018-01-29 04:41 UTC, deathride58 approved these changes

2018-01-31 09:02 UTC, merged

2018-01-31 20:57 UTC, Poojawa commented
TEST YOUR SHIT

2018-01-31 20:57 UTC, Poojawa commented
the ORM is placed backwards.