Adds some tracks to the discoball for extreme awooing and a awooing sound affect
citadel-station/citadel-main pull request #5201
Opened 2018-01-30 20:17 UTC by improvedname

Awooooo!!

Tracks include as the following.
Awoo sound affect - https://www.youtube.com/watch?v=8AeQnH3JX_c
This is how it goes - https://www.youtube.com/watch?v=mjLbXwdqs18
Telephone number - https://www.youtube.com/watch?v=I0JVRcJLea8
Awakening wolf instinct - https://www.youtube.com/watch?v=V_uikyoC95c

:cl: Improvedname
tweak: adds more stuff to the discoball
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.) More variations then just doom and 2 versions of the shuffle duffle

2018-01-30 20:21 UTC, deathride58 requested changes
Good content, but you can modularize all of this. Only the awoo button in interact really needs to be touching the code.

2018-01-30 21:36 UTC, deathride58 requested changes

2018-01-30 21:36 UTC, deathride58 commented on modular_citadel/code/game/machinery/dance_machine.dm
> +	/list/songs = list(
You don't need /list/, you just need songs.

2018-01-30 21:36 UTC, deathride58 commented on modular_citadel/code/game/machinery/dance_machine.dm
> +		list/available = list()
This is defined in a proc. You don't need this here.

2018-01-30 21:36 UTC, deathride58 commented on modular_citadel/code/game/machinery/dance_machine.dm
> +			deejay('sound/misc/Awoo.ogg')
This should go under topic. This is a proc thing.

2018-01-30 21:36 UTC, deathride58 commented on code/game/machinery/dance_machine.dm
> +		charge -= 5
You don't need this whitespace change

2018-01-30 21:36 UTC, deathride58 commented on code/game/machinery/dance_machine.dm
> +		new /datum/track("Ultimate High-Energy Hustle",					'sound/misc/boogie2.ogg',	1770, 	5),
These whitespace changes, reeeEE

2018-01-30 21:36 UTC, deathride58 commented on code/game/machinery/dance_machine.dm
> +		new /datum/track("Ultimate High-Energy Hustle",					'sound/misc/boogie2.ogg',	1770, 	5),
Also you should copy and paste everything here into the overridden songs var in modular_citadel.

2018-01-31 05:19 UTC, deathride58 requested changes

2018-01-31 05:19 UTC, deathride58 commented on modular_citadel/code/game/machinery/dance_machine.dm
> +/obj/machinery/disco/Topic(href_list)
Topic(href, href_list)

Also be sure to add a `. = ..()` here

2018-02-01 11:42 UTC, improvedname commented
Working on this later

2018-02-01 11:42 UTC, closed without merging