Buffs tablepushing
citadel-station/citadel-main pull request #5222
Opened 2018-01-31 14:09 UTC by cebutris

title

2018-01-31 17:57 UTC, deathride58 requested changes
You can probably modularize this

2018-01-31 17:57 UTC, deathride58 commented on code/game/objects/structures/tables_racks.dm
> +	if(H.ckey == "kevinz000")
istype(H) && H.ckey ==

2018-01-31 17:57 UTC, deathride58 commented on code/game/objects/structures/tables_racks.dm
> +		return
No need for this return

2018-01-31 18:17 UTC, cebutris commented
I can definitely modularize it but that would require it not being a meme

2018-02-01 17:21 UTC, deathride58 approved these changes

2018-02-05 05:26 UTC, merged