[Help Wanted] [DNM] [Work in Progress] Robust industrial gear
citadel-station/citadel-main pull request #5583
Opened 2018-02-19 03:01 UTC by Zna12

Alrighty. The grate space suit rework is upon us. This is going to be an effort to port over Bay/VORE's RIG suits and space suit taur sprites.

- [ ]  Add basic RIG code.
- [ ] Smooth out errors with RIG code, bring it up to CIT/TG standards.
- [ ] Figure out how to get space suits/hardsuits to have taur specific sprites.

2018-02-19 03:04 UTC, Zna12 commented
Let me know if you want in on this crazy train.

2018-02-19 04:09 UTC, jakeramsay007 commented
I've started a port of Bay's rigsuits as well, so I'll be using this for reference and such.

2018-02-19 04:10 UTC, Zna12 commented
Well, there's always the option of collaborating.

2018-02-19 05:38 UTC, deathride58 commented
Taur-specific sprites for suits is already handled by #4322 , that PR just needs more sprites for all 6 unique taurtypes. You don't need to stress yourself out for taur altsprites, as I've already done most of the heavy lifting on the code side of things in #4322

2018-02-22 05:05 UTC, kevinz000 commented
All I can say is baystation rigsuits are horrible in balance and if you Port this you're going to have to make it balanced to tg/cit combat.

2018-02-23 05:56 UTC, Poojawa commented
I have plans for balancing them. 

It's also liable that I'll convert flightsuits to rigs in terms of set up as well. or if just for power code memes

2018-02-24 01:53 UTC, kevinz000 commented
flightsuits were made because i wanted to make power armor but i got lazy so i just made flightsuits and called it a day.

2018-03-11 07:10 UTC, silicons requested changes
Instead of stubbornly leaving ~400 comments or whatever on the PR before you're even done, please look at the coding standards I pinned on discord dev channels or whatnot so that we both have less work when you're ready for review.

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +	selectable = 1
TRUE

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +	selectable = 1
TRUE

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +	usable = 1
TRUE

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +/obj/item/rig_module/mounted/New()
Initialize()

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +		return 0
FALSE

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +	return 1
TRUE

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +	usable = 0
FALSE

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +	usable = 0
FALSE

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +	selectable = 1
TRUE

2018-03-11 07:10 UTC, kevinz000 commented on modular_citadel/code/modules/clothing/spacesuits/rig/modules/combat.dm
> +	toggleable = 1
TRUE

2018-03-16 14:16 UTC, closed without merging

2018-03-16 14:19 UTC, Zna12 commented
shit whoops