[WIP] Stabsinthe!
citadel-station/citadel-main pull request #5639
Opened 2018-02-21 18:50 UTC by cebutris

:cl: Cebutris
add: Stabsinthe! A new alcohol you can brew with absinthe and acid spit, or make an entire bottle by tablecrafting a full absinthe bottle with a nettle branch!
/:cl:

In the Spirit of the current Bastion drinks (Fetching Fizz and Hearty Punch), I wanted to add some more! Stabsinthe seemed pretty simple, so I wanted to try my hand at it. I gave it a unique recipe and even it's own tablecrafting recipe!
 
TODO:

- [ ] framework
- [ ] sprites
- [ ] retaliation code
- [ ] bugfixes

2018-02-21 18:54 UTC, cebutris commented on modular_citadel/code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
> +/datum/crafting_recipe/food/stabsinthe //You can make a bottle of stabsinthe with a full bottle of absinthe and a nettle
The tablecrafting is a bit weird. It doesn't consume any of the required items, just spawning the result. It DOES move the absinthe from whatever container it was in into the new bottle (which already has 100 stabsinthe, resulting in 200u total). I have no idea why it happens like that!

2018-02-21 22:14 UTC, cebutris commented
An unintended (but hilarious) side effect of this is that if you don't drink it fast enough you'll splash yourself with the glass or smash yourself with the bottle when you get forced into harm intent. I'm calling it a feature

2018-02-26 13:06 UTC, cebutris commented
Update so it's not stale. It still isn't working anywhere close to how I want it to be but there's an idea for framework in place. Feedback or suggestions would be appreciated!

2018-02-26 13:08 UTC, cebutris commented on modular_citadel/code/modules/reagents/chemistry/reagents.dm
> +/datum/reagent/water/on_mob_attacked(mob/living/M)
ignore this, this is just what I use for testing the proc. It'll be removed once I get things running proper

2018-02-26 18:57 UTC, cebutris commented
This is ready for a review! There's still the tablecrafting bug that I need to sort out, but other than that this is in a good place for a review

2018-02-26 19:00 UTC, deathride58 requested changes

2018-02-26 19:00 UTC, deathride58 commented on code/modules/mob/living/carbon/carbon_defense.dm
> +	if(src.reagents) //CIT CHANGE. Handles datum/reagent/proc/on_mob_attacked
No need for the src. here

2018-02-26 19:00 UTC, deathride58 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	if(src.reagents) //CIT CHANGE. Handles datum/reagent/proc/on_mob_attacked
Ditto. No need for the src. here

2018-02-27 14:51 UTC, cebutris commented
Okay so this is a problem. I can't have the icon in a modular file because that would mess up the broken bottle sprite, but I also can't put it in the normal file because that will make merge conflicts...

2018-02-27 15:19 UTC, cebutris commented
THERE'S NO MORE MERGE CONFLICT, MR.BOT, YOU CAN REMOVE THE TAG NOW

2018-02-28 12:29 UTC, cebutris commented
So I tried to pull to fix the merge conflicts and I succeeded in breaking absolutley everything about my local repo. The only bug present with the PR as it stands is that the bottle lacks a broken sprite, and because I cocked everything up I don't think I can fix it in this PR. I CAN, however, make a followup PR to fix it. I'm just bad at Git.

I commented out the tablecraft recipe because I could not figure out WHY it wasn't working. It was as far as I could see identical to how other tablecraft recipes are handled, but it didn't behave the same way at all. Once someone figures out why it happened like that the recipe can be uncommented, I guess.

I'm considering this ready. As ready as it's going to get, in any case

2018-03-03 02:10 UTC, Poojawa commented
since this was ported upstream, we don't need this anymore yah?

2018-03-03 02:10 UTC, closed without merging

2018-03-03 03:09 UTC, cebutris commented
Well, it might not be merged upstream. I was planning on closing the PR if the upstream one got merged, and if it didn't, working on fixing this one.

However I fucked my repo pretty hard so yeah closing it is fine