Nymphotrait
citadel-station/citadel-main pull request #5827
Opened 2018-03-06 20:51 UTC by NopeMcHaltman

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Anonymous
add: Adds nymphomania trait, which will raise your minimal arousal and boost rate of it.
/:cl:

[why]: # 
I did this out of boredom. **Not sure about values, though.**

2018-03-06 20:51 UTC, deathride58 requested changes
Move to modular_citadel/code/datums/traits/neutral.dm

2018-03-07 02:07 UTC, mattroks101 commented on code/datums/traits/neutral.dm
> +	desc = "You're always feeling a bit in heat. You're also get in steamy mood slightly faster than usual."
"You're also get in steamy mood"
Bad grammar.

2018-03-07 16:39 UTC, NopeMcHaltman commented
@deathride58, consider it done.

2018-03-07 16:40 UTC, deathride58 approved these changes
Yiff! ✊

2018-03-09 18:44 UTC, merged