my fulton changes
citadel-station/citadel-main pull request #59
Opened 2016-09-25 11:31 UTC by katnep

fulton rework to make them worth getting
added the medipen from the medevac bundle
made fulton able to carry people
removed medevac because it was made redundant
renamed fulton to "extract and rescue kit" and "extract and rescue pack"

2016-09-26 21:50 UTC, TalkingCactus commented on code/modules/mining/machine_vending.dm
> +	var/items = list("Crusher Kit", "Extract amd Rescue Kit", "Hunter Kit", "Mining Drone", "Resonator and Advanced Scanner", "Survival Capsule and Explorer's Webbing")//Alphabetical, please.
`"Extract amd Rescue Kit"` -> `"Extract and Rescue Kit"`

2016-09-26 21:51 UTC, TalkingCactus commented on code/modules/mining/fulton.dm
> +	var/safe_for_living_creatures = 1
Should probably change the description and name so the players know that they can use this on living things, too.

2016-09-26 21:53 UTC, TalkingCactus requested changes
Typo fix as well as a name and description change for the extraction pack.

2016-09-27 10:01 UTC, katnep commented
made the changes, had to do it in a really roundabout way but fixed them :p

2016-09-27 10:07 UTC, TalkingCactus commented on code/modules/mining/fulton.dm
>  	name = "fulton material extraction pack"
`"fulton material extraction pack"` -> "fulton extraction pack"

2016-09-27 11:06 UTC, katnep commented on code/modules/mining/fulton.dm
>  	name = "fulton material extraction pack"
fixed

2016-09-27 11:39 UTC, TalkingCactus approved these changes

2016-09-27 19:29 UTC, ghost approved these changes

2016-09-28 15:17 UTC, closed without merging