Allows players to commit seppuku with any katana, adds SFX for seppuku
citadel-station/citadel-main pull request #6945
Opened 2018-05-28 23:26 UTC by ElPresidentePoole

Title says it all; special messages for commiting suicide with replica katanas/energy katanas

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl:
add: SFX for seppuku (on all katanas)
add: suicide message for energy katanas ("cyber-seppuku")
add: suicide message for replica katanas ("seppuku")
/:cl:

[why]: In a game like SS13, where the unofficial motto is "the developers thought of everything", I found it annoying that you don't get a special suicide message if you have a replica katana or an energy katana.  It just seems like such an obvious interaction, I figured it would already be in the game by now.  However, the interaction only exists with the base katana, not the toy or energy version.  This PR fixes that.

This change does not affect gameplay at all, just flavor text.

2018-05-29 00:39 UTC, deathride58 requested changes
Modularize it by moving the overridden procs to `modular_citadel`

2018-05-29 17:34 UTC, ElPresidentePoole commented
Okay, I'll do that.

2018-07-02 19:50 UTC, deathride58 commented
It's been a month, what's the status on this PR?

2018-07-02 20:00 UTC, ElPresidentePoole commented
I tried to add it to modular_citadel but it wouldn't work for some reason.  Is there something special I have to do to get the modular thingy to work?

2018-07-02 20:18 UTC, deathride58 commented
You have to be sure to add the modular_citadel files to the .dme, yeah. Aside from that, there's really not much else required to add overridden procs to modular_citadel

2018-08-17 19:43 UTC, silicons approved these changes

2018-08-17 20:55 UTC, deathride58 approved these changes
Modularization's no longer necessary, as we no longer have to worry about the mirror bot

2018-08-17 20:55 UTC, merged

2018-08-17 20:56 UTC, ElPresidentePoole commented
Lucky me!