Midround Event changes
citadel-station/citadel-main pull request #7076
Opened 2018-06-12 05:09 UTC by Cw3040

Changelogs in the Commits my friends

2018-06-12 06:42 UTC, Cw3040 commented
Wait this fucked up

2018-06-12 16:27 UTC, CameronWoof commented
Sure.

2018-06-12 22:32 UTC, deathride58 submitted a review, later dismissed
Modularize these changes by overriding them in modular_citadel or add `//CITADEL CHANGE - adjusts x to y` comments to every single line you've changed

2018-06-12 22:32 UTC, deathride58 requested changes
hec wrong button

2018-06-13 00:22 UTC, silicons commented on modular_citadel/code/modules/events/devil.dm
> +/datum/round_event_control/devil
No devil.
Just no.

2018-06-13 00:23 UTC, silicons requested changes
Therei s no possible way you can convince me spawning a devil without a crazy admin doing it is a good idea.

2018-06-14 09:14 UTC, deathride58 requested changes
Add the new files to the .dme, and make sure the files only override the variables you've changed

2018-06-15 23:41 UTC, Cw3040 commented
alright time to quit doing this, my position is clearly in the map world

2018-06-15 23:41 UTC, closed without merging