Modifies the vTec cyborg upgrade to be toggleable between off/half/full
citadel-station/citadel-main pull request #7129
Opened 2018-06-16 18:44 UTC by PolymorphBlue

Adds a set of chevron icons to icons/mob/actions.dmi to show this - provided by Toriate

Makes this modification because a few different borgs stated that vTec could be hard to control, so makes it have a half-power feature.

2018-06-17 13:14 UTC, deathride58 requested changes
Needs to be modularized. The replacement of `R.speed = -2` with `R.AddAbility(...)` can stay in the file, but with a `//Citadel change - makes vtecs give an ability rather than reducing the borg's speed instantly` added onto it

2018-06-17 19:11 UTC, jakeramsay007 requested changes

2018-06-17 19:11 UTC, jakeramsay007 commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/effect/proc_holder/silicon/cyborg/vtecControl
This proc can be modularised into modular_citadel

2018-06-17 19:11 UTC, jakeramsay007 commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/effect/proc_holder/silicon/cyborg/vtecControl/Click(mob/living/silicon/robot/user)
As can this one

2018-07-09 04:26 UTC, deathride58 approved these changes
We don't really have to worry about modularization anymore, since the mirror bot's turned off. So this can be merged

2018-07-09 04:26 UTC, merged