Removes armor form Non-head only suits
citadel-station/citadel-main pull request #7354
Opened 2018-07-06 17:51 UTC by Trilbyspaceclone

Basically get better armored suits then sec do!

[Changelogs]: # Removes the armor form MedSci Uniform, and Operations Uniform. 

[why]: # Not a good idea to give better armor'ed jumpsuits to 70% of the crew by using a magic 1-2 points in there Load-out tab
Resemblance Trek Uniforms
Should remove/redo the Head-only uniform seeing how its still better then HOS uniform and such

2018-07-06 21:10 UTC, deathride58 requested changes
No need for the `//Cit change` comments in modular_citadel

2018-07-07 13:12 UTC, Trilbyspaceclone commented
Need me to edit anything more?

2018-07-08 15:03 UTC, Poojawa commented
Most jumpsuits have 10 or more resistances to various things, 
Sec jumpsuit is:
`armor = list("melee" = 10, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 30)`

2018-07-08 16:18 UTC, Trilbyspaceclone commented
@Poojawa Better armor as in the basic jumpsuits don't have any combat armor, like Docs get bio, Sci get acid armoring. Sec gets melee ect. Those armors give the basic armor to the department as well as 10 melee armor. There is no reason to make Trek suits basically what there department jumpsuit gives + melee. 

Medical jumpsuit
armor = list("melee" = 0, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 10, "rad" = 0, "fire" = 0, "acid" = 0)
Trek Medical jumpsuit
armor = list("melee" = 10, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 10, "rad" = 10, "fire" = 0, "acid" = 10) 
Its flat out better for no reason

2018-07-09 04:20 UTC, Poojawa commented
To be honest it wouldn't make a difference anyway. just get tator weapons 10 ap if there's balance concerns.

2018-07-09 04:35 UTC, kevinz000 commented
same for this one @Trilbyspaceclone

2018-07-09 04:36 UTC, Poojawa commented
aaaa. what. WHY IS THIS CLOSED??

2018-07-10 06:04 UTC, deathride58 approved these changes

2018-07-10 06:04 UTC, merged