Ports Construction Hardsuits back from 5th port. Not mapped yet.
citadel-station/citadel-main pull request #7384
Opened 2018-07-20 01:29 UTC by RoyalKurwa

Construction Hardsuits are bright orange hardsuits. The difference being from engineering ones is that they're supposed to be used for quick fixes or general station work, could also be surplus incase more than 2 basic engineers sign up. Quicker movement speed than the regular Engisuit but not gamebreakingly so (hopefully).

Suits aren't mapped in yet because I'm unsure of how this works but there would be two in the secure tech storage as one of the main issues of them on 5th was the ease of access into the construction area.

:cl: RoyalKurwa
add: Added Construction Hardsuits
/:cl:

2018-07-20 04:19 UTC, deathride58 requested changes

2018-07-20 04:19 UTC, deathride58 commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list(melee = 5, bullet = 5, laser = 5, energy = 5, bomb = 5, bio = 100, rad = 0)
wrap all of these var names in quotes. not doing so will result in the armor not applying at all

2018-07-20 04:19 UTC, deathride58 commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list(melee = 5, bullet = 5, laser = 5, energy = 5, bomb = 5, bio = 100, rad = 0)
wrap all of these var names in quotes. not doing so will result in the armor not applying at all

2018-07-22 02:55 UTC, improvedname commented
If theres no way to get this why add them sprites look meh
But without aan purpose code bloat

2018-07-22 13:04 UTC, RoyalKurwa commented
Still trying to figure out on how to add things, I'll ask someone for some help doing it.

2018-07-26 05:17 UTC, Poojawa commented
this was basically a way for assistants to get more hardsuits. since engineering almost never needed them.

2018-07-28 13:25 UTC, deathride58 commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	slowdown = 0.75
Outside of very specific edge cases, this only differs from slowdown=1 when the server's tickrate is set to 40 ticks per second. The live server's tickrate is 20.

2018-07-28 13:27 UTC, deathride58 approved these changes
I can see these being pretty alright for adminbus, or available as surplus hardsuits that only spawn when more than a certain amount of engineers are active, similar to how extra sec lockers spawn in when there's enough sec officers latejoining.

2018-09-27 02:30 UTC, deathride58 commented
Has conflicts with hard sync

2018-11-19 18:53 UTC, nik707 commented
If this is fixed and re-opened, I'd probably approve it, Until then...

2018-11-19 18:53 UTC, closed without merging