Adds a new mass hallucination, courtesy of Izzy
citadel-station/citadel-main pull request #7430
Opened 2018-08-02 17:31 UTC by kevinz000

2018-08-02 17:36 UTC, deathride58 requested changes

2018-08-02 17:36 UTC, deathride58 commented on code/modules/events/mass_hallucination.dm
> +				to_chat(i, "<span class="big bold"><font color="red">Shuttle Purchase</font><br>Kate Walker has purchased Standby Evacuation Vessel "Scrapheap Challenge" for -1000 credits.</span>")
Escape the quotes you unrobust feline

2018-08-02 23:18 UTC, Trilbyspaceclone commented
We also need Kate being capo 
And maybe a Hairly joining as capo

2018-08-06 07:11 UTC, Dankseed commented
Much needed feature for some time now, glad to see it finally being added. +1 merge when

2018-08-06 07:16 UTC, zombieme7 commented
+1

2018-08-12 00:47 UTC, deathride58 requested changes
Make it compile

2018-08-23 07:28 UTC, closed without merging