Nuclear Operatives are no longer exclusively human
citadel-station/citadel-main pull request #7492
Opened 2018-08-23 23:18 UTC by Tupinambis

:cl: Tupinambis
tweak: When spawned as a nuclear operative, you keep your characters race instead of being changed into a human. Plasmamen are an exception to this change.
/:cl:

[why]: The original reason that the players race was always changed to human was because of tg's default Asimov lawset. On citadel crewsimov is followed instead. This should also make stealth ops more effective, as a group of unknown pure humans on cit is a lot more suspicious than it would be on tg.

2018-08-23 23:22 UTC, deathride58 requested changes

2018-08-23 23:22 UTC, deathride58 commented on code/modules/antagonists/nukeop/nukeop.dm
> +		return
`return TRUE`

2018-08-24 01:25 UTC, Hatterhat commented
>snowflake ops
oh no

2018-08-25 11:01 UTC, deathride58 approved these changes

2018-08-27 01:23 UTC, merged