Makes the syndicate suspicous toolbox not be called "suspicous anymore" but just black and red striped instead.
citadel-station/citadel-main pull request #7497
Opened 2018-08-25 19:43 UTC by improvedname

UHHH BLACK TOOLBUX LOOKS SUSPICUS

:cl: Improvedgay
balance: Naming immerions
/:cl:

2018-08-28 18:38 UTC, MimicFaux commented
I'd like something with a little more tongue in cheek. "Perfectly ordinary Toolbox" for example. Still maintains muh immurshuns, but gets the point across.

2018-08-29 11:47 UTC, deathride58 requested changes

2018-08-29 11:47 UTC, deathride58 commented on code/game/objects/items/storage/toolbox.dm
> +	desc = "A toolbox painted black with a red stripe. It looks more heavy then normal toolboxes."
s/looks more heavy then/looks heavier than

2018-09-01 10:09 UTC, deathride58 approved these changes

2018-09-03 17:49 UTC, merged