Accessory armor vests!
citadel-station/citadel-main pull request #7585
Opened 2018-09-21 01:02 UTC by Trilbyspaceclone

[Changelogs]: 
Adds in many different types of vest for each department to help people better survive in there 100% safe work!
Adds in a new node having more advance protection for sec!
List of vest added
Illegal Vest -Admin only ATM
Biohazard resistant vest
Bomb resistant vest
Fire resistant vest
Lava Land Vest
Miner Vest
Ballistic vest -Civ
Close Quarter Combat Vest -Civ
Military grade physal armor vest - Sec
Most armor dosn't do all that much for more combat, everything is less then or the same to bone talisman, in the combat
[why]: 
Accessory slot is never used actively unless your a miner, lets change that!

2018-09-21 02:13 UTC, Poojawa commented on code/modules/clothing/under/accessores/armor.dm
> +	desc = "A illegal vest with a mix of diffent metals and plastics."
diffent

2018-09-21 02:13 UTC, Poojawa commented on code/modules/clothing/under/accessores/armor.dm
> +	icon_state = "waistcoat"
copypasta out the ass btw

2018-09-21 02:14 UTC, Poojawa commented on code/modules/clothing/under/accessores/armor.dm
> +	desc = "A heavy vest that can be attached to a jumpsuit to help protect against a blast."
if it's heavy it should cause some slow down penalties

2018-09-21 02:15 UTC, Poojawa commented on code/modules/clothing/under/accessores/armor.dm
> +	armor = list("melee" = 0, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 0)
50% fire damage nerfing. lol

2018-09-21 02:18 UTC, Poojawa commented on code/modules/clothing/under/accessores/armor.dm
> +/obj/item/clothing/accessory/engery_vest
engery_vest

2018-09-21 02:19 UTC, Poojawa commented on code/modules/clothing/under/accessores/armor.dm
> +	name = "Laser Dispersion Vest.."
Vest..

2018-09-21 02:19 UTC, Poojawa commented on code/modules/clothing/under/accessores/armor.dm
> +	armor = list("melee" = 0, "bullet" = 0, "laser" = 0,"energy" = 15, "bomb" = 15, "bio" = 5, "rad" = 50, "fire" = -50, "acid" = 25)
"fire" = -50

2018-09-21 02:20 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	name = "Bomb resitsent vest."
resitsent

2018-09-21 02:20 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	name = "Bio Hazer resistent vest"
Hazer

2018-09-21 02:21 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	desc = "Heavy plastic padding with some plasma to greaty redeuce radition.."
redeuce

2018-09-21 02:21 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	name = "Millitart grade physal armor vest.."
physal

2018-09-21 02:21 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	desc = "A well made vest that helps protect againts phycal harm. NT still cuts corrners when they can and uses less then optimal matitarls."
matitarls

2018-09-21 02:21 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	name = "Millitart grade physal armor vest."
Millitart

2018-09-21 02:22 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	name = "Engery protection padding."
Engery

2018-09-21 02:22 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	name = "Laser disbushen vest."
disbushen

2018-09-21 02:23 UTC, Poojawa commented on code/modules/research/techweb/all_nodes.dm
> +	design_ids = list("ballistic_vest", "melee_vest", "sec_ballistic_vest", "sec_melee_vest", "engery_vest",  "engery_vest")
engery

also it's listed twice.

all of these have the exact same icon, so you can't differentiate from them.

2018-09-21 02:23 UTC, Poojawa requested changes
Please please please spell check everything

also remove the '.' from names

2018-09-26 19:48 UTC, deathride58 commented
Conflicts

2018-09-26 21:50 UTC, closed without merging

2018-09-26 21:50 UTC, Trilbyspaceclone commented
...