Armor vest (Accessory)  - Best grammar and no conflicts (Maybe)
citadel-station/citadel-main pull request #7595
Opened 2018-09-27 01:39 UTC by Trilbyspaceclone

Changelogs]:
Adds in many different types of vest for each department to help people better survive in there 100% safe work!
Adds in a new node having more advance protection for sec!
List of vest added
Illegal Vest -Admin only ATM
Biohazard resistant vest
Bomb resistant vest
Fire resistant vest
Lava Land Vest
Miner Vest
Ballistic vest -Civ
Close Quarter Combat Vest -Civ
Military grade physal armor vest - Sec
[why]:
Accessory slot is never used actively unless your a miner, lets change that!

2018-09-28 01:30 UTC, deathride58 requested changes
There's undocumented changes. Did you commit to the wrong branch?

2018-09-28 01:30 UTC, deathride58 commented on code/datums/traits/negative.dm
> +	H.gain_trauma(phobia, TRAUMA_RESILIENCE_SURGERY)
???????????????

2018-09-28 01:30 UTC, deathride58 commented on code/controllers/subsystem/traumas.dm
> +						/obj/item/clothing/under/sexymime, /obj/item/toy/figure/mime, /obj/item/toy/crayon/mime, /obj/item/mecha_parts/mecha_equipment/weapon/ballistic/silenced, /obj/mecha/combat/reticence))
???????????

2018-09-28 06:56 UTC, Poojawa commented
@deathride58 they PR'd with their master branch

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A illegal vest with a mix of different metals and plastics."
a,e,i,o,u

all of these get "an" instead of 'a'

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A vest that was made to help protect miners from danger form all sorts of hazards. There are countless labels saying not to wash the vest with any acids."
"A vest that was designed to protect miners from a variety of hazards. A label advises against acid based cleaning agents."

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A advanced vest that was made to help protect miners from danger from all sorts of hazards. This one is acid-proof."
"An advanced protective vest designed for mining hazard mitigation."

It's not actually acid proof, just more resistant.

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A flimsy used to help protect against bullets. It's better then nothing... "
"A thin lining of Kevlar derivatives, designed to mitigate low power kinetic energy impacts."

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A flimsy vest with some plastic to protect against minor physical harm... "
"A thin lining of Kevlar derivatives, designed to mitigate low power brute force trauma."

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	name = "Military grade physal armor vest"
"Surplus Military physical armor vest"

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A well made vest that helps protect against physical harm. NT still cuts corners when they can and uses less then optimal materials."
"A surplus military armor lining mean for brute force mitigation."

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	name = "Military grade bullet armor vest"
"Surplus Military flak vest"

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A well made vest that helps protect against bullets. In the space days its still as basic as it always was."
"A surplus military lining for low power ballistic protection."

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	name = "Laser Dispersion Vest"
Energy dampening vest

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A vest made to protect and disperse the power of lasers without reflection."
A vest designed to mitigate low powered energy weapon impacts

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "Heavy plastic padding with some plasma to greatly reduce radiation."
A flammable vest designed to resist radiation.

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	name = "Fire resistant vest"
Flame Retardant vest

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A vest that can be placed over normal clothing to help protect against fire.."
A vest designed to improve the fire resistance of clothing.

2018-09-28 17:06 UTC, Poojawa commented on code/modules/clothing/under/armor.dm
> +	desc = "A heavy vest that can be attached to a jumpsuit to help protect against a blast."
A heavy, padded lining designed to mitigate explosive pressure.

2018-09-29 00:28 UTC, deathride58 submitted a review, later dismissed
The spelling errors add to the charm

Can be merged with kev's approval

2018-09-30 00:28 UTC, Poojawa approved these changes

2018-09-30 00:32 UTC, Poojawa reviewed
just these two missed things, then we're all good. <3

2018-09-30 00:32 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	name = "Engery protection padding"
Energy

2018-09-30 00:32 UTC, Poojawa commented on code/modules/research/designs/vest_designs.dm
> +	name = "Bomb resitsent vest"
resistant

2018-10-07 02:11 UTC, ghost requested changes
You're getting better at the spelling but I caught a few

2018-10-07 02:11 UTC, ursamedium commented on code/modules/clothing/under/armor.dm
> +	name = "Lava Land Vest"
Lavaland

2018-10-07 02:11 UTC, ursamedium commented on code/modules/clothing/under/armor.dm
> +	desc = "Padding used on suits to try to prevent shocks form being as lethal."
Form -> From

2018-10-07 02:11 UTC, ursamedium commented on code/modules/research/designs/vest_designs.dm
> +	desc = "BioHazer resistent vest that is easly attached to a jumpsuit."
Biohazard

2018-10-07 02:11 UTC, ursamedium commented on code/modules/research/designs/vest_designs.dm
> +	name = "Bomb resistsent vest"
Resistant

2018-10-07 02:11 UTC, ursamedium commented on code/modules/research/techweb/all_nodes.dm
> +	description = "High grade protection vests for Civ and Military presents.."
"for civilian and military presence"?

2018-10-07 03:48 UTC, deathride58 commented on code/modules/research/designs/vest_designs.dm
> +	name = "BioHazerd resistent vest"
Biohazard

2018-10-07 03:48 UTC, deathride58 commented on code/modules/research/designs/vest_designs.dm
> +	name = "Bomb resistantt vest"
resistant

2018-10-12 12:17 UTC, Trilbyspaceclone commented
There in Datum and I somehow don't have the branch anymore.

2018-10-30 22:58 UTC, closed without merging