[Ready]Silly Tips
citadel-station/citadel-main pull request #7684
Opened 2018-10-29 03:22 UTC by Trilbyspaceclone

[Changelogs]
100% needed, We should also update and add to CAS as well as other memey text strings
Side note: Drinking and coding is bad and leads to you not making a new branch. Leading to your master branch being messy!
[why]
Why not?

2018-10-30 22:32 UTC, deathride58 submitted a review, later dismissed

2018-10-30 22:32 UTC, deathride58 commented on strings/sillytips.txt
> +Play a Vampire, there over powerd and broken with no downsides that matter!
s/there over powerd/they're overpowered

2018-10-30 22:32 UTC, deathride58 commented on strings/sillytips.txt
> +You can make a Beepsky with E-swords that will murder people for not wareing there IDs!
s/wareing/wearing
s/there/their

2018-10-30 22:32 UTC, deathride58 commented on strings/sillytips.txt
> +You can make a Beepsky with Toy-E-Swords if you want. There like a cheaper Beepsky that will trip people and maybe shout on the sec channle about people its "Arresting"
s/There/It's
s/chanle/channel

2018-10-30 22:32 UTC, deathride58 commented on strings/sillytips.txt
> +Toxins Bombs are not the only way to get Rnd points. Tho no one will ever do any other method to get sci points...
s/Rnd/RnD
s/Tho no one/However, nobody

2018-10-30 22:32 UTC, deathride58 commented on strings/sillytips.txt
> +Plasma men are a powerful race with many perks! No really I sware! So what if they need a "ERP Plasma room" to fuck, who cares!
s/No really I sware!/No really, I swear!
s/if they need a/if they need an

2018-10-30 22:32 UTC, deathride58 commented on strings/sillytips.txt
> +As a Cargo Tech make sure to allways buy a tesla to sell back to CC. They love those those. Trust me!
s/allways/always

2018-10-30 22:32 UTC, deathride58 commented on strings/sillytips.txt
> +BZ stops or slows down Lings chem reaeration drastically, make sure to BZ flood the station when lings are confirmed!
s/reaeration/regeneration

2018-11-10 05:34 UTC, cebutris commented on strings/sillytips.txt
> +Mhelp is basically useless, and never used correctly. Being a Mentor just means that admins will do Mhelps for you and you get to learn the round type when someone asks you a basic question regarding
```suggestion
Mhelp is basically useless, and never used correctly. Being a Mentor just means that admins will do Mhelps for you and you get to learn the round type when someone asks you a basic question regarding their antag status.
```

2018-11-10 05:35 UTC, cebutris commented on strings/sillytips.txt
> +Toxins Bombs are not the only way to get RnD points. However, nobody one will ever do any other method to get sci points...
```suggestion
Toxins Bombs are not the only way to get RnD points. However, nobody will ever do any other method to get sci points...
```
```suggestion
Toxins Bombs are not the only way to get RnD points. However, no-one will ever do any other method to get sci points...
```
take your pick

2018-11-19 19:00 UTC, nik707 submitted a review, later dismissed
This looks ready to go.

2018-11-19 19:02 UTC, nik707 requested changes
Just fucking kidding

2018-11-19 19:03 UTC, nik707 requested changes

2018-11-19 19:03 UTC, nik707 commented on strings/sillytips.txt
> +There is a magic chem that truns people into Cat Girls/Boys. Its called "Felinid Mutation Toxin"!
truns > turns

2018-11-19 19:03 UTC, nik707 commented on strings/sillytips.txt
> +There is a magic chem that truns people into Cat Girls/Boys. Its called "Felinid Mutation Toxin"!
Fix this and I'll merge it.

2018-11-21 00:31 UTC, nik707 approved these changes

2018-11-21 00:31 UTC, merged