Security Stun Rebalancing
citadel-station/citadel-main pull request #7758
Opened 2018-11-21 19:30 UTC by Tupinambis

:cl: Tupinambis
balance: Stunbatons will now only cause knockdown and disarm if the target has already received at least 36 stamloss. This should prevent some instances where antagonists lose a battle before it even starts.
balance: Taser bolts now cost 250 energy instead of 200, meaning you can only fire 4 bolts before running out of charge.
/:cl:

[why]: Currently stunbatons serve as an instant win button, as getting hit once means you will get hit repeatedly until you reach stamcrit (there is little delay between hits). With this change fights, particularly melee fights, should be more interesting. Ambushing security should now give an actual advantage as well. 
Tasers would ultimately replace stunbatons as the "win button." Fortunately these are harder to hit, easier to dodge, and more limited in use. In order to avoid taser spam regardless, the cost of firing a taser bolts has been increased.

Notes: Telescopic batons and police batons are not affected, as they have a slower "firing rate" and are generally only used by high value targets (heads of staff).

2018-11-21 20:14 UTC, deathride58 commented
The stunbaton nerf here is extremely heavy-handed, and will only serve to make tasers the primary knockdown source from sec mains.A much better nerf would be to make the disarm effect on stunbatons only happen once a certain threshold of staminaloss has been reached, which can be done by adding a multiplier determined by staminaloss to the knockdown() value. For reference, knockdown() only disarms if a value over 80 is passed to it
There's no reason soap should be more effective on a first strike than a stunbaton, and this PR in its current state makes stunbatons weaker than soap on the first hit

2018-11-21 20:26 UTC, deathride58 requested changes

2018-11-21 20:26 UTC, deathride58 commented on code/game/objects/items/stunbaton.dm
> +		return 1
This return will stop the stutter, logging, component signal, chat message, and staminaloss from going through

2018-11-22 14:56 UTC, kevinz000 commented
Oh god the pain!

2018-11-22 14:57 UTC, kevinz000 commented
Tupinambis collapses, too exhausted to keep fighting...

2018-11-22 17:44 UTC, Tupinambis commented
> Oh god the pain!

My first version of this did kind of suck I admit, but as it is now, this nerf I feel is perfectly reasonable. Stunbatons are currently an instant win button. An armored sec player can shrug off 4 esword hits without falling into crit. A traitor with an esword will immediately lose the fight if they take one stunbaton hit. Obviously this does not just apply to eswords. Melee combat as a whole is useless against sec since you will just get stunbatonned and lose. And that is of course assuming sec didn't give urist mcgreyshit a stunbaton so he can validhunt you through maint. Stunbatons NEED a nerf, and this is honestly not that heavy handed of one all things considered.

And as a side note, I feel like shitting on this PR is completely unfounded when you never actually play as antags, and you are well known for powergaming your way to victory against antags. I play both security and antag, and honestly instantly winning with a single baton hit is not very satisfying as sec, and extremely frustrating as an antag.

2018-11-23 21:09 UTC, nik707 commented
I'm not gonna touch this one, main balance scares me. GL @kevinz000 and @deathride58

2018-11-25 19:00 UTC, Poojawa commented
🏷 Test Merge Candidate 

because, y'know. That's what it's there for.

2018-11-26 19:50 UTC, Nayser8 commented
The stun baton rebalance might be more interesting but the reducing taser shots is really uncalled for.
The "because people spam it" reasoning can be applied to anything, taser as is already has only enough shots to usually deal with one criminal and is easy to dodge due to range limitations, if disabler is not being used often, it's only because it's kind of bad right now, i personnally use it only to slow down people rather than take them down as it is it's all good for. The changes to stunbatons are really bad due to other antag items not being nerfed accordingly. Here's example: get a sleeping carp or CQC (especially sleeping carp) and you can essentially shit on sec without any effort.

2018-11-27 08:17 UTC, Poojawa commented
Sleeping carp needs a 10% failure chance on blocking things. Not even kung fu masters got away without a scratch in their movies.

2018-11-27 16:06 UTC, Nayser8 commented
When i said stunbaton rebalance might be more interesting, i misunderstood things, stunbaton is utterly useless for non-lethal apprehension, it's basicly a toolbox combined with push. If you need such hard "rebalances" of sec gear just to get a chance as an antag, i'm afraid problem does not lay within the ingame balance, problem is with you or in other words how that cheeky bastard pointing down at me after killing me in dark souls said - "Git Gud"

2018-11-28 23:16 UTC, deathride58 commented
General feedback on server seems to be pretty negative overall, gonna be letting this run testmerged on the server for a couple more days and advise people to actually leave their criticism on the PR instead of salting in OOC and LOOC

2018-11-28 23:27 UTC, Tupinambis commented
Alright, after valid complains, and me actually playing the game with the changes, the taser nerf is ultimately excessive and has been reverted. Stunbatons feel like they are now in a good place, and will remain for now.

2018-12-04 10:33 UTC, silicons requested changes
New baton values, without taking in account diminishing damage from having staminaloss:
140 stunforce:
14 base stamina damage
Existing stamina damage * 0.0115 * stunforce + 1 Knockdown() force
Knockdown 100 force disarm threshold
Soft stamcrit at 100. Prevents getting up or stamina-costing items, but does not force rest or stop movement.
Hard stamcrit at 140. Prevents movement in addition to the above and forces rest.
Not taking into account existant or nonexistant diminishing returns.
Proccall chain applies Knockdown() and then base.
DAMAGE PRECISION IS CLOSEST ROUND TO 0.1.
THEORETICAL CALCULATIONS:
First hit: Existing: 15 Apply: 14.0 base + 1 ds Knockdown() translating into 0.25 stamina Damage: 14.25 --> 14.3 Total: 14.3
Second hit: Existing: 14.3 Apply: 14.0 base + 24.023 Knockdown() translating into 6.00575 stamina. Damage: 20.00575 --> 20.0 Total: 34.3
Third hit: Existing: 34.3 Apply: 14.0 base + 56.223 Knockdown() translating into 14.05575 stamina. Damage: 28.05575 --> 28.1 Total: 62.4
Fourth hit: Existing: 62.4 Apply: 14.0 base + 101.464 Knockdown() translating into 25.366 stamina. Damage: 39.366 --> 39.4 Total: 101.8
Fifth hit: Existing: 101.8 Apply: 14.0 base + 164.898 Knockdown() translating into 41.2245 stamina. Damage: 55.2245 --> 55.2 Total: 157.0

KNOCKDOWN: First hit.
DISARM: Fourth hit.
Soft stamcrit: Fourth hit.
Hard stamcrit: Fifth hit.

REALISTIC TESTING RESULTS WITH FRESH SPAWNED CARBON/HUMAN AND DEFAULT STUNBATON.

RAW RESULTS WITHOUT MOBS BEING PROCESSED AND NO CLICKDELAY
14.3
36.1
69.3
119.3
186.1

KNOCKDOWN: First hit
DISARM: Fourth hit
SOFT STAMCRIT: Fourth hit
HARD STAMCRIT: Fifth hit

REALISTIC TESTING RESULTS WITH PROCESSING AND CLICKDELAY
14.3
33.1
64.7
109.3
171.2

KNOCKDOWN: First hit
DISARM: Fourth hit
SOFT STAMCRIT: Fourth hit
HARD STAMCRIT: Fifth hit

Baton default cell 10000 charge, 1000 hitcost = 10 hits
Soft stamcrit capacity: 2 people
Hard stamcrit capacity: 2 people
Knockdown capacity: 10 people
Disarm capacity: 2 people

Note how knockdowns still happen on the first hit, and disarms only happen at fourth hit, which is already soft stamcrit?

With no undue offense, is this PR even rudimentarily tested
How can this kind of variance possibly not get caught in testing?

2018-12-04 12:43 UTC, Tupinambis commented
Ss13 code angers me

2018-12-04 12:43 UTC, closed without merging