Armory Standardization and more!
citadel-station/citadel-main pull request #7763
Opened 2018-11-24 18:32 UTC by Tupinambis

:cl: Tupinambis
add: New "armory" loot spawner has been added to every maps armory. Has a chance of spawning a taser, disabler, mini e-gun, or (most rare) a m1911.
tweak: The armory contraband spawner has been added to every map except omega, and features an expanded list of potential spawns, of which it will spawn two items from. Combat shotguns and stetchkins are now much rarer than they were before.
balance: All station armories with the exception of omega station have now been standardized to contain 3 hybrid tasers, 3 blaster rifles, 2 blaster carbines, and 2 riot shotguns with 4 rubber shot boxes, as well as two sets of riot armor and bulletproof armor (Delta features 2 sets of standard armor as well). Omega is a scaled down version of this.
/:cl:

[why]: This should hopefully bring more variety to the armory, and as a result more variety to rounds, while not giving too much power to sec. A benefit of standardization is that security on one map shouldn't be weaker on another map and vice versa. A large benefit of reducing round start security equipment on some maps, is that it should encourage security to order equipment from cargo (interdepartmental interaction and the risk of antagonists possibly intervening.)

2018-11-24 22:48 UTC, deathride58 requested changes

2018-11-24 22:48 UTC, deathride58 commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	pixel_y = 0
This increases memory usage and floods the travis output logs. You can safely remove it

2018-11-24 22:48 UTC, deathride58 commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	pixel_y = 0
Ditto

2018-11-24 22:48 UTC, deathride58 commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	pixel_y = 0
Ditto

2018-11-24 22:48 UTC, deathride58 commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	pixel_y = 0
Ditto

2018-11-24 22:48 UTC, deathride58 commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	pixel_y = 0
Ditto

2018-11-24 22:48 UTC, deathride58 commented on _maps/map_files/PubbyStation/PubbyStation.dmm
> +	pixel_y = 0
Ditto

2018-11-24 22:49 UTC, deathride58 commented
On one hand, this PR feels like sec nerfs for the sake of sec nerfs, but on the other hand, the existence of all that sec gear orderable from cargo needs an excuse to exist

2018-11-24 23:08 UTC, Tupinambis commented
> On one hand, this PR feels like sec nerfs for the sake of sec nerfs, but on the other hand, the existence of all that sec gear orderable from cargo needs an excuse to exist

This is also only a nerf for some stations. For others this was basically what was already there. And yes, if they want more order it from cargo. Eguns and such are actually very cheap and can even be ordered roundstart

2018-11-29 03:51 UTC, kevinz000 commented
@Tupinambis dragnets, tempgun, ion, and all those stuff still there yes?

2018-11-29 04:16 UTC, Tupinambis commented
@kevinz000 those weren't even touched, so yes.

2018-12-11 00:38 UTC, deathride58 approved these changes

2018-12-13 19:59 UTC, kevinz000 commented
Not a fan of this. Not all maps need to be the same and I don't feel this is necessary. Current balance works fine.

2018-12-14 19:47 UTC, Tupinambis commented
I have thought of a better way of going about this. Gonna involve more variety and a utilization of currently underused equipment.

2018-12-14 19:47 UTC, closed without merging