Buffs RPE and nerfs BSRPEs
citadel-station/citadel-main pull request #7766
Opened 2018-11-26 00:50 UTC by Trilbyspaceclone

[Changelogs]
RPE now holds 75 parts (25 more items)
BSRPEs now hold 250 parts (150 less)

[why]
QoL of RPEs making them hold more for t3/t2 upgrades before silver is gotten
BSRPEs holding 400 is insane and is more then double the parts it takes to max even delta

2018-11-26 11:22 UTC, kevinz000 commented
Against BSRPED :-1:

2018-11-26 17:48 UTC, improvedname commented
dont listen to kevinz hes a science main, he will cry about science nerfs its only natural

2018-11-27 03:12 UTC, Trilbyspaceclone commented
@improvedname 
900+ hours as sci

2018-11-29 03:47 UTC, silicons requested changes
yeah there's no reason to nerf bsrped, other than maybe them carrying too many power cells and other non tiny stock parts but that can be fixed separately

2018-11-30 00:14 UTC, Trilbyspaceclone commented
@kevinz000 300 parts meeting halfway

2018-11-30 06:50 UTC, silicons approved these changes

2018-11-30 06:50 UTC, merged