Cargo Hardsuit Packets as well as a pare of soft suits (DPO)
citadel-station/citadel-main pull request #7767
Opened 2018-11-26 05:29 UTC by Trilbyspaceclone

[Changelogs]
Basic hardsuits for each department only able to be unlocked via basic access to each department. Like how they are on station! - Drop pod only for these

[why]
Poly "WHO TOOK ALL THE HARDSUITS!!" 
Also Poly "WIRE SOLOS YOU LAZY BASTERS"
Medical "X Died in space"
Sec "Armory breached"
All antags ever that have space proofing I.e Xenos/blob/ninja/changling/nukies
"Lets hide in space to lick wounds and only have to deal with unarmored targets and or the 4 people that do if they get a capo suit and Hos suit"

2018-11-26 05:30 UTC, Trilbyspaceclone commented
@CitadelStationBot Fuck you

IDK about costs getting there for "Oh shit" problems like ninja or such mite want them 3000 or such for sec but not like to exspen so that people will get them

2018-11-26 05:32 UTC, lolman360 commented
softsuit crate already exists- there are two of them, actually. One's the plasmaman EVA suit pack for 4k and one's just softsuits for 2k (iirc). Both need EVA access to open, though.

2018-11-26 05:33 UTC, lolman360 commented
And Mk1 swat suits, which are armoured and cost 6k credits for 2.

2018-11-26 05:53 UTC, Trilbyspaceclone commented
@lolman360 Yep but there EVA access so those are ment for "Oh shit meteors everything is dieing no air!!!"
As well as not being armored like EVA suits.

2018-11-26 17:38 UTC, improvedname commented
swat suits arent insulated against tesla,

2018-11-29 03:48 UTC, silicons requested changes
no reason to make this drop pod only why

2018-12-01 03:51 UTC, nik707 commented
@kevinz000 give final word on this thanks

2018-12-05 02:14 UTC, silicons approved these changes

2018-12-05 02:14 UTC, merged