Makes Foam force magpistol's no longer fit on gloves slots
citadel-station/citadel-main pull request #7775
Opened 2018-11-28 00:48 UTC by Trilbyspaceclone

[Changelogs]
Removes mag pistols form being a belt slot witch was a gloves slot for some reason 

[why]
Fixes a harmless bug with a harmless solution

2018-11-28 23:31 UTC, deathride58 commented
I'm perplexed as to how the belt slot has any correlation with the gloves slot. Are you sure it wasn't adminbus?

2018-11-29 03:49 UTC, silicons requested changes
This is not the right fix.
If they're somehow wearable in glove slot something is more fucked than this thing being able to fit in belt.

2018-11-30 00:17 UTC, Trilbyspaceclone commented
@kevinz000 As stated in a bug report *You are pinged in* I have listed out the problem as well as the fact of issue and how removing its belt slot fixes this problem

2018-12-04 16:09 UTC, kevinz000 commented
@Trilbyspaceclone It's still not the right fix and I think it's better to wait for the right fix than merge something to bandaid over the problem potentially ignoring worse issues down the line.

2018-12-04 20:12 UTC, closed without merging