Added a new carpet
citadel-station/citadel-main pull request #7783
Opened 2018-12-02 04:27 UTC by R3dtail

Worked on adding a new carpet.  It isn't -finished- yet and Trilby is going to help look over what I've done so I can make this work.

[Changelogs]: # carpet_red.dmi .  A new carpet added that's just a recolor of carpet_black.dmi.  Comes with its own unique icon/tile in tiles.dmi .  

:cl: optional name here
add: Added a new carpet.  Red!  Also added said carpet to the Premium Carpet crate from the cargo supply console.  Trilby said she'd take care of the crafting recipe.

/:cl:

[why]: # 

I wanted more carpets added to the game.  I wanted to test to see if I could do it, and through the assistance of many people, I managed to make it happen.  More importantly, I wanted to increase the options available to decorate with.

2018-12-02 04:43 UTC, nik707 requested changes
fix

2018-12-02 04:43 UTC, nik707 commented on code/__HELPERS/icons.dm
> +    All alpha values are set to 255 throughout the icon. Transparen pixels become black, or whatever background color you specify.
??

2018-12-02 17:12 UTC, R3dtail commented on code/__HELPERS/icons.dm
> +    All alpha values are set to 255 throughout the icon. Transparen pixels become black, or whatever background color you specify.
I uh.  I don't actually know what happened there.

2018-12-03 03:51 UTC, nik707 approved these changes

2018-12-03 03:52 UTC, merged