PDA hand Headset nodes!
citadel-station/citadel-main pull request #7792
Opened 2018-12-06 22:14 UTC by Trilbyspaceclone

[Changelogs]
Adds in most PDA cards into Rnd tech webs and such!
Adds in many headset keys for Rnd tech webs and such
3 nodes for PDAs 
2 nodes for Headsets

[why]
Most PDAs cards are not used at all! Maybe mainstreaming them will see more use.
Head set keys often get lost/stolen/or all gone do to reasons. Thus this new tech web node set will fix that!

2018-12-06 23:05 UTC, Trilbyspaceclone commented
Triv rethink*

2018-12-07 01:58 UTC, Trilbyspaceclone commented
REEEEE

2018-12-07 03:35 UTC, nik707 requested changes

2018-12-07 03:35 UTC, nik707 commented on code/modules/research/designs/misc_designs.dm
> +	name = "Sci cription Key"
All mentions of "cription" to "encryption"

2018-12-07 03:35 UTC, nik707 commented on code/modules/research/designs/misc_designs.dm
> +	desc = "A headset key for sci channle."
all mentions of "channle" to "channel"

2018-12-07 03:35 UTC, nik707 commented on code/modules/research/designs/misc_designs.dm
> +/datum/design/headset_rob
Tbh a robotic encryption key being printable seems uhhhhhhhhhhhhhhhhhhhhhhhhh nuts

2018-12-07 03:35 UTC, nik707 commented on code/modules/research/techweb/all_nodes.dm
> +	description = "Data chips to place in PDAs for more functions. These have even more fuctions then before!"
then to than

2018-12-07 03:35 UTC, nik707 commented on code/modules/research/techweb/all_nodes.dm
> +	description = "DELUXE Data chips to place in PDAs for more functions. Ment for Heads and higher ranking crew."
Ment to Meant

2018-12-07 03:35 UTC, nik707 commented on code/modules/research/techweb/all_nodes.dm
> +	description = "Privet channles that people use."
Private channels

2018-12-07 03:35 UTC, nik707 commented on code/modules/research/techweb/all_nodes.dm
> +	description = "Headset keys that incrip more then one channle."
encrypt more than one channel.

2019-01-03 12:42 UTC, kevinz000 commented
I don't think most of these are something we want spam-built, sorry.

2019-01-03 12:42 UTC, closed without merging