[Ready] Russian, NT, Synda ammo tech nodes
citadel-station/citadel-main pull request #7806
Opened 2018-12-09 20:41 UTC by Trilbyspaceclone

[Changelogs]
Brakes up Ballistic tech and Illegal Ballistic tech into 3 new nodes!
NT has .45 and all adv WT-550 ammo
Russian has clips, 9mm, n762
Synda has all 10mm and .357
[why]
Russian guns are mega rare, so we should be able to make ammo for them do to them being on the "To few to use"
NT guns shouldn't be illegal and helps brake down the WT-550 into more then on node
Synda guns are uncommon and should be able to get some ammo or such.
Autolathen shouldn't be able to print out speed loaders for such a high damg gun-s

2018-12-10 03:05 UTC, Trilbyspaceclone commented
@kevinz000, I dont understand the error im getting with triv

2018-12-11 16:33 UTC, Tupinambis commented
You are going to have to decrease syndie revolver ammo/revolver itself price then, because otherwise it won't ever be worth it.

2018-12-12 03:27 UTC, silicons requested changes
This is horrible horrible balance wise.
Just stop.

2018-12-12 03:27 UTC, silicons commented on code/modules/research/designs/autolathe_designs.dm
> -/datum/design/a357
No.

2018-12-12 03:27 UTC, silicons commented on code/modules/research/designs/weapon_designs.dm
> +	materials = list(MAT_METAL = 60000)
No

2018-12-12 03:27 UTC, silicons commented on code/modules/research/designs/weapon_designs.dm
> +	materials = list(MAT_METAL = 600000, MAT_TITANIUM = 100000)
What the fuck

2018-12-12 03:27 UTC, silicons commented on code/modules/research/designs/weapon_designs.dm
> +/datum/design/deagle
Stop

2018-12-12 03:27 UTC, silicons commented on code/modules/research/techweb/all_nodes.dm
> -	design_ids = list("mag_oldsmg", "mag_oldsmg_ap", "mag_oldsmg_ic")
No.

2018-12-12 03:27 UTC, silicons commented on code/modules/research/techweb/all_nodes.dm
> +/datum/techweb_node/oldguns
Just stop.

2018-12-12 03:27 UTC, silicons commented on modular_citadel/code/modules/research/techweb/all_nodes.dme.dm
> -	. = ..()
No.

2019-01-08 20:13 UTC, closed without merging