Lowers threat level of magical hats from 6 to 4 for securitron threat assessment
citadel-station/citadel-main pull request #7808
Opened 2018-12-11 09:07 UTC by kevinz000

-_-

2018-12-14 09:25 UTC, lolman360 commented
based pr

2018-12-15 21:20 UTC, nik707 approved these changes

2018-12-15 21:20 UTC, nik707 commented
haha get fucked idiot fix this

2018-12-15 21:21 UTC, nik707 requested changes
fix conflict

2018-12-16 07:31 UTC, Poojawa commented
i ded

2018-12-18 03:29 UTC, Poojawa commented on code/modules/mob/living/carbon/human/human.dm
> +
You should really just make your anime hat a different item, then you wouldn't need to buff syndicates and wizards

2018-12-20 08:31 UTC, deathride58 requested changes
fix the line endings plz

2019-01-03 12:45 UTC, closed without merging