New adv surgery tools!
citadel-station/citadel-main pull request #7879
Opened 2019-01-02 06:48 UTC by Trilbyspaceclone

[Changelogs]
Adds a new set of surgery tools that are not as good as augmented tools
New node that holds the tools as well as drapes and the basic medkit

[why]
Medkits are for Medibot army
drapes and tools so that people don't need augmented tools to be faster.
Augmented tools are still faster and will always be with you, not taking space in your bag. Its a nice middle ground

2019-01-03 12:11 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "Medical Kit"
Empty Medkit

2019-01-03 12:29 UTC, Ragolution requested changes

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "Medical Kit"
```suggestion
	name = "Empty Medkit"
```

So it doesn't get confused with full ones.

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "Medical Kit"
Also seems as if this recipe would be better put into the autolathe.

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +/datum/design/drapes
Drapes also really belong in the autolathe and not the protolathe

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	desc = "Retracts stuff. This one has been made of silver and gold, clearly making it better at retracting!"
```suggestion
	desc = "A high-class, premium retractor, featuring precision crafted, silver-plated hook-ends and an electrum handle."
```
Or whatever. Just a suggestion.

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "Advanced retractor"
```suggestion
	name = "Advanced Retractor"
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "advanced hemostat"
```suggestion
	name = "Advanced Hemostat"
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	desc = "You think you have seen this before. But not as golden or lustrous as this one..."
```suggestion
	desc = "An exceptionally fine pair of arterial forceps. These appear to be plated in electrum and feel soft to the touch."
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "advanced cautery"
```suggestion
	name = "Electrocautery" //This is based on real-life science.
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	desc = "This stops bleeding. This cautery has a exstended nose with a golden tip at the end."
```suggestion
	desc = "This stops bleeding. This cautery has a extended nose with a golden tip at the end."
```

Fix typo

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	desc = "This stops bleeding. This cautery has a exstended nose with a golden tip at the end."
Alternatively:
```suggestion
	desc = "A high-tech unipolar Electrocauter. This tiny device contains an extremely powerful microbattery that uses arcs of electricity to painlessly sear wounds shut. It seems to recharge with the user's body-heat. Wow!"
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "advanced surgicaldrill"
```suggestion
	name = "Advanced Surgical Drill"
```
or
```suggestion
	name = "Surgical Autodrill"
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	desc = "You can drill using this item. It has a damion tip at the end of its' golden drill."
```suggestion
	desc = "You can drill using this item. It has a diamond tip at the end of its golden drill."
```
or
```suggestion
	desc = "With a diamond tip and built-in depth and safety sensors, this drill alerts the user before overpenetrating a patient's skull or tooth. There also appears to be a disable switch."
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "advanced scalpel"
```suggestion
	name = "Advanced Scalpel"
```
or
```suggestion
	name = "Precision Scalpel"
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	desc = "Cut, cut, and once more cut now with a golden eage. Clearly made of mostly silver yet as you pick it up it feels lighter then normal."
```suggestion
	desc = "A perfectly balanced electrum scalpel with a silicon-coated edge to eliminate wear and tear."
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	name = "advanced circular saw"
```suggestion
	name = "Diamond-Grit Circular Saw"
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	desc = "For heavy duty cutting now with a damion eage saw!"
```suggestion
	desc = "For those Assistants with REALLY thick skulls."
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/techweb/all_nodes.dm
> +	description = "New faster and lighter surgical tools made of rare metals and gems."
```suggestion
	description = "Refined and improved redesigns for the run-of-the-mill medical utensils."
```

2019-01-03 12:29 UTC, Ragolution commented on code/modules/research/techweb/all_nodes.dm
> +	description = "New faster and lighter surgical tools made of rare metals and gems."
Or whatever.

2019-01-03 12:38 UTC, silicons requested changes
most of what rags said

2019-01-03 12:46 UTC, Ragolution commented on code/modules/research/designs/medical_designs.dm
> +	desc = "For heavy duty cutting now with a damion eage saw!"
This one is my favourite.

2019-01-03 13:23 UTC, Ragolution requested changes
Mirrors changes made to medical_designs.dm

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	name = "Advanced retractor"
```suggestion
	name = "Advanced Retractor"
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	desc = "Retracts stuff. This one has been made of silver and gold, clearly making it better at retracting!"
```suggestion
	desc = "A high-class, premium retractor, featuring precision crafted, silver-plated hook-ends and an electrum handle."
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	desc = "You think you have seen this before. But not as golden or lustrous as this one..."
```suggestion
	desc = "An exceptionally fine pair of arterial forceps. These appear to be plated in electrum and feel soft to the touch."
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	name = "advanced hemostat"
```suggestion
	name = "Advanced Hemostat"
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	name = "advanced cautery"
```suggestion
	name = "Electrocautery"
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	desc = "This stops bleeding. This cautery has a exstended nose with a golden tip at the end."
```suggestion
	desc = "A high-tech unipolar Electrocauter. This tiny device contains an extremely powerful microbattery that uses arcs of electricity to painlessly sear wounds shut. It seems to recharge with the user's body-heat. Wow!"
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	desc = "You can drill using this item. It has a damion tip at the end of its' golden drill."
```suggestion
	desc = "With a diamond tip and built-in depth and safety sensors, this drill alerts the user before overpenetrating a patient's skull or tooth. There also appears to be a disable switch."
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	name = "advanced scalpel"
```suggestion
	name = "Precision Scalpel"
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	desc = "Cut, cut, and once more cut now with a golden eage. Clearly made of mostly silver yet as you pick it up it feels lighter then normal"
```suggestion
desc = "A perfectly balanced electrum scalpel with a silicon-coated edge to eliminate wear and tear."
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	name = "advanced circular saw"
```suggestion
	name = "Diamond-Grit Circular Saw"
```

2019-01-03 13:23 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	desc = "For heavy duty cutting now with a damion eage saw!"
```suggestion
	desc = "For those Assistants with REALLY thick skulls."
```

2019-01-03 13:24 UTC, Ragolution requested changes
Forgot this one.

2019-01-03 13:24 UTC, Ragolution commented on code/modules/surgery/tools.dm
> +	name = "advanced surgical drill"
```suggestion
	name = "Surgical Autodrill"
```

2019-01-04 00:51 UTC, Ragolution commented
Looks fine if @kevinz000 thinks it passes Balance.

2019-01-04 00:52 UTC, Ragolution approved these changes
Looks fine if @kevinz000 thinks it passes Balance.

2019-01-08 10:36 UTC, silicons approved these changes

2019-01-08 10:36 UTC, merged