Makes paper work for cargo to do for spare credits!
citadel-station/citadel-main pull request #7924
Opened 2019-01-12 00:01 UTC by Trilbyspaceclone

[Changelogs]
Adds in Completed Paper work worth 50 credits to sell back to NT
Adds in Incomplete Paper work witch if you try to sell back will cost you 500 credits!
Adds in a new crafting recipe that will make one Completed paper work but costs 2 incomplete paper work and a fountain pen
Brand new crate holding the goodies to make 5 sets of Completed Paper work with two fountains pens to spare!

[why]
Realism.
Spare way for cargo to get small amounts of quick cash for legit doing there job.

2019-01-12 06:16 UTC, Ragolution commented
Why a fountain pen?

2019-01-12 08:07 UTC, Ragolution requested changes
Seems that way.

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/exports/manifest.dm
> +	unit_name = "retruned late paperwork"
```suggestion
	unit_name = "returned incorrect paperwork"
```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/order.dm
> +	name = "Undone Paper work"
```suggestion
	name = "Incomplete Paperwork"
```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/order.dm
> +	desc = "Undone paper work that has been left undone for freelancers to complete."
```suggestion
	desc = "These should've been filled out four months ago! Unfinished grant papers issued by Nanotrasen's finance department. Complete this page for additional funding."
```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/order.dm
> +	name = "Done Paper work"
```suggestion
	name = "Finished Paperwork"
```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/order.dm
> +	desc = "Paper work that has been completed, has a nice pen attached to the papers making sure they don't become messy well in travel."
```suggestion
	desc = "A neat stack of filled-out forms, in triplicate and signed. Is there anything more satisfying? Make sure they get stamped."
```
Would be nice if we could do this with a clipboard, instead, honestly.

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/packs.dm
> +					/obj/item/storage/box/fountainpens) // Two spare pens just in case
```suggestion

```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/crafting/recipes.dm
> +	reqs = list(/obj/item/pen/fountain = 1,
```suggestion
	reqs = list(/obj/item/clipboard = 1,
```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/exports/manifest.dm
> +/datum/export/paperwork_correct
```suggestion
/datum/export/paperwork_incorrect
```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/exports/manifest.dm
> +/datum/export/paperwork_correct
I really hope you tested this. :(

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/packs.dm
> +	desc = "Need a little more credits for that bike for little Timmy? Well I'm willing to pay ya for some accounting that needs to get done. I'll send ya umm ten copies of some paper work and a fountai
```suggestion
	desc = "The Nanotrasen Primary Bureaucratic Database Intelligence (PDBI) reports that the station has not completed its funding and grant paperwork this solar cycle. In order to gain further funding, your station is required to fill out (10) ten of these forms or no additional capital will be disbursed. We have sent you ten copies of the following form and we expect every one to be up to Nanotrasen Standards." // Disbursement. It's not a typo, look it up.
```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/cargo/packs.dm
> +	crate_name = "paper work"
```suggestion
	crate_name = "Paperwork"
```

2019-01-12 08:07 UTC, Ragolution commented on code/modules/crafting/recipes.dm
> +					/obj/item/paper/fluff/jobs/cargo/manifest/paperwork = 2)
```suggestion
					/obj/item/paper/fluff/jobs/cargo/manifest/paperwork = 2, /obj/item/pen = 1)
```

2019-01-20 08:03 UTC, deathride58 requested changes

2019-01-20 08:03 UTC, deathride58 commented on code/modules/cargo/packs.dm
> +	desc = "The Nanotrasen Primary Bureaucratic Database Intelligence (PDBI) reports that the station has not completed its funding and grant paperwork this solar cycle. In order to gain further funding
According to the description, there's supposed to be 10, but there's only actually nine in the crate

2019-01-20 08:03 UTC, deathride58 commented on code/modules/crafting/recipes.dm
> +	reqs = list(/obj/item/pen/fountain = 1,
Requiring fountain pens specifically is a little silly
```suggestion
	reqs = list(/obj/item/pen = 1,
```

2019-01-22 00:46 UTC, deathride58 approved these changes

2019-01-22 00:46 UTC, merged