Adds the abilty to make 3 lesser race tonics
citadel-station/citadel-main pull request #7932
Opened 2019-01-13 17:46 UTC by Trilbyspaceclone

[Changelogs]
Adds feline race toxic crafting with
mind breaker = 1
ammonia = 1
water" = 1
aphro = 10
with a heat needed required_temp = 450

Adds Moffman toxic crafting with
liquid dark matter = 1
ammonia = 1
lithium = 1
with a heat needed required_temp = 320

Adds Shady toxic crafting with
liquid dark matter = 5
synaptizine = 10
oculine = 1
with a heat needed required_temp = 600

[why]
Bad memes and likely never really will be used

2019-01-13 18:17 UTC, deathride58 requested changes
Make them require at least mutation toxin, just like the old mutation toxins used to. [Here's a chem recipe list showing all of the old mutation toxin recipes, for reference](https://tgstation13.org/wiki//index.php?title=Guide_to_chemistry&oldid=20387)

2019-01-13 22:31 UTC, LeonDuvall commented
Liquid dark matter detonates immediately upon mixing, making those recipes insanely difficult to craft.

2019-01-20 16:24 UTC, MimicFaux commented
> Liquid dark matter detonates immediately upon mixing, making those recipes insanely difficult to craft.

Just stabilize it

2019-01-22 00:47 UTC, deathride58 approved these changes

2019-01-22 00:47 UTC, merged