Adds 2 new quirks! Quick step and Light Sensitivity
citadel-station/citadel-main pull request #7933
Opened 2019-01-13 21:18 UTC by Trilbyspaceclone

[Changelogs]
2 New Quirks!
Light Sensitivity - Well in light you feel bad give 1 point
Quick step - You walk faster cost 2 points

[why]
Was asked to make these works and Cydia helped make them!
K5 and Cydia helped me make them! What good friends,

2019-01-13 21:28 UTC, king5327 commented
In all fairness, the speed boost could be a bit smaller.

2019-01-13 21:31 UTC, deathride58 submitted a review, later dismissed

2019-01-13 21:31 UTC, deathride58 commented on code/modules/mob/living/carbon/human/species.dm
> +		. -= 0.5
No. Especially not with the current tile-based & delay-based movement system.

2019-01-13 21:32 UTC, deathride58 commented
A better alternative to a flat movement speed increase across the board would be to just increase walking speed a smidge when the trait's present

2019-01-13 22:35 UTC, LeonDuvall commented
I like the idea of these in theory, though with the effects mood has on gameplay and the fact that sanity comes into play, I would think that light sensitivity(depending on how bright the light needs to be) would be a bit too large of an impediment for just one point.

2019-01-13 23:12 UTC, Ghommie commented on code/modules/mob/living/carbon/human/species.dm
> +	if (H.m_intent == MOVEMENT_INTENT_WALK && has_trait("quickie_feet"))
`if (H.m_intent == MOVEMENT_INTENT_WALK && H.has_trait(TRAIT_SPEEDY_STEP))`

Also check if this isn't overridden by the subtypes.

2019-01-13 23:53 UTC, deathride58 commented on code/modules/mob/living/carbon/human/species.dm
> +	if (H.m_intent == MOVEMENT_INTENT_WALK && H.has_trait(TRAIT_SPEEDY_STEP))
```suggestion
	if (H.m_intent == MOVE_INTENT_WALK && H.has_trait(TRAIT_SPEEDY_STEP))
```

2019-01-19 23:49 UTC, MimicFaux commented
To be clear, is this increasing walk speed, or run speed slightly?
One would be pleasant tweak, the other would be almost universally taken.

2019-01-20 07:48 UTC, deathride58 commented
It's a walk speed increase, run speed is unaffected

2019-01-20 20:12 UTC, Ragolution requested changes

2019-01-20 20:12 UTC, Ragolution commented on code/datums/traits/good.dm
> +	desc = "You walk with a bounce in you'r step; Making you slightly faster then most other crewmembers."
```suggestion
	desc = "You walk with determined strides, and out-pace most people when walking."
```

2019-01-20 20:12 UTC, Ragolution commented on code/datums/traits/good.dm
> +	gain_text = "<span class='notice'>You feel quick on your feet.</span>"
```suggestion
	gain_text = "<span class='notice'>You feel determined. No time to lose.</span>"
```

2019-01-20 20:12 UTC, Ragolution commented on code/datums/traits/good.dm
> +	lose_text = "<span class='danger'>You feel a little more slow.</span>"
```suggestion
	lose_text = "<span class='danger'>You feel less determined. What's the rush, man?</span>"
```

2019-01-20 20:12 UTC, Ragolution commented on code/datums/traits/negative.dm
> +	desc = "Any type of light just makes you feel uneasy, it's hard to keep in a good mood when your sink itches and eyes burn from light!"
I too hate when my sink itches.

2019-01-20 20:12 UTC, Ragolution commented on code/datums/traits/negative.dm
> +	desc = "Any type of light just makes you feel uneasy, it's hard to keep in a good mood when your sink itches and eyes burn from light!"
```suggestion
	desc = "Bright lights irritate you. Your eyes start to water, your skin feels itchy against the photon radiation, and your hair gets dry and frizzy. Maybe it's a medical condition. If only Nanotrasen was more considerate of your needs..."
```

2019-01-20 20:12 UTC, Ragolution commented on code/datums/traits/negative.dm
> +/datum/quirk/lightless
Needs gain/loss messages

2019-02-06 02:12 UTC, silicons requested changes
Put the check in base mob movement and use the movement modification system if it exists here.

2019-02-22 14:11 UTC, silicons approved these changes

2019-02-22 14:11 UTC, merged