Adds new huds that help correct vision.
citadel-station/citadel-main pull request #7943
Opened 2019-01-17 00:49 UTC by Trilbyspaceclone

[Changelogs]
Adds 2 new nodes for all the new goggles and huds with correction lens
A counter part to each type of HUDs that are ***NOT NV*** with a prescription lens
A brand new cargo crate that has 2 Sunglasses that are also sec huds for 2500
Miner gar glasses now are prescription lens do to Power Creep
[why]
QoL and basic things for people that have neg traits and get fucked over by it. 
After all we have NV prescription goggles lets branch it out!

2019-01-17 07:45 UTC, deathride58 requested changes

2019-01-17 07:45 UTC, deathride58 commented on code/modules/clothing/glasses/hud.dm
> +/obj/item/clothing/glasses/hud/security/sunglasses/prescription
No.

2019-01-17 07:45 UTC, deathride58 commented on code/modules/cargo/packs.dm
> +/datum/supply_pack/security/prescription_sec_sung
No.

2019-01-18 04:49 UTC, LeonDuvall commented
I'd rather see these on the same node that unlocks the original item, as nightvision does. Or on the Nightvision node itself, as the added nodes bloat points.

2019-01-20 07:58 UTC, deathride58 submitted a review, later dismissed

2019-01-20 07:58 UTC, deathride58 commented on code/modules/clothing/glasses/hud.dm
> +/obj/item/clothing/glasses/hud/health_prescription
Make this a subtype of `/obj/item/clothing/glasses/hud/health`

2019-01-20 07:58 UTC, deathride58 commented on code/modules/clothing/glasses/hud.dm
> +/obj/item/clothing/glasses/hud/diagnostic_prescription
Make this a subtype of `/obj/item/clothing/glasses/hud/diagnostic`

2019-01-20 07:58 UTC, deathride58 commented on code/modules/clothing/glasses/hud.dm
> +/obj/item/clothing/glasses/hud/security_prescription
Make this a subtype of `/obj/item/clothing/glasses/hud/security`

2019-02-06 02:09 UTC, silicons approved these changes

2019-02-06 02:09 UTC, merged