Adds coin items and hacked items to all wardrobes
citadel-station/citadel-main pull request #7975
Opened 2019-02-01 22:11 UTC by Trilbyspaceclone

[Changelogs]
So much...
[why]
I love making use of coins and adding in this stuff shouldnt be to power braking. A lot of it is just joke items or easily made. Well other items can be coin sinks for people to easily get basic items - Kinda like bottle water being over $3 but tap is free

2019-02-04 06:40 UTC, Ragolution requested changes
I used the word 'hugbox' a lot here, and I want to be very clear what I mean when I say 'hugbox'.

Hugbox, in this usage case, refers to the fact that you are giving people less reasons to leave their department and stay in their safe little 'hugbox'. It reduces interdepartmental activity and encourages people to stay where they're nice and safe and not let themselves be vulnerable.

I am also a purist when it comes to wardrobes as they should only contain items that are *worn* by a character. Headsets, HUDs, masks, etc are fine, but adding extinguishers seems really goofy when there's already other machines that can lay host to interesting items. Furthermore, part of what makes Wardrobes shitty to hack or use a coin on is... they just provide clothes.

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	contraband = list(/obj/item/storage/box/rxglasses = 1,
Why? You can start with these on your loadout.

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	premium = list(/obj/item/storage/box/stockparts/basic = 1)
No please. The toolboxes should be Premium, considering they have tools already inside of them. The stock parts box shouldn't even be on this list. THIS IS A WARDROBE. You should put the toolboxes in the toolmate.

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	premium = list(/obj/item/extinguisher/advanced = 2)
More gear that doesn't make sense in the wardrobe. Base Extinguishers as contraband?? Why even bother??? Move Advanced to contraband and maybe it's worth actually hacking it but why is it in a WARDROBE!!!

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	contraband = list(/obj/item/storage/box/stockparts/basic = 1)
Why is this contraband in the Roboticist Wardrobe but Premium in the Engineer's???? Still doesn't belong in a wardrobe.

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	premium = list(/obj/item/storage/box/stockparts/basic = 2)
???? WHY

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	contraband = list(/obj/item/storage/bag/bio = 2)
I would make this premium but otherwise yeah that's cool.

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	premium = list(/obj/item/reagent_containers/glass/bottle/mutagen = 2)
Hugbox

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	contraband = list(/obj/item/stack/ore/glass = 1)
One single sheet of glass? Why?

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	premium = list(/obj/item/clothing/head/crown/fancy = 1)
WHY IN THE MINING WARDROBE?

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +						/obj/item/reagent_containers/food/snacks/monkeycube = 3)
hugbox, also doesn't belong in a wardrobe

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	premium = list(/obj/item/storage/box/lights/mixed = 2,
Why would the Chef need lights? Why is this in a wardrobe?

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	contraband = list(/obj/item/storage/box/condimentbottles = 3,
doesn't belong in a wardrobe but would be a great addition to the kitchenmate or whatever it's called

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +					/obj/item/reagent_containers/spray/cleaner = 1)
hugbox

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +						/obj/item/clothing/under/maid = 1)
Why even make this contraband?

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +					/obj/item/reagent_containers/spray/cleaner = 1)
doesn't belong in a wardrobe but otherwise a great addition to the janitor vendor

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	premium = list(/obj/item/seeds/watermelon/holy = 1,
Hugbox. If anything, give him a melon keg.

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +						/obj/item/toy/crayon/spraycan = 2,
Ehhh debatable but alright

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +					/obj/item/reagent_containers/food/drinks/bottle/holywater = 2)
doesn't belong in a wardrobe but i guess where else do you put it for the chaplain

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	contraband = list(/obj/item/reagent_containers/dropper = 2)
Why is this contraband? Also doesn't _really_ belong in a wardrobe

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	premium = list(/obj/item/storage/box/monkeycubes = 1,
Hugbox

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +					  /obj/item/clothing/mask/muzzle = 1)
:+1:

2019-02-04 06:40 UTC, Ragolution commented on code/modules/vending/wardrobes.dm
> +	contraband = list(/obj/item/reagent_containers/dropper = 2,
not contraband-worthy also doesn't belong in a wardrobe

2019-02-05 03:54 UTC, Poojawa commented on code/modules/vending/wardrobes.dm
> +					/obj/item/reagent_containers/food/drinks/bottle/holywater = 2)
legit chaplains just use their holy book to make holy water, this is hugbox

2019-02-06 01:58 UTC, kevinz000 commented
I'd rather not have wardrobes and coin go in this direction, sorry.

2019-02-06 01:58 UTC, closed without merging