Update ion_storm.dm
citadel-station/citadel-main pull request #7980
Opened 2019-02-05 12:29 UTC by MediHound

:cl:
[Changelogs]: # Changes done to the Ion Storm event
add: Made Cyborgs be affected by Ion Storm Law Changes like AIs
/:cl:

[why]: # This makes Cyborgs be affected by Ion Storms and gives them Ion Laws.
Why this change? First of all, it was weird that AIs and small Bots get affected by Ion Storms, but Cyborgs didn't. Secondly, people were Metagaming that unsynced Borgs were safe. The emagging chance might be a bit high, compared to before, but a 20% chance for such a rare event isn't too much in my opinion.

2019-02-05 12:34 UTC, Poojawa commented
use :cl: : cl : without spaces

:cl: Alina
add: AI-less borgs are now susceptible to Ion storms, both law changes and potential emag effects.
/:cl:

2019-02-06 01:55 UTC, kevinz000 commented on code/modules/events/ion_storm.dm
> +	if(botEmagChance)
Let's not.

2019-02-06 01:57 UTC, silicons requested changes
Yeah uh don't buff the chances of emagging/law remove/shuffles and make sure it only works for unsynced cyborgs. No random cyborg emagging either.

2019-02-06 11:25 UTC, MediHound commented
Testing together with BlackMajor showed: AI Synced borgs get the same Laws AIs get, without losing sync. Multiple unsycned borgs can get different law changes.

2019-02-08 10:13 UTC, silicons approved these changes

2019-02-08 10:13 UTC, merged