More clown and hos/warden uplink only items
citadel-station/citadel-main pull request #8000
Opened 2019-02-14 22:07 UTC by Trilbyspaceclone

[Changelogs]
Dear god why
Clown HONK can now get a DNA injector that has the Clumsy gene
Warden and hos can get DNA injectors to remove Clumsy gene
Honk, Clown angets can now get HONK PINS
[why]
Clown pins are for clowns to use other traitor guns or lock out others form their own guns
Clown DNA are for clowns to work with a team if they are one, having their DNA injectors and such 
DNA fixing injector is for warden and hos to get something to combat clowns

2019-02-14 22:08 UTC, IrkallaEpsilon commented
Interesting idea, are the injectors instant? Is it fixable by genetics?

2019-02-14 22:53 UTC, Trilbyspaceclone commented
@IrkallaEpsilon Injectors are not instant and genetics cant fit it

2019-02-15 00:03 UTC, Ignari-Coldstorm commented on code/modules/uplink/uplink_items.dm
> +	desc = "A DNA injector that has been loaded with the clown gene that makes people clumsy. \
desc = "A DNA injector that has been loaded with the clown gene that makes people clumsy.

2019-02-15 00:05 UTC, Ignari-Coldstorm commented on code/modules/uplink/uplink_items.dm
> +	Making someone clumsy will allow them to use clown firing pins as well as Reverse Revolvers. For a laugh try useing this on HOS to see how many times they shoot themselfs in the foot!"
Making someone clumsy will allow them to use clown firing pins as well as Reverse Revolvers. For a laugh try using this on the HOS to see how many times they shoot themselves in the foot!"

2019-02-15 00:06 UTC, Ignari-Coldstorm commented on code/modules/uplink/uplink_items.dm
> +	desc = "HONK Looks like one of are angents got, got! \
desc = "HONK! Looks like one of our agents got got!

2019-02-15 00:07 UTC, Ignari-Coldstorm commented on code/modules/uplink/uplink_items.dm
> +	We got a barrle of laughs for you, HONK, we got a Mime DNA injector HONK! Use this on a clown HONK to make them not clusmy HONK!"
We got a barrel of laughs for you, HONK, we got a Mime DNA injector HONK! Use this on a clown HONK to make them not clumsy HONK!"

2019-02-15 00:08 UTC, Ignari-Coldstorm commented on code/modules/uplink/uplink_items.dm
> +	cost = 1 //If Hos or warden gets a uplink they should be able to get it for allmost free
cost = 1 //If Hos or warden gets an uplink they should be able to get it for almost free

2019-02-15 16:14 UTC, silicons requested changes
restricted items should be niche useful items and I fail to see the legitimate use of these DNA injectors.

2019-02-15 18:51 UTC, Trilbyspaceclone commented
@Trilbyspaceclone 
CLOWNUT trait lets them use their own firing pins
Buy sketchin, remove pin, add your own, Bam you can now use it without shooting your foot
*or*
Stun/KO sec, inject them, watch them now shoot their foot

2019-02-22 13:58 UTC, silicons requested changes
The clown punishment thing is just silly and doesn't need to be an uplink item
clumsy clown injector can stand to be 1-2 TC
Also, get rid of the undocumented changes of getting rid of surplus = 0, you should know better by now.

2019-02-28 00:18 UTC, silicons approved these changes

2019-02-28 00:18 UTC, merged