Makes transformation slings have a loundess of 3 factor
citadel-station/citadel-main pull request #8105
Opened 2019-03-10 17:32 UTC by Trilbyspaceclone

[Changelogs]
Now they will come up as ling in a basic test. Its a rather loud option in the first place!

[why]
Its obvs as fuck if a ling starts to do it, it fucks over other lings, and people that need it will likely allready be possive on the test so making it more amp to bomb is a + for them. Ling buff as a whole

2019-03-10 19:03 UTC, deathride58 requested changes

2019-03-10 19:03 UTC, deathride58 commented on code/modules/antagonists/changeling/powers/tiny_prick.dm
> +	loudness = 3
Inconsistent with other loudness values. If you want to buff its loudness, set it to 2 instead of making it an arbitrary 3

2019-03-10 19:03 UTC, deathride58 commented on code/modules/antagonists/changeling/powers/tiny_prick.dm
> +	helptext = "The victim will transform much like a changeling would. Does not provide a warning to others. Mutations will not be transferred, and monkeys will become human. This ability is somewhat l
Inconsistent with other loudness descriptions.

2019-03-13 19:19 UTC, Ragolution commented on code/modules/antagonists/changeling/powers/tiny_prick.dm
> +	helptext = "The victim will transform much like a changeling would. Does not provide a warning to others. Mutations will not be transferred, and monkeys will become human. This ability is somewhat l
larg

2019-03-21 19:14 UTC, deathride58 submitted a review, later dismissed
Loudness description is inconsistent with its actual loudness

2019-04-23 04:34 UTC, silicons approved these changes

2019-04-23 04:34 UTC, merged