Adds a shitty shuttle with some meteor defenses.
citadel-station/citadel-main pull request #8148
Opened 2019-03-20 01:50 UTC by Ragolution

Probably doesn't work but here we go anyway.

2019-03-21 00:10 UTC, Ragolution commented
WHAT'S A MAP COMPILER?

2019-03-21 03:42 UTC, Ghommie reviewed
Since you need to convert the map file to the `tgm` format anyway, because it's more robust against eventual conflicts..
https://tgstation13.org/wiki/Map_Merger#Manual_Use

2019-03-21 03:42 UTC, Ghommie commented on _maps/shuttles/emergency_stormrider.dmm
> +"a" = (/obj/structure/lattice,/obj/machinery/satellite/meteor_shield{active = 1},/turf/open/space/basic,/area/shuttle/escape)
Make a subtype of meteor_shield that toogles on Initialize() instead, so it can update icon, anchored status and its floaty animation.

2019-03-21 03:42 UTC, Ghommie commented on code/datums/shuttles.dm
> +	name = "Asteroid With Engines Strapped To It"
Some fluff you missed here.

2019-03-21 03:42 UTC, Ghommie commented on code/datums/shuttles.dm
> +	admin_notes = "An antag-bombers wet dream. But at least it stops meteors..."
It's bigger and sturdier than the  "Oh Hi Daniel", calling it an "antag-bomber wet dream" may be misleading, It's just a bit stripped down of furniture.

2019-03-21 04:53 UTC, Ragolution commented on code/datums/shuttles.dm
> +	name = "Asteroid With Engines Strapped To It"
Thanks.

2019-03-21 19:03 UTC, deathride58 requested changes
Use mapmerger

2019-04-01 01:32 UTC, deathride58 requested changes
MAPMERGER

2019-04-18 06:42 UTC, closed without merging