Adds rule 3 from the Lavaland Role Antag Policy to the ash walker spawn text
citadel-station/citadel-main pull request #8157
Opened 2019-03-21 07:21 UTC by izzyinbox

Hotel staff have an equivalent, and it's a problem that happens enough here that this can help change.

:cl: 
tweak: add additional flavor/rules spawn text to ashwalkers
/:cl:

2019-03-21 07:43 UTC, deathride58 requested changes
Modularization is no longer necessary on main

2019-03-21 07:46 UTC, deathride58 commented
Also tbqh this could probably be handled much better by simply making it so that ashwalkers are unable to safely survive within the station's environment by giving them working lungs, making their breathing tuned to match lavaland's atmosphere, increasing their body temperature, adjusting their temperature damage thresholds so that they take temperature damage on station, and adjusting their pressure damage thresholds so that they take pressure damage on station.

2019-03-21 12:35 UTC, Poojawa commented
o yeah I was gunna do that

at least the lung stuff, not the body temp fuckery

2019-05-21 07:01 UTC, kevinz000 commented
inactivity

2019-05-21 07:01 UTC, closed without merging