Give some blob things basic armor
citadel-station/citadel-main pull request #8242
Opened 2019-04-14 21:38 UTC by Trilbyspaceclone

[Changelogs]
Blob shields and factors have basic armor

[why]
Blobs are "To week" for later end game play when all of the station can print mag guns and such

2019-04-14 21:53 UTC, Trilbyspaceclone commented
why has this failed?

2019-04-15 05:29 UTC, Poojawa commented
Uhhhhhhhhhh what

blobs get armor depending on their chemical. you're better off porting the free chemical reroll PR than giving them baseline super armor

2019-04-20 23:31 UTC, silicons requested changes
No armor on shields, make it a separate PR.

2019-04-25 11:18 UTC, silicons approved these changes

2019-04-25 11:18 UTC, merged