Lowers pda sounds as well as make them respect ringer off
citadel-station/citadel-main pull request #8250
Opened 2019-04-16 03:44 UTC by Trilbyspaceclone

[Changelogs]
Makes all pda sounds softer and if ringer or silenced will no longer make the beeps and boops

[why]
Kev wanted to remove them!
Im not Lazy
This is legit tested by the by
Helping

2019-04-16 03:59 UTC, Poojawa requested changes

2019-04-16 03:59 UTC, Poojawa commented on code/game/objects/items/devices/PDA/PDA.dm
> +					playsound(src, 'sound/items/bikehorn.ogg', 15, 1)
unneeded change

2019-04-16 03:59 UTC, Poojawa commented on code/game/objects/items/devices/PDA/PDA.dm
> +					playsound(src, 'sound/misc/sadtrombone.ogg', 15, 1)
unneeded change

2019-04-16 04:17 UTC, deathride58 requested changes

2019-04-16 04:17 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +				playsound(src, 'sound/machines/terminal_select.ogg', 15, 1)
dont forget the silent checks

2019-04-16 04:17 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +		playsound(src, 'sound/machines/twobeep.ogg', 15, 1)
unneeded change, sound is already quiet enough

2019-04-16 04:17 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +			playsound(src, 'sound/machines/button4.ogg', 15, 1)
unneeded volume decrease, sound is already quiet enough

2019-04-16 04:17 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +			playsound(src, 'sound/machines/terminal_eject_disc.ogg', 15, 1)
unneeded change, sound is already quiet

2019-04-16 04:17 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +					playsound(src, 'sound/machines/terminal_eject_disc.ogg', 15, 1)
unneeded volume decrease, sound is already quiet

2019-04-16 04:17 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +				playsound(src, 'sound/machines/button.ogg', 15, 1)
unneeded volume decrease, sound is already quiet

2019-04-16 21:19 UTC, deathride58 submitted a review, later dismissed

2019-04-16 21:19 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +			playsound(src, 'sound/machines/button.ogg', 15, 1)
Sound is already quiet, volume change can be reverted. Also, this is a mechanical sound, making this mutable via a software toggle makes no logical sense

2019-04-16 21:19 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +			playsound(src, 'sound/machines/button.ogg', 15, 1)
Sound is already quiet, volume change can be reverted. Also, this is a mechanical sound, making this mutable via a software toggle makes no logical sense

2019-04-16 21:19 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +			playsound(src, 'sound/machines/terminal_eject_disc.ogg', 50, 1)
This is a mechanical sound, making this mutable via a software toggle makes no logical sense

2019-04-16 21:19 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +			playsound(src, 'sound/machines/button4.ogg', 50, 1)
This is a mechanical sound, making this mutable via a software toggle makes no logical sense

2019-04-16 21:19 UTC, deathride58 commented on code/game/objects/items/devices/PDA/PDA.dm
> +				playsound(src, 'sound/machines/button.ogg', 50, 1)
This is a mechanical sound, making this mutable via a software toggle makes no logical sense

2019-04-23 04:30 UTC, silicons approved these changes

2019-04-23 04:31 UTC, merged