New high alert ERT suits. Amber alert ERT is now high alert ERT too.
citadel-station/citadel-main pull request #8256
Opened 2019-04-17 13:36 UTC by Coolgat3

[Changelogs]:

:cl: Coolgat3
add: Added a better armor for Amber and Red alert ERT
tweak: Made Amber alert ERT spawn Red alert equipped ERT
imageadd: Added sprites for Amber/Red ERT armors and made muzzled, digitigrade leg, and lazy naga versions of those.
/:cl:

[why]: Alright so:
Adding the ERT is a cool thing, literally why not, I don't think there's any problem with that. They look cool, High alert ERTs should be armored more than the low alert ones, no?

Why would Amber spawn Red alert ERTs? Well, see. Amber alert is stupid, it is supposed to be something like code red, appearently? Or is it more towards blue? Literally what is amber alert? I feel like that alert is something of the likes of "We will all die!" While red is "We are all dying!" This is why I think Amber alert ERT should spawn Red alert ERT, We rarely have code red anymore because nobody is bothered to swipe the things, they rather just go amber and leave it be, therefore we never really see red alert ERT at all. I think making Amber alert ERT also a high alert response team is a good solution, besides, ERT is admin spawn so there's not really much talk about "oh yeah this is op" because an admin can choose whether to give that ERT those 2 pulse carbines and slightly better armor, right..?

So that'd be pretty much it, except the fact that making naga and taur sprites is literally the most damn terrible thing I've been put up against. I made the naga sprites only have the suit from waist up, so let's just all assume that ERT nagas have spaceproof tails until I get the vein to actually do it and manage to make it not look like utter garbage, because I am TERRIBLE at spriting characters and already spent like 5 hours on just doing the muzzles for the helmets, I shit you not.
Or if someone wants to do those version themself and are skilled in character spriting then hell, go ahead.

2019-04-19 18:09 UTC, Trilbyspaceclone requested changes

2019-04-19 18:09 UTC, Trilbyspaceclone commented on code/modules/clothing/spacesuits/miscellaneous.dm
> +	armor = list("melee" = 75, "bullet" = 60, "laser" = 60, "energy" = 60, "bomb" = 60, "bio" = 100, "rad" = 100, "fire" = 90, "acid" = 80)
Not even death armor gives that much laser armor.
I also think they should be fire proof or such

2019-04-23 04:38 UTC, silicons approved these changes

2019-05-29 20:48 UTC, Coolgat3 commented
Okay yeah fuck that i'm not fixing this conflict shit on a pc that takes fucking ages to launch dreammaker. The PR was fine when it was created and then something was created after it and was merged sooner, fucking this up. No thanks.

2019-05-29 20:48 UTC, closed without merging