New holy weapon: Ratvarian Spear with throw-jaunting
citadel-station/citadel-main pull request #8272
Opened 2019-04-21 02:56 UTC by kevinz000

10 seocnd cooldown, if it hits something within 14 tiles of you you teleport to it, otherwise it teleports to you and you pick it up in both cases if you can.

2019-04-21 07:31 UTC, Poojawa commented on code/game/objects/items/holy_weapons.dm
> +/obj/item/nullrod/ratvarian_spear
you added this in the middle of the scythe code.

2019-06-17 02:57 UTC, deathride58 requested changes

2019-06-17 02:57 UTC, deathride58 commented on code/game/objects/items/holy_weapons.dm
> +			to_chat(L, "<span class='boldwarning'>[src] materializes beneath you[picked_up? ", and you reflexively pick it up!" : ""]!</span>")
"The bronze spear materializes beneath you, and you reflexively pick it up!!"
```suggestion
			to_chat(L, "<span class='boldwarning'>[src] materializes beneath you[picked_up? ", and you reflexively pick it up" : ""]!</span>")
```

2019-06-17 02:57 UTC, deathride58 commented on code/game/objects/items/holy_weapons.dm
> +		to_chat(L, "<span class='boldwarning'>[src] clicks, its whirring growing softer. You probably won't be able to utilize its throw jaunt for [throw_special_cooldown/10] seconds!</span>")
time for micro-optimizations, grmbl grmbl
```suggestion
		to_chat(L, "<span class='boldwarning'>[src] clicks, its whirring growing softer. You probably won't be able to utilize its throw jaunt for [throw_special_cooldown*0.1] seconds!</span>")
```

2019-06-21 15:46 UTC, Ghommie commented
This reminds me of the old Sky Bulge (yes, it was its actual name) pogo-spear.

2019-10-22 09:07 UTC, closed without merging