fixed the warp whistle
citadel-station/citadel-main pull request #8275
Opened 2019-04-23 01:46 UTC by Seris02

[Changelogs]:

:cl: fixed the warp whistle
fix: fixed the warp whistle
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Because we just had a round where some people got really angry at a wizard that was invisible and invincible, and that's not fun for anybody.

2019-04-25 08:55 UTC, silicons approved these changes

2019-05-07 01:22 UTC, deathride58 requested changes
Make your PR changelog and PR title say what this PR actually does. Because this isn't a fix at all, this is a balance change

2019-05-08 08:36 UTC, silicons requested changes
somehow i forgot entirely to do this wew but yeah this isn't the right fix, the right fix is finding out WHY it isn't de-setting GODMODE from status flags, not removing godmode/invis.

2019-05-21 06:38 UTC, kevinz000 commented
inactivity

2019-05-21 06:38 UTC, closed without merging