Nerfs Engi printing and organized many designs
citadel-station/citadel-main pull request #8295
Opened 2019-04-27 02:24 UTC by Trilbyspaceclone

[Changelogs]
Nerfed Engi printer aka did nothing do to them being able to print off a unrestricted printer anyways

**Removed engi from printing ID and Communication consoles**

:cl: optional name here
del: Many engi flags on non-engi things
code: changed some code to be organized at a glance 
/:cl:

[why]
WEW that was messy!
Engi printer is powerfull to be able to print lethal all of medica/sci/sec gear

2019-04-27 04:11 UTC, Poojawa requested changes
I don't at all agree with depriving Engineering of it's core responsibility. If you want to nerf this, make it access locked

2019-04-27 04:11 UTC, Poojawa commented on code/modules/research/designs/comp_board_designs.dm
> +	desc = "A blank compurter board!"
computer

2019-04-27 04:11 UTC, Poojawa commented on code/modules/research/designs/comp_board_designs.dm
> +	departmental_flags = DEPARTMENTAL_FLAG_ALL
Why would service, security, medical, and science need to be able to print library book console circuits?

2019-04-27 22:48 UTC, Trilbyspaceclone commented on code/modules/research/designs/comp_board_designs.dm
> +	departmental_flags = DEPARTMENTAL_FLAG_ALL
IDK it was all ALL flag'ed

2019-04-27 23:05 UTC, Trilbyspaceclone commented on code/modules/research/designs/comp_board_designs.dm
> +	departmental_flags = DEPARTMENTAL_FLAG_ALL
Also thats console not printer, its prob to add in books/catalogs without needing to leave you department

2019-04-27 23:49 UTC, kevinz000 commented
Engineering is supposed to be able to print all circuitboard types and it is staying that way.

2019-05-30 18:12 UTC, silicons approved these changes

2019-05-30 18:12 UTC, merged