buff sleepy pens to quickly drain stamina after 10 seconds
citadel-station/citadel-main pull request #8307
Opened 2019-04-29 11:00 UTC by kevinz000

they're too unused and crappy under stamina combat, easily combatable with coffee and more or less useless unless they manage to down you first or lock you into a room.

2019-05-03 02:53 UTC, Trilbyspaceclone approved these changes
All and all Prala pen is op weapon do to holding 30u of any chem to auto 0 delay inject, buying a toxin kit or making your own toxins with maint chemist is viable as ever and will always be the robust way to use these. Its starting mix is meant in my eyes to be a low-effect only muting and starting of sleep, well quickly loading a gun behind your back to take them out that way.
Or doing a quick pen reload mid talk or such also tends to work when I used to role antag.

2019-05-03 02:53 UTC, Trilbyspaceclone commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
>  		if(20 to INFINITY)
knocking this down to 15 wouldnt be a bad idea.

2019-05-03 02:53 UTC, Trilbyspaceclone commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
>  		if(10 to 20)
10-15 would be better

2019-05-03 02:53 UTC, Trilbyspaceclone commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +			M.adjustStaminaLossBuffered(5)
15 would make it viable

2019-05-07 00:57 UTC, deathride58 requested changes

2019-05-07 00:57 UTC, deathride58 commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +			M.adjustStaminaLossBuffered(5)
Affecting the stamina buffer directly is a hard no, as the stamina buffer is intended to only be affected by the user's actions and only the user's actions.

2019-05-08 08:32 UTC, kevinz000 commented
@deathride58 done
@Trilbyspaceclone i buffed the stam to 7.5/tick, that's 75 stam over 10 ticks and way better compounded with the tirizine. metabolization rate also makes it last longer overall. 
it is not meant to require you to go high-effort route of making your own mix. hell, i do not think chemical injections that way are balanced at all right now, mixing toxins to stack damage is bullshit and a terrible use of the goofchem system in my opinion.

2019-05-08 10:08 UTC, Trilbyspaceclone commented
Toxin kit gives a dropper iirc and then you can mix in a 30u bottle the worst mixes ever to crit someone in 2 ticks like, no joke. So its rather good to get the bottle premade, set to 30u transfer,jab the target quick load, jab again and then drag the now dead toxin'ed airless body into a locker or throw their poor body out the airlock

2019-05-12 08:59 UTC, deathride58 approved these changes
This here's pretty good at the moment

2019-05-17 04:54 UTC, merged