Adds the Mimesquad ERT (Serious)
citadel-station/citadel-main pull request #8343
Opened 2019-05-11 08:40 UTC by BurgerLUA

[Changelogs]: 
:cl: BurgerBB
add: Adds the Mime ERT, a special type of ERT with one goal: Lower the god damn noise of the station. Mime ERT are equipped with a range of special weapons and gear that are meant to non-lethally silence a person, such as a silenced pistol that shoots soporific bullets, mutetoxin grenades, and DNA syringe guns that contain the mute gene.
admin: Admins don't have to give the Mime ERT access to the armory. They spawn with everything they need in their loadout to deal with noisy heads of staff. Really only 1-2 mime ERT are needed to deal with 1 rowdy head of staff.
/:cl:
[why]: On some rounds, heads of staff can get pretty loud. Very loud. Currently the only way centcom can deal with these peoples is magically disable loudmode for headsets or microphones over comms. I think that a much funner way of dealing with these people should be introduced: The Mime ERT.

Mime ERT loadout includes:
- ERT All-Access ID
- Mime Uniform
- Mime ERT Hardsuit + Helmet
- Mime Mask
- Earmuffs
- Sunglasses
- Mime Backpack
- Special Mime Suspenders
- Mime PDA for communication
- A muzzle for ERP
- Engineer Internals + Medipen
- Bottle of Nothing
- Mime Banana
- Mime Spraycan for communication
- DNA Syringe Gun
- Soporific 10mm Silenced Pistol
- Extra Soporific Mag
- x4 mute syringes
- A Flashbang, except it doesn't bang, so it's just a flash.
- A mutetoxin smoke grenade

2019-05-11 14:56 UTC, Trilbyspaceclone approved these changes
<3 Love this

2019-05-11 14:56 UTC, Trilbyspaceclone commented on code/modules/projectiles/pins.dm
> +/obj/item/firing_pin/mime/pin_auth(mob/living/user)
Mute trait should make it useable as well

2019-05-17 03:59 UTC, deathride58 requested changes

2019-05-17 03:59 UTC, deathride58 commented on code/game/objects/items/grenades/chem_grenade.dm
> +
Needless whitespace makes me cry

2019-05-17 03:59 UTC, deathride58 commented on code/modules/clothing/spacesuits/miscellaneous.dm
> +	helmettype = /obj/item/clothing/suit/space/hardsuit/ert/med
???

2019-05-17 19:56 UTC, BurgerLUA commented on code/modules/clothing/spacesuits/miscellaneous.dm
> +	helmettype = /obj/item/clothing/suit/space/hardsuit/ert/med
don't know what happened here

2019-05-21 10:13 UTC, BurgerLUA commented
@deathride58 Done

2019-06-09 23:42 UTC, BurgerLUA commented
aaaa so many merge conflicts jfc

2019-06-17 02:36 UTC, kevinz000 commented
stale

2019-06-17 02:37 UTC, closed without merging