Cryosleep no longer holds Borg blueprints
citadel-station/citadel-main pull request #8345
Opened 2019-05-12 01:51 UTC by Trilbyspaceclone

[Changelogs]
bug fixing that /obj/item/areaeditor/blueprints/cyborg is held in cryosleep
:cl: optional name here
fix: bug
/:cl:

[why]
Cryo sleep isnt ment to hold robotic things, bug fixing

2019-05-12 05:27 UTC, Poojawa approved these changes

2019-05-12 09:22 UTC, deathride58 commented
waitwaitwait why the fuck are borg modules getting accepted into cryo storage

2019-05-12 09:23 UTC, deathride58 requested changes
fix it properly by making cryo refuse to preserve anything from borgs instead of relying on a snowflake blacklist

2019-05-12 09:26 UTC, Poojawa commented
that's exactly what the black list does. it deletes the snowflake borg versions of stuff that is usually OK to preserve.

2019-06-08 07:56 UTC, kevinz000 commented
stale

2019-06-08 07:56 UTC, closed without merging

2019-06-08 08:12 UTC, Poojawa commented
It's.. not stale, it's good to merge?