Reduces the complexity of the two new circuits: pneumatic cannon and stunner.
citadel-station/citadel-main pull request #8359
Opened 2019-05-15 21:29 UTC by Useroth

Considering both have pretty hefty cooldown (3 sec for the cannon, 5 for the stunner) and external cooldown (1.5 sec for the cannon and 2.5 for the stunner) making them pretty challenging to stack in any effective way, I think it's just fair, because currently it's _pretty_ hard to make anything interesting and have it fit in a single assembly.
Also, I will want stun implants eventually, yes.

2019-05-15 21:32 UTC, BurgerLUA approved these changes

2019-05-17 04:00 UTC, deathride58 reviewed
Yeah I'm really not liking how low these values are. Can be merged with other maintainer's approval, but I'm personally on the fence about this.

2019-05-17 04:41 UTC, Useroth commented
What values would you suggest for them? They're already rather niche gimmicks, to be entirely honest. Like, for example, the pneumatic cannon doesn't compare in any way to the traditional pneuma-cannon, because it can only fire a single item, rather than a bunch.

2019-05-21 06:43 UTC, silicons requested changes
let's try 50/30 instead of 40/15

2019-06-01 02:18 UTC, silicons approved these changes

2019-06-01 02:18 UTC, merged