*think [emote]
citadel-station/citadel-main pull request #8418
Opened 2019-05-23 06:28 UTC by kevinz000

2019-05-23 08:16 UTC, davidchan13 commented
>Not added to *help 

REEEEEE

2019-05-23 12:34 UTC, deathride58 commented
🤔 
@davidchan13 *help is automatically generated

2019-05-23 13:15 UTC, davidchan13 commented
@deathride58 If thats true why are none of the citadel specific emotes in the *help

2019-08-27 02:57 UTC, nik707 requested changes
get it together

2019-08-27 02:57 UTC, nik707 commented on code/modules/mob/living/emote.dm
> +	message = "makes a thinking face."
"does a think"

2019-08-27 02:57 UTC, nik707 commented on code/modules/mob/living/emote.dm
> +	message_param = "makes a thinking face at %t."
ditto

2019-09-11 05:03 UTC, closed without merging