Ported the nudity permit from RP and made it a loadout option. You're welcome, Everoth
citadel-station/citadel-main pull request #8565
Opened 2019-06-07 16:39 UTC by SkullyRoberts

[Changelogs]: # Ported the nudity permit.

[why]: # 
Someone asked me to do it in dchat

2019-06-07 23:01 UTC, Ghommie commented on code/modules/clothing/under/miscellaneous.dm
> +//	sprite_sheets = list() //Dunno why this is here so I'm gonna comment it out and hope it still works.
Remove this comment.

2019-06-07 23:01 UTC, Ghommie commented on code/modules/clothing/under/miscellaneous.dm
> +	body_parts_covered = 0
```suggestion
	body_parts_covered = NONE
```

2019-06-07 23:01 UTC, Ghommie commented on code/modules/clothing/under/miscellaneous.dm
> +	item_state = "golem"  //This is dumb and hacky but was here when I got here.//No, it really isn't. Why make a new blank clothing sprite if we already have one?
delete comment-ception. Tastes like salt.

2019-06-08 09:55 UTC, silicons requested changes
we are absolutely not having people with nudity permits unless hiding genitals is coded.
erp server != enable everyone to run around with their dicks out and sticking out of their sprite. i don't care if it's already a thing, let's not make it worse. there's lines here, and the entire server shouldn't revolve around supporting being as lewd and involved with erp as possible.

2019-06-08 09:59 UTC, silicons requested changes
i was told hiding genitals is already a thing and i'm stupid so
alright one condition if this is loadout loaded have the person default to "always hidden genitals" when it's loaded because i don't want people running around with their dicks always out.

2019-06-09 20:11 UTC, SkullyRoberts commented
@kevinz000 Fixed it like you said. They now cover genitals and boobs by default.

2019-06-16 08:19 UTC, silicons approved these changes

2019-06-16 08:19 UTC, merged