Atmos updates
citadel-station/citadel-main pull request #8622
Opened 2019-06-11 11:34 UTC by Arturlang

Adds examine message to all stuff you can CTRL and Alt click, so people actually know its possible. Fixes some logging messages.
:cl:
add: You can now examine pumps filters and mixers to see if you can use CTRL and Alt click on them.
/:cl:

2019-06-11 22:16 UTC, deathride58 requested changes
Code quality and consistency.

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/binary_devices/pump.dm
> +	to_chat(user,"<span class='notice'>You can hold CTRL and click on it to toggle it on and off.</span>")
```suggestion
	to_chat(user,"<span class='notice'>You can hold <b>Ctrl</b> and click on it to toggle it on and off.</span>")
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/binary_devices/pump.dm
> +	to_chat(user,"<span class='notice'>You can hold ALT and click on it to maximize its pressure.</span>")
```suggestion
	to_chat(user,"<span class='notice'>You can hold <b>Alt</b> and click on it to maximize its pressure.</span>")
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
> +	to_chat(user,"<span class='notice'>You can hold CTRL and click on it to toggle it on and off.</span>")
```suggestion
	to_chat(user,"<span class='notice'>You can hold <b>Ctrl</b> and click on it to toggle it on and off.</span>")
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
> +	to_chat(user,"<span class='notice'>You can hold ALT and click on it to maximize its pressure.</span>")
```suggestion
	to_chat(user,"<span class='notice'>You can hold <b>Alt</b> and click on it to maximize its pressure.</span>")
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
> +	to_chat(user,"<span class='notice'>You can hold CTRL and click on it to toggle it on and off.</span>")
```suggestion
	to_chat(user,"<span class='notice'>You can hold <b>Ctrl</b> and click on it to toggle it on and off.</span>")
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
> +	to_chat(user,"<span class='notice'>You can hold ALT and click on it to maximize its pressure.</span>")
```suggestion
	to_chat(user,"<span class='notice'>You can hold <b>Alt</b> and click on it to maximize its pressure.</span>")
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
> +	to_chat(user,"<span class='notice'>You can hold CTRL and click on it to toggle it on and off.</span>")
```suggestion
	to_chat(user,"<span class='notice'>You can hold <b>Ctrl</b> and click on it to toggle it on and off.</span>")
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
> +	to_chat(user,"<span class='notice'>You can hold ALT and click on it to maximize its pressure.</span>")
```suggestion
	to_chat(user,"<span class='notice'>You can hold <b>Alt</b> and click on it to maximize its pressure.</span>")
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/binary_devices/pump.dm
> +	..()
```suggestion
	. = ..()
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
> +	..()
```suggestion
	. = ..()
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
> +	..()
```suggestion
	. = ..()
```

2019-06-11 22:16 UTC, deathride58 commented on code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
> +	..()
```suggestion
	. = ..()
```

2019-06-12 20:41 UTC, Arturlang commented
Going to redo the PR since i accidentally deleted the fork, with the suggestions done.

2019-06-12 20:41 UTC, closed without merging