Hotel Fixing and addition of heaters/QoL
citadel-station/citadel-main pull request #8635
Opened 2019-06-12 21:48 UTC by Trilbyspaceclone

## About The Pull Request

Fixing the random field 2 solars from being too far with a closer console
Fixes missing wire on field 1 solars 
Adds a few space heaters around the space hotel
Adds 2 crates with 1 flash light and 10 solar panels
## Why It's Good For The Game

Space hotel is rarely used, maybe this will give the ghosts that spawn their something more to do.
Broken solar fields are bad
Lack of flash lights suck

## Changelog
:cl:
add: heats/solars/light
fix: broken solar fields 
/:cl:

2019-06-13 22:17 UTC, Trilbyspaceclone commented
recompile

2019-06-14 23:14 UTC, deathride58 requested changes
A solar control console on the exterior? Extra solar panels added to the hotel exterior haphazardly without a care for symmetry? You can do a lot better than this.

2019-06-16 08:07 UTC, silicons submitted a review, later dismissed

2019-06-16 14:16 UTC, Trilbyspaceclone commented
@deathride58 The console one the outside is for second solar field, Solar consoles have a AOE rather then linking to ever solar pannal ever

2019-10-30 04:45 UTC, closed without merging