Brings back Big Wolf ears for humans
citadel-station/citadel-main pull request #8668
Opened 2019-06-17 09:17 UTC by poptar4551

This use to be here, and I'm no furry, but it needed to come back.

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2019-06-17 09:21 UTC, Poojawa requested changes
Aaaalmost. Just missing these bits and then you're golden.

2019-06-17 09:21 UTC, Poojawa commented on modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "bigwolf"
```suggestion
	icon_state = "bigwolf"
	icon = 'modular_citadel/icons/mob/mam_ears.dmi'
	color_src = MATRIXED
```

2019-06-17 09:21 UTC, Poojawa commented on modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
> +	hasinner = 1
```suggestion
	hasinner = 1
	icon = 'modular_citadel/icons/mob/mam_ears.dmi'
	color_src = MATRIXED
```

2019-06-17 09:21 UTC, Poojawa commented on modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "bigwolfdark"
```suggestion
	icon_state = "bigwolfdark"
	icon = 'modular_citadel/icons/mob/mam_ears.dmi'
	color_src = MATRIXED
```

2019-06-17 09:21 UTC, Poojawa commented on modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
> +	hasinner = 1
```suggestion
	hasinner = 1
	icon = 'modular_citadel/icons/mob/mam_ears.dmi'
	color_src = MATRIXED
```

2019-06-17 09:25 UTC, Poojawa approved these changes

2019-06-22 02:32 UTC, silicons approved these changes

2019-06-22 02:32 UTC, merged