Tweaks dogborg sleeper insert/resist values, and adds the ability to pry open dogborg sleepers via crowbar
citadel-station/citadel-main pull request #8790
Opened 2019-06-30 08:42 UTC by deathride58

## About The Pull Request
This PR does exactly as it says on the tin. It now takes 10 seconds for dogborgs to insert people into their sleepers, which is double their prior value of 5 seconds. The baseline resist value to get out of dogborg sleepers has been decreased from 30 seconds to 15 seconds. Medihounds have a 3 second resist timer to get out of their sleeper. Sechounds in particular retain their original value of 30 seconds. Additionally, this PR also adds the ability to pry open dogborg sleepers by simply using a crowbar on them. If the dogborg has anything in their sleeper, crowbarring them will instantly eject the sleeper's occupants.

## Why It's Good For The Game
It's annoying as hell from all sides, administrative and player alike, when dogborgs refuse to listen to your repeated law 2 requests to eject the contents of their sleeper. It's also incredibly annoying when a dogborg sleepers you while you're in a life-or-death situation that requires your immediate action. The positives of this PR are self-explanatory.

## Changelog
:cl: Bhijn
add: It's now possible to forcefully eject the occupants of a dogborg's sleeper by using a crowbar on them. This action is instant.
tweak: Resist values for dogborg sleepers have been adjusted. The baseline has been decreased from 30 seconds to 15 seconds. Medihound sleepers have a resist timer of 3 seconds. Sechound sleepers retain a resist timer of 30 seconds.
tweak: It now takes 10 full seconds to insert people into your sleeper. This should hopefully give people some more room to breathe and react to a dogborg attempting to sleeper someone either for no reason or in a way that violates law 2.
/:cl:

2019-07-02 22:19 UTC, Poojawa commented
y tho

this seems like an administrator issue that's being fixed with ham-handed code nerfs.

This also circumvents Law 1's detective, which, if you recall, overrules law 2. 

A crowbar instant eject is only going to mean someone can randomly slap a medihound and run off with someone.

2019-07-02 22:21 UTC, Poojawa requested changes

2019-07-02 22:21 UTC, Poojawa commented on code/game/objects/items/devices/dogborg_sleeper.dm
> +	breakout_time = 300
```suggestion
	breakout_time = 30 SECONDS
```

2019-07-02 22:21 UTC, Poojawa commented on code/game/objects/items/devices/dogborg_sleeper.dm
> +	breakout_time = 30 //Medical sleepers should be designed to be as easy as possible to get out of.
```suggestion
	breakout_time = 3 SECONDS //Medical sleepers should be designed to be as easy as possible to get out of.
```

2019-07-02 22:21 UTC, Poojawa commented on code/modules/mob/living/silicon/robot/robot.dm
> +/mob/living/silicon/robot/crowbar_act(mob/living/user, obj/item/I) //TODO: make fucking everything up there in that attackby() proc use the proper tool_act() procs. But honestly, who has time for tha
why tho

2019-07-03 12:25 UTC, kevinz000 commented
@Poojawa Because without this the only way to eject would be to kill them.

2019-07-03 12:25 UTC, kevinz000 commented
Merging when the timers are changed to use defines or 24 hours passes.

2019-07-04 05:26 UTC, Poojawa commented
> @Poojawa Because without this the only way to eject would be to kill them.

It still shouldn't be ***instant*** is my point. a short delay.

2019-07-05 13:55 UTC, silicons approved these changes

2019-07-05 13:55 UTC, merged