Makes surgery stealthy! Brainwash your coworkers with nobody being the wiser.
citadel-station/citadel-main pull request #8814
Opened 2019-07-02 15:22 UTC by Sishen1542

## About The Pull Request
* Port of https://github.com/tgstation/tgstation/pull/44483

* Surgery now gives detailed description to the surgeon, and more vague or ambiguous descriptions to the patient and anyone further away. This can lead to a surgeon being able to perform a brainwashing in place of a brain surgery with nobody being the wiser, or implanting a different organ than the one agreed on, and so on.

## Why It's Good For The Game
* Helps add on some extra paranoia to surgery, since everybody hates using N2O in a MRP server.

## Changelog
:cl: Sishen1542, original by XDTM
add: Surgery steps are now shown in detail only to the surgeon and anyone standing adjacent to them; the patient and people watching from further away get a more vague/ambiguous description.
/:cl:

2019-07-02 15:28 UTC, deathride58 requested changes
the `display_results()` proc calls are supposed to replace the `visible_message()` calls. This PR in its current state will result in all surgery messages being repeated twice, once for the original method, then again with the new message with a separation between detailed and vague descriptions

2019-07-02 15:53 UTC, Sishen1542 commented
> the `display_results()` proc calls are supposed to replace the `visible_message()` calls. This PR in its current state will result in all surgery messages being repeated twice, once for the original method, then again with the new message with a separation between detailed and vague descriptions

Didn't notice in testing, but should be good now. Removed any visible_message() that was where a display_results() should have been.

2019-07-12 14:39 UTC, silicons approved these changes

2019-08-11 03:41 UTC, dapnee requested changes
They did surgery /on a grape/ on a subtler. Fix your shit.

2019-08-11 03:41 UTC, dapnee commented on code/modules/surgery/cavity_implant.dm
> +		if(IC || tool.w_class > WEIGHT_CLASS_NORMAL || HAS_TRAIT(tool, NODROP) || istype(tool, /obj/item/organ))
```suggestion
		if(IC || tool.w_class > WEIGHT_CLASS_NORMAL || HAS_TRAIT(tool, TRAIT_NODROP) || istype(tool, /obj/item/organ))
```

2019-08-11 03:41 UTC, dapnee commented on code/modules/mob/mob.dm
> +/atom/proc/visible_message(message, self_message, blind_message, vision_distance, list/ignored_mobs)
```suggestion
/atom/proc/visible_message(message, self_message, blind_message, vision_distance, list/ignored_mobs, no_ghosts = FALSE)
```

2019-08-11 05:22 UTC, closed without merging