You can now eat dead headslugs.
citadel-station/citadel-main pull request #8838
Opened 2019-07-07 11:34 UTC by BlackMajor

![grayons](https://cdn.discordapp.com/attachments/161574200581029888/597376881947574272/meme.png)

Suru complained to me that if a ling last resorts into a headslug you can't absorb them as a ling.

So now you can eat dead headslugs to absorb them as a changeling.

Eating a dead headslug will also give the user 20u of changelingmeth.
Anyone who is not a changeling who eats one will immediately vomit.
I'm aware that that means this can be used as a hard ling test, that's intentional.
 I mean, it's a one time use thing, and you're only going to get 1-2 of them a changeling round tops.

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/obj/item/headcrab //Edible headslug obj so lings who last resort can still be absorbed
uuuh, try to make this a subtype of `obj/item/reagent_containers/food/snacks` if possible.

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	qdel(slug) //You ate it
qdel(src) already handles it since it also deletes its contents.

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		M.forceMove(drop_location())
except you did this. May I ask why? Shouldn't this item only contain the real headslug?

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(istype(loc, /turf))
```suggestion
	if(isturf(loc))
```

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +			var/datum/antagonist/changeling/target_ling = slug.mind.has_antag_datum(/datum/antagonist/changeling)
remove this line, absorb_mind already deals with changeling minds on top of normal mind memory stuff.

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +			if(target_ling)
Same.

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		if(istype(target, /mob/living/carbon))
```suggestion
		if(iscarbon(target))
```

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +	if(target == user)
This doesn't take in account whether the mob is a carbon or not.
Drones, gorillas and dextrous holoparasites (or just any simple animal if the admin knows how to edit them) can pick up and use items while not being carbon subtypes.

That's another reason this should be a subtype of snacks.

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +/obj/item/headcrab/afterattack(atom/target, mob/user, proximity)
Pretty sure you'll bonk the targets on attack() everytime beforehand which could be annoying for some.

Another reason you should make this a subtype of snacks, less snowflaking.

2019-07-07 18:01 UTC, Ghommie commented on code/modules/antagonists/changeling/changeling.dm
> +		target_ling.canrespec = 0
FALSE

2019-07-07 18:01 UTC, Ghommie commented on code/modules/antagonists/changeling/changeling.dm
> +	canrespec = 1
TRUE

2019-07-07 18:01 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +			src.forceMove(H)
remove src. prefix

2019-07-08 21:32 UTC, deathride58 requested changes
yeah what gommie said

2019-07-25 04:36 UTC, EgoSumStultus commented
Consuming a headslug as a changeling does not count for the 'absorb another changeling' objective. Not sure if this is intended or not.

2019-10-03 05:57 UTC, BlackMajor commented
Closing this since we're going to rework lings.

2019-10-03 05:57 UTC, closed without merging