Adds a gun range to Box Station.
citadel-station/citadel-main pull request #8932
Opened 2019-07-21 00:27 UTC by EmeraldSundisk

## About The Pull Request

Adds a gun range to Box Station's Security wing. Slightly adjusts the rest of the wing to accommodate this change.
![Primetime](https://user-images.githubusercontent.com/51142887/61585567-27aeb480-ab13-11e9-8ddd-43fff61ddedc.PNG)

## Why It's Good For The Game

Good for roleplay and potentially skill-building. Right now only two of the four maps in rotation currently have a range - this increases the number to three in such a way game balance shouldn't be a concern. Likewise, Box Station is the most commonly played map in rotation, meaning the benefits the range provides should be present a lot more often.

## Changelog
:cl:
add: Adds a gun range to Box Station
add: Provides some extra power grid connections
del: Sunglasses and Earmuffs removed from the Warden's Office - they can be found at the range instead
tweak: Rearranges a few objects within the prison as to accommodate the new gun range
/:cl:

2019-07-21 17:49 UTC, Thalpy commented
0.06s$ tools/travis/build_byond.sh
_maps/map_files/BoxStation/BoxStation.dmm:	step_y = 5
_maps/map_files/BoxStation/BoxStation.dmm:	step_y = 11
_maps/map_files/BoxStation/BoxStation.dmm:	step_y = 4
_maps/map_files/BoxStation/BoxStation.dmm:	step_y = 0
step_x/step_y variables detected in maps, please remove them.

You might need to fix this, but I honestly don't know how mapping works so maybe not.

2019-07-22 00:57 UTC, EmeraldSundisk commented
I'm...not sure either if I'm honest. Figuring out how to get it on here was difficult enough, but I do want to make this work if it doesn't.

2019-07-22 01:40 UTC, BlackMajor commented
> I'm...not sure either if I'm honest. Figuring out how to get it on here was difficult enough, but I do want to make this work if it doesn't.

Use pixel_x / pixel_y.
step_x and step_y are a movement feature that byond supports but isn't implemented in tg builds of SS13, and the mere existence of one instance of step_x/y breaks movement animation on a running game.

Dream Maker has an option in edit or something for "Nudge as pixel" if you're trying to offset items for fashion purposes.
Otherwise open the .dmm in some text program and delete the lines referencing a step_x/y, as setting them to 0 won't remove them in dream maker.

2019-07-22 02:06 UTC, EmeraldSundisk commented
I think I can do that second part, but would that reset the object positions in the map itself?

2019-07-22 11:31 UTC, Ghommie commented
No, they'll appear in the map just the same as now, simply without the errors and problems of the unsupported step_*.

2019-07-22 15:33 UTC, EmeraldSundisk commented
Okay, got the new file prepared. How do I swap out the current one?

2019-07-23 07:47 UTC, Linzolle commented
Just push a new commit to your PR branch.

2019-07-24 00:21 UTC, EmeraldSundisk commented
Hey I fixed it I think!

2019-07-24 00:22 UTC, Thalpy commented
Seems so!

2019-08-07 14:55 UTC, EmeraldSundisk commented
Well shoot. Apparently that conflict makes it unusable. I know about the mapmerge tool, but it didn't seem to do anything. Any suggestions?

2019-08-07 14:56 UTC, Thalpy commented
Hmm, I can't help you, but maybe one of the maintainers/Ghommie might now?

2019-08-07 22:38 UTC, EmeraldSundisk commented
Remade it to use the newest version of the map but it seems I'm not any closer here...

2019-08-08 00:12 UTC, EmeraldSundisk commented
It may be a bit less pretty this time around but at this point I just want to be sure it works.

2019-08-28 18:03 UTC, nik707 requested changes
Random earmuffs in the clinic can be removed, then it'll be RTM

2019-08-28 18:09 UTC, EmeraldSundisk commented
Yeah how'd those get there...I'll see what I can do.

2019-08-29 23:45 UTC, nik707 approved these changes

2019-09-02 23:23 UTC, merged