[TESTMERGE ONLY] Hardsuit helmets can now be used as internals masks. Rejoice, CE mains.
citadel-station/citadel-main pull request #8992
Opened 2019-07-28 16:35 UTC by jakeramsay007

Also reworks internals code a little to be much more friendly. Any head or mask item with the flag should now function as an internals mask if it has the ALLOWSINTERNALS flag.

Testmerge only for now until I'm 100% sure it has no bugs at all. Local testing shows that internals function as intended, but as we all know, there's always edge cases.

:cl: Chayse
add: Assorted space-worthy helmets can now act as masks for internals.
refactor: Internals code can now check any item with the ALLOWSINTERNALS flag through the check_internals_slot() proc. For now this only checks head and mask slots, since those are the most realistically speaking usable ones.
/:cl:

2019-07-30 01:36 UTC, YakumoChen commented
Does the mouth tube implant still work?
Does this mean you can smoke a cigar while wearing a helmet?

2019-07-30 04:07 UTC, jakeramsay007 commented
Yes, and technically yes, unintended feature but hilarious all the same.

2019-07-31 21:23 UTC, YakumoChen commented
![image](https://user-images.githubusercontent.com/10399117/62249210-69741080-b3d9-11e9-9e34-178e678a613a.png)

Hell, it's about time.

2019-08-04 04:20 UTC, deathride58 requested changes

2019-08-04 04:20 UTC, deathride58 commented on code/modules/mob/living/carbon/life.dm
> +	var/internalslots = list(
Make this a define, as per my comment in inventory.dm

2019-08-04 04:20 UTC, deathride58 commented on code/modules/mob/living/carbon/life.dm
> +		else if (internals == FALSE && !getorganslot(ORGAN_SLOT_BREATHING_TUBE))
There's no need to check explicitly for FALSE
```suggestion
		else if (!internals && !getorganslot(ORGAN_SLOT_BREATHING_TUBE))
```

2019-08-04 04:20 UTC, deathride58 commented on code/modules/mob/living/carbon/inventory.dm
> +/mob/living/carbon/proc/get_internal_slots()
Why is this a proc? This has no reason at all to be a proc when the contents are guaranteed to always be the same. Proc calls have a fairly significant overhead, far greater than the overhead of declaring a var.
Turn this into a define.
```
#define GET_INTERNAL_SLOTS(C) list(C.head, C.wear_mask)
```

2019-08-04 04:20 UTC, deathride58 commented on code/modules/mob/living/carbon/inventory.dm
> +		wear_mask,
This here will make most third-party byond dev tools cry. Here's an easy fix. Also there's no need for this to be multi-line, I'm not sure how this even compiles when you aren't cancelling out the linebreaks
```suggestion
		wear_mask
```

2019-08-05 09:24 UTC, deathride58 approved these changes

2019-08-06 04:37 UTC, lolman360 commented
now i can wear balaclava under helmet

>Le epic CEsuit traitor
>Unknown
>Pull helmet off
>Balaclava, still unknown
>Pull balaclava off, acid'd face
>still unknown

2019-08-11 17:15 UTC, silicons approved these changes

2019-08-11 17:15 UTC, merged