Ports some recent /tg/ medical changes.
citadel-station/citadel-main pull request #9003
Opened 2019-07-29 10:52 UTC by lolman360

## About The Pull Request

Adds Trophazole, Mitogen Factor, Peptides, Rhigoxane, Thizalid and Oxzalid from /traditionalgames/station. Thizalid and Oxzalid don't do liver damage, and Thizalid ODs at 10u instead of 6.

## Why It's Good For The Game

These chemicals are more interesting than the current bicard/kelo/antitox core ones, more powerful in their specific niches and harder to make. They make a good intermediate between bicard/kelo/antitox and penetic/saliacid/oxalandrone as they don't need a specific amount of damage to work at their full power, but instead need a specific delivery method.

(kev please no "CHEM WAREFARE BAD!!" comment)

## Changelog
:cl:
add: NT has updated the station's chemical infrastructure to allow production of Trophazole, Thizalid and Rhigoxane.
/:cl:

2019-07-30 04:37 UTC, Linzolle commented
this PR title scared me for a moment

2019-07-31 07:03 UTC, Poojawa requested changes
🤔

2019-07-31 07:03 UTC, Poojawa commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list("melee" = 25, "bullet" = 25, "laser" = 25, "energy" = 100, "bomb" = 100, "bio" = 100, "rad" = 100, "fire" = 100, "acid" = 100)
undocumented change

2019-07-31 07:03 UTC, Poojawa commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	allowed = list(/obj/item/flashlight, /obj/item/tank/internals, /obj/item/construction/rcd, /obj/item/pipe_dispenser)
undocumented change

2019-07-31 07:03 UTC, Poojawa commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list("melee" = 25, "bullet" = 25, "laser" = 25, "energy" = 100, "bomb" = 100, "bio" = 100, "rad" = 100, "fire" = 100, "acid" = 100)
undocumented change

2019-07-31 21:19 UTC, YakumoChen commented
>he put commits from other PRs in Master

2019-08-01 02:33 UTC, lolman360 commented
>mfw forgot to delete and reopen fork to have a clean fork

2019-08-01 04:21 UTC, CameronWoof commented
Trophazole won't do anything useful, as you didn't port the reaction that causes metafactor to turn into peptides.

2019-08-01 07:34 UTC, lolman360 commented
not yet i had to go out

2019-08-02 12:57 UTC, lolman360 commented
done

2019-08-03 23:38 UTC, lolman360 commented
travis is shitting itself because pr is half modularized, on it

2019-10-22 09:07 UTC, closed without merging