Adds Elemolens
citadel-station/citadel-main pull request #9031
Opened 2019-08-01 13:03 UTC by Trilbyspaceclone

## About The Pull Request

Adds a new cargo crate that has a single seed of Elemolens

Adds 5 more plants that have many many elements in them.

## Why It's Good For The Game

Puns are nice, more plants for people to abuse, what could go wrong? Any who
Adding in more plants for cargo to get/hydro should be a nice change if only a few rounds and a high cost to avoid ever round abuse.

## Changelog
:cl:
add: Elemolens
/:cl:

2019-08-01 16:16 UTC, Poojawa commented
More cargo and botany powercreep

2019-08-01 16:26 UTC, Linzolle commented
> 
> 
> More cargo and botany powercreep

How is this powercreep? It's just some new seeds to toy with, none of which seem to do anything especially note worthy.

2019-08-01 16:35 UTC, Poojawa reviewed
Sure just give Cult and blob chems to botanists.

Seems like great idea.

What could possibly go wrong.

2019-08-01 16:35 UTC, Poojawa commented on code/modules/hydroponics/grown/melon.dm
> +	reagents_add = list("liquid_dark_matter" = 0.1, "singulo" = 0.2)
> none of which seem to do anything especially note worthy.

2019-08-01 16:35 UTC, Poojawa commented on code/modules/hydroponics/grown/melon.dm
> +	reagents_add = list("hell_water" = 0.1, "condensedcapsaicin" = 0.3, "hell_ramen" = 0.5, "clf3" = 0.01) //Better have fire proof gloves
> none of which seem to do anything especially note worthy.

2019-08-01 16:35 UTC, Poojawa commented on code/modules/hydroponics/grown/melon.dm
> +	reagents_add = list("water" = 0.4, "hell_water" = 0.04, "holywater" = 0.03, "unholywater" = 0.03, "oxygen" = 0.2, "hydrogen" = 0.1)
> none of which seem to do anything especially note worthy.

2019-08-01 16:52 UTC, Trilbyspaceclone commented
You can get unholy fasks for silver slimes, as well as hell water. Not really seeing the problem

2019-08-01 16:56 UTC, Poojawa commented
> You can get unholy fasks for silver slimes, as well as hell water. Not really seeing the problem

That is also a problem. wtf

2019-08-01 17:02 UTC, RogueSteampunker commented
It... doesn't seem like all that big of a deal. It just seems like some neat plants with a few more things to toy with, and locked behind cargo noless.

2019-08-02 03:37 UTC, lolman360 commented
>hell water melons
>unholy water melons
>combine with deathnettle
>deathnettle now applies firestacks and fucks up everyone unless cult

2019-08-02 09:28 UTC, Trilbyspaceclone commented
@lolman360 We all know its better to go down the omega weed path + death needles and nova flower. So that on throw you crit people, and kill them in 2 second with tons of brain damage. You can also go above and such with carp/normal toxins to make it a 1 tick kill on throw thats a supper light and a just in case 40 mj power cell.

2019-08-02 11:13 UTC, Ratvar commented
That's, surprisingly, also a problem that better be fixed in future

2019-08-02 12:05 UTC, lolman360 commented
@Trilbyspaceclone ok tested all of it and... it seems deathnettles don't like injecting reagents how fun.

2019-08-02 12:21 UTC, lolman360 requested changes

2019-08-02 12:21 UTC, lolman360 commented on code/modules/cargo/packs.dm
> +	name = "Elemolen Seed Crate"
spelt elemolen here but elemelon in other places

2019-08-02 12:21 UTC, lolman360 commented on code/modules/hydroponics/grown/melon.dm
> +	desc = "This transparent blueish fruit is said to be as from a clouds."
Description suggestion: "This translucent, blueish fruit is said to only grow among clouds."

2019-08-02 12:21 UTC, lolman360 commented on code/modules/hydroponics/grown/melon.dm
> +	desc = "This red fruit is said to be as from a different plan... Never found on lava land for some reason"
Description suggestion: "This red fruit is said to originate from the infernal plane, however it can't be found on Lavaland."

2019-08-02 12:21 UTC, lolman360 commented on code/modules/hydroponics/grown/melon.dm
> +	desc = "This dark blue fruit is said to be as from a from bluesea pocket"
Description suggestion: "This navy blue fruit is said to originate from an oceanic bluespace pocket."

2019-08-02 12:21 UTC, lolman360 commented on code/modules/hydroponics/grown/melon.dm
> +	desc = "This brown fruit is said to be from a massive meteor core that was able to sustain life inside of it before NT mind into it..."
Description suggestion: "This brown fruit is fabled to be from a massive hollow meteor able to sustain life within its interior."

2019-08-06 17:49 UTC, Thalpy commented
I support Elemelon's active consideration.

Hell water can be bad but, I've used it before and it's just a stronger plog, with brain damage.
Liquid dark matter and singulo aren't blob reagents as far as I can tell. Looking over the code it's the ones you can make in chem, and are under pyrotechnic_reagents.
And the other reagents seem fine and aren't worth commenting on.
clf3 vastly depend on how the reagent interacts with the game (turf vs mob)
I don't know unholy water to comment.

(Though I'm looking at it from the a chem perspective, not a botany one. I'm not much of a botanist, nor do I understand traits.)

2019-08-06 21:43 UTC, Trilbyspaceclone commented
@Thalpy <3
The cfl3 will fire bomb on pick making it a rather messy plant, thats the balance their
The unholy water is basically a toxin

2019-08-07 07:54 UTC, kevinz000 commented
The last thing botany needs is a buff.

2019-08-07 07:54 UTC, closed without merging

2019-08-07 10:03 UTC, Thalpy commented
If you want Lily, we can work out silly chems that aren't so round affecting to redirect the nature of this PR, so it's not a buff to botany.