Buffs wiz armor
citadel-station/citadel-main pull request #9190
Opened 2019-08-24 00:04 UTC by Trilbyspaceclone

## About The Pull Request
Gives wiz robs and hat 20 magic armor
all fake wiz gear/witch gets 1 magic armor
and wiz hardsuit gets 40 magic armor
## Why It's Good For The Game

Wiz keeps dieing, maybe this will help them prolong life or something

## Changelog
:cl:
balance: wiz armor to protect against wiz magic stuff
/:cl:

2019-08-27 02:41 UTC, silicons approved these changes
this better be tested

2019-08-27 02:41 UTC, silicons requested changes
actually can you tell us what this actually does because not everyone knows what magica rmor does at first glance and i don't like looking through the entire codebase to review when it should be in the desc optimally.

2019-08-30 00:42 UTC, nik707 commented
@Trilbyspaceclone

2019-08-31 21:19 UTC, nik707 commented
@kevinz000

2019-09-28 07:32 UTC, kevinz000 commented
stale

2019-09-28 07:32 UTC, closed without merging