I Used The Shotgun, You Know Why? (Shotgun Balance Pass)
citadel-station/citadel-main pull request #9199
Opened 2019-08-26 20:07 UTC by Tupinambis

## About The Pull Request

Lowers the damage output of the more commonly used and powerful shotgun shell variations, and gives a slight fire delay to automatic shotguns.

Two shot meatshots are still possible, they just have less room for error and armor.

## Why It's Good For The Game

Shotguns are objectively one of the best (non admin spawn) weapons in the game (and are pretty easy to use). They hard counter pretty much everything short of nuke ops, and even then shotguns are incredibly strong. They pretty much make every other weapon obsolete. Why use a stunbaton, taser, or disabler when rubbershot can stamcrit in ONE MEATSHOT? Why use lethal lasers with their pathetic 20 burn when you can two shot kill with slugs or buckshot? This brings shotguns down a notch so they aren't as much of an absolute ass to fight against. 

And for anyone who calls this a salt PR, I have managed to kill 12 revs during a rev round as warden with just the shotgun, alone. Only expensive syndicate weapons really match the power of the shotgun (the revolver is really just a shittier shotgun right now)

## Changelog
:cl:
balance: added a small fire delay (3 ticks) to automatic shotguns
balance: Reduced buckshot brute damage by 20%. (12.5 -> 10 brute per pellet) (75 -> 60 brute at close range)
balance: Reduced rubbershot stamina damage by 40% (25 -> 15 stamina per pellet) (150 -> 90 stamina at close range) 
balance: Reduced beanbag stamina damage by 12.5% (80 -> 70 stamina per shot)
/:cl:

2019-08-26 20:33 UTC, Trilbyspaceclone commented on code/modules/projectiles/guns/ballistic/shotgun.dm
> +	fire_delay = 5
3 is much better for this

2019-08-27 02:32 UTC, silicons commented on code/modules/projectiles/guns/ballistic/shotgun.dm
> +	fire_delay = 3
make sure this actually does something as last i checked it doesn't.

2019-08-27 02:32 UTC, silicons commented
@Tupinambis put the actual numbers in the pr desc and the percentage increase/decrease, point blank stats, etc.

2019-08-27 02:37 UTC, Tupinambis commented on code/modules/projectiles/guns/ballistic/shotgun.dm
> +	fire_delay = 3
It does for the autoshotties. I tested it. well not at the value of 3, but that was Lilly's suggestion not mine.

2019-08-27 07:48 UTC, YakumoChen commented
The rubber shot nerf seems a little harsh. rubber and buckshot ammo only do their listed values at point blank range, and lose damage as they travel. At that point you might as well be using a stun baton since you have to get into melee range to do appreciable damage anyway.

2019-08-27 15:57 UTC, cebutris commented
Cause the shot gun doesn't miss, and unlike the shitty hybrid taser it stops a criminal in their tracks in two hits. Bang, bang, and they're fucking done. I use four shots just to make damn sure. Because, once again, I'm not there to coddle a buncha criminal scum sucking f------, I'm there to 1) Survive the fucking round. 2) Guard the armory. So you can absolutely get fucked. If I get unbanned, which I won't, you can guarantee I will continue to use the shotgun to apprehend criminals. Because it's quick, clean and effective as fuck. Why in the seven hells would I fuck around with the disabler shots, which take half a clip just to bring someone down, or with the tazer bolts which are slow as balls, impossible to aim and do about next to jack shit, fuck all. The shotgun is the superior law enforcement weapon. Because it stops crime. And it stops crime by reducing the number of criminals roaming the fucking halls.

2019-08-30 00:35 UTC, nik707 approved these changes
@kevinz000 @deathride58 take a look to make sure this isn't too unbalanced me smallbrain

2019-09-06 07:57 UTC, Sishen1542 commented
number of pellets cause chat lag, not the damage on the guns

cut pellets and keep damage values the same, otherwise :-1:

2019-09-07 18:39 UTC, silicons requested changes
haha wait hold on 60 was the buckshot damage before shotguns had falloff
idk if we should be going back to it again considering they have falloff now and we're not even on /tg/ movespeed and in theory it's more reasonable to expect people to avoid it. @deathride58

2019-09-13 17:47 UTC, silicons approved these changes
eh fuck it let's go

2019-09-13 17:47 UTC, merged