Lighting Tweaks
citadel-station/citadel-main pull request #9213
Opened 2019-08-29 00:29 UTC by chefferz

Tweaks lighting wattage to be far more realistic to futuristic tech.

1) Lighting now takes half the wattage as normal, A standard light tube draws only 80w now, vs 160. 
2) The emergency lighting color is now fire engine/emergency red
3) Night shift lighting is now slightly brighter to ensure hallways aren't near pitch black in some areas.

2019-08-29 17:57 UTC, Poojawa commented
The power draw is so that the engine has reason to be powered. This'll just make solar only stations easier

2019-08-29 18:08 UTC, chefferz commented
> 
> 
> The power draw is so that the engine has reason to be powered. This'll just make solar only stations easier

The RP server already merged one that made it even lower than this. This game was designed in the mid 2000s before there was anything such as LED lighting/actual efficient lighting. It just boils down to, it's like 25XX and there's weapons that can launch BSAs across galaxies, yet we've got stupid inefficient lights? 

At one point I'd like to add in some efficiency tweaks. Ideally I'd like to make janitors able to upgrade lights with a new light bulb that draws less power, as it would give them something to do, but I'm not experienced coding enough to do something to that extent.

2019-08-29 18:12 UTC, deathride58 commented
its retrofuturism. tbh i wouldn't be opposed to adding fluorescent light tubes/bulbs as an rnd upgrade, and keeping the current incandescent ones as-is. all the necessary groundwork to support em is already in place. give janitors and engineers something to do etc etc

2019-08-29 18:17 UTC, chefferz commented
> 
> 
> its retrofuturism. tbh i wouldn't be opposed to adding fluorescent light tubes/bulbs as an rnd upgrade, and keeping the current incandescent ones as-is. all the necessary groundwork to support em is already in place. give janitors and engineers something to do etc etc

There's still a bit of pitch black areas on delta so 0.70 covers it just enough.

I'd really like a LITTLE bit more efficiency, so would 15w per lum sound a bit more fair?  (A normal bulb is 8 lum, so 120w)

Ideally if RnD got upgraded bulbs I'd want those stupid efficient, like +/- 50W

2019-08-30 00:16 UTC, nik707 commented
@deathride58 final comments?

2019-08-30 01:44 UTC, deathride58 requested changes

2019-08-30 01:44 UTC, deathride58 commented on code/modules/power/lighting.dm
> +	var/nightshift_light_power = 0.70
This is way too close to the baseline light power (which is 0.75). With this proposed value, it'll be impossible to actually notice any difference between baseline lighting and night shift lighting, and there'd no longer be any mechanical advantages/disadvantages to night shifts (such as, but not limited to, nightmares getting some wiggle room with station lighting, podpeople needing to stay closer to station lights, botany plants growing slower with roundstart light setups, etc etc). This proposed value practically removes night shifts.

2019-08-30 01:45 UTC, deathride58 commented
If the issue is that certain maps have dark spots, then it'd be better to make adjustments to the map's light layouts directly, as those dark spots are present regardless if night shifts are active or not.

2019-08-30 04:54 UTC, Linzolle commented
To be perfectly honest I'd rather night shift lighting just completely removed, it's annoying at best and makes it impossible to see in some areas at worst.

2019-08-30 22:07 UTC, Tupinambis commented
I have never met one player that likes night shift lighting. I'd rather it just be removed.

2019-08-31 03:34 UTC, Linzolle commented
Night shift lighting doesn't even make sense IC, why would we need to stimulate the circadian rhythm of species that are currently supposed to be awake and working?

2019-09-05 11:07 UTC, Trilbyspaceclone commented
If night shift was only on for low pop it would be better imo as it leaves slower draining APCs and such but being a Rng event that can happen at any time just is kinda bad and has no real logic to is

2019-09-13 17:42 UTC, kevinz000 commented
i honestly don't like the whole "change balance to be realistic" thing because it usually changes it for the worse.

2019-09-28 07:36 UTC, kevinz000 commented
stale and lack of maintainer interest

2019-09-28 07:36 UTC, closed without merging