[WIP] adds in a laser(tag) AK nullrod, and some back end null rod refactors
citadel-station/citadel-main pull request #9221
Opened 2019-08-30 20:54 UTC by Sishen1542

## About The Pull Request
wip

## Why It's Good For The Game
wip

## Changelog
:cl:
fix: fixed kevinz code to add in non-null rod child items as holy weapons
/:cl:

2019-08-30 21:52 UTC, Drowzyleaf commented
they made https://imgur.com/t5lTLYk into a real thing

2019-09-01 03:02 UTC, Trilbyspaceclone requested changes

2019-09-01 03:02 UTC, Trilbyspaceclone commented on code/modules/antagonists/cult/runes.dm
> +		user.say("BEGONE FOUL MAGICKS!!", forced = "bible")
Why not make both work?

2019-09-01 03:02 UTC, Trilbyspaceclone commented on modular_citadel/code/game/objects/items/holy_weapons.dm
> -			if(iscultist(M) || is_servant_of_ratvar(M)) //ripped from holywater code.
??? 
Out side the scope of the PR, and not needed change this worked fine

2019-09-01 03:37 UTC, Trilbyspaceclone commented on code/game/objects/items/holy_weapons.dm
> +	force = 12
Why nerf chainhand

2019-09-01 07:05 UTC, Sishen1542 commented on code/modules/antagonists/cult/runes.dm
> +		user.say("BEGONE FOUL MAGICKS!!", forced = "bible")
im fine with both, up to maintainers

2019-09-01 07:05 UTC, Sishen1542 commented on modular_citadel/code/game/objects/items/holy_weapons.dm
> -			if(iscultist(M) || is_servant_of_ratvar(M)) //ripped from holywater code.
10 sec for deconvert vs 30+ through holy water is a little silly

2019-09-01 13:47 UTC, Trilbyspaceclone commented
Im strongly against the rosary beads nerf, it makes its job worst.
Its ment to help people and be a non-harmful way. Adding in holywater to the proc rather then a deconvert is dumb.
Theirs no reason to change it from its 10 second deconvert, as thats the same time it takes to convert people. Its rather well balanced and rarely abused. + outside of 2 game modes is only able to do small heals that anyone with a soda despender can.
Changing it seems more of a salt nerf then anything.

2019-09-01 19:41 UTC, Sishen1542 commented
> Changing it seems more of a salt nerf then anything.

salt nerf from someone who doesn't play antags :thinking:

2019-09-01 21:15 UTC, Drowzyleaf commented
I'd say the prayer bead change isn't horrible. Right now, they may as well be useless on non-cult, since the healing is negligible for ten seconds of prayer. Now, they can still deconvert if a bit slower with the holy water, and they can work decently well on non-cult rounds for more pacifistic chaplains to heal others.

2019-09-01 21:37 UTC, Sishen1542 commented
> I'd say the prayer bead change isn't horrible. Right now, they may as well be useless on non-cult, since the healing is negligible for ten seconds of prayer. Now, they can still deconvert if a bit slower with the holy water, and they can work decently well on non-cult rounds for more pacifistic chaplains to heal others.

it also heals damage types that the bible doesnt cover, so yeah its pretty good at that
5 oxy/toxic per tick (chem ticks are effectively 2 secs, length of the action timer) is strong

2019-09-02 11:43 UTC, Trilbyspaceclone commented
They now CANT deconvert with beads as 5u isnt going to last 10 seconds, thus making it useless for that and only deal harm to the person they are healing

2019-09-02 15:30 UTC, Drowzyleaf commented
well, no. The timer was reduced to 2 seconds.

2019-09-02 23:27 UTC, Sishen1542 commented
> well, no. The timer was reduced to 2 seconds. Won't metabolize in that time, I'm sure.

the idea is you slap them a few times with it, yeah

2019-09-03 00:03 UTC, Trilbyspaceclone commented
Unlisted change didnt, know it would be lowered to 2 seconds, im now ok with this all

2019-09-05 01:37 UTC, nik707 approved these changes
The code looks awesome. That said, because I'm not super up to par yet on mains balancing standards, ask Kev or Bhijn to give it a quick glance over to make sure they don't have any grievances.

2019-09-06 23:47 UTC, silicons approved these changes

2019-09-06 23:47 UTC, merged