Shamelessly adds Engineering powercreep by stealing valuable original code from Paradise.
citadel-station/citadel-main pull request #9258
Opened 2019-09-08 03:18 UTC by lolman360

## About The Pull Request
Ports a modified version of https://github.com/ParadiseSS13/Paradise/pull/12062 adapted to tgui (god help me).

## Why It's Good For The Game
Powercreep = good.
Use for autism-level power = good.
Black okayed it.
## Changelog
:cl:
add: Adds a new station goal that generates cool stuff.
/:cl:

2019-09-08 03:21 UTC, Trilbyspaceclone commented on code/modules/station_goals/bluespace_tap.dm
> +		/obj/item/dnainjector/morph = 5,
Why add in self antags

2019-09-08 03:22 UTC, Trilbyspaceclone commented on code/modules/station_goals/bluespace_tap.dm
> +		/obj/item/gun/energy/plasma/MP40k = 5,
These are brokenly good

2019-09-08 03:25 UTC, Trilbyspaceclone requested changes
Please remove morph injectors

2019-09-08 03:25 UTC, Trilbyspaceclone commented on code/modules/station_goals/bluespace_tap.dm
> +		/obj/item/gun/energy/laser/LaserAK = 2,
They auto charge

2019-09-08 03:25 UTC, Trilbyspaceclone commented on code/modules/station_goals/bluespace_tap.dm
> +	name = "cultural artifacts"
Why is this one the best one?

2019-09-08 03:28 UTC, TDSSS commented
Seeing my shitcode ported to another codebase, wew.

2019-09-08 03:54 UTC, deathride58 commented
wait dont we have oracleui now

2019-09-08 04:22 UTC, kappa-sama commented
this sounds awesome

2019-09-08 15:27 UTC, Linzolle commented
> 
> 
> wait dont we have oracleui now

oracle isn't merged yet and also the person making this PR would probably use tgui anyway because they said "tgui > oui" on my PR for oracle

2019-09-09 03:28 UTC, lolman360 commented
i like tgui i just have a reputation for unironically liking it so i cant stop

2019-09-09 15:23 UTC, Arturlang commented
Finally a reason for retard amounts of powergen

2019-09-17 03:55 UTC, lolman360 commented
not stale sorry for not pushing commits but i use webgit

2019-10-08 07:30 UTC, kevinz000 commented
stale and a draft too

2019-10-08 07:30 UTC, closed without merging