Adds a new traitor bundle - Synda Major Leage Player
citadel-station/citadel-main pull request #9263
Opened 2019-09-09 01:51 UTC by Trilbyspaceclone

## About The Pull Request
Semi-tested!
New base ball bat that reflects all laser based weaponds and deals spear harm levels
New suit/hat that have some armor and theme fitting to a major player
New stimpack hypo/medpens

## Why It's Good For The Game

Fun baseball gimmic to spice things up, has weight 1, and is a basically alt of a dark lord that dosnt have TK + magic, should be balanced around its main gimmic being only laser proof and with 0 block without other items

## Changelog
:cl:
add: new traitor bundle
/:cl:

2019-09-09 02:55 UTC, YakumoChen commented
it needs baseballs

2019-09-09 13:22 UTC, Trilbyspaceclone commented
We do

2019-09-10 14:38 UTC, cebutris requested changes
Spelling errors

2019-09-10 14:38 UTC, cebutris commented on code/modules/clothing/shoes/miscellaneous.dm
> +	desc = "A pair of black shoes, they have the souls of galoshes making them unable to be slipped on a wet surface."
```suggestion
	desc = "A pair of black shoes, they have the soles of galoshes making them unable to be slipped on a wet surface."
```

2019-09-10 14:38 UTC, cebutris commented on code/game/objects/items/weaponry.dm
> +/obj/item/melee/baseball_bat/ablative/synda
```suggestion
/obj/item/melee/baseball_bat/ablative/syndi
```

2019-09-10 14:38 UTC, cebutris commented on code/modules/clothing/under/syndicate.dm
> +	name = "major leage, number unknown"
```suggestion
	name = "major league, number unknown"
```

2019-09-10 14:38 UTC, cebutris commented on code/modules/clothing/under/syndicate.dm
> +	desc = "A major leage outfit with the number faded number on the back. Seems rather robust for just a game"
```suggestion
	desc = "A major league outfit with the number faded number on the back. Seems rather robust for just a game"
```

2019-09-10 14:38 UTC, cebutris commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	desc = "A highly illegal medipen do to its load and small injections, allow for five uses before being drained"
```suggestion
	desc = "A highly illegal medipen due to its load and small injections, allow for five uses before being drained"
```

2019-09-10 14:38 UTC, cebutris commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	desc = "They say drugs never win, but look were you are now, then were they are."
```suggestion
	desc = "They say drugs never win, but look where you are now, then where they are."
```

2019-09-21 08:56 UTC, silicons approved these changes
i'm nerfing/reverting this so fast if murderbones become common because of this.

2019-09-21 08:56 UTC, merged