how many maintainers does it take to nerf xenomorphs (or fix the stamina combat system)
citadel-station/citadel-main pull request #9328
Opened 2019-09-21 08:29 UTC by kevinz000

## About The Pull Request

Refactors stamina combat Knockdown status override to apply on Knockdown() rather than status new.
This is because without this or another solution, Knockdown() just adds/min()s the duration you are attempting to be stunned for without doing the stamina combat overrides, making it so if you are stunned while already stunned you receive the full value of the stun in hardstun rather than the stamina combat overrides triggering.

## Why It's Good For The Game

Because without this, you can hardstun people by just having enough people baton them at the same time, or y'know, have xenos just instantly with a single click as the second click will hardstun for 10 seconds.

## Changelog
:cl:
experimental: Stamina combat refactored to apply knockdown overrides on Knockdown() rather than status_effect/knockdown/on_creation().
/:cl:

also adds logging to xeno disarms :)

2019-09-21 08:37 UTC, Thalpy commented
I was going to jokingly review this but combat PRs are confusing, where's the overcomplciated equations?

2019-09-22 00:50 UTC, deathride58 requested changes
The new knockdown proc is missing the resting = true and update_canmove() (meaning knockdowns won't actually knock spacemen down), the ability for knockdowns to knock spacemen off of vehicles (returning them back to their state of nigh-invulnerability), and the check that only goes through with the stun if the amount is over 80 (making *all* knockdown sources trigger the disarming and timer interrupting, regardless of strength)

2019-09-22 00:50 UTC, deathride58 commented on code/modules/mob/living/status_procs.dm
> +			amount *= 0.01
This is here only as a hack to force disarms and interrupt timers, it'd probably be better to make this directly force those things in the proc under the proper conditions (knockdown strength is more than 80 and the hardstun isnt being overridden)

2019-09-22 00:50 UTC, deathride58 commented on code/modules/mob/living/status_procs.dm
> +		else if(amount > 0)
You're missing the check that cancels the knockdown if it's over 80, meaning *all* knockdown sources will force people to drop things in their hands and cancel timers

2019-10-30 04:32 UTC, kevinz000 commented
bhijn fix it pls

2019-10-30 04:46 UTC, closed without merging