Removal of Nazi items
citadel-station/citadel-main pull request #9371
Opened 2019-09-29 23:09 UTC by r4d6

##  About The Pull Request

Removing the Nazi Hardsuit & Hardsuit helmet code and sprite.

## Why It's Good For The Game

According to Citadel's CONTRIBUTING guide, we can't have nazi shit in the game.

> Do not add any of the following in a Pull Request or risk getting the PR closed:

- National Socialist Party of Germany content, National Socialist Party of Germany related content, or National Socialist Party of Germany references
- Code where one line of code is split across mutiple lines (except for multiple, separate strings and comments; in those cases, existing longer lines must not be split up)
- Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.
- Just because something isn't on this list doesn't mean that it's acceptable. Use common sense above all else.

Also I was told that apparently Github bans any mention of nazis. So better safe than sorry

## Changelog
:cl:
del: Removed Nazi Clothing
del: Removed Nazi Hardsuit
del: Removed Nazi Gun
del: Removed Nazi Vendor
del: Removed Nazi Clothing Sprites
/:cl:

2019-09-30 02:36 UTC, lolman360 commented
that's actually a holdover from /tg/'s guidelines, citadel hasn;t bothered to change it

2019-09-30 09:36 UTC, r4d6 commented
I did not know that

2019-09-30 21:33 UTC, deathride58 requested changes

2019-09-30 21:33 UTC, deathride58 commented on code/modules/projectiles/guns/energy/plasma_cit.dm
> -/obj/item/gun/energy/plasma/MP40k
There's no need to remove this.

2019-09-30 22:21 UTC, r4d6 commented
Probably an error

On Mon, Sep 30, 2019, 5:33 PM deathride58, <notifications@github.com> wrote:

> *@deathride58* requested changes on this pull request.
> ------------------------------
>
> In code/modules/projectiles/guns/energy/plasma_cit.dm
> <https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9371#discussion_r329796393>
> :
>
> > @@ -32,16 +32,6 @@
>  	ammo_type = list(/obj/item/ammo_casing/energy/plasmagun/light)
>  	ammo_x_offset = 2
>
> -
> -/obj/item/gun/energy/plasma/MP40k
>
> There's no need to remove this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9371?email_source=notifications&email_token=AL7SRNII3LT5UUPJ4XZXAYDQMJWENA5CNFSM4I3UOL6KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCGMV6ZY#pullrequestreview-295264103>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AL7SRNLKAD2Z3LRCB7RUHE3QMJWENANCNFSM4I3UOL6A>
> .
>

2019-10-01 03:59 UTC, Linzolle commented
> 
> 
> that's actually a holdover from /tg/'s guidelines, citadel hasn;t bothered to change it

even if it is a holdover it's.... a very rightfully placed holdover

2019-10-01 23:20 UTC, r4d6 commented on code/modules/projectiles/guns/energy/plasma_cit.dm
> -/obj/item/gun/energy/plasma/MP40k
How to I change it?

2019-10-02 07:09 UTC, Weblure commented
Deleting 11 items for vague association with WWII Germany is overkill. I'm alright with changing any tasteless item descriptions that were grandfathered in, but a lot of these items otherwise have no direct correlation with Nazis.

2019-10-02 09:30 UTC, r4d6 commented
> Deleting 11 items for vague association with WWII Germany is overkill. I'm alright with changing any tasteless item descriptions that were grandfathered in, but a lot of these items otherwise have no direct correlation with Nazis.

>Vague association with WWII Germany
>Hardsuit named "Nazi Hardsuit"
>Vender named "NaziVend"
>"Vague" association

2019-10-02 18:49 UTC, Weblure commented
> > Deleting 11 items for vague association with WWII Germany is overkill. I'm alright with changing any tasteless item descriptions that were grandfathered in, but a lot of these items otherwise have no direct correlation with Nazis.
> 
> Vague association with WWII Germany
> Hardsuit named "Nazi Hardsuit"
> Vender named "NaziVend"
> "Vague" association

The physical items themselves, not their names and descriptions, which I'm fine with changing, as already stated.

2019-10-08 00:57 UTC, closed without merging

2019-10-08 01:05 UTC, Keekenox commented
I can't believe anyone was defending the removal of the dumb broken nazi shit you guys are wild lmao.

2019-10-08 22:48 UTC, Weblure commented
> I can't believe anyone was disagreeing with the removal of the dumb broken nazi shit you guys are wild lmao.

This wasn't the right way to do it.