Nerfs portable crew monitors - No more pocket/deep inventory usage
citadel-station/citadel-main pull request #9411
Opened 2019-10-04 18:48 UTC by kevinz000

## About The Pull Request

Crew monitors can no longer be used from within pockets or other forms of inventory/storage other than hands or it being in the game world adjacent or ontop of your tile, even with TK.

## Why It's Good For The Game

Both makes thematic sense (even though telekenesis doesn't obey the laws of physics yet with anything else) and a good way to rebalance the whole issue of 24/7 pocket crew monitors.

## Changelog
:cl:
balance: Portable crew monitors are no longer able to be used (see: automatically updating) from within pockets, inventory storage, or really, anything but your hands and by being next to you and in view.
/:cl:

2019-10-04 20:32 UTC, Ghommie commented on code/modules/tgui/states/non_concealed_update.dm
> +GLOBAL_DATUM_INIT(non_concealed_update /datum/ui_state/non_concealed_update, new)
```suggestion
GLOBAL_DATUM_INIT(non_concealed_update, /datum/ui_state/non_concealed_update, new)
```
A missing comma that made it not compile.

2019-10-04 20:37 UTC, Poojawa commented
cool, a medical nerf. just what medbay needs

2019-10-05 01:20 UTC, IronEleven commented
> cool, a medical nerf. just what medbay needs

Blame sec powergaming with monitors I guess.

2019-10-05 21:08 UTC, Weblure commented
I'd suggest keeping the monitor visible and usable from your belt slot, since you can see/use your PDA from your ID slot. Neither of these break reality, since they're both just hanging from your belt and aren't visibly or physically obstructed. This keeps constant crew-monitoring viable for medics as a trade-off of not wearing a belt, which is a much larger trade-off for security, effectively limiting its usage as a power-gaming tool.

Also, every time you open the crew monitor window, you have to resize, reposition, and scroll to get it back to where it was. You have to do this every time you remove the monitor from your hands (currently excluding pockets/belt slot). It's incredibly annoying and another reason to keep it visible from your belt.

2019-10-06 01:03 UTC, Poojawa commented
What it should do is stay up if you have a medical hud at the same time, tbh.

2019-10-08 06:28 UTC, kevinz000 commented
i'll make it stay up if you have a medical hud and it's in pockets, or without one if it's in belt, inventory nesting was stupid.

2019-11-21 05:01 UTC, nik707 requested changes
do the things you said you would

2019-11-21 14:23 UTC, davidchan13 commented
TBH just add it as a function to the MedHUD.

2019-12-06 04:41 UTC, closed without merging