Removes tracking beacons on Synda/CC mechs
citadel-station/citadel-main pull request #9555
Opened 2019-10-20 21:15 UTC by Trilbyspaceclone

## About The Pull Request
Removes the tracking/emp beacon from all synda/CC combat mechs

## Why It's Good For The Game

Stealth ops and such with mech (Dont laugh) become viable again and stops EMPing the baddies well they are in their base setting up

## Changelog
:cl:
fix: beacon on CC and Synda mechs
/:cl:

2019-10-21 05:50 UTC, Ghommie reviewed
Also, one thing, fix your description, you just wrote down that this will close a PR definitely irrelevant to the issue.

2019-10-21 05:50 UTC, Ghommie commented on code/game/mecha/combat/gygax.dm
> -	. = ..()
It's pretty vital for Initialize() to call parent. Don't do this unless you totally know what the heck is up.
Instead, Add a new `auto_mecha_tracking` var (name it however you want) to `/obj/mech/combat` of value FALSE, then set it TRUE for the base Durand, Gygax, H.O.N.K. and Phazon typepaths, then make sure the dark Gygax and dark H.O.N.K. and possibly other special sub-typepaths have it FALSE...

2019-10-21 05:50 UTC, Ghommie commented on code/game/mecha/combat/combat.dm
> +	trackers += new /obj/item/mecha_parts/mecha_tracking(src)
And cherry on top, add a generic if clauses variable check.
```
	if(auto_mecha_tracking)
		trackers += new /obj/item/mecha_parts/mecha_tracking(src)
```

2019-10-25 01:50 UTC, silicons requested changes
what ghom said, initialize not calling ..() is an absolutely "have a really damn good reason to do this like performance" thing, not to be done for this kind of stuff.

2019-10-29 15:20 UTC, closed without merging