Lowers ghosts and insain clowns hp to 120 from 1e6
citadel-station/citadel-main pull request #9614
Opened 2019-10-25 22:10 UTC by Trilbyspaceclone

## About The Pull Request

Lowers the npc shade ghost things that spawn in lockers to 120 as well as insain clowns

## Why It's Good For The Game

They cant really be killed and theirs not reason for that, they can float onto cargo shuttle and stop it from going

## Changelog
:cl:
tweak: shades and clowns HP
/:cl:

2019-10-25 23:49 UTC, Ghommie commented
This alone won't stop their unkillable status. 
They have godmode enabled on Initialize(), and their `adjustHealth()` ovverride also make them invincible short of admin intervention. I just looked at the file a couple days ago and I'm spooked by the potential sentience potion abuse on top of other things.
Regardless, if you want to make those shades pullable, you should consider removing the `anchored = TRUE`.

2019-10-27 23:10 UTC, kevinz000 commented on code/modules/holiday/halloween/halloween.dm
>  	return
remove this return while you're at it

2019-10-27 23:11 UTC, silicons requested changes
like ghom said this won't work because adjustHealth is still overridden, change the . = 0 to . = ..() please.

2019-10-30 02:40 UTC, Ghommie commented on code/modules/holiday/halloween/halloween.dm
> +	. = ..()
You can just remove this then, all it does is call parent, which it kinda does by default.

2019-11-14 23:05 UTC, silicons approved these changes

2019-11-14 23:07 UTC, merged