[WIP] MK II Cargo Rework - Sell harder edition
citadel-station/citadel-main pull request #9628
Opened 2019-10-26 23:16 UTC by Trilbyspaceclone

## About The Pull Request

Removes the default Elstic on most things as a base -Fuck that shit said by everyone
Most cooked/made food now sells,
Silk has been made!
Two new cargo crates one barrel on Loom
The third new crate is 40 sheets(?) of cotten for manufactering 
Silk can be sold for 200 per woven sheet
Wooden barrles now only take 10 wood to be made
Cleans up the wood crafting menu adds spaces.
More mech parts and weaponds can be sold!
Upped the export of mechs so their worth it
Fixed issues with breath implants

##Still working on booze crafting!

## Why It's Good For The Game

More options and gear to sell to CC/NT for the time being well still keeping it harder to get money other then waiting for miners or setting up Factoroi 2d spess men addition 

## Changelog
:cl:
add: Three more crates, A barrel, A Loom, 40 cotton sheets
add: Loads more to sell - Mech gear, Cooking and some reagents 
tweak: Moved around the vaule of some things and removed elastic of most items 
balance: Rebreather implants will now loss vaule, Do to being just metal and glass
/:cl:

2019-10-27 01:29 UTC, dapnee requested changes
Misspelling and grammar fixes.

2019-10-27 01:29 UTC, dapnee commented on code/modules/cargo/exports/food_wine.dm
> +/datum/export/food/douge
```suggestion
/datum/export/food/dough
```

2019-10-27 01:29 UTC, dapnee commented on code/modules/cargo/exports/food_wine.dm
> +/datum/export/food/cooked_douge
```suggestion
/datum/export/food/cooked_dough
```

2019-10-27 01:29 UTC, dapnee commented on code/modules/cargo/packs/materials.dm
> +	desc = "A wooden barrles ready for storge."
```suggestion
	desc = "Wooden barrels ready for storage."
```

2019-10-27 01:29 UTC, dapnee commented on code/modules/cargo/packs/organic.dm
> +	desc = "Plushies have been on the down in the market, and now do to a flood of raw cotton the price of it is so cheap its a steal! Contains 40 raw cotton sheets."
```suggestion
	desc = "Plushies have been on the down in the market, and now due to a flood of raw cotton the price of it is so cheap, its a steal! Contains 40 raw cotton sheets."
```

2019-10-27 01:29 UTC, dapnee commented on code/modules/cargo/exports/organs_robotics.dm
> +/datum/export/orgains/cybernetic
```suggestion
/datum/export/organs/cybernetic
```

2019-10-27 01:29 UTC, dapnee commented on code/modules/cargo/exports/organs_robotics.dm
> +/datum/export/orgains/upgraded
```suggestion
/datum/export/organs/upgraded
```

2019-10-27 01:29 UTC, dapnee commented on code/modules/cargo/exports/organs_robotics.dm
>  /datum/export/orgains/tail //Shhh
```suggestion
/datum/export/organs/tail //Shhh
```

Will probably need to check further for more mentions of “orgains” and switch it to the correct spelling of organs.

2019-11-14 22:59 UTC, silicons approved these changes

2019-11-14 23:00 UTC, merged