Ports "Makes felinids die from chocolate."
citadel-station/citadel-main pull request #9859
Opened 2019-11-18 20:26 UTC by Ghommie

## About The Pull Request
Doing what @Sishen1542 should have done months prior.
Porting tgstation/tgstation#46238, also #46339, #46366 and #46790, by GuyonBroadway.

## Why It's Good For The Game
I regret nothing.

## Changelog
:cl: GuyonBroadway
balance: Felinids now have a very adverse reaction to chocolate products.
/:cl:

2019-11-18 20:33 UTC, Trilbyspaceclone commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +	if(chem.di == "cocoa" || chem.id == "hot_coco" || chem.id == "chocolate_milk" || chem.id == "chocolatepudding")
Forgot villina

2019-11-18 20:45 UTC, Thalpy commented
As this is a nerf to felinids, perhaps you could propose a counter buff, to keep things balanced? Purrhaps a purr action button?

2019-11-18 20:59 UTC, Ghommie commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +	if(chem.di == "cocoa" || chem.id == "hot_coco" || chem.id == "chocolate_milk" || chem.id == "chocolatepudding")
Vanilla is not chocolate toh.

2019-11-19 05:09 UTC, PersianXerxes commented
Bad meme >:(

2019-11-19 06:32 UTC, YakumoChen commented
Can we not

2019-11-19 10:04 UTC, Tename commented
Don't forget dogs too.

2019-11-19 14:08 UTC, Ghommie commented
> 
> 
> Don't forget dogs too.

I mean, we could make all antropomorphs die from chocolate too. That'd only upset 90% of the community and not just felinid mains. :smiling_imp: 

> 
> 
> As this is a nerf to felinids, perhaps you could propose a counter buff, to keep things balanced? Purrhaps a purr action button?

Countering gameplay drawbacks with roleplay buffs? Really?

2019-11-19 14:11 UTC, Thalpy commented
> Countering gameplay drawbacks with roleplay buffs? Really?

Clearly the purr would allow for some mechanical self heal, or the ability to reflect bullets from the internal self resonance causing projectiles to hit their resonance frequency causing their inertia to invert.

I was being silly Ghommie.

2019-11-19 16:18 UTC, xurxomario commented
Wasnt this a "felinids bad" salt pr back there?

But hey, regardless of that, if we are gonna meme felinids may as well go the whole nine yards, give em the ability to spit out non-damaging furballs or something similar for the giggles.

2019-11-19 17:05 UTC, Ghommie commented
> 
> 
> Wasnt this a "felinids bad" salt pr back there?

Nah, new players have been restricted from making felinid characters on tgstation for more than a year now. No real salt, just a dab on them.

2019-11-20 01:38 UTC, ShadeAware commented
It is now time for execution by chocolate.

2019-11-20 02:49 UTC, lolman360 commented
at worst people are going to use chocolate as a unique and fun poison, what's wrong with that?

2019-11-20 03:09 UTC, Ghommie commented
You can always make a revert as soon as this PR is merged (implying it even will).

2019-11-20 04:35 UTC, silicons requested changes
dude just make it do slight tox and maybe a message/stunless throwups none of the ridiculous organ damage/disgust mess jesus dude

2019-11-20 06:44 UTC, lolman360 commented
>balance that directly affects kevinz
>kevinz: "reeeee"

lmao

2019-11-21 05:03 UTC, kevinz000 commented
dude that's still organ damage which is a horrible idea with where our medical code is is there a reason to not do tox damage?

2019-11-22 17:41 UTC, Ghommie commented
Low toxin damage is easy to counter, disgust slowly leads to emesis and purge of the mob's reagents and charcoal already purges all chemicals.
A normal felinid mob has 10 internal organs, excluding genitalia. most of which have 100 health points.
While the effects are stackable with multiple chocolate reagents. The disgust will inevitably end up clearing them at one point or another.

And we both know that this will be reverted if ever merged, no need to take this seriously.

2019-11-24 05:34 UTC, Poojawa commented
This is a shit meme, because if we're gunna try to finger point chocolate being toxic to cats/dogs, you have to realize it's about dosage and bodyweight for theobromine poisoning.

if a saint bernard eats a fuckin' milk dud, it isn't going to drop dead.

This is just shitty tg 'REEEE FURRIES' bullshit.

2019-12-01 07:20 UTC, optimumtact commented
it shouldn't have been merged in the first place

2019-12-01 07:58 UTC, Ghommie commented
We all let crap fly past the radar once in a while.
Maintainers go do whatever.

2019-12-07 05:57 UTC, Ghommie commented
This meme is not a thing anymore on tgstation, took ne a while to notice.
Hoke's old, the needless debate also made it even more boring.

2019-12-07 05:57 UTC, closed without merging