Honkbot slip and slide fun ride.
citadel-station/citadel-main pull request #9874
Opened 2019-11-20 03:07 UTC by Ghommie

## About The Pull Request
Making honkbot's oil spills of the slippery kind. Apply care when bashing them.

## Why It's Good For The Game
Consistency, honk.

## Changelog
:cl:
add: Honkbot oil spills are of the slippery kind now. Honk.
/:cl:

2019-11-21 04:47 UTC, silicons approved these changes

2019-11-21 04:48 UTC, silicons requested changes
actually hol' up @Ghommie does this expire or does it require soap/cleaner/mopping because if it's the latter and there's no other way it's a bit powerful.

2019-11-21 04:52 UTC, Ghommie commented
Doesn't expire, but won't slip unless the mob is sprinting or fatigued.

2019-11-23 18:49 UTC, silicons approved these changes
ehhhhhhhhhh
admin only
and most admins are smart enough to not spawn 30 right?

2019-11-23 18:49 UTC, merged