Removes circuitry
citadel-station/citadel-main pull request #9944
Opened 2019-11-26 05:35 UTC by GrayRachnid

## About The Pull Request
Removes circuits.

## Why It's Good For The Game
Kevinz told me that he doesn't have the time to balance/shield it and it has too many exploits to be kept in the game without a maintainer.

## Changelog
:cl:
del: Removed circuits
/:cl:

2019-11-26 05:39 UTC, silicons requested changes
i just said i don't give a shit because i barely have time to do anything let alone maintain circuits because i get 4 pings in 10 minutes after a round ends from someone abusing the shit out of it every antag round 

if you really want the nuclear option, comment out the designs from R&D, not remove all the files, we're not there yet. i'd rather this be operational.

2019-11-26 05:50 UTC, GrayRachnid commented
wat

2019-11-26 05:51 UTC, Linzolle commented
someone needs to merge master into their branch...

2019-11-26 05:53 UTC, GrayRachnid commented
> 
> 
> someone needs to merge master into their branch...

i tried.....

2019-11-26 06:00 UTC, IronEleven commented
🦀Circuits are gone🦀

2019-11-26 06:03 UTC, GrayRachnid commented
> 
> 
> i just said i don't give a shit because i barely have time to do anything let alone maintain circuits because i get 4 pings in 10 minutes after a round ends from someone abusing the shit out of it every antag round
> 
> if you really want the nuclear option, comment out the designs from R&D, not remove all the files, we're not there yet. i'd rather this be operational.

Done

2019-11-27 07:31 UTC, ShadeAware commented
This is a needlessly expansive, nuclear option of removing an entire part of Science over a few incidents. I can think of plenty more reasons to remove Xenobiology if we're going with this mindset.

Heres an idea: If you have a problem with weaponized circuits, just remove reagent and weaponized circuits? Or lock them behind an extra tech node?

Don't just remove an entire (and very fun) portion of Science because a few people got creative.

2019-11-29 01:52 UTC, Tename commented
Another, let's remove this entire part of the game people enjoy playing because why not.

2019-11-29 01:54 UTC, GrayRachnid commented
> 
> 
> Another, let's remove this entire part of the game people enjoy playing because why not.

There is nobody to maintain it and it has too many exploits. That's why.

2019-12-21 12:02 UTC, Ghommie commented
I'd rather deal with waves of issues concerning circuitry until I give up and say this was the best solution.
Otherwise this bandaid of a PR will stay open forevermore.

2019-12-21 12:02 UTC, closed without merging