adds new nanite sensor readings
citadel-station/citadel-main pull request #9968
Opened 2019-11-28 01:54 UTC by Seris02

…r equal

## About The Pull Request

Gives nanite volume/health/damage sensors Above, Below, Equal to, Above or equal to, and Below or equal to.

## Why It's Good For The Game

Because it was annoying that it was above or equal to and said above, and had no equal.

## Changelog
:cl:
tweak: tweaks the way nanite/health/damage sensors get their limit
/:cl:

2019-11-28 02:04 UTC, Ghommie commented
This feels fairly useless. The "equal to" settings and similar are very unpractical in a game with different sources of different damage/healing output, armor values, coefficient etcetera.
Just rename the "Above" setting to "Above or equal to" for consistency.

2019-11-29 06:04 UTC, silicons requested changes
what ghom said

2019-12-21 12:12 UTC, Ghommie commented
As I said above, these changes are hardly useful.
Hell it'd be way more useful if the nanite sensor was reworked to check a health range (like -100 to 25 or 50 to 100). I'll gladly merge a new PR following this suggestion, not this one.

2019-12-21 12:12 UTC, closed without merging

2019-12-27 10:42 UTC, Seris02 commented
I forgot about this PR